#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
3-latent_state_and_observation_model_diagnostics.py
===================================================

ClonoDynamics Step 3: diagnostic characterization of the pair-specific latent
consensus representation and observation-model outputs generated by Step 2.

Purpose
-------
Step 3 is a DIAGNOSTIC layer. It does not re-fit the Step-2 model, redefine
clonotype abundance, create longitudinal transitions, select the primary
forward or fluctuation estimand, or filter states from downstream analyses.

The production ClonoDynamics architecture is replicate-resolved. Step 2
preserves three distinct information layers:

    1. model-based latent consensus representation
       x_latent_median and the paired posterior from the pair-specific
       Negative-Binomial model;

    2. replicate-resolved observed measurements
       count_rep1/count_rep2, freq_rep1/freq_rep2 and
       x_obs_rep1/x_obs_rep2, retained as independent measurements for the
       primary downstream AB/BA forward estimator and cross-replicate
       displacement covariance;

    3. observation-state annotations
       realized technical detection, model-based posterior-predictive
       detectability/dropout, and p_value-based operational observability.

An auxiliary positive-only summary (x_positive_current / f_positive_current)
is also retained by Step 2 for representation diagnostics and backward
compatibility. It is NOT the primary fluctuation displacement in the final
pipeline.

Step 3 concentrates on the first and third layers and on the behavior of the
latent consensus when technical support differs between the two replicates.
It preserves relevant observed-replicate fields for provenance, but it does not
estimate any downstream dynamical quantity.

Final downstream contract
-------------------------
Step 3 must not be interpreted as choosing the primary dynamical
representation. The final production roles remain:

    latent consensus representation
        -> noise-aware state representation
        -> conditioning geometry (including xmid_latent downstream)
        -> posterior uncertainty characterization
        -> latent-representation sensitivity analyses

    replicate-resolved observed measurements
        -> primary replicate-decoupled forward estimator downstream
           AB: condition on replicate A and measure displacement in B
           BA: condition on replicate B and measure displacement in A
        -> primary fluctuation estimator downstream
           Cov(delta_x_rep1, delta_x_rep2) on common4 eligibility

    operational observation state
        -> observable(alpha) = 1[p_value < alpha]
        -> TT / TF / FT / FF transition annotation
        -> observation-domain and alpha-threshold sensitivity analyses

Scientific questions
--------------------
The analysis addresses six diagnostic questions:

    A. How concentrated is the paired-replicate latent posterior?

    B. How well do the two single-replicate latent posteriors agree when they
       are evaluated under the same pair-specific gamma, kappa and frequency
       grid?

    C. How does exact paired-state posterior-predictive detectability compare
       with the FACTORIZED UNION approximation obtained by combining the two
       replicate-specific posterior means?

       These two quantities are not algebraically equivalent in general.
       With q_r(f) denoting replicate-r dropout probability and expectation
       taken under the shared paired posterior,

           p_dropout_state = E[q_1(f) q_2(f)]

       whereas the factorized union uses

           E[q_1(f)] E[q_2(f)].

       Their difference therefore describes shared-posterior coupling; it is
       not a failed identity check and not an external calibration of
       detectability.

    D. How do posterior uncertainty and replicate agreement differ between
       states supported by one versus two positive technical replicates?

    E. How far does the latent consensus lie from the auxiliary positive-only
       abundance summary, especially in ONE_POSITIVE states where a zero count
       enters the NB likelihood but does not enter the positive-only center?

    F. In ONE_POSITIVE states, is the latent-versus-positive shift associated
       with the sequencing opportunity of the non-detecting replicate, after
       avoiding clonotype-level pseudoreplication of replicate depth?

Position in the pipeline
------------------------

    Step 1  1-repertoire_characterization.py
        -> observed repertoire architecture and descriptive heavy-tail fitting
        -> no filtering and no parameter transfer to Step 2

    Step 2  2-multirepresentation_clonotype_state_inference.py
        -> pair-specific latent consensus + posterior uncertainty
        -> replicate-resolved observed measurements
        -> realized detection + model-based detectability
        -> p_value-based operational observability

    Step 3  3-latent_state_and_observation_model_diagnostics.py
        -> latent-posterior concentration
        -> single-replicate posterior agreement
        -> factorized-union detectability diagnostic
        -> ONE_POSITIVE versus TWO_POSITIVE support characterization
        -> latent-versus-positive representation contrast
        -> pair-aware and paired-orientation depth diagnostics
        -> NO filtering

    Step 4  replicate-resolved trajectory construction
    Step 5  generic transition construction

Canonical input
---------------
The canonical input is the combined Step-2 table:

    per_clone_latent_subject.parquet

produced by:

    2-multirepresentation_clonotype_state_inference.py

The table must identify subject, time and aaSeqCDR3 and contain the paired and
single-replicate posterior summaries required by this diagnostic analysis.
The canonical Step-2 production table also contains:

    count_rep1, count_rep2
    depth_rep1, depth_rep2
    freq_rep1, freq_rep2
    x_obs_rep1, x_obs_rep2
    f_observed_rep1, f_observed_rep2
    x_observed_rep1, x_observed_rep2

    f_positive_current, x_positive_current
    n_positive_replicates
    positive_state_class
    positive_replicate_source

    logP, p_value, observable
    p_detect_state, p_dropout_state
    p_detect_rep1, p_detect_rep2
    p_dropout_rep1, p_dropout_rep2.

For compatibility with older Step-2 tables, the positive-state fields may be
reconstructed from count_rep1/count_rep2 and the historical freq_geo/x_obs_geo
aliases when possible. This compatibility path does not change the latent
posterior.

Latent-posterior diagnostics
----------------------------
Posterior uncertainty is summarized in natural-log frequency space by:

    cqc_posterior_width95_x
        x_latent_q975 - x_latent_q025;

    cqc_posterior_fold_range95
        exp(cqc_posterior_width95_x);

    cqc_posterior_sd_x
        posterior standard deviation in x = ln(f);

    cqc_posterior_entropy
        discrete posterior Shannon entropy;

    cqc_effective_posterior_support
        exp(entropy), i.e. Shannon effective support;

    cqc_posterior_entropy_normalized
        entropy / ln(grid_size).

Exact inverse-Simpson posterior support, 1/sum_j p_j^2, is attached only when
it is already available in the Step-2 table or an explicitly supplied keyed
support table. It is never reconstructed from entropy.

No posterior-width, entropy or support threshold is used for inclusion.

Single-replicate posterior agreement
------------------------------------
The two single-replicate posterior distributions are diagnostics of how the
same pair-specific observation model behaves when each replicate is considered
separately. They are not the primary observed AB/BA measurements.

Exact discrete-grid Bhattacharyya overlap is preferred:

    BC = sum_j sqrt[p_1(j) p_2(j)].

If exact overlap is unavailable, a Gaussian approximation is used and its
source is explicitly recorded. The output also contains absolute and
standardized differences between single-replicate latent medians and the
corresponding Hellinger distance.

Detectability: exact paired state versus factorized union
---------------------------------------------------------
The Step-2 engine defines paired-state dropout as:

    p_dropout_state = E_post[q_1(f) q_2(f)]

and:

    p_detect_state = 1 - p_dropout_state.

The script also computes the factorized-union approximation:

    p_detect_factorized_union
        = 1 - (1 - p_detect_rep1)(1 - p_detect_rep2).

Because p_detect_rep1 and p_detect_rep2 are themselves posterior-integrated
quantities under the shared posterior, the factorized union replaces
E[q_1 q_2] with E[q_1]E[q_2]. Equality is therefore not expected in general.

Canonical diagnostic names are:

    cqc_factorized_union_detectability
    cqc_delta_state_vs_factorized_union
    cqc_abs_delta_state_vs_factorized_union.

Historical aliases are retained:

    cqc_union_detectability
    cqc_delta_detectability
    cqc_abs_delta_detectability.

The primary summary file is:

    state_detectability_factorized_union_diagnostic.csv

Historical files

    state_detectability_internal_consistency_summary.csv
    state_detectability_validation_summary.csv

are written only as compatibility aliases and must not be described as
independent validation.

ONE_POSITIVE and TWO_POSITIVE support strata
--------------------------------------------
Realized technical support is classified as:

    ONE_POSITIVE
        exactly one replicate has count > 0;

    TWO_POSITIVE
        both replicates have count > 0.

These are technical-detection strata, not quality classes and not biological
presence/absence states.

The script reports their counts, fractions, posterior uncertainty, replicate
agreement and latent-versus-positive contrasts in:

    clonotype_latent_posterior_qc_by_positive_state.csv
    state_representation_class_summary.csv.

Latent consensus versus auxiliary positive-only summary
-------------------------------------------------------
For each state:

    cqc_latent_minus_positive_x
        = x_latent_median - x_positive_current

and:

    cqc_abs_latent_minus_positive_x
        = |x_latent_median - x_positive_current|.

These are descriptive representation contrasts only. They do not replace the
latent consensus, the observed replicate measurements, or any downstream
estimand.

ONE_POSITIVE depth diagnostics and analysis units
-------------------------------------------------
Sequencing depth is a technical-replicate-level variable shared by all
clonotypes within the same subject-timepoint-replicate. Treating every
ONE_POSITIVE clonotype as an independent depth observation would therefore be
pseudoreplication.

The script first collapses ONE_POSITIVE clonotypes to one unit for each:

    subject x time x zero-replicate side

which is equivalent to:

    subject x time x positive_replicate_source.

For each unit it records zero-side and positive-side sequencing depth, the
number of ONE_POSITIVE clonotypes, and robust summaries of
x_latent_median - x_positive_current.

The preferred relative-depth descriptor is:

    delta_log_depth_zero_minus_positive
        = log(depth_zero) - log(depth_positive).

Absolute zero-side log depth is retained as a secondary descriptor.

A second diagnostic pairs the two possible ONE_POSITIVE orientations within
each subject-timepoint:

    zero in replicate 1 / positive in replicate 2
    zero in replicate 2 / positive in replicate 1.

It compares:

    log(depth_rep1 / depth_rep2)

with:

    median_shift_zero_rep1 - median_shift_zero_rep2,

where median_shift is the median latent-minus-positive contrast in the
corresponding orientation.

The paired summary reports Spearman correlation, Pearson correlation and the
simple linear-regression slope/intercept/R^2. These statistics are calculated
across subject-timepoint paired-orientation units, not across clonotype rows.

Corresponding outputs are:

    one_positive_zero_depth_by_subject_time_replica.csv
    one_positive_zero_depth_diagnostic.csv
    one_positive_paired_replica_depth_by_subject_time.csv
    one_positive_paired_replica_depth_diagnostic.csv.

Observation terminology
-----------------------
The script maintains the following distinction:

    realized technical detection
        observed count status in replicate 1 and replicate 2;

    model-based posterior-predictive detectability
        p_detect_state / p_dropout_state and replicate-specific counterparts;

    operational observability
        observable(alpha) = 1[p_value < alpha], inherited from Step 2.

None of these is a ground-truth biological presence/absence variable.
Step 3 does not recalculate p_value or change alpha.

Filtering policy
----------------
No abundance threshold, posterior-width threshold, composite QC score,
ONE_POSITIVE/TWO_POSITIVE restriction, detectability threshold or operational
observability filter is applied. Every successfully inferred Step-2 state
remains eligible for downstream trajectory construction.

Main outputs
------------
The principal output is:

    clonotype_latent_posterior_qc.parquet.

Summary outputs include posterior metric distributions, subject and
subject-timepoint summaries, abundance and detectability stratifications,
full-data Spearman matrices, positive-state summaries, ONE_POSITIVE depth
analyses and the factorized-union detectability diagnostic.

The Step-3 outputs are diagnostic assets and manuscript-support tables; they do
not constitute a filtered input dataset for Step 4.

Interpretive boundary
---------------------
Step 3 establishes how the fitted latent/observation model behaves across the
real technical-replicate dataset. It can demonstrate posterior concentration,
replicate agreement, ONE_POSITIVE depth coupling and the distinction between
exact paired-state and factorized detectability summaries.

It does NOT demonstrate that:

    - x_latent is true abundance;
    - posterior-predictive detectability is externally calibrated;
    - one abundance representation is optimal for every dynamical estimand;
    - ONE_POSITIVE states are low-quality states that should be discarded;
    - TT is a preferred biological domain;
    - the primary forward or fluctuation signal has been identified.

Those dynamical questions are addressed downstream using the replicate-resolved
estimands validated against the pseudo-longitudinal technical null.

Compatible with Python 3.9 and Polars 1.36.x.
"""
from __future__ import annotations

import argparse
import json
import math
import numpy as np
from pathlib import Path
from typing import Optional, Sequence

import polars as pl

EPS = 1e-12
SCRIPT_VERSION = "v11-replicate-resolved-model-diagnostics-2026-09-09"
INVERSE_SIMPSON_CANDIDATES = [
    "cqc_effective_posterior_support_simpson",
    "posterior_inverse_simpson_support",
    "inverse_simpson_support",
    "posterior_effective_support_simpson",
]

EXACT_BC_CANDIDATES = [
    "cqc_replicate_bhattacharyya_exact",
    "replicate_posterior_bhattacharyya",
    "posterior_bhattacharyya_exact",
    "bhattacharyya_exact",
]


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def resolve_input(path: Path, pattern: str) -> Path:
    if path.is_file():
        return path
    if not path.is_dir():
        raise FileNotFoundError("Input does not exist: %s" % path)
    matches = sorted(path.glob(pattern))
    if len(matches) != 1:
        raise FileNotFoundError(
            "Expected exactly one file matching %r in %s; found %d" %
            (pattern, path, len(matches))
        )
    return matches[0]


def scan_table(path: Path) -> pl.LazyFrame:
    suffix = path.suffix.lower()
    if suffix in (".parquet", ".pq"):
        return pl.scan_parquet(path)
    if suffix in (".csv", ".tsv", ".txt"):
        sep = "\t" if suffix in (".tsv", ".txt") else ","
        return pl.scan_csv(path, separator=sep, infer_schema_length=10000)
    raise ValueError("Unsupported input format: %s" % suffix)


def require_columns(names, required) -> None:
    missing = [c for c in required if c not in names]
    if missing:
        raise ValueError("Missing required Step-2 columns: %s" % ", ".join(missing))


def first_present(names, candidates):
    for c in candidates:
        if c in names:
            return c
    return None


def attach_exact_overlap(
    lf: pl.LazyFrame,
    overlap_path: Optional[Path],
    clone_col: str,
    exact_bc_col: Optional[str],
) -> tuple:
    """Attach an exact posterior-overlap scalar when available.

    External table must contain subject, time, clone_col and one exact-BC
    column. The result is normalized to cqc_replicate_bhattacharyya_exact.
    """
    names = lf.collect_schema().names()
    source_col = None
    source_description = None

    if exact_bc_col and exact_bc_col in names:
        source_col = exact_bc_col
        source_description = "input_column:%s" % exact_bc_col
    elif not exact_bc_col:
        source_col = first_present(names, EXACT_BC_CANDIDATES)
        if source_col:
            source_description = "input_column:%s" % source_col

    if source_col:
        if source_col != "cqc_replicate_bhattacharyya_exact":
            lf = lf.with_columns(
                pl.col(source_col).cast(pl.Float64, strict=False)
                .alias("cqc_replicate_bhattacharyya_exact")
            )
        return lf, source_description

    if overlap_path is None:
        return lf, None

    olf = scan_table(overlap_path)
    onames = olf.collect_schema().names()
    require_columns(onames, ["subject", "time", clone_col])
    source_col = exact_bc_col if exact_bc_col else first_present(onames, EXACT_BC_CANDIDATES)
    if source_col is None:
        raise ValueError(
            "Exact-overlap table contains no recognized Bhattacharyya column. "
            "Use --exact-bc-col to identify it."
        )
    olf = olf.select([
        pl.col("subject"), pl.col("time"), pl.col(clone_col),
        pl.col(source_col).cast(pl.Float64, strict=False)
        .alias("cqc_replicate_bhattacharyya_exact"),
    ])
    lf = lf.join(olf, on=["subject", "time", clone_col], how="left")
    return lf, "external_table:%s:%s" % (overlap_path, source_col)



def attach_inverse_simpson_support(
    lf: pl.LazyFrame,
    support_path: Optional[Path],
    clone_col: str,
    support_col: Optional[str],
) -> tuple:
    """Attach exact inverse-Simpson posterior support when available.

    The metric is 1 / sum(p_i^2) on the discrete posterior grid. It cannot be
    reconstructed from entropy or marginal summaries, so it is accepted only
    as an existing Step-2 column or from an external keyed table.
    """
    names = lf.collect_schema().names()
    source_col = None
    source_description = None
    if support_col and support_col in names:
        source_col = support_col
        source_description = "input_column:%s" % support_col
    elif not support_col:
        source_col = first_present(names, INVERSE_SIMPSON_CANDIDATES)
        if source_col:
            source_description = "input_column:%s" % source_col
    if source_col:
        if source_col != "cqc_effective_posterior_support_simpson":
            lf = lf.with_columns(
                pl.col(source_col).cast(pl.Float64, strict=False)
                .alias("cqc_effective_posterior_support_simpson")
            )
        return lf, source_description
    if support_path is None:
        return lf, None
    slf = scan_table(support_path)
    snames = slf.collect_schema().names()
    require_columns(snames, ["subject", "time", clone_col])
    source_col = support_col if support_col else first_present(snames, INVERSE_SIMPSON_CANDIDATES)
    if source_col is None:
        raise ValueError(
            "Posterior-support table contains no recognized inverse-Simpson column. "
            "Use --inverse-simpson-col to identify it."
        )
    slf = slf.select([
        pl.col("subject"), pl.col("time"), pl.col(clone_col),
        pl.col(source_col).cast(pl.Float64, strict=False)
        .alias("cqc_effective_posterior_support_simpson"),
    ])
    lf = lf.join(slf, on=["subject", "time", clone_col], how="left")
    return lf, "external_table:%s:%s" % (support_path, source_col)


def attach_positive_state_context(lf: pl.LazyFrame) -> tuple:
    """Ensure the revised Step-2 positive-state fields are available.

    Canonical v8 Step-2 outputs are used directly. For legacy inputs, fields are
    reconstructed only when the required observed count/frequency columns are
    available. This compatibility path does not alter the latent posterior.
    """
    names = set(lf.collect_schema().names())
    reconstructed = []

    if "n_positive_replicates" not in names:
        if {"count_rep1", "count_rep2"}.issubset(names):
            lf = lf.with_columns(
                (
                    (pl.col("count_rep1").cast(pl.Float64, strict=False) > 0).cast(pl.Int64)
                    + (pl.col("count_rep2").cast(pl.Float64, strict=False) > 0).cast(pl.Int64)
                ).alias("n_positive_replicates")
            )
            reconstructed.append("n_positive_replicates")
        else:
            raise ValueError(
                "Step 3 requires n_positive_replicates or count_rep1/count_rep2 "
                "to reconstruct the revised Step-2 detection-support stratum."
            )

    names = set(lf.collect_schema().names())
    if "positive_state_class" not in names:
        lf = lf.with_columns(
            pl.when(pl.col("n_positive_replicates") == 2)
            .then(pl.lit("TWO_POSITIVE"))
            .when(pl.col("n_positive_replicates") == 1)
            .then(pl.lit("ONE_POSITIVE"))
            .otherwise(pl.lit("UNSUPPORTED"))
            .alias("positive_state_class")
        )
        reconstructed.append("positive_state_class")

    names = set(lf.collect_schema().names())
    if "positive_replicate_source" not in names:
        if {"count_rep1", "count_rep2"}.issubset(names):
            c1 = pl.col("count_rep1").cast(pl.Float64, strict=False) > 0
            c2 = pl.col("count_rep2").cast(pl.Float64, strict=False) > 0
            lf = lf.with_columns(
                pl.when(c1 & c2).then(pl.lit("BOTH"))
                .when(c1 & ~c2).then(pl.lit("REP1_ONLY"))
                .when(~c1 & c2).then(pl.lit("REP2_ONLY"))
                .otherwise(pl.lit("NONE"))
                .alias("positive_replicate_source")
            )
        else:
            lf = lf.with_columns(
                pl.when(pl.col("n_positive_replicates") == 2)
                .then(pl.lit("BOTH"))
                .when(pl.col("n_positive_replicates") == 1)
                .then(pl.lit("UNKNOWN_ONE_POSITIVE"))
                .otherwise(pl.lit("NONE"))
                .alias("positive_replicate_source")
            )
        reconstructed.append("positive_replicate_source")

    names = set(lf.collect_schema().names())
    if "f_positive_current" not in names:
        if "freq_geo" in names:
            lf = lf.with_columns(
                pl.col("freq_geo").cast(pl.Float64, strict=False)
                .alias("f_positive_current")
            )
            reconstructed.append("f_positive_current")
        else:
            raise ValueError(
                "Step 3 requires f_positive_current or legacy freq_geo."
            )

    names = set(lf.collect_schema().names())
    if "x_positive_current" not in names:
        if "x_obs_geo" in names:
            lf = lf.with_columns(
                pl.col("x_obs_geo").cast(pl.Float64, strict=False)
                .alias("x_positive_current")
            )
            reconstructed.append("x_positive_current")
        else:
            lf = lf.with_columns(
                pl.col("f_positive_current").cast(pl.Float64, strict=False)
                .clip(lower_bound=1e-300).log().alias("x_positive_current")
            )
            reconstructed.append("x_positive_current")

    source = (
        "canonical_step2_replicate_resolved_fields"
        if not reconstructed
        else "legacy_reconstruction:" + ",".join(reconstructed)
    )
    return lf, source


def build_diagnostics(
    lf: pl.LazyFrame,
    clone_col: str,
    grid_size: int,
    exact_overlap_path: Optional[Path],
    exact_bc_col: Optional[str],
    require_exact_overlap: bool,
    posterior_support_path: Optional[Path],
    inverse_simpson_col: Optional[str],
    require_inverse_simpson: bool,
) -> tuple:
    lf, positive_context_source = attach_positive_state_context(lf)
    names = lf.collect_schema().names()
    required = [
        "subject", "time", clone_col,
        "x_latent_median", "x_latent_sd", "x_latent_q025", "x_latent_q975",
        "posterior_entropy", "p_detect_state", "p_dropout_state",
        "p_detect_rep1", "p_detect_rep2",
        "x_rep1_latent_median", "x_rep2_latent_median",
        "rep1_x_latent_sd", "rep2_x_latent_sd",
        "f_positive_current", "x_positive_current",
        "n_positive_replicates", "positive_state_class",
    ]
    require_columns(names, required)

    lf, exact_source = attach_exact_overlap(
        lf, exact_overlap_path, clone_col, exact_bc_col
    )
    lf, support_source = attach_inverse_simpson_support(
        lf, posterior_support_path, clone_col, inverse_simpson_col
    )
    names = lf.collect_schema().names()
    if require_inverse_simpson and "cqc_effective_posterior_support_simpson" not in names:
        raise ValueError(
            "Exact inverse-Simpson posterior support was required but is unavailable. "
            "Supply --posterior-support-table or a recognized input column."
        )
    if require_exact_overlap and "cqc_replicate_bhattacharyya_exact" not in names:
        raise ValueError(
            "Exact posterior overlap was required but is unavailable. Supply "
            "--exact-overlap-table or an exact-BC column from Step 2."
        )

    context = [
        "pair_id", "count_rep1", "count_rep2", "depth_rep1", "depth_rep2",
        "freq_rep1", "freq_rep2", "x_obs_rep1", "x_obs_rep2",
        "f_observed_rep1", "f_observed_rep2", "x_observed_rep1", "x_observed_rep2",
        "freq_geo", "x_obs_geo",
        "f_latent_mean", "f_latent_median",
        "f_latent_q025", "f_latent_q975", "x_latent_mean", "x_latent_median",
        "f_positive_current", "x_positive_current",
        "n_positive_replicates", "positive_state_class",
        "positive_replicate_source", "positive_abundance_method",
        "logP", "p_value", "observable", "p_detect_state", "p_dropout_state",
        "p_detect_rep1", "p_detect_rep2", "p_dropout_rep1", "p_dropout_rep2",
        "cqc_replicate_bhattacharyya_exact",
        "cqc_effective_posterior_support_simpson",
    ]
    selected = ["subject", "time", clone_col] + [c for c in context if c in names] + required[3:]
    selected = list(dict.fromkeys(selected))

    non_numeric = {
        "subject", "time", clone_col, "pair_id", "observable",
        "positive_state_class", "positive_replicate_source",
        "positive_abundance_method",
    }
    numeric = [c for c in selected if c not in non_numeric]
    q = lf.select([pl.col(c) for c in selected]).with_columns([
        pl.col(c).cast(pl.Float64, strict=False) for c in numeric
    ])

    log_grid = math.log(float(grid_size))
    s1 = pl.col("rep1_x_latent_sd").clip(lower_bound=0.0)
    s2 = pl.col("rep2_x_latent_sd").clip(lower_bound=0.0)
    s1sq = s1.pow(2)
    s2sq = s2.pow(2)
    variance_sum = s1sq + s2sq + pl.lit(EPS)
    delta = (pl.col("x_rep1_latent_median") - pl.col("x_rep2_latent_median")).abs()
    width_x = pl.col("x_latent_q975") - pl.col("x_latent_q025")

    expressions = [
        width_x.alias("cqc_posterior_width95_x"),
        width_x.exp().alias("cqc_posterior_fold_range95"),
        pl.col("x_latent_sd").alias("cqc_posterior_sd_x"),
        pl.col("posterior_entropy").alias("cqc_posterior_entropy"),
        pl.col("posterior_entropy").exp().alias("cqc_effective_posterior_support"),
        (pl.col("posterior_entropy") / pl.lit(log_grid))
            .clip(0.0, 1.0).alias("cqc_posterior_entropy_normalized"),
        pl.col("p_detect_state").clip(0.0, 1.0)
            .alias("cqc_state_detectability"),
        pl.col("p_dropout_state").clip(0.0, 1.0)
            .alias("cqc_state_dropout"),
        # Factorized union of the replicate-specific posterior-predictive
        # detection means. This is NOT algebraically identical to the exact
        # paired-state quantity, because the latter integrates q1(f)q2(f)
        # over the shared posterior whereas this factorizes the expectations.
        (
            1.0
            - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
              * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
        ).clip(0.0, 1.0).alias("cqc_factorized_union_detectability"),
        (
            pl.col("p_detect_state").clip(0.0, 1.0)
            - (
                1.0
                - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
                  * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
              )
        ).alias("cqc_delta_state_vs_factorized_union"),
        (
            pl.col("p_detect_state").clip(0.0, 1.0)
            - (
                1.0
                - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
                  * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
              )
        ).abs().alias("cqc_abs_delta_state_vs_factorized_union"),
        # Historical aliases retained for downstream compatibility.
        (
            1.0
            - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
              * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
        ).clip(0.0, 1.0).alias("cqc_union_detectability"),
        (
            pl.col("p_detect_state").clip(0.0, 1.0)
            - (
                1.0
                - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
                  * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
              )
        ).alias("cqc_delta_detectability"),
        (
            pl.col("p_detect_state").clip(0.0, 1.0)
            - (
                1.0
                - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
                  * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
              )
        ).abs().alias("cqc_abs_delta_detectability"),
        (
            pl.col("p_detect_rep1").clip(0.0, 1.0)
            * pl.col("p_detect_rep2").clip(0.0, 1.0)
        ).sqrt().alias("cqc_replicate_joint_detection_evidence"),
        # Backward-compatible alias. This remains a replicate-level QC metric,
        # not the primary detectability of the latent biological state.
        (
            pl.col("p_detect_rep1").clip(0.0, 1.0)
            * pl.col("p_detect_rep2").clip(0.0, 1.0)
        ).sqrt().alias("cqc_joint_detection_evidence"),
        (pl.col("p_detect_rep1") - pl.col("p_detect_rep2")).abs()
            .alias("cqc_detection_imbalance"),
        delta.alias("cqc_replicate_abs_delta_x"),
        (delta / variance_sum.sqrt()).alias("cqc_replicate_standardized_delta"),
        (pl.col("x_latent_median") - pl.col("x_positive_current"))
            .alias("cqc_latent_minus_positive_x"),
        (pl.col("x_latent_median") - pl.col("x_positive_current")).abs()
            .alias("cqc_abs_latent_minus_positive_x"),
    ]

    if {"depth_rep1", "depth_rep2", "positive_replicate_source"}.issubset(names):
        zero_depth = (
            pl.when(pl.col("positive_replicate_source") == "REP1_ONLY")
            .then(pl.col("depth_rep2"))
            .when(pl.col("positive_replicate_source") == "REP2_ONLY")
            .then(pl.col("depth_rep1"))
            .otherwise(pl.lit(None, dtype=pl.Float64))
        )
        positive_depth = (
            pl.when(pl.col("positive_replicate_source") == "REP1_ONLY")
            .then(pl.col("depth_rep1"))
            .when(pl.col("positive_replicate_source") == "REP2_ONLY")
            .then(pl.col("depth_rep2"))
            .otherwise(pl.lit(None, dtype=pl.Float64))
        )
        expressions.extend([
            zero_depth.alias("cqc_zero_replicate_depth"),
            positive_depth.alias("cqc_positive_replicate_depth"),
            pl.when(zero_depth > 0).then(zero_depth.log()).otherwise(None)
                .alias("cqc_zero_replicate_log_depth"),
            pl.when(positive_depth > 0).then(positive_depth.log()).otherwise(None)
                .alias("cqc_positive_replicate_log_depth"),
        ])

    # Relative uncertainty in linear frequency space, where available.
    if all(c in names for c in ["f_latent_q025", "f_latent_q975", "f_latent_median"]):
        expressions.append(
            ((pl.col("f_latent_q975") - pl.col("f_latent_q025")) /
             pl.col("f_latent_median").abs().clip(lower_bound=EPS))
            .alias("cqc_posterior_relative_width95_f")
        )

    q = q.with_columns(expressions)

    # Gaussian fallback retained only when exact overlap is not supplied.
    scale_term = ((2.0 * s1 * s2) / variance_sum).clip(0.0, 1.0).sqrt()
    location_term = (-(delta.pow(2)) / (4.0 * variance_sum)).exp()
    q = q.with_columns(
        (scale_term * location_term).clip(0.0, 1.0)
        .alias("cqc_replicate_bhattacharyya_gaussian")
    )

    has_exact = "cqc_replicate_bhattacharyya_exact" in q.collect_schema().names()
    if has_exact:
        q = q.with_columns([
            pl.col("cqc_replicate_bhattacharyya_exact").clip(0.0, 1.0),
            pl.coalesce([
                pl.col("cqc_replicate_bhattacharyya_exact"),
                pl.col("cqc_replicate_bhattacharyya_gaussian"),
            ]).alias("cqc_replicate_bhattacharyya"),
            pl.when(pl.col("cqc_replicate_bhattacharyya_exact").is_not_null())
              .then(pl.lit("EXACT_DISCRETE_POSTERIOR"))
              .otherwise(pl.lit("GAUSSIAN_FALLBACK"))
              .alias("cqc_replicate_agreement_source"),
        ])
    else:
        q = q.with_columns([
            pl.col("cqc_replicate_bhattacharyya_gaussian")
              .alias("cqc_replicate_bhattacharyya"),
            pl.lit("GAUSSIAN_FALLBACK").alias("cqc_replicate_agreement_source"),
        ])

    q = q.with_columns(
        (1.0 - pl.col("cqc_replicate_bhattacharyya"))
        .clip(0.0, 1.0).sqrt().alias("cqc_replicate_hellinger")
    )

    diagnostic_cols = [
        "cqc_posterior_width95_x",
        "cqc_posterior_fold_range95",
        "cqc_posterior_sd_x",
        "cqc_posterior_entropy",
        "cqc_effective_posterior_support",
        "cqc_state_detectability",
        "cqc_state_dropout",
        "cqc_factorized_union_detectability",
        "cqc_delta_state_vs_factorized_union",
        "cqc_abs_delta_state_vs_factorized_union",
        "cqc_replicate_joint_detection_evidence",
        "cqc_detection_imbalance",
        "cqc_replicate_abs_delta_x",
        "cqc_replicate_standardized_delta",
        "cqc_replicate_bhattacharyya",
        "cqc_replicate_hellinger",
    ]
    qnames = q.collect_schema().names()
    if "cqc_posterior_relative_width95_f" in qnames:
        diagnostic_cols.append("cqc_posterior_relative_width95_f")
    if "cqc_effective_posterior_support_simpson" in qnames:
        diagnostic_cols.append("cqc_effective_posterior_support_simpson")

    valid_expr = pl.all_horizontal([pl.col(c).is_finite() for c in diagnostic_cols])
    q = q.with_columns([
        valid_expr.alias("cqc_diagnostics_valid"),
        pl.when(valid_expr).then(pl.lit("VALID")).otherwise(pl.lit("INVALID_NUMERICAL"))
            .alias("cqc_diagnostic_status"),
        pl.lit(True).alias("cqc_included_downstream"),
    ])
    return q, exact_source, support_source, positive_context_source


def write_csv(lf: pl.LazyFrame, path: Path) -> None:
    lf.collect(engine="streaming").write_csv(path)


def metric_summary(lf: pl.LazyFrame, metrics) -> pl.DataFrame:
    rows = []
    for metric in metrics:
        rows.append(lf.select([
            pl.lit(metric).alias("metric"),
            pl.col(metric).is_not_null().sum().alias("n_non_null"),
            pl.col(metric).is_finite().sum().alias("n_finite"),
            pl.col(metric).min().alias("min"),
            pl.col(metric).quantile(0.01).alias("q01"),
            pl.col(metric).quantile(0.025).alias("q025"),
            pl.col(metric).quantile(0.10).alias("q10"),
            pl.col(metric).quantile(0.25).alias("q25"),
            pl.col(metric).median().alias("median"),
            pl.col(metric).quantile(0.75).alias("q75"),
            pl.col(metric).quantile(0.90).alias("q90"),
            pl.col(metric).quantile(0.95).alias("q95"),
            pl.col(metric).quantile(0.975).alias("q975"),
            pl.col(metric).quantile(0.99).alias("q99"),
            pl.col(metric).max().alias("max"),
            pl.col(metric).mean().alias("mean"),
            pl.col(metric).std().alias("sd"),
        ]).collect(engine="streaming"))
    return pl.concat(rows)


def grouped_summary(lf: pl.LazyFrame, group_cols, output_path: Path) -> None:
    names = lf.collect_schema().names()
    aggs = [
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_diagnostics_valid").mean().alias("fraction_valid"),
        pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
        pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
        pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
        pl.col("cqc_posterior_entropy").median().alias("posterior_entropy_median"),
        pl.col("cqc_effective_posterior_support").median().alias("shannon_effective_support_median"),
        pl.col("cqc_state_detectability").median().alias("state_detectability_median"),
        pl.col("cqc_state_detectability").quantile(0.25).alias("state_detectability_q25"),
        pl.col("cqc_state_detectability").quantile(0.75).alias("state_detectability_q75"),
        pl.col("cqc_state_dropout").median().alias("state_dropout_median"),
        pl.col("cqc_factorized_union_detectability").median().alias("factorized_union_detectability_median"),
        pl.col("cqc_delta_state_vs_factorized_union").median().alias("delta_state_vs_factorized_union_median"),
        pl.col("cqc_delta_state_vs_factorized_union").quantile(0.25).alias("delta_state_vs_factorized_union_q25"),
        pl.col("cqc_delta_state_vs_factorized_union").quantile(0.75).alias("delta_state_vs_factorized_union_q75"),
        pl.col("cqc_abs_delta_state_vs_factorized_union").mean().alias("abs_delta_state_vs_factorized_union_mean"),
        pl.col("cqc_abs_delta_state_vs_factorized_union").max().alias("abs_delta_state_vs_factorized_union_max"),
        # Historical summary aliases.
        pl.col("cqc_union_detectability").median().alias("union_detectability_median"),
        pl.col("cqc_delta_detectability").median().alias("delta_detectability_median"),
        pl.col("cqc_delta_detectability").quantile(0.25).alias("delta_detectability_q25"),
        pl.col("cqc_delta_detectability").quantile(0.75).alias("delta_detectability_q75"),
        pl.col("cqc_abs_delta_detectability").mean().alias("abs_delta_detectability_mean"),
        pl.col("cqc_abs_delta_detectability").max().alias("abs_delta_detectability_max"),
        pl.col("cqc_replicate_joint_detection_evidence").median().alias("replicate_joint_detection_median"),
        pl.col("cqc_replicate_joint_detection_evidence").quantile(0.25).alias("replicate_joint_detection_q25"),
        pl.col("cqc_replicate_joint_detection_evidence").quantile(0.75).alias("replicate_joint_detection_q75"),
        pl.col("cqc_replicate_bhattacharyya").median().alias("replicate_bc_median"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.25).alias("replicate_bc_q25"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.75).alias("replicate_bc_q75"),
        pl.col("cqc_replicate_standardized_delta").median().alias("replicate_z_median"),
        pl.col("cqc_replicate_standardized_delta").quantile(0.25).alias("replicate_z_q25"),
        pl.col("cqc_replicate_standardized_delta").quantile(0.75).alias("replicate_z_q75"),
        pl.col("cqc_detection_imbalance").median().alias("detection_imbalance_median"),
        (pl.col("cqc_replicate_agreement_source") == "EXACT_DISCRETE_POSTERIOR")
            .mean().alias("fraction_exact_posterior_overlap"),
    ]
    if "cqc_effective_posterior_support_simpson" in names:
        aggs.extend([
            pl.col("cqc_effective_posterior_support_simpson").median().alias("inverse_simpson_support_median"),
            pl.col("cqc_effective_posterior_support_simpson").quantile(0.25).alias("inverse_simpson_support_q25"),
            pl.col("cqc_effective_posterior_support_simpson").quantile(0.75).alias("inverse_simpson_support_q75"),
        ])
    write_csv(lf.group_by(group_cols).agg(aggs).sort(group_cols), output_path)


def write_abundance_reference(lf: pl.LazyFrame, output_path: Path) -> None:
    if "x_latent_median" not in lf.collect_schema().names():
        return
    out = lf.select([
        pl.col("x_latent_median").quantile(0.025).alias("x_q025"),
        pl.col("x_latent_median").median().alias("x_median"),
        pl.col("x_latent_median").quantile(0.975).alias("x_q975"),
        pl.len().alias("n_clonotype_timepoints"),
    ]).collect(engine="streaming")
    out.write_csv(output_path)


def write_abundance_summary(lf: pl.LazyFrame, output_path: Path, bin_width: float) -> None:
    if "x_latent_median" not in lf.collect_schema().names():
        return
    binned = lf.with_columns(
        ((pl.col("x_latent_median") / pl.lit(bin_width)).floor() * pl.lit(bin_width))
        .alias("x_bin_left")
    ).with_columns((pl.col("x_bin_left") + pl.lit(bin_width)).alias("x_bin_right"))
    grouped_summary(binned, ["x_bin_left", "x_bin_right"], output_path)



def write_detection_summary(lf: pl.LazyFrame, output_path: Path, bin_width: float) -> None:
    """Summarize posterior width and replicate overlap across state detectability."""
    d = lf.with_columns(
        ((pl.col("cqc_state_detectability").clip(0.0, 1.0 - EPS) / pl.lit(bin_width)).floor() * pl.lit(bin_width))
        .alias("detection_bin_left")
    ).with_columns(
        (pl.col("detection_bin_left") + pl.lit(bin_width)).clip(upper_bound=1.0)
        .alias("detection_bin_right")
    )
    out = d.group_by(["detection_bin_left", "detection_bin_right"]).agg([
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
        pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
        pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
        pl.col("cqc_replicate_bhattacharyya").median().alias("replicate_bc_median"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.25).alias("replicate_bc_q25"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.75).alias("replicate_bc_q75"),
    ]).sort("detection_bin_left")
    write_csv(out, output_path)


def write_replicate_z_summary(
    lf: pl.LazyFrame, output_path: Path, bin_width: float, z_max: float
) -> None:
    """Summarize posterior uncertainty across standardized replicate differences."""
    z = pl.col("cqc_replicate_standardized_delta").clip(0.0, z_max - EPS)
    d = lf.with_columns(
        ((z / pl.lit(bin_width)).floor() * pl.lit(bin_width)).alias("replicate_z_bin_left")
    ).with_columns(
        (pl.col("replicate_z_bin_left") + pl.lit(bin_width)).clip(upper_bound=z_max)
        .alias("replicate_z_bin_right")
    )
    out = d.group_by(["replicate_z_bin_left", "replicate_z_bin_right"]).agg([
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
        pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
        pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
    ]).sort("replicate_z_bin_left")
    write_csv(out, output_path)


def _spearman_from_unit_frame(df: pl.DataFrame, x: str, y: str) -> Optional[float]:
    """Spearman rho across aggregated analysis units, or None if undefined."""
    if df.height < 3:
        return None
    finite = df.filter(pl.col(x).is_finite() & pl.col(y).is_finite())
    if finite.height < 3:
        return None
    if finite.get_column(x).n_unique() < 2 or finite.get_column(y).n_unique() < 2:
        return None
    value = finite.select(pl.corr(x, y, method="spearman").alias("rho"))["rho"][0]
    return float(value) if value is not None else None


def _pearson_from_unit_frame(df: pl.DataFrame, x: str, y: str) -> Optional[float]:
    """Pearson r across aggregated analysis units, or None if undefined."""
    if df.height < 3:
        return None
    finite = df.filter(pl.col(x).is_finite() & pl.col(y).is_finite())
    if finite.height < 3:
        return None
    if finite.get_column(x).n_unique() < 2 or finite.get_column(y).n_unique() < 2:
        return None
    value = finite.select(pl.corr(x, y, method="pearson").alias("r"))["r"][0]
    return float(value) if value is not None else None


def _linear_fit_from_unit_frame(df: pl.DataFrame, x: str, y: str) -> dict:
    """Simple OLS y ~ intercept + slope*x across aggregated analysis units."""
    finite = df.filter(pl.col(x).is_finite() & pl.col(y).is_finite())
    if finite.height < 3:
        return {"n": int(finite.height), "slope": None, "intercept": None, "r2": None}
    xv = np.asarray(finite.get_column(x).to_list(), dtype=float)
    yv = np.asarray(finite.get_column(y).to_list(), dtype=float)
    if np.unique(xv).size < 2 or np.unique(yv).size < 2:
        return {"n": int(finite.height), "slope": None, "intercept": None, "r2": None}
    x_mean = float(np.mean(xv))
    y_mean = float(np.mean(yv))
    ss_x = float(np.sum((xv - x_mean) ** 2))
    if not np.isfinite(ss_x) or ss_x <= 0:
        return {"n": int(finite.height), "slope": None, "intercept": None, "r2": None}
    slope = float(np.sum((xv - x_mean) * (yv - y_mean)) / ss_x)
    intercept = float(y_mean - slope * x_mean)
    fitted = intercept + slope * xv
    ss_tot = float(np.sum((yv - y_mean) ** 2))
    ss_res = float(np.sum((yv - fitted) ** 2))
    r2 = float(1.0 - ss_res / ss_tot) if ss_tot > 0 else None
    return {"n": int(finite.height), "slope": slope, "intercept": intercept, "r2": r2}


def _summarize_zero_depth_units(df: pl.DataFrame, scope: str, zero_replicate: str) -> dict:
    """Create one pair-aware summary row from subject-time-zero-replicate units."""
    empty = {
        "scope": scope,
        "zero_replicate": zero_replicate,
        "n_analysis_units": 0,
        "n_subjects": 0,
        "n_subject_timepoints": 0,
        "median_one_positive_clonotypes_per_unit": None,
        "q25_one_positive_clonotypes_per_unit": None,
        "q75_one_positive_clonotypes_per_unit": None,
        "spearman_zero_log_depth_vs_unit_median_latent_minus_positive_x": None,
        "spearman_zero_log_depth_vs_unit_median_abs_latent_minus_positive_x": None,
        "spearman_relative_log_depth_vs_unit_median_latent_minus_positive_x": None,
        "spearman_relative_log_depth_vs_unit_median_abs_latent_minus_positive_x": None,
        "median_delta_log_depth_zero_minus_positive": None,
        "q25_delta_log_depth_zero_minus_positive": None,
        "q75_delta_log_depth_zero_minus_positive": None,
        "median_unit_latent_minus_positive_x": None,
        "median_unit_abs_latent_minus_positive_x": None,
        "analysis_unit": "subject_time_zero_replicate",
        "primary_depth_descriptor": "delta_log_depth_zero_minus_positive",
    }
    if df.is_empty():
        return empty

    n_subject_timepoints = df.select(["subject", "time"]).unique().height
    out = dict(empty)
    out.update({
        "n_analysis_units": int(df.height),
        "n_subjects": int(df.get_column("subject").n_unique()),
        "n_subject_timepoints": int(n_subject_timepoints),
        "median_one_positive_clonotypes_per_unit": float(df.get_column("n_one_positive_clonotypes").median()),
        "q25_one_positive_clonotypes_per_unit": float(df.get_column("n_one_positive_clonotypes").quantile(0.25)),
        "q75_one_positive_clonotypes_per_unit": float(df.get_column("n_one_positive_clonotypes").quantile(0.75)),
        "spearman_zero_log_depth_vs_unit_median_latent_minus_positive_x": _spearman_from_unit_frame(
            df, "zero_replicate_log_depth", "median_latent_minus_positive_x"
        ),
        "spearman_zero_log_depth_vs_unit_median_abs_latent_minus_positive_x": _spearman_from_unit_frame(
            df, "zero_replicate_log_depth", "median_abs_latent_minus_positive_x"
        ),
        "spearman_relative_log_depth_vs_unit_median_latent_minus_positive_x": _spearman_from_unit_frame(
            df, "delta_log_depth_zero_minus_positive", "median_latent_minus_positive_x"
        ),
        "spearman_relative_log_depth_vs_unit_median_abs_latent_minus_positive_x": _spearman_from_unit_frame(
            df, "delta_log_depth_zero_minus_positive", "median_abs_latent_minus_positive_x"
        ),
        "median_delta_log_depth_zero_minus_positive": float(df.get_column("delta_log_depth_zero_minus_positive").median()),
        "q25_delta_log_depth_zero_minus_positive": float(df.get_column("delta_log_depth_zero_minus_positive").quantile(0.25)),
        "q75_delta_log_depth_zero_minus_positive": float(df.get_column("delta_log_depth_zero_minus_positive").quantile(0.75)),
        "median_unit_latent_minus_positive_x": float(df.get_column("median_latent_minus_positive_x").median()),
        "median_unit_abs_latent_minus_positive_x": float(df.get_column("median_abs_latent_minus_positive_x").median()),
    })
    return out


def _build_paired_replica_depth_frame(unit_df: pl.DataFrame) -> pl.DataFrame:
    """Match the two ONE_POSITIVE zero orientations within subject-timepoint."""
    if unit_df.is_empty():
        return pl.DataFrame()

    zero1 = (
        unit_df.filter(pl.col("zero_replicate") == "REP1")
        .select([
            "subject", "time",
            pl.col("zero_replicate_depth").alias("depth_rep1_from_zero1"),
            pl.col("positive_replicate_depth").alias("depth_rep2_from_zero1"),
            pl.col("n_one_positive_clonotypes").alias("n_one_positive_zero_rep1"),
            pl.col("median_latent_minus_positive_x").alias("median_shift_zero_rep1"),
            pl.col("median_abs_latent_minus_positive_x").alias("median_abs_shift_zero_rep1"),
        ])
    )
    zero2 = (
        unit_df.filter(pl.col("zero_replicate") == "REP2")
        .select([
            "subject", "time",
            pl.col("positive_replicate_depth").alias("depth_rep1_from_zero2"),
            pl.col("zero_replicate_depth").alias("depth_rep2_from_zero2"),
            pl.col("n_one_positive_clonotypes").alias("n_one_positive_zero_rep2"),
            pl.col("median_latent_minus_positive_x").alias("median_shift_zero_rep2"),
            pl.col("median_abs_latent_minus_positive_x").alias("median_abs_shift_zero_rep2"),
        ])
    )

    paired = zero1.join(zero2, on=["subject", "time"], how="inner")
    if paired.is_empty():
        return paired

    depth1 = 0.5 * (pl.col("depth_rep1_from_zero1") + pl.col("depth_rep1_from_zero2"))
    depth2 = 0.5 * (pl.col("depth_rep2_from_zero1") + pl.col("depth_rep2_from_zero2"))
    log_ratio = (depth1 / depth2).log()
    delta_shift = pl.col("median_shift_zero_rep1") - pl.col("median_shift_zero_rep2")

    return (
        paired.with_columns([
            depth1.alias("depth_rep1"),
            depth2.alias("depth_rep2"),
            (pl.col("depth_rep1_from_zero1") - pl.col("depth_rep1_from_zero2")).abs()
                .alias("depth_rep1_consistency_abs_difference"),
            (pl.col("depth_rep2_from_zero1") - pl.col("depth_rep2_from_zero2")).abs()
                .alias("depth_rep2_consistency_abs_difference"),
            log_ratio.alias("log_depth_ratio_rep1_over_rep2"),
            delta_shift.alias("delta_shift_zero_rep1_minus_zero_rep2"),
            (pl.col("median_abs_shift_zero_rep1") - pl.col("median_abs_shift_zero_rep2"))
                .alias("delta_abs_shift_zero_rep1_minus_zero_rep2"),
        ])
        .with_columns([
            pl.when(
                pl.col("log_depth_ratio_rep1_over_rep2").is_finite()
                & pl.col("delta_shift_zero_rep1_minus_zero_rep2").is_finite()
                & (pl.col("log_depth_ratio_rep1_over_rep2") != 0)
                & (pl.col("delta_shift_zero_rep1_minus_zero_rep2") != 0)
            )
            .then(
                (pl.col("log_depth_ratio_rep1_over_rep2")
                 * pl.col("delta_shift_zero_rep1_minus_zero_rep2")) < 0
            )
            .otherwise(None)
            .alias("directionally_concordant_deeper_zero_more_negative")
        ])
        .sort(["subject", "time"])
    )


def _summarize_paired_replica_depth(paired: pl.DataFrame) -> dict:
    """Summarize the within-subject-time paired depth-orientation diagnostic."""
    empty = {
        "n_complete_subject_timepoints": 0,
        "n_subjects": 0,
        "n_complete_for_primary_relation": 0,
        "spearman_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": None,
        "pearson_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": None,
        "linear_slope_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": None,
        "linear_intercept_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": None,
        "linear_r2_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": None,
        "spearman_log_depth_ratio_rep1_over_rep2_vs_delta_abs_shift_zero_rep1_minus_zero_rep2": None,
        "pearson_log_depth_ratio_rep1_over_rep2_vs_delta_abs_shift_zero_rep1_minus_zero_rep2": None,
        "fraction_directionally_concordant_deeper_zero_more_negative": None,
        "median_abs_log_depth_ratio_rep1_over_rep2": None,
        "median_abs_delta_shift_zero_rep1_minus_zero_rep2": None,
        "max_depth_rep1_consistency_abs_difference": None,
        "max_depth_rep2_consistency_abs_difference": None,
        "analysis_unit": "subject_time_paired_zero_orientations",
        "primary_relation": (
            "log_depth_ratio_rep1_over_rep2 vs "
            "delta_shift_zero_rep1_minus_zero_rep2"
        ),
    }
    if paired.is_empty():
        return empty

    primary_fit = _linear_fit_from_unit_frame(
        paired,
        "log_depth_ratio_rep1_over_rep2",
        "delta_shift_zero_rep1_minus_zero_rep2",
    )
    directional = paired.get_column(
        "directionally_concordant_deeper_zero_more_negative"
    ).drop_nulls()

    out = dict(empty)
    out.update({
        "n_complete_subject_timepoints": int(paired.height),
        "n_subjects": int(paired.get_column("subject").n_unique()),
        "n_complete_for_primary_relation": int(primary_fit["n"]),
        "spearman_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": _spearman_from_unit_frame(
            paired, "log_depth_ratio_rep1_over_rep2", "delta_shift_zero_rep1_minus_zero_rep2"
        ),
        "pearson_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": _pearson_from_unit_frame(
            paired, "log_depth_ratio_rep1_over_rep2", "delta_shift_zero_rep1_minus_zero_rep2"
        ),
        "linear_slope_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": primary_fit["slope"],
        "linear_intercept_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": primary_fit["intercept"],
        "linear_r2_log_depth_ratio_rep1_over_rep2_vs_delta_shift_zero_rep1_minus_zero_rep2": primary_fit["r2"],
        "spearman_log_depth_ratio_rep1_over_rep2_vs_delta_abs_shift_zero_rep1_minus_zero_rep2": _spearman_from_unit_frame(
            paired, "log_depth_ratio_rep1_over_rep2", "delta_abs_shift_zero_rep1_minus_zero_rep2"
        ),
        "pearson_log_depth_ratio_rep1_over_rep2_vs_delta_abs_shift_zero_rep1_minus_zero_rep2": _pearson_from_unit_frame(
            paired, "log_depth_ratio_rep1_over_rep2", "delta_abs_shift_zero_rep1_minus_zero_rep2"
        ),
        "fraction_directionally_concordant_deeper_zero_more_negative": (
            float(directional.cast(pl.Float64).mean()) if len(directional) else None
        ),
        "median_abs_log_depth_ratio_rep1_over_rep2": float(
            paired.get_column("log_depth_ratio_rep1_over_rep2").abs().median()
        ),
        "median_abs_delta_shift_zero_rep1_minus_zero_rep2": float(
            paired.get_column("delta_shift_zero_rep1_minus_zero_rep2").abs().median()
        ),
        "max_depth_rep1_consistency_abs_difference": float(
            paired.get_column("depth_rep1_consistency_abs_difference").max()
        ),
        "max_depth_rep2_consistency_abs_difference": float(
            paired.get_column("depth_rep2_consistency_abs_difference").max()
        ),
    })
    return out


def write_positive_state_summaries(lf: pl.LazyFrame, output_dir: Path) -> None:
    """Summarize positive-state support and pair-aware/paired depth diagnostics."""
    names = set(lf.collect_schema().names())
    if "positive_state_class" not in names:
        return

    total = lf.select(pl.len().alias("n")).collect(engine="streaming")["n"][0]
    summary = (
        lf.group_by("positive_state_class")
        .agg([
            pl.len().alias("n_clonotype_timepoints"),
            pl.col("cqc_diagnostics_valid").mean().alias("fraction_valid"),
            pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
            pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
            pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
            pl.col("cqc_posterior_entropy").median().alias("posterior_entropy_median"),
            pl.col("cqc_state_detectability").median().alias("state_detectability_median"),
            pl.col("cqc_replicate_bhattacharyya").median().alias("replicate_bc_median"),
            pl.col("cqc_replicate_standardized_delta").median().alias("replicate_z_median"),
            pl.col("cqc_latent_minus_positive_x").median().alias("latent_minus_positive_x_median"),
            pl.col("cqc_latent_minus_positive_x").quantile(0.25).alias("latent_minus_positive_x_q25"),
            pl.col("cqc_latent_minus_positive_x").quantile(0.75).alias("latent_minus_positive_x_q75"),
            pl.col("cqc_abs_latent_minus_positive_x").median().alias("abs_latent_minus_positive_x_median"),
            pl.col("cqc_abs_delta_state_vs_factorized_union").median().alias("abs_state_vs_factorized_union_median"),
            # Historical summary alias retained for compatibility.
            pl.col("cqc_abs_delta_detectability").median().alias("abs_detectability_discrepancy_median"),
        ])
        .with_columns((pl.col("n_clonotype_timepoints") / pl.lit(float(total))).alias("fraction_of_all_states"))
        .sort("positive_state_class")
    )
    write_csv(summary, output_dir / "clonotype_latent_posterior_qc_by_positive_state.csv")

    class_summary = (
        lf.group_by(["positive_state_class", "positive_replicate_source"])
        .agg(pl.len().alias("n_clonotype_timepoints"))
        .with_columns((pl.col("n_clonotype_timepoints") / pl.lit(float(total))).alias("fraction_of_all_states"))
        .sort(["positive_state_class", "positive_replicate_source"])
    )
    write_csv(class_summary, output_dir / "state_representation_class_summary.csv")

    required = {
        "subject", "time", "positive_replicate_source",
        "cqc_zero_replicate_depth", "cqc_zero_replicate_log_depth",
        "cqc_positive_replicate_depth",
        "cqc_latent_minus_positive_x", "cqc_abs_latent_minus_positive_x",
    }
    if not required.issubset(names):
        return

    # Sequencing depth is a technical-replicate-level variable. ONE_POSITIVE
    # clonotypes are therefore collapsed before any depth correlation is
    # computed. The analysis unit is subject x time x zero-replicate side.
    one_units_lf = (
        lf.filter(
            (pl.col("positive_state_class") == "ONE_POSITIVE")
            & pl.col("positive_replicate_source").is_in(["REP1_ONLY", "REP2_ONLY"])
            & pl.col("cqc_zero_replicate_log_depth").is_finite()
            & pl.col("cqc_latent_minus_positive_x").is_finite()
        )
        .group_by(["subject", "time", "positive_replicate_source"])
        .agg([
            pl.len().alias("n_one_positive_clonotypes"),
            pl.col("cqc_zero_replicate_depth").n_unique().alias("n_unique_zero_depth_values"),
            pl.col("cqc_positive_replicate_depth").n_unique().alias("n_unique_positive_depth_values"),
            pl.col("cqc_zero_replicate_depth").median().alias("zero_replicate_depth"),
            pl.col("cqc_zero_replicate_log_depth").median().alias("zero_replicate_log_depth"),
            pl.col("cqc_positive_replicate_depth").median().alias("positive_replicate_depth"),
            pl.col("cqc_latent_minus_positive_x").median().alias("median_latent_minus_positive_x"),
            pl.col("cqc_latent_minus_positive_x").quantile(0.25).alias("q25_latent_minus_positive_x"),
            pl.col("cqc_latent_minus_positive_x").quantile(0.75).alias("q75_latent_minus_positive_x"),
            pl.col("cqc_abs_latent_minus_positive_x").median().alias("median_abs_latent_minus_positive_x"),
            pl.col("cqc_posterior_width95_x").median().alias("median_posterior_width95_x"),
            pl.col("cqc_state_detectability").median().alias("median_state_detectability"),
        ])
        .with_columns([
            pl.when(pl.col("positive_replicate_source") == "REP1_ONLY")
              .then(pl.lit("REP2"))
              .when(pl.col("positive_replicate_source") == "REP2_ONLY")
              .then(pl.lit("REP1"))
              .otherwise(pl.lit("UNKNOWN"))
              .alias("zero_replicate"),
            pl.when(pl.col("positive_replicate_source") == "REP1_ONLY")
              .then(pl.lit("REP1"))
              .when(pl.col("positive_replicate_source") == "REP2_ONLY")
              .then(pl.lit("REP2"))
              .otherwise(pl.lit("UNKNOWN"))
              .alias("positive_replicate"),
            pl.when(pl.col("positive_replicate_depth") > 0)
              .then(pl.col("positive_replicate_depth").log())
              .otherwise(None)
              .alias("positive_replicate_log_depth"),
        ])
        .with_columns([
            (pl.col("zero_replicate_log_depth") - pl.col("positive_replicate_log_depth"))
                .alias("delta_log_depth_zero_minus_positive"),
            pl.when(pl.col("positive_replicate_depth") > 0)
              .then(pl.col("zero_replicate_depth") / pl.col("positive_replicate_depth"))
              .otherwise(None)
              .alias("depth_ratio_zero_over_positive"),
        ])
        .sort(["subject", "time", "zero_replicate"])
    )

    unit_df = one_units_lf.collect(engine="streaming")
    unit_df.write_csv(output_dir / "one_positive_zero_depth_by_subject_time_replica.csv")

    summary_rows = [
        _summarize_zero_depth_units(unit_df, "ALL_ONE_POSITIVE_UNITS", "BOTH_SIDES"),
        _summarize_zero_depth_units(
            unit_df.filter(pl.col("zero_replicate") == "REP1"),
            "ZERO_REPLICATE_1", "REP1"
        ),
        _summarize_zero_depth_units(
            unit_df.filter(pl.col("zero_replicate") == "REP2"),
            "ZERO_REPLICATE_2", "REP2"
        ),
    ]
    pl.DataFrame(summary_rows).write_csv(output_dir / "one_positive_zero_depth_diagnostic.csv")

    paired_df = _build_paired_replica_depth_frame(unit_df)
    paired_df.write_csv(output_dir / "one_positive_paired_replica_depth_by_subject_time.csv")
    pl.DataFrame([_summarize_paired_replica_depth(paired_df)]).write_csv(
        output_dir / "one_positive_paired_replica_depth_diagnostic.csv"
    )


SPEARMAN_BASE_METRICS = [
    "cqc_posterior_width95_x",
    "cqc_posterior_entropy",
    "cqc_state_detectability",
    "cqc_factorized_union_detectability",
    "cqc_replicate_bhattacharyya",
]


def _full_data_spearman_pair(lf: pl.LazyFrame, a: str, b: str) -> tuple:
    """Return pairwise-finite n and Spearman rho using only two columns in memory."""
    pair = lf.select([a, b]).filter(
        pl.col(a).is_finite() & pl.col(b).is_finite()
    )
    out = pair.select([
        pl.len().alias("n_complete"),
        pl.corr(a, b, method="spearman").alias("spearman_rho"),
    ]).collect()
    return int(out["n_complete"][0]), float(out["spearman_rho"][0])


def write_full_dataset_spearman(lf: pl.LazyFrame, output_dir: Path) -> None:
    """Export manuscript Spearman statistics from the full QC dataset.

    Correlations are computed pairwise from the complete QC parquet. Processing
    one metric pair at a time deliberately limits peak memory use on large
    clonotype-level tables; plotting subsamples are never used for these values.
    """
    names = lf.collect_schema().names()
    matrix_metrics = [c for c in SPEARMAN_BASE_METRICS if c in names]
    if "cqc_effective_posterior_support_simpson" in names:
        matrix_metrics.append("cqc_effective_posterior_support_simpson")

    required_for_key = [
        "cqc_posterior_width95_x",
        "cqc_state_detectability",
        "cqc_abs_delta_state_vs_factorized_union",
    ]
    missing = [c for c in required_for_key if c not in names]
    if missing:
        raise ValueError(
            "Cannot compute full-dataset QC correlations; missing columns: %s" %
            ", ".join(missing)
        )

    requested_pairs = []
    for i, a in enumerate(matrix_metrics):
        for j in range(i + 1, len(matrix_metrics)):
            requested_pairs.append((a, matrix_metrics[j]))
    requested_pairs.extend([
        ("cqc_posterior_width95_x", "cqc_abs_delta_state_vs_factorized_union"),
        ("cqc_state_detectability", "cqc_abs_delta_state_vs_factorized_union"),
    ])

    # Deduplicate without changing deterministic order.
    unique_pairs = []
    seen = set()
    for a, b in requested_pairs:
        key = tuple(sorted((a, b)))
        if key not in seen:
            seen.add(key)
            unique_pairs.append((a, b))

    pair_stats = {}
    total = len(unique_pairs)
    for idx, (a, b) in enumerate(unique_pairs, start=1):
        print("[STEP3] Full-data Spearman %d/%d: %s vs %s" % (idx, total, a, b))
        n_complete, rho = _full_data_spearman_pair(lf, a, b)
        pair_stats[(a, b)] = (n_complete, rho)
        pair_stats[(b, a)] = (n_complete, rho)

    matrix_rows = []
    n_rows = []
    for a in matrix_metrics:
        corr_row = {"metric": a}
        n_row = {"metric": a}
        for b in matrix_metrics:
            if a == b:
                # The diagonal is exactly one; n is the finite count for that metric.
                n_diag = int(
                    lf.select(pl.col(a).is_finite().sum().alias("n")).collect()["n"][0]
                )
                corr_row[b] = 1.0
                n_row[b] = n_diag
            else:
                n_complete, rho = pair_stats[(a, b)]
                corr_row[b] = rho
                n_row[b] = n_complete
        matrix_rows.append(corr_row)
        n_rows.append(n_row)

    pl.DataFrame(matrix_rows).write_csv(
        output_dir / "qc_metric_spearman_correlations.csv"
    )
    pl.DataFrame(n_rows).write_csv(
        output_dir / "qc_metric_spearman_n_complete.csv"
    )

    key_pairs = [
        (
            "posterior_width95_vs_abs_state_factorized_union_delta",
            "cqc_posterior_width95_x",
            "cqc_abs_delta_state_vs_factorized_union",
        ),
        (
            "state_detectability_vs_abs_state_factorized_union_delta",
            "cqc_state_detectability",
            "cqc_abs_delta_state_vs_factorized_union",
        ),
    ]
    key_rows = []
    for relationship, x_metric, y_metric in key_pairs:
        n_complete, rho = pair_stats[(x_metric, y_metric)]
        key_rows.append({
            "relationship": relationship,
            "x_metric": x_metric,
            "y_metric": y_metric,
            "n_complete": n_complete,
            "spearman_rho": rho,
        })
    pl.DataFrame(key_rows).write_csv(
        output_dir / "clonotype_latent_posterior_qc_key_relationships.csv"
    )

    pl.DataFrame({
        "matrix_metrics": [";".join(matrix_metrics)],
        "correlation_definition": ["Spearman rank correlation"],
        "data_scope": ["full QC parquet; pairwise finite rows"],
        "plotting_sample_used": [False],
    }).write_csv(output_dir / "qc_metric_spearman_metadata.csv")

def write_summaries(parquet_path: Path, output_dir: Path, abundance_bin_width: float, detection_bin_width: float, replicate_z_bin_width: float, replicate_z_max: float) -> None:
    lf = pl.scan_parquet(parquet_path)
    metrics = [
        "cqc_posterior_width95_x", "cqc_posterior_fold_range95",
        "cqc_posterior_sd_x", "cqc_posterior_entropy",
        "cqc_effective_posterior_support", "cqc_posterior_entropy_normalized",
        "cqc_state_detectability", "cqc_state_dropout",
        "cqc_factorized_union_detectability",
        "cqc_delta_state_vs_factorized_union",
        "cqc_abs_delta_state_vs_factorized_union",
        "cqc_union_detectability", "cqc_delta_detectability",
        "cqc_abs_delta_detectability",
        "cqc_replicate_joint_detection_evidence", "cqc_joint_detection_evidence",
        "cqc_detection_imbalance",
        "cqc_replicate_abs_delta_x", "cqc_replicate_standardized_delta",
        "cqc_replicate_bhattacharyya", "cqc_replicate_hellinger",
        "cqc_replicate_bhattacharyya_gaussian",
        "cqc_latent_minus_positive_x", "cqc_abs_latent_minus_positive_x",
    ]
    names = lf.collect_schema().names()
    for optional in ["cqc_posterior_relative_width95_f", "cqc_replicate_bhattacharyya_exact", "cqc_effective_posterior_support_simpson", "logP"]:
        if optional in names:
            metrics.append(optional)
    metric_summary(lf, metrics).write_csv(
        output_dir / "clonotype_latent_posterior_qc_metric_summary.csv"
    )
    write_state_detectability_factorized_union_diagnostic(lf, output_dir)
    write_positive_state_summaries(lf, output_dir)
    write_full_dataset_spearman(lf, output_dir)

    status = (
        lf.group_by(["cqc_diagnostic_status", "cqc_replicate_agreement_source"])
        .agg(pl.len().alias("n"))
        .with_columns((pl.col("n") / pl.col("n").sum()).alias("fraction"))
        .sort("n", descending=True)
    )
    write_csv(status, output_dir / "clonotype_latent_posterior_qc_status_summary.csv")
    grouped_summary(lf, ["subject"], output_dir / "clonotype_latent_posterior_qc_subject_summary.csv")
    grouped_summary(lf, ["subject", "time"], output_dir / "clonotype_latent_posterior_qc_pair_summary.csv")
    write_abundance_reference(
        lf, output_dir / "clonotype_latent_posterior_qc_abundance_reference.csv"
    )
    write_abundance_summary(
        lf, output_dir / "clonotype_latent_posterior_qc_by_abundance.csv", abundance_bin_width
    )
    write_detection_summary(
        lf, output_dir / "clonotype_latent_posterior_qc_by_detection.csv", detection_bin_width
    )
    write_replicate_z_summary(
        lf, output_dir / "clonotype_latent_posterior_qc_by_replicate_difference.csv",
        replicate_z_bin_width, replicate_z_max
    )


def write_state_detectability_factorized_union_diagnostic(
    lf: pl.LazyFrame, output_dir: Path
) -> None:
    """Compare exact paired-state detectability with the factorized-union approximation.

    The quantities are not expected to be identical: the exact state-level
    dropout integrates q1(f)q2(f) over the shared posterior, whereas the
    factorized union combines the separately integrated replicate dropout
    probabilities. The difference therefore quantifies posterior coupling, not
    calibration error.
    """
    finite = lf.filter(
        pl.all_horizontal([
            pl.col("cqc_state_detectability").is_finite(),
            pl.col("cqc_factorized_union_detectability").is_finite(),
            pl.col("cqc_delta_state_vs_factorized_union").is_finite(),
            pl.col("cqc_abs_delta_state_vs_factorized_union").is_finite(),
            pl.col("cqc_state_dropout").is_finite(),
        ])
    )
    summary = finite.select([
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_delta_state_vs_factorized_union").mean().alias(
            "mean_signed_delta_state_minus_factorized_union"
        ),
        pl.col("cqc_abs_delta_state_vs_factorized_union").mean().alias(
            "mean_absolute_delta_state_vs_factorized_union"
        ),
        pl.col("cqc_abs_delta_state_vs_factorized_union").median().alias(
            "median_absolute_delta_state_vs_factorized_union"
        ),
        pl.col("cqc_abs_delta_state_vs_factorized_union").quantile(0.99).alias(
            "q99_absolute_delta_state_vs_factorized_union"
        ),
        pl.col("cqc_abs_delta_state_vs_factorized_union").max().alias(
            "max_absolute_delta_state_vs_factorized_union"
        ),
        (pl.col("cqc_abs_delta_state_vs_factorized_union") > 1e-12).mean().alias(
            "fraction_abs_delta_gt_1e_12"
        ),
        (pl.col("cqc_abs_delta_state_vs_factorized_union") > 1e-6).mean().alias(
            "fraction_abs_delta_gt_1e_6"
        ),
        (pl.col("cqc_abs_delta_state_vs_factorized_union") > 1e-3).mean().alias(
            "fraction_abs_delta_gt_1e_3"
        ),
        (pl.col("cqc_state_detectability") + pl.col("cqc_state_dropout") - 1.0)
            .abs().max().alias("max_state_dropout_complementarity_error"),
        pl.corr(
            "cqc_state_detectability",
            "cqc_factorized_union_detectability",
            method="pearson",
        ).alias("pearson_state_vs_factorized_union"),
        pl.corr(
            "cqc_state_detectability",
            "cqc_factorized_union_detectability",
            method="spearman",
        ).alias("spearman_state_vs_factorized_union"),
    ]).collect(engine="streaming")

    summary.write_csv(
        output_dir / "state_detectability_factorized_union_diagnostic.csv"
    )

    # Compatibility aliases. These files contain the same posterior-coupling
    # diagnostic and must not be described as independent validation.
    summary.write_csv(
        output_dir / "state_detectability_internal_consistency_summary.csv"
    )
    summary.write_csv(
        output_dir / "state_detectability_validation_summary.csv"
    )


# Backward-compatible callable alias for external imports.
def write_state_detectability_internal_consistency(
    lf: pl.LazyFrame, output_dir: Path
) -> None:
    write_state_detectability_factorized_union_diagnostic(lf, output_dir)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Diagnose the Step-2 latent consensus and observation-model outputs without filtering or redefining downstream estimands."
    )
    p.add_argument("--input", type=Path, required=True)
    p.add_argument("--input-pattern", default="per_clone_latent_subject.parquet")
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--clone-col", default="aaSeqCDR3")
    p.add_argument("--grid-size", type=int, default=500)
    p.add_argument("--abundance-bin-width", type=float, default=1.0)
    p.add_argument("--compression", default="zstd")
    p.add_argument("--detection-bin-width", type=float, default=0.02,
                   help="Bin width for state-detectability summaries.")
    p.add_argument("--replicate-z-bin-width", type=float, default=0.25,
                   help="Bin width for standardized replicate-difference summaries.")
    p.add_argument("--replicate-z-max", type=float, default=5.0,
                   help="Upper clipping bound for standardized-difference summaries.")
    p.add_argument("--exact-overlap-table", type=Path, default=None,
                   help="Optional table keyed by subject,time,clone with exact discrete-posterior BC.")
    p.add_argument("--exact-bc-col", default=None,
                   help="Name of exact BC column in input or --exact-overlap-table.")
    p.add_argument("--require-exact-overlap", action="store_true",
                   help="Fail rather than use Gaussian fallback when exact overlap is unavailable.")
    p.add_argument("--posterior-support-table", type=Path, default=None,
                   help="Optional table keyed by subject,time,clone containing exact inverse-Simpson posterior support.")
    p.add_argument("--inverse-simpson-col", default=None,
                   help="Name of the inverse-Simpson support column in input or support table.")
    p.add_argument("--require-inverse-simpson", action="store_true",
                   help="Fail if exact inverse-Simpson posterior support is unavailable.")
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    if args.grid_size < 8:
        raise ValueError("--grid-size must be >= 8")
    if args.abundance_bin_width <= 0:
        raise ValueError("--abundance-bin-width must be > 0")
    if args.detection_bin_width <= 0 or args.detection_bin_width > 1:
        raise ValueError("--detection-bin-width must be in (0, 1]")
    if args.replicate_z_bin_width <= 0:
        raise ValueError("--replicate-z-bin-width must be > 0")
    if args.replicate_z_max <= 0:
        raise ValueError("--replicate-z-max must be > 0")

    input_path = resolve_input(args.input, args.input_pattern)
    output_dir = ensure_dir(args.output_dir)
    output_path = output_dir / "clonotype_latent_posterior_qc.parquet"

    print("[STEP3] Input:", input_path)
    diagnostics, exact_source, support_source, positive_context_source = build_diagnostics(
        scan_table(input_path), args.clone_col, args.grid_size,
        args.exact_overlap_table, args.exact_bc_col, args.require_exact_overlap,
        args.posterior_support_table, args.inverse_simpson_col, args.require_inverse_simpson,
    )
    diagnostics.sink_parquet(
        output_path, compression=args.compression, statistics=True, mkdir=True
    )
    write_summaries(output_path, output_dir, args.abundance_bin_width, args.detection_bin_width, args.replicate_z_bin_width, args.replicate_z_max)

    manifest = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "input": str(input_path),
        "canonical_step2_source": "2-multirepresentation_clonotype_state_inference.py",
        "positive_state_context_source": positive_context_source,
        "output": str(output_path),
        "grid_size": args.grid_size,
        "abundance_bin_width": args.abundance_bin_width,
        "detection_bin_width": args.detection_bin_width,
        "replicate_z_bin_width": args.replicate_z_bin_width,
        "replicate_z_max": args.replicate_z_max,
        "diagnostic_domains": {
            "posterior_uncertainty": [
                "cqc_posterior_width95_x", "cqc_posterior_fold_range95",
                "cqc_posterior_entropy", "cqc_effective_posterior_support",
                "cqc_effective_posterior_support_simpson",
                "cqc_posterior_relative_width95_f",
            ],
            "state_detectability": [
                "cqc_state_detectability", "cqc_state_dropout",
                "cqc_factorized_union_detectability",
                "cqc_delta_state_vs_factorized_union",
                "cqc_abs_delta_state_vs_factorized_union",
            ],
            "replicate_detection_qc": [
                "cqc_replicate_joint_detection_evidence",
                "cqc_joint_detection_evidence",
                "cqc_detection_imbalance",
            ],
            "replicate_agreement": [
                "cqc_replicate_bhattacharyya", "cqc_replicate_hellinger",
                "cqc_replicate_standardized_delta",
            ],
            "latent_vs_positive_representation": [
                "cqc_latent_minus_positive_x",
                "cqc_abs_latent_minus_positive_x",
                "positive_state_class",
                "n_positive_replicates",
            ],
            "model_compatibility": ["logP"],
        },
        "exact_overlap_source": exact_source,
        "inverse_simpson_support_source": support_source,
        "state_detectability_policy": (
            "p_detect_state is the exact model-based posterior-predictive detectability of the paired-replicate "
            "state under the shared posterior. The factorized union 1-(1-p1)(1-p2) combines separately integrated "
            "replicate detectabilities and is not algebraically equivalent in general. Their difference is a "
            "posterior-coupling diagnostic, not an external calibration error or failed identity check."
        ),
        "detectability_independently_calibrated": False,
        "positive_state_policy": (
            "ONE_POSITIVE and TWO_POSITIVE are realized technical-detection support strata, not quality classes. "
            "x_positive_current is an auxiliary positive-only summary used here only for representation diagnostics. "
            "It is not the primary downstream fluctuation displacement, and no representation is replaced or filtered in Step 3."
        ),
        "one_positive_zero_depth_policy": (
            "Sequencing depth is a technical-replicate-level variable. ONE_POSITIVE clonotypes are therefore "
            "collapsed to subject x time x zero-replicate analysis units before any depth correlation is calculated. "
            "Absolute zero-side depth is retained as a secondary descriptor; the primary depth descriptor is "
            "log(depth_zero) - log(depth_positive). Clonotype rows are not treated as independent depth observations."
        ),
        "one_positive_relative_depth_policy": (
            "The primary unit-level depth diagnostic is delta_log_depth_zero_minus_positive = "
            "log(depth_zero) - log(depth_positive), evaluated against the unit median latent-minus-positive state shift."
        ),
        "one_positive_paired_orientation_policy": (
            "Within each subject-timepoint, the two ONE_POSITIVE orientations are paired. The script relates "
            "log(depth_rep1/depth_rep2) to the difference between the median representation shift when replicate 1 "
            "is zero and the median representation shift when replicate 2 is zero. This is an observation-model "
            "diagnostic, not a biological longitudinal effect."
        ),
        "agreement_policy": (
            "Exact discrete-posterior Bhattacharyya overlap is preferred. "
            "Gaussian BC is used only for rows lacking exact overlap and is marked "
            "in cqc_replicate_agreement_source."
        ),
        "inverse_simpson_policy": (
            "Inverse-Simpson support is computed as 1/sum(p_i^2) on the full discrete posterior. "
            "It is never approximated from entropy; the field is present only when supplied by Step 2 or an external keyed table."
        ),
        "manuscript_statistics_policy": (
            "Metric quantiles and ordinary QC Spearman correlations are computed from the full QC parquet. "
            "The ONE_POSITIVE depth diagnostics are an explicit exception: because depth is shared within a "
            "technical replicate, depth correlations are computed only after aggregation to subject x time x "
            "zero-replicate units. The paired orientation diagnostic reports Spearman, Pearson and simple OLS R2 "
            "across subject-timepoint paired-orientation units. Plotting subsamples are used only for graphical rendering."
        ),
        "dynamic_estimands_defined_in_step3": False,
        "downstream_primary_estimands": {
            "forward": "observed replicate-decoupled AB/BA",
            "fluctuations": "Cov(delta_x_rep1, delta_x_rep2) on common4",
            "fluctuation_conditioning": "xmid_latent",
        },
        "operational_observability_policy": (
            "observable is inherited from Step 2 as 1[p_value < alpha]. Step 3 does not recompute p_value, change alpha, "
            "or treat p_detect_state as the operational threshold."
        ),
        "composite_score": False,
        "quality_classes": False,
        "filtering": False,
    }
    with open(output_dir / "clonotype_latent_posterior_qc_manifest.json", "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    print("[STEP3] Completed. No clonotypes were excluded.")
    if exact_source:
        print("[STEP3] Exact posterior overlap source:", exact_source)
    else:
        print("[STEP3] WARNING: exact overlap unavailable; Gaussian fallback used.")
    print("[STEP3] Positive-state context:", positive_context_source)
    print("[STEP3] Main output:", output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())