#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
5-longitudinal_transition_assembly.py
=====================================

Production assembly of finite-time clonotype transitions for the
replicate-resolved ClonoDynamics framework.

Overview
--------
This script implements Step 5 of the current ClonoDynamics pipeline.

It converts the standardized multirepresentation state table generated by
Step 4 (`4-multirepresentation_trajectory_assembly.py`) into a generic
endpoint-paired transition table. The transition table deliberately preserves
three conceptually distinct layers:

    1. model-based latent consensus

       Endpoint latent abundance, posterior uncertainty and conditioning
       coordinates are retained as a model-based representation layer. The
       canonical longitudinal conditioning coordinate is `xmid_latent`.
       `dx_latent` is retained as a latent-representation displacement, but it
       is NOT defined here as the primary biological forward-drift estimand.

    2. replicate-resolved observed measurements

       Technical replicates remain separate at both endpoints. Step 5 carries
       forward replicate-specific counts, depths, observed frequencies and
       observed log-frequencies and constructs the corresponding observed
       displacements:

           dx_observed_rep1 = x_observed_rep1(t1) - x_observed_rep1(t0)
           dx_observed_rep2 = x_observed_rep2(t1) - x_observed_rep2(t0).

       No pseudocount is introduced. An observed displacement is therefore
       defined only when the relevant replicate is positive at both endpoints.

       These quantities provide the measurement layer required by the primary
       downstream replicate-decoupled forward-drift and cross-replicate
       fluctuation estimands.

    3. observation annotations

       Endpoint realized positivity, empirical `p_value`, reference operational
       observability and posterior-predictive detectability/dropout are carried
       forward separately. Reference TT/TF/FT/FF classes are generated from the
       reference observability annotation, while the endpoint `p_value` values
       remain available so later sensitivity analyses can reconstruct

           observable(alpha) = 1[p_value < alpha]

       on the SAME transition universe for arbitrary operational thresholds.

Step 5 is an ASSEMBLY step. It does not estimate forward drift, fluctuation
magnitude, temporal scaling or observation-boundary effects. It does not apply
an abundance-, posterior-quality-, detectability- or observation-class filter.

Position in the current pipeline
--------------------------------

    Step 1
    1-repertoire_characterization.py
        -> descriptive repertoire architecture

    Step 2
    2-multirepresentation_clonotype_state_inference.py
        -> model-based consensus
        -> replicate-resolved observed measurements
        -> observation annotations

    Step 3
    3-latent_state_and_observation_model_diagnostics.py
        -> diagnostic characterization only

    Step 4
    4-multirepresentation_trajectory_assembly.py
        -> one standardized multirepresentation state per
           subject x clonotype x time

    Step 5
    5-longitudinal_transition_assembly.py
        -> generic endpoint pairing across requested temporal lags
        -> latent conditioning coordinates
        -> replicate-resolved observed endpoint/displacement fields
        -> reference observation classes
        -> estimand-eligibility flags
        -> optional latent-posterior displacement propagation

    Step 6
        -> transition/support and eligibility characterization

    Step 7+
        -> pseudo technical-null benchmarks and estimand-specific dynamics

Canonical input contract
------------------------
The canonical input is the Step-4 production table:

    multirepresentation_trajectories_long.parquet

Required identifiers:

    subject
    aaSeqCDR3
    time

Required model-based consensus fields:

    f_latent
    x_latent

Required replicate-resolved observed fields:

    count_rep1
    count_rep2
    depth_rep1
    depth_rep2
    f_observed_rep1
    f_observed_rep2
    x_observed_rep1
    x_observed_rep2
    read_positive_rep1
    read_positive_rep2

Required observation annotations:

    p_value
    reference_alpha
    observable_reference
    p_detect_state
    p_dropout_state

Step 5 uses the canonical names emitted by Step 4. There is deliberately no
cross-representation fallback. If the production contract is incomplete, the
script stops rather than silently substituting one abundance representation
for another.

Additional grouping variables
-----------------------------
Pseudo, null or experimental workflows can preserve explicit grouping columns
using:

    --extra-group-cols experiment,configuration_id

The processing unit becomes:

    <extra groups> x subject

and endpoint pairing is performed separately inside each unit. Extra grouping
columns are copied to every transition row and are included in resumable part
identifiers. They are never interpreted as biological subjects.

Transition universe
-------------------
Production Step 5 constructs ALL eligible temporal pairs inside each processing
unit. For each pair of available times t0 < t1 satisfying:

    min_dt <= t1 - t0 <= max_dt,

states are inner-joined by `aaSeqCDR3`.

Thus a transition exists when the Step-4 state table contains the same
subject-specific clonotype at both endpoints. Step 5 does not add synthetic
both-zero states and does not remove transitions because of observation class.

For the primary weekly cohort the production defaults are:

    min_dt = 1
    max_dt = 5.

Latent transition representation
--------------------------------
For model-based consensus states:

    x0_latent = x_latent(t0)
    x1_latent = x_latent(t1)
    dx_latent = x1_latent - x0_latent

and:

    xmid_latent = (x0_latent + x1_latent) / 2.

`xmid_latent` is the primary conditioning coordinate used by the downstream
cross-replicate fluctuation analysis.

When endpoint posterior standard deviations are available, Step 5 also
constructs the sensitivity coordinate:

    xstar_latent = (w0*x0 + w1*x1) / (w0+w1),

with inverse-variance weights:

    w0 = 1 / sigma0^2
    w1 = 1 / sigma1^2.

If valid endpoint standard deviations are unavailable, `xstar_latent` falls
back to `xmid_latent` and this is recorded in `xstar_source`.

Observed replicate transitions
------------------------------
The replicate-resolved endpoint fields are preserved explicitly:

    x_observed_rep1_t0
    x_observed_rep1_t1
    x_observed_rep2_t0
    x_observed_rep2_t1

and similarly for observed frequencies, counts and depths.

Observed displacements are:

    dx_observed_rep1
    dx_observed_rep2.

Because Step 4 defines observed log-frequency only for positive counts, these
fields are null whenever a required observed endpoint is zero. Step 5 does not
fill or impute those null values.

Primary-estimand eligibility flags
----------------------------------
Step 5 annotates, but does not filter on, the support required by the current
primary observed estimands.

For forward orientation AB:

    conditioning measurement = replicate 1 at t0
    displacement measurement = replicate 2 from t0 to t1

so:

    forward_ab_eligible
        = rep1 positive at t0
          AND rep2 positive at t0
          AND rep2 positive at t1.

For reciprocal orientation BA:

    forward_ba_eligible
        = rep2 positive at t0
          AND rep1 positive at t0
          AND rep1 positive at t1.

For shared fluctuations, the strict primary support is:

    common4
        = both replicates positive at t0
          AND both replicates positive at t1.

On common4, both observed displacements are defined and downstream analyses can
estimate:

    Cov(dx_observed_rep1, dx_observed_rep2 | xmid_latent, dt).

These flags define measurement eligibility only. They are not quality scores
and are not used by Step 5 to discard transitions.

Operational observation classes
-------------------------------
Step 4 provides `reference_alpha` and `observable_reference` for each state.
Step 5 requires a single reference alpha across the input dataset and checks
that:

    observable_reference == (p_value < reference_alpha).

For each transition, Step 5 writes:

    p_value_t0
    p_value_t1
    observable_reference_t0
    observable_reference_t1
    obs_class_reference

where `obs_class_reference` is one of:

    TT
    TF
    FT
    FF.

These are operational endpoint-observation classes at the reference threshold.
They must NOT be interpreted as persistence, contraction, expansion or
biological absence.

For compatibility with older downstream code the aliases:

    obs0
    obs1
    obs_class

are also written and refer specifically to the REFERENCE threshold.

No `--keep-obs-class` filtering is implemented in the production builder.
Observation-domain restrictions belong downstream, where the full transition
universe and endpoint `p_value` fields remain available.

Auxiliary positive-only representation
--------------------------------------
When present from Step 4, the auxiliary positive-only coordinates are carried
forward as:

    x_positive_current_t0
    x_positive_current_t1
    dx_positive_current

and corresponding frequency fields.

They remain representation diagnostics/sensitivity quantities and are not
used by Step 5 to define a primary dynamic estimand.

Optional full latent-posterior propagation
------------------------------------------
Step 5 can optionally propagate the complete discrete latent posteriors of the
two endpoints into a model-based displacement posterior using independent
endpoint draws.

Enable this with:

    --posterior-dir <directory>

The default relative file template is:

    latent_per_clone_logP_{subject}_{time}.posterior.npz

and can be changed with:

    --posterior-template

For grouped pseudo/null datasets, every extra grouping column must appear as a
format placeholder in the template unless `--allow-shared-posterior-files` is
explicitly supplied. Example:

    --extra-group-cols configuration_id \
    --posterior-template \
      '{configuration_id}/latent_per_clone_logP_{subject}_{time}.posterior.npz'

Each posterior NPZ must contain:

    f_grid
    posterior_matrix
    aaSeqCDR3.

The optional propagated fields include:

    x0_post_mean
    x1_post_mean
    x0_post_median
    x1_post_median
    dx_post_mean
    dx_post_median
    dx_post_q025
    dx_post_q975
    dx_post_sd
    p_dx_gt0
    p_dx_lt0
    posterior_success
    posterior_message.

These fields form an OPTIONAL model-based uncertainty layer. The production
transition contract does not require them for primary replicate-resolved
forward or fluctuation analyses.

Removed legacy behavior
-----------------------
The current production Step 5 intentionally removes several behaviors of the
older latent-transition builder:

    - no observation-class filtering during assembly;
    - no TT/TF/FT/FF class weights;
    - no gamma_cross / gamma_ff weighting;
    - no clone- or lag-balancing weights;
    - no claim that `dx_latent` is the primary forward displacement;
    - no adjacency mode in the production builder;
    - no silent representation fallback.

Any estimand-specific weighting, support restriction or sensitivity definition
belongs in the corresponding downstream analysis step.

Memory-bounded architecture
---------------------------
The script preserves the memory-bounded architecture of the previous Step 5:

    1. one <extra groups> x subject processing unit is loaded at a time;
    2. one temporal pair is built at a time;
    3. the pair is written to temporary Parquet;
    4. optional full-posterior propagation is performed in Arrow batches;
    5. completed pair parts are resumable;
    6. parts are concatenated incrementally into the final Parquet output.

Canonical output
----------------
The canonical production output is:

    longitudinal_transitions.parquet

Core output groups are:

    identifiers / temporal structure
    latent consensus endpoints and conditioning coordinates
    replicate-resolved observed endpoints and displacements
    positive-support and primary-estimand eligibility flags
    endpoint p-values and reference observation classes
    posterior-predictive detectability annotations
    optional model-based posterior propagation summaries.

A human-readable report and machine-readable manifest are also written:

    transition_assembly_report.md
    transition_assembly_manifest.json

Compatible with Python >= 3.9, Polars 1.36.x and PyArrow.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import math
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np

try:
    import polars as pl
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "ERROR: polars is required. Install/activate the production environment "
        "containing Polars 1.36.x."
    ) from exc

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "ERROR: pyarrow is required for incremental Parquet writing and optional "
        "posterior propagation."
    ) from exc


SCRIPT_VERSION = "v4-multirepresentation-transition-contract-2026-09-09"

PARQUET_SUFFIXES = {".parquet", ".pq"}
TEXT_SUFFIXES = {".csv", ".tsv", ".txt"}
OBS_CLASSES = {"TT", "TF", "FT", "FF"}

CORE_REQUIRED_COLUMNS = [
    "subject",
    "aaSeqCDR3",
    "time",
    "f_latent",
    "x_latent",
    "count_rep1",
    "count_rep2",
    "depth_rep1",
    "depth_rep2",
    "f_observed_rep1",
    "f_observed_rep2",
    "x_observed_rep1",
    "x_observed_rep2",
    "read_positive_rep1",
    "read_positive_rep2",
    "p_value",
    "reference_alpha",
    "observable_reference",
    "p_detect_state",
    "p_dropout_state",
]

OPTIONAL_ENDPOINT_COLUMNS = [
    "pair_id",
    "freq_latent",
    "f_latent_q025",
    "f_latent_q975",
    "x_latent_q025",
    "x_latent_q975",
    "x_latent_sd",
    "posterior_entropy",
    "logP",
    "both_replicates_positive",
    "n_positive_replicates",
    "positive_state_class",
    "positive_replicate_source",
    "f_positive_current",
    "x_positive_current",
    "observable",
    "p_detect_rep1",
    "p_detect_rep2",
    "p_dropout_rep1",
    "p_dropout_rep2",
    "replicate_posterior_bhattacharyya",
    # single-replicate latent summaries retained for diagnostic/sensitivity use
    "rep1_f_latent_mean",
    "rep1_f_latent_median",
    "rep1_f_latent_mode",
    "rep1_f_latent_q025",
    "rep1_f_latent_q975",
    "rep1_x_latent_mean",
    "rep1_x_latent_median",
    "rep1_x_latent_mode",
    "rep1_x_latent_q025",
    "rep1_x_latent_q975",
    "rep1_x_latent_sd",
    "rep1_posterior_entropy",
    "rep2_f_latent_mean",
    "rep2_f_latent_median",
    "rep2_f_latent_mode",
    "rep2_f_latent_q025",
    "rep2_f_latent_q975",
    "rep2_x_latent_mean",
    "rep2_x_latent_median",
    "rep2_x_latent_mode",
    "rep2_x_latent_q025",
    "rep2_x_latent_q975",
    "rep2_x_latent_sd",
    "rep2_posterior_entropy",
    "f_rep1_latent_median",
    "f_rep2_latent_median",
    "x_rep1_latent_median",
    "x_rep2_latent_median",
    "x_rep1_latent_q025",
    "x_rep1_latent_q975",
    "x_rep2_latent_q025",
    "x_rep2_latent_q975",
]

POSTERIOR_FLOAT_COLUMNS = [
    "x0_post_mean",
    "x1_post_mean",
    "x0_post_median",
    "x1_post_median",
    "dx_post_mean",
    "dx_post_median",
    "dx_post_q025",
    "dx_post_q975",
    "dx_post_sd",
    "p_dx_gt0",
    "p_dx_lt0",
]


def eprint(*args: Any, **kwargs: Any) -> None:
    print(*args, file=sys.stderr, **kwargs)


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def remove_if_exists(path: Path) -> None:
    try:
        path.unlink()
    except FileNotFoundError:
        pass


def collect_streaming(lf: pl.LazyFrame) -> pl.DataFrame:
    try:
        return lf.collect(engine="streaming")
    except TypeError:
        return lf.collect(streaming=True)


def sink_parquet_streaming(
    lf: pl.LazyFrame,
    path: Path,
    compression: str,
    row_group_size: int,
) -> None:
    ensure_parent(path)
    kwargs: Dict[str, Any] = {
        "compression": compression,
        "statistics": True,
        "maintain_order": True,
    }
    if row_group_size > 0:
        kwargs["row_group_size"] = int(row_group_size)

    try:
        lf.sink_parquet(path, engine="streaming", mkdir=True, **kwargs)
    except TypeError:
        try:
            lf.sink_parquet(path, **kwargs)
        except TypeError:
            kwargs.pop("row_group_size", None)
            lf.sink_parquet(path, **kwargs)


def split_csv(text: Optional[str]) -> list[str]:
    if text is None:
        return []
    return [item.strip() for item in str(text).split(",") if item.strip()]


def scan_table(path: Path, separator: str) -> pl.LazyFrame:
    suffix = path.suffix.lower()
    if suffix in PARQUET_SUFFIXES:
        return pl.scan_parquet(path)
    if suffix == ".csv":
        return pl.scan_csv(path, separator=",", infer_schema_length=10000)
    if suffix == ".tsv":
        return pl.scan_csv(path, separator="\t", infer_schema_length=10000)
    if suffix == ".txt":
        return pl.scan_csv(path, separator=separator, infer_schema_length=10000)
    raise ValueError(
        f"Unsupported trajectory format: {path.suffix}. Use Parquet, CSV, TSV or TXT."
    )


def input_signature(path: Path) -> Dict[str, Any]:
    stat = path.stat()
    return {
        "path": str(path.resolve()),
        "size_bytes": int(stat.st_size),
        "mtime_ns": int(stat.st_mtime_ns),
    }


def sanitize_token(value: Any) -> str:
    text = str(value)
    text = re.sub(r"[^A-Za-z0-9_.-]+", "-", text)
    return text[:60] or "empty"


def unit_identity(
    unit_values: Mapping[str, Any],
    subject: int,
) -> str:
    parts = [f"{key}={unit_values[key]}" for key in sorted(unit_values)]
    parts.append(f"subject={int(subject)}")
    payload = "|".join(parts)
    digest = hashlib.blake2b(payload.encode("utf-8"), digest_size=6).hexdigest()
    readable = "__".join(
        f"{sanitize_token(key)}={sanitize_token(value)}"
        for key, value in sorted(unit_values.items())
    )
    prefix = (readable + "__") if readable else ""
    return f"{prefix}s{int(subject):04d}__{digest}"


def unit_filter_expr(
    subject: int,
    unit_values: Mapping[str, Any],
) -> pl.Expr:
    expression = pl.col("subject") == int(subject)
    for column, value in unit_values.items():
        expression = expression & (pl.col(column) == pl.lit(value))
    return expression


def require_columns(
    schema_names: Sequence[str],
    required: Sequence[str],
) -> None:
    names = set(schema_names)
    missing = [column for column in required if column not in names]
    if missing:
        raise ValueError(
            "Step-5 input is missing required Step-4 production columns: "
            + ", ".join(missing)
        )


def validate_reference_contract(
    input_scan: pl.LazyFrame,
) -> float:
    """Validate reference-alpha and reference-observability consistency."""
    summary = collect_streaming(
        input_scan.select(
            [
                pl.col("reference_alpha").n_unique().alias("n_alpha"),
                pl.col("reference_alpha").min().alias("alpha_min"),
                pl.col("reference_alpha").max().alias("alpha_max"),
                (
                    pl.col("observable_reference").cast(pl.Boolean, strict=False)
                    != (pl.col("p_value") < pl.col("reference_alpha"))
                )
                .fill_null(True)
                .sum()
                .alias("n_observable_mismatch"),
            ]
        )
    ).row(0, named=True)

    n_alpha = int(summary["n_alpha"] or 0)
    if n_alpha != 1:
        raise ValueError(
            "Step-5 production input must contain exactly one reference_alpha; "
            f"found {n_alpha}."
        )

    alpha = float(summary["alpha_min"])
    if not (0.0 < alpha < 1.0):
        raise ValueError(f"Invalid reference_alpha={alpha}; expected 0 < alpha < 1.")

    mismatches = int(summary["n_observable_mismatch"] or 0)
    if mismatches:
        raise ValueError(
            "observable_reference does not match p_value < reference_alpha for "
            f"{mismatches:,} states. Rebuild Step 4 before Step 5."
        )
    return alpha


def validate_state_contract(
    input_scan: pl.LazyFrame,
    extra_group_cols: Sequence[str],
) -> None:
    """Fail on malformed Step-4 observed/positivity fields."""
    checks: List[pl.Expr] = [
        pl.len().alias("n_rows"),
        (
            pl.col("count_rep1").is_null()
            | pl.col("count_rep2").is_null()
            | (pl.col("count_rep1") < 0)
            | (pl.col("count_rep2") < 0)
        ).sum().alias("invalid_counts"),
        (
            pl.col("depth_rep1").is_null()
            | pl.col("depth_rep2").is_null()
            | (pl.col("depth_rep1") <= 0)
            | (pl.col("depth_rep2") <= 0)
        ).sum().alias("invalid_depths"),
        (
            pl.col("x_latent").is_null()
            | ~pl.col("x_latent").is_finite()
            | pl.col("f_latent").is_null()
            | ~pl.col("f_latent").is_finite()
            | (pl.col("f_latent") <= 0)
        ).sum().alias("invalid_latent"),
        (
            pl.col("p_value").is_null()
            | ~pl.col("p_value").is_finite()
            | (pl.col("p_value") < 0)
            | (pl.col("p_value") > 1)
        ).sum().alias("invalid_p_value"),
        (
            pl.col("p_detect_state").is_null()
            | ~pl.col("p_detect_state").is_finite()
            | (pl.col("p_detect_state") < 0)
            | (pl.col("p_detect_state") > 1)
            | pl.col("p_dropout_state").is_null()
            | ~pl.col("p_dropout_state").is_finite()
            | (pl.col("p_dropout_state") < 0)
            | (pl.col("p_dropout_state") > 1)
        ).sum().alias("invalid_detectability"),
        (
            pl.col("read_positive_rep1").cast(pl.Boolean, strict=False)
            != (pl.col("count_rep1") > 0)
        ).fill_null(True).sum().alias("rep1_positivity_mismatch"),
        (
            pl.col("read_positive_rep2").cast(pl.Boolean, strict=False)
            != (pl.col("count_rep2") > 0)
        ).fill_null(True).sum().alias("rep2_positivity_mismatch"),
        (
            ((pl.col("count_rep1") > 0) & pl.col("x_observed_rep1").is_null())
            | ((pl.col("count_rep1") == 0) & pl.col("x_observed_rep1").is_not_null())
        ).sum().alias("rep1_log_observation_mismatch"),
        (
            ((pl.col("count_rep2") > 0) & pl.col("x_observed_rep2").is_null())
            | ((pl.col("count_rep2") == 0) & pl.col("x_observed_rep2").is_not_null())
        ).sum().alias("rep2_log_observation_mismatch"),
    ]

    for column in extra_group_cols:
        checks.append(pl.col(column).is_null().sum().alias(f"null_group__{column}"))

    summary = collect_streaming(input_scan.select(checks)).row(0, named=True)
    problems = {
        key: int(value or 0)
        for key, value in summary.items()
        if key != "n_rows" and int(value or 0) > 0
    }
    if problems:
        raise ValueError(
            "Step-5 input failed the Step-4 state contract: "
            + ", ".join(f"{key}={value}" for key, value in problems.items())
        )


def validate_unique_state_keys(
    input_scan: pl.LazyFrame,
    extra_group_cols: Sequence[str],
) -> None:
    key_cols = list(extra_group_cols) + ["subject", "aaSeqCDR3", "time"]
    duplicates = collect_streaming(
        input_scan
        .group_by(key_cols)
        .agg(pl.len().alias("n_rows"))
        .filter(pl.col("n_rows") > 1)
        .sort("n_rows", descending=True)
        .head(10)
    )
    if not duplicates.is_empty():
        raise ValueError(
            "Duplicate trajectory state keys detected. Step 5 does not aggregate "
            "duplicate states. Examples:\n" + str(duplicates)
        )


def prepare_unit(
    trajectories: Path,
    separator: str,
    subject: int,
    unit_values: Mapping[str, Any],
    extra_group_cols: Sequence[str],
    endpoint_columns: Sequence[str],
) -> pl.DataFrame:
    scan = scan_table(trajectories, separator)
    filtered = scan.filter(unit_filter_expr(subject, unit_values))
    selected = ["aaSeqCDR3", "time"] + list(endpoint_columns)
    frame = collect_streaming(
        filtered
        .select([pl.col(column) for column in selected])
        .sort(["aaSeqCDR3", "time"])
    )
    return frame


def endpoint_frame(
    unit_frame: pl.DataFrame,
    time_value: int,
    suffix: str,
) -> pl.DataFrame:
    endpoint = unit_frame.filter(pl.col("time") == int(time_value)).drop("time")
    rename_map = {
        column: f"{column}_{suffix}"
        for column in endpoint.columns
        if column != "aaSeqCDR3"
    }
    return endpoint.rename(rename_map)


def _literal_group_expressions(
    unit_values: Mapping[str, Any],
) -> List[pl.Expr]:
    return [pl.lit(value).alias(column) for column, value in unit_values.items()]


def transition_projection(
    joined: pl.DataFrame,
    subject: int,
    unit_values: Mapping[str, Any],
    t0: int,
    t1: int,
    reference_alpha: float,
) -> pl.DataFrame:
    """Build one generic transition block without estimand-specific filtering."""
    dt_value = int(t1 - t0)

    rp1_t0 = pl.col("read_positive_rep1_t0").cast(pl.Boolean, strict=False)
    rp1_t1 = pl.col("read_positive_rep1_t1").cast(pl.Boolean, strict=False)
    rp2_t0 = pl.col("read_positive_rep2_t0").cast(pl.Boolean, strict=False)
    rp2_t1 = pl.col("read_positive_rep2_t1").cast(pl.Boolean, strict=False)

    obs0_bool = pl.col("observable_reference_t0").cast(pl.Boolean, strict=False)
    obs1_bool = pl.col("observable_reference_t1").cast(pl.Boolean, strict=False)
    obs0_label = pl.when(obs0_bool).then(pl.lit("T")).otherwise(pl.lit("F"))
    obs1_label = pl.when(obs1_bool).then(pl.lit("T")).otherwise(pl.lit("F"))

    expressions: List[pl.Expr] = []
    expressions.extend(_literal_group_expressions(unit_values))
    expressions.extend(
        [
            pl.lit(int(subject), dtype=pl.Int64).alias("subject"),
            pl.col("aaSeqCDR3"),
            pl.lit(int(t0), dtype=pl.Int64).alias("t0"),
            pl.lit(int(t1), dtype=pl.Int64).alias("t1"),
            pl.lit(dt_value, dtype=pl.Int64).alias("dt"),
            pl.lit("all").alias("pattern"),
            # model-based consensus
            pl.col("f_latent_t0").alias("f0_latent"),
            pl.col("f_latent_t1").alias("f1_latent"),
            # stable compatibility aliases retained for existing downstream readers
            pl.col("f_latent_t0").alias("freq0_latent"),
            pl.col("f_latent_t1").alias("freq1_latent"),
            pl.col("x_latent_t0").alias("x0_latent"),
            pl.col("x_latent_t1").alias("x1_latent"),
            (pl.col("x_latent_t1") - pl.col("x_latent_t0")).alias("dx_latent"),
            (0.5 * (pl.col("x_latent_t0") + pl.col("x_latent_t1"))).alias(
                "xmid_latent"
            ),
            pl.col("x_latent_t0").alias("x0_condition_latent"),
            pl.col("x_latent_t0").alias("x0_condition"),
            pl.lit(dt_value, dtype=pl.Int64).alias("n_steps"),
            # replicate-resolved observed endpoints
            pl.col("count_rep1_t0"),
            pl.col("count_rep1_t1"),
            pl.col("count_rep2_t0"),
            pl.col("count_rep2_t1"),
            pl.col("depth_rep1_t0"),
            pl.col("depth_rep1_t1"),
            pl.col("depth_rep2_t0"),
            pl.col("depth_rep2_t1"),
            pl.col("f_observed_rep1_t0"),
            pl.col("f_observed_rep1_t1"),
            pl.col("f_observed_rep2_t0"),
            pl.col("f_observed_rep2_t1"),
            pl.col("x_observed_rep1_t0"),
            pl.col("x_observed_rep1_t1"),
            pl.col("x_observed_rep2_t0"),
            pl.col("x_observed_rep2_t1"),
            (pl.col("x_observed_rep1_t1") - pl.col("x_observed_rep1_t0")).alias(
                "dx_observed_rep1"
            ),
            (pl.col("x_observed_rep2_t1") - pl.col("x_observed_rep2_t0")).alias(
                "dx_observed_rep2"
            ),
            rp1_t0.alias("read_positive_rep1_t0"),
            rp1_t1.alias("read_positive_rep1_t1"),
            rp2_t0.alias("read_positive_rep2_t0"),
            rp2_t1.alias("read_positive_rep2_t1"),
            (rp1_t0 & rp2_t0).alias("both_replicates_positive_t0"),
            (rp1_t1 & rp2_t1).alias("both_replicates_positive_t1"),
            # primary-estimand eligibility flags
            (rp1_t0 & rp2_t0 & rp2_t1).alias("forward_ab_eligible"),
            (rp2_t0 & rp1_t0 & rp1_t1).alias("forward_ba_eligible"),
            (rp1_t0 & rp2_t0 & rp1_t1 & rp2_t1).alias("common4"),
            # operational observation layer
            pl.col("p_value_t0").alias("p_value_t0"),
            pl.col("p_value_t1").alias("p_value_t1"),
            pl.lit(float(reference_alpha), dtype=pl.Float64).alias("reference_alpha"),
            obs0_bool.alias("observable_reference_t0"),
            obs1_bool.alias("observable_reference_t1"),
            pl.concat_str([obs0_label, obs1_label]).alias("obs_class_reference"),
            # compatibility aliases: explicitly reference-threshold classes
            obs0_label.alias("obs0"),
            obs1_label.alias("obs1"),
            pl.concat_str([obs0_label, obs1_label]).alias("obs_class"),
            # model-based detectability annotations
            pl.col("p_detect_state_t0").alias("p_detect_state_t0"),
            pl.col("p_detect_state_t1").alias("p_detect_state_t1"),
            pl.col("p_dropout_state_t0").alias("p_dropout_state_t0"),
            pl.col("p_dropout_state_t1").alias("p_dropout_state_t1"),
        ]
    )

    # Optional state identifiers.
    for column in ["pair_id"]:
        c0 = f"{column}_t0"
        c1 = f"{column}_t1"
        if c0 in joined.columns:
            expressions.append(pl.col(c0))
        if c1 in joined.columns:
            expressions.append(pl.col(c1))

    # Optional latent uncertainty and xstar sensitivity coordinate.
    if {"x_latent_sd_t0", "x_latent_sd_t1"}.issubset(joined.columns):
        sd0 = pl.col("x_latent_sd_t0")
        sd1 = pl.col("x_latent_sd_t1")
        valid_sd = sd0.is_finite() & sd1.is_finite() & (sd0 > 0) & (sd1 > 0)
        w0 = 1.0 / (sd0.pow(2) + 1e-12)
        w1 = 1.0 / (sd1.pow(2) + 1e-12)
        midpoint = 0.5 * (pl.col("x_latent_t0") + pl.col("x_latent_t1"))
        xstar = (
            pl.when(valid_sd)
            .then((w0 * pl.col("x_latent_t0") + w1 * pl.col("x_latent_t1")) / (w0 + w1))
            .otherwise(midpoint)
        )
        expressions.extend(
            [
                sd0.alias("x0_latent_sd"),
                sd1.alias("x1_latent_sd"),
                (sd0.pow(2) + sd1.pow(2)).sqrt().alias("dx_latent_sd_approx"),
                xstar.alias("xstar_latent"),
                pl.when(valid_sd)
                .then(pl.lit("inverse_variance_weighted"))
                .otherwise(pl.lit("midpoint_fallback"))
                .alias("xstar_source"),
            ]
        )
    else:
        expressions.extend(
            [
                pl.lit(float("nan"), dtype=pl.Float64).alias("x0_latent_sd"),
                pl.lit(float("nan"), dtype=pl.Float64).alias("x1_latent_sd"),
                pl.lit(float("nan"), dtype=pl.Float64).alias("dx_latent_sd_approx"),
                (0.5 * (pl.col("x_latent_t0") + pl.col("x_latent_t1"))).alias(
                    "xstar_latent"
                ),
                pl.lit("midpoint_fallback").alias("xstar_source"),
            ]
        )

    # Optional latent endpoint quantiles.
    for source, out0, out1 in [
        ("f_latent_q025", "f0_latent_q025", "f1_latent_q025"),
        ("f_latent_q975", "f0_latent_q975", "f1_latent_q975"),
        ("x_latent_q025", "x0_latent_q025", "x1_latent_q025"),
        ("x_latent_q975", "x0_latent_q975", "x1_latent_q975"),
    ]:
        c0 = f"{source}_t0"
        c1 = f"{source}_t1"
        if c0 in joined.columns:
            expressions.append(pl.col(c0).alias(out0))
        if c1 in joined.columns:
            expressions.append(pl.col(c1).alias(out1))

    # Auxiliary positive-only representation.
    if {"x_positive_current_t0", "x_positive_current_t1"}.issubset(joined.columns):
        expressions.extend(
            [
                pl.col("x_positive_current_t0"),
                pl.col("x_positive_current_t1"),
                (
                    pl.col("x_positive_current_t1")
                    - pl.col("x_positive_current_t0")
                ).alias("dx_positive_current"),
            ]
        )
    if {"f_positive_current_t0", "f_positive_current_t1"}.issubset(joined.columns):
        expressions.extend(
            [pl.col("f_positive_current_t0"), pl.col("f_positive_current_t1")]
        )

    for source in [
        "positive_state_class",
        "positive_replicate_source",
        "n_positive_replicates",
        "posterior_entropy",
        "logP",
        "replicate_posterior_bhattacharyya",
        "p_detect_rep1",
        "p_detect_rep2",
        "p_dropout_rep1",
        "p_dropout_rep2",
    ]:
        c0 = f"{source}_t0"
        c1 = f"{source}_t1"
        if c0 in joined.columns:
            expressions.append(pl.col(c0))
        if c1 in joined.columns:
            expressions.append(pl.col(c1))

    # Preserve optional single-replicate latent summaries as endpoint fields.
    optional_endpoint_names = [
        column
        for column in OPTIONAL_ENDPOINT_COLUMNS
        if column.startswith("rep1_")
        or column.startswith("rep2_")
        or column.startswith("f_rep")
        or column.startswith("x_rep")
    ]
    for source in optional_endpoint_names:
        c0 = f"{source}_t0"
        c1 = f"{source}_t1"
        if c0 in joined.columns:
            expressions.append(pl.col(c0))
        if c1 in joined.columns:
            expressions.append(pl.col(c1))

    return joined.select(expressions).sort(
        list(unit_values.keys()) + ["subject", "aaSeqCDR3", "t0", "t1"]
    )


def build_temporal_pair(
    unit_frame: pl.DataFrame,
    subject: int,
    unit_values: Mapping[str, Any],
    t0: int,
    t1: int,
    reference_alpha: float,
) -> pl.DataFrame:
    endpoint0 = endpoint_frame(unit_frame, t0, "t0")
    endpoint1 = endpoint_frame(unit_frame, t1, "t1")
    joined = endpoint0.join(endpoint1, on="aaSeqCDR3", how="inner")
    del endpoint0, endpoint1
    if joined.is_empty():
        return joined
    return transition_projection(
        joined=joined,
        subject=subject,
        unit_values=unit_values,
        t0=t0,
        t1=t1,
        reference_alpha=reference_alpha,
    )


# =============================================================================
# Optional full latent-posterior propagation
# =============================================================================


def posterior_path(
    posterior_dir: Path,
    template: str,
    subject: int,
    time_value: int,
    unit_values: Mapping[str, Any],
) -> Path:
    values: Dict[str, Any] = dict(unit_values)
    values.update({"subject": int(subject), "time": int(time_value)})
    try:
        relative = template.format(**values)
    except KeyError as exc:
        raise KeyError(
            f"Posterior template placeholder {exc} cannot be resolved from "
            f"available values: {sorted(values)}"
        ) from exc
    return posterior_dir / relative


def load_posterior_file(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(str(path))

    with np.load(path, allow_pickle=True) as archive:
        required = {"f_grid", "posterior_matrix", "aaSeqCDR3"}
        missing = required.difference(archive.files)
        if missing:
            raise KeyError(
                f"Posterior file {path.name} is missing arrays: {sorted(missing)}"
            )
        f_grid = np.asarray(archive["f_grid"], dtype=np.float64)
        posterior_matrix = np.asarray(archive["posterior_matrix"], dtype=np.float32)
        clones = np.asarray(archive["aaSeqCDR3"]).astype(str)

    if f_grid.ndim != 1:
        raise ValueError(f"f_grid must be one-dimensional in {path.name}")
    if posterior_matrix.ndim != 2:
        raise ValueError(f"posterior_matrix must be two-dimensional in {path.name}")

    if (
        posterior_matrix.shape[0] == f_grid.size
        and posterior_matrix.shape[1] == clones.size
    ):
        posterior_matrix = posterior_matrix.T

    if posterior_matrix.shape[0] != clones.size:
        raise ValueError(
            f"Posterior rows ({posterior_matrix.shape[0]:,}) do not match clones "
            f"({clones.size:,}) in {path.name}"
        )
    if posterior_matrix.shape[1] != f_grid.size:
        raise ValueError(
            f"Posterior columns ({posterior_matrix.shape[1]:,}) do not match f_grid "
            f"({f_grid.size:,}) in {path.name}"
        )

    safe_grid = np.maximum(f_grid, np.finfo(np.float64).tiny)
    return {
        "x_grid": np.log(safe_grid),
        "posterior_matrix": posterior_matrix,
        "clone_to_index": {clone: idx for idx, clone in enumerate(clones)},
    }


def sample_posterior(
    x_grid: np.ndarray,
    probabilities: np.ndarray,
    n_samples: int,
    rng: np.random.Generator,
) -> np.ndarray:
    probs = np.asarray(probabilities, dtype=np.float64)
    probs = np.where(np.isfinite(probs) & (probs > 0), probs, 0.0)
    total = float(probs.sum())
    if not np.isfinite(total) or total <= 0:
        raise ValueError("Posterior probabilities are empty or non-finite")
    probs /= total
    return rng.choice(x_grid, size=int(n_samples), replace=True, p=probs)


def deterministic_pair_seed(
    base_seed: int,
    subject: int,
    t0: int,
    t1: int,
    unit_values: Mapping[str, Any],
) -> int:
    groups = "|".join(
        f"{key}={unit_values[key]}" for key in sorted(unit_values)
    )
    payload = f"{base_seed}|{groups}|subject={subject}|{t0}|{t1}|all"
    digest = hashlib.blake2b(payload.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, byteorder="little", signed=False) % (2**32)


def append_posterior_columns(
    record_batch: pa.RecordBatch,
    posterior0: Optional[Dict[str, Any]],
    posterior1: Optional[Dict[str, Any]],
    file_error: Optional[str],
    n_samples: int,
    rng: np.random.Generator,
) -> pa.Table:
    table = pa.Table.from_batches([record_batch])
    clones = table.column("aaSeqCDR3").to_pylist()
    row_count = len(clones)

    output_arrays: Dict[str, np.ndarray] = {
        column: np.full(row_count, np.nan, dtype=np.float64)
        for column in POSTERIOR_FLOAT_COLUMNS
    }
    success = np.zeros(row_count, dtype=np.bool_)
    messages: List[str] = [""] * row_count

    if file_error is not None or posterior0 is None or posterior1 is None:
        messages = [file_error or "posterior_file_error"] * row_count
    else:
        map0 = posterior0["clone_to_index"]
        map1 = posterior1["clone_to_index"]
        grid0 = posterior0["x_grid"]
        grid1 = posterior1["x_grid"]
        matrix0 = posterior0["posterior_matrix"]
        matrix1 = posterior1["posterior_matrix"]
        ddof = 1 if int(n_samples) > 1 else 0

        for row_index, raw_clone in enumerate(clones):
            clone = str(raw_clone)
            try:
                idx0 = map0.get(clone)
                idx1 = map1.get(clone)
                if idx0 is None:
                    raise KeyError(f"clone missing at t0: {clone}")
                if idx1 is None:
                    raise KeyError(f"clone missing at t1: {clone}")

                samples0 = sample_posterior(grid0, matrix0[idx0], n_samples, rng)
                samples1 = sample_posterior(grid1, matrix1[idx1], n_samples, rng)
                displacement = samples1 - samples0

                output_arrays["x0_post_mean"][row_index] = float(np.mean(samples0))
                output_arrays["x1_post_mean"][row_index] = float(np.mean(samples1))
                output_arrays["x0_post_median"][row_index] = float(np.median(samples0))
                output_arrays["x1_post_median"][row_index] = float(np.median(samples1))
                output_arrays["dx_post_mean"][row_index] = float(np.mean(displacement))
                output_arrays["dx_post_median"][row_index] = float(np.median(displacement))
                output_arrays["dx_post_q025"][row_index] = float(
                    np.quantile(displacement, 0.025)
                )
                output_arrays["dx_post_q975"][row_index] = float(
                    np.quantile(displacement, 0.975)
                )
                output_arrays["dx_post_sd"][row_index] = float(
                    np.std(displacement, ddof=ddof)
                )
                output_arrays["p_dx_gt0"][row_index] = float(
                    np.mean(displacement > 0)
                )
                output_arrays["p_dx_lt0"][row_index] = float(
                    np.mean(displacement < 0)
                )
                success[row_index] = True
            except Exception as exc:
                messages[row_index] = (
                    f"transition_error: {type(exc).__name__}: {exc}"
                )

    for column in POSTERIOR_FLOAT_COLUMNS:
        table = table.append_column(
            column, pa.array(output_arrays[column], type=pa.float64())
        )
    table = table.append_column(
        "posterior_success", pa.array(success, type=pa.bool_())
    )
    table = table.append_column(
        "posterior_message", pa.array(messages, type=pa.string())
    )
    return table


def enrich_pair_with_posterior(
    raw_path: Path,
    output_path: Path,
    posterior_dir: Path,
    posterior_template: str,
    subject: int,
    unit_values: Mapping[str, Any],
    t0: int,
    t1: int,
    n_samples: int,
    seed: int,
    batch_size: int,
    compression: str,
    row_group_size: int,
) -> None:
    posterior0: Optional[Dict[str, Any]] = None
    posterior1: Optional[Dict[str, Any]] = None
    file_error: Optional[str] = None

    try:
        posterior0 = load_posterior_file(
            posterior_path(
                posterior_dir, posterior_template, subject, t0, unit_values
            )
        )
        posterior1 = load_posterior_file(
            posterior_path(
                posterior_dir, posterior_template, subject, t1, unit_values
            )
        )
    except Exception as exc:
        file_error = f"posterior_file_error: {type(exc).__name__}: {exc}"

    rng = np.random.default_rng(
        deterministic_pair_seed(seed, subject, t0, t1, unit_values)
    )

    parquet_file = pq.ParquetFile(raw_path)
    writer: Optional[pq.ParquetWriter] = None
    try:
        for record_batch in parquet_file.iter_batches(
            batch_size=int(batch_size), use_threads=True
        ):
            enriched = append_posterior_columns(
                record_batch=record_batch,
                posterior0=posterior0,
                posterior1=posterior1,
                file_error=file_error,
                n_samples=int(n_samples),
                rng=rng,
            )
            if writer is None:
                ensure_parent(output_path)
                writer = pq.ParquetWriter(
                    output_path,
                    enriched.schema,
                    compression=compression,
                    use_dictionary=True,
                    write_statistics=True,
                )
            writer.write_table(enriched, row_group_size=int(row_group_size))
            del enriched, record_batch
    finally:
        if writer is not None:
            writer.close()
        del posterior0, posterior1
        gc.collect()


def copy_pair_without_posterior(
    raw_path: Path,
    output_path: Path,
    batch_size: int,
    compression: str,
    row_group_size: int,
) -> None:
    parquet_file = pq.ParquetFile(raw_path)
    writer: Optional[pq.ParquetWriter] = None
    try:
        for record_batch in parquet_file.iter_batches(
            batch_size=int(batch_size), use_threads=True
        ):
            table = pa.Table.from_batches([record_batch])
            if writer is None:
                ensure_parent(output_path)
                writer = pq.ParquetWriter(
                    output_path,
                    table.schema,
                    compression=compression,
                    use_dictionary=True,
                    write_statistics=True,
                )
            writer.write_table(table, row_group_size=int(row_group_size))
            del table, record_batch
    finally:
        if writer is not None:
            writer.close()


# =============================================================================
# Resumable part management
# =============================================================================


def write_raw_pair(
    transitions: pl.DataFrame,
    raw_path: Path,
    compression: str,
    row_group_size: int,
) -> int:
    if transitions.is_empty():
        return 0
    ensure_parent(raw_path)
    transitions.write_parquet(
        raw_path,
        compression=compression,
        statistics=True,
        row_group_size=int(row_group_size),
    )
    return int(transitions.height)


def finalize_pair_part(
    raw_path: Path,
    part_path: Path,
    args: argparse.Namespace,
    subject: int,
    unit_values: Mapping[str, Any],
    t0: int,
    t1: int,
) -> int:
    if not raw_path.exists():
        return 0

    partial = part_path.with_suffix(part_path.suffix + ".partial")
    remove_if_exists(partial)

    if args.posterior_dir is not None:
        enrich_pair_with_posterior(
            raw_path=raw_path,
            output_path=partial,
            posterior_dir=args.posterior_dir,
            posterior_template=args.posterior_template,
            subject=subject,
            unit_values=unit_values,
            t0=t0,
            t1=t1,
            n_samples=int(args.n_posterior_samples),
            seed=int(args.posterior_seed),
            batch_size=int(args.posterior_chunk_size),
            compression=args.parquet_compression,
            row_group_size=int(args.parquet_row_group_size),
        )
    else:
        copy_pair_without_posterior(
            raw_path=raw_path,
            output_path=partial,
            batch_size=int(args.posterior_chunk_size),
            compression=args.parquet_compression,
            row_group_size=int(args.parquet_row_group_size),
        )

    if not partial.exists():
        raise RuntimeError(
            f"Pair output was not created for subject={subject}, {t0}->{t1}."
        )

    partial.replace(part_path)
    remove_if_exists(raw_path)
    return int(pq.ParquetFile(part_path).metadata.num_rows)


def empty_marker_path(part_path: Path) -> Path:
    return part_path.with_suffix(part_path.suffix + ".empty.json")


def write_empty_marker(
    marker_path: Path,
    subject: int,
    unit_values: Mapping[str, Any],
    t0: int,
    t1: int,
) -> None:
    ensure_parent(marker_path)
    marker_path.write_text(
        json.dumps(
            {
                **dict(unit_values),
                "subject": int(subject),
                "t0": int(t0),
                "t1": int(t1),
                "pattern": "all",
                "rows": 0,
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )


def pair_is_complete(part_path: Path, resume: bool) -> bool:
    return bool(resume) and (
        part_path.exists() or empty_marker_path(part_path).exists()
    )


def combine_parts(
    parts: Sequence[Path],
    output: Path,
    compression: str,
    batch_size: int,
    row_group_size: int,
) -> None:
    if not parts:
        raise RuntimeError("No non-empty transition parts were generated.")

    ensure_parent(output)
    partial_output = output.with_suffix(output.suffix + ".partial")
    remove_if_exists(partial_output)

    writer: Optional[pq.ParquetWriter] = None
    target_schema: Optional[pa.Schema] = None
    try:
        for part in parts:
            parquet_file = pq.ParquetFile(part)
            for record_batch in parquet_file.iter_batches(
                batch_size=int(batch_size), use_threads=True
            ):
                table = pa.Table.from_batches([record_batch])
                if writer is None:
                    target_schema = table.schema
                    writer = pq.ParquetWriter(
                        partial_output,
                        target_schema,
                        compression=compression,
                        use_dictionary=True,
                        write_statistics=True,
                    )
                elif target_schema is not None and table.schema != target_schema:
                    table = table.cast(target_schema, safe=False)
                writer.write_table(table, row_group_size=int(row_group_size))
                del table, record_batch
    finally:
        if writer is not None:
            writer.close()

    if not partial_output.exists():
        raise RuntimeError("Final Parquet output was not created.")
    partial_output.replace(output)


def build_manifest(
    args: argparse.Namespace,
    extra_group_cols: Sequence[str],
    reference_alpha: float,
) -> Dict[str, Any]:
    return {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "input": input_signature(args.trajectories),
        "extra_group_cols": list(extra_group_cols),
        "min_dt": int(args.min_dt),
        "max_dt": int(args.max_dt),
        "reference_alpha": float(reference_alpha),
        "transition_mode": "all_temporal_pairs",
        "observation_class_filtering": False,
        "structural_weights": False,
        "posterior_dir": (
            str(args.posterior_dir.resolve())
            if args.posterior_dir is not None
            else None
        ),
        "posterior_template": (
            args.posterior_template if args.posterior_dir is not None else None
        ),
        "n_posterior_samples": int(args.n_posterior_samples),
        "posterior_seed": int(args.posterior_seed),
        "parquet_compression": args.parquet_compression,
        "parquet_row_group_size": int(args.parquet_row_group_size),
        "architecture": "multirepresentation_subject_pair_streaming_v4",
    }


def prepare_work_directory(
    work_directory: Path,
    manifest: Dict[str, Any],
    restart: bool,
) -> None:
    if restart and work_directory.exists():
        shutil.rmtree(work_directory)

    work_directory.mkdir(parents=True, exist_ok=True)
    manifest_path = work_directory / "manifest.json"
    if manifest_path.exists():
        previous = json.loads(manifest_path.read_text(encoding="utf-8"))
        if previous != manifest:
            raise RuntimeError(
                "The existing Step-5 work directory was created with different "
                "inputs or parameters. Use --restart or choose another --work-dir."
            )
    else:
        manifest_path.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )


# =============================================================================
# Reporting
# =============================================================================


def summarize_output(output: Path, extra_group_cols: Sequence[str]) -> Dict[str, Any]:
    lf = pl.scan_parquet(output)
    total_rows = int(pq.ParquetFile(output).metadata.num_rows)

    by_dt = collect_streaming(
        lf.group_by("dt")
        .agg(
            [
                pl.len().alias("n_transitions"),
                pl.col("common4").cast(pl.Float64).mean().alias("fraction_common4"),
                pl.col("forward_ab_eligible").cast(pl.Float64).mean().alias(
                    "fraction_forward_ab_eligible"
                ),
                pl.col("forward_ba_eligible").cast(pl.Float64).mean().alias(
                    "fraction_forward_ba_eligible"
                ),
            ]
        )
        .sort("dt")
    )

    by_class = collect_streaming(
        lf.group_by("obs_class_reference")
        .agg(pl.len().alias("n"))
        .sort("obs_class_reference")
    )

    overall_flags = collect_streaming(
        lf.select(
            [
                pl.col("common4").cast(pl.Float64).mean().alias("fraction_common4"),
                pl.col("forward_ab_eligible").cast(pl.Float64).mean().alias(
                    "fraction_forward_ab_eligible"
                ),
                pl.col("forward_ba_eligible").cast(pl.Float64).mean().alias(
                    "fraction_forward_ba_eligible"
                ),
                pl.col("subject").n_unique().alias("n_subjects"),
                pl.struct(list(extra_group_cols) + ["subject", "aaSeqCDR3"])
                .n_unique()
                .alias("n_subject_clone_pairs"),
                pl.struct(list(extra_group_cols) + ["subject", "t0", "t1"])
                .n_unique()
                .alias("n_subject_interval_pairs"),
            ]
        )
    ).row(0, named=True)

    summary: Dict[str, Any] = {
        "transition_rows": total_rows,
        "n_subjects": int(overall_flags["n_subjects"]),
        "n_subject_clone_pairs": int(overall_flags["n_subject_clone_pairs"]),
        "n_subject_interval_pairs": int(overall_flags["n_subject_interval_pairs"]),
        "fraction_common4": float(overall_flags["fraction_common4"]),
        "fraction_forward_ab_eligible": float(
            overall_flags["fraction_forward_ab_eligible"]
        ),
        "fraction_forward_ba_eligible": float(
            overall_flags["fraction_forward_ba_eligible"]
        ),
        "counts_by_dt": {
            str(row[0]): int(row[1]) for row in by_dt.iter_rows()
        },
        "common4_fraction_by_dt": {
            str(row[0]): float(row[2]) for row in by_dt.iter_rows()
        },
        "counts_by_reference_obs_class": {
            str(row[0]): int(row[1]) for row in by_class.iter_rows()
        },
    }

    schema_names = set(lf.collect_schema().names())
    if "posterior_success" in schema_names:
        posterior = collect_streaming(
            lf.select(
                [
                    pl.col("posterior_success").sum().alias("n_success"),
                    pl.col("posterior_success").mean().alias("fraction"),
                ]
            )
        ).row(0, named=True)
        summary["posterior_success_n"] = int(posterior["n_success"] or 0)
        summary["posterior_success_fraction"] = float(posterior["fraction"] or 0.0)

    return summary


def write_report(path: Path, payload: Dict[str, Any]) -> None:
    ensure_parent(path)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Longitudinal transition assembly report\n\n")
        for key, value in payload.items():
            if isinstance(value, (dict, list, tuple)):
                value = json.dumps(value, ensure_ascii=False)
            handle.write(f"- {key}: {value}\n")


# =============================================================================
# CLI
# =============================================================================


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Assemble generic finite-time transitions from Step-4 "
            "multirepresentation trajectories without estimand-specific filtering."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--trajectories", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--file-sep", default="\t")
    parser.add_argument("--extra-group-cols", default="")

    parser.add_argument("--min-dt", type=int, default=1)
    parser.add_argument("--max-dt", type=int, default=5)

    parser.add_argument("--parquet-compression", default="zstd")
    parser.add_argument("--parquet-row-group-size", type=int, default=100000)
    parser.add_argument("--write-csv-compat", action="store_true")

    parser.add_argument("--posterior-dir", type=Path, default=None)
    parser.add_argument(
        "--posterior-template",
        default="latent_per_clone_logP_{subject}_{time}.posterior.npz",
        help="Relative template inside --posterior-dir; may use extra-group placeholders.",
    )
    parser.add_argument(
        "--allow-shared-posterior-files",
        action="store_true",
        help=(
            "Allow grouped workflows to reuse posterior files whose template does "
            "not contain every extra grouping placeholder. Use only deliberately."
        ),
    )
    parser.add_argument("--n-posterior-samples", type=int, default=1000)
    parser.add_argument("--posterior-seed", type=int, default=123)
    parser.add_argument("--posterior-chunk-size", type=int, default=5000)

    parser.add_argument("--work-dir", type=Path, default=None)
    parser.add_argument("--resume", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--restart", action="store_true")
    parser.add_argument("--keep-work-dir", action="store_true")
    parser.add_argument("--report-md", type=Path, default=None)
    return parser


def validate_arguments(args: argparse.Namespace, extra_group_cols: Sequence[str]) -> None:
    if not args.trajectories.exists():
        raise FileNotFoundError(f"Trajectory file not found: {args.trajectories}")
    if args.out.suffix.lower() not in PARQUET_SUFFIXES:
        raise ValueError("--out must be a .parquet or .pq file")
    if int(args.min_dt) < 1:
        raise ValueError("--min-dt must be at least 1")
    if int(args.max_dt) < int(args.min_dt):
        raise ValueError("--max-dt must be >= --min-dt")
    if int(args.parquet_row_group_size) <= 0:
        raise ValueError("--parquet-row-group-size must be positive")
    if int(args.posterior_chunk_size) <= 0:
        raise ValueError("--posterior-chunk-size must be positive")

    if args.posterior_dir is not None:
        if not args.posterior_dir.exists():
            raise FileNotFoundError(
                f"Posterior directory not found: {args.posterior_dir}"
            )
        if int(args.n_posterior_samples) <= 0:
            raise ValueError("--n-posterior-samples must be positive")
        if extra_group_cols and not args.allow_shared_posterior_files:
            missing_placeholders = [
                column
                for column in extra_group_cols
                if "{" + column + "}" not in args.posterior_template
            ]
            if missing_placeholders:
                raise ValueError(
                    "Grouped posterior propagation requires every extra group column "
                    "in --posterior-template to prevent cross-configuration reuse. "
                    "Missing placeholders: " + ", ".join(missing_placeholders)
                )


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    extra_group_cols = split_csv(args.extra_group_cols)
    validate_arguments(args, extra_group_cols)

    print(f"[STEP5] {SCRIPT_VERSION}")
    input_scan = scan_table(args.trajectories, args.file_sep)
    schema_names = input_scan.collect_schema().names()

    require_columns(
        schema_names,
        list(extra_group_cols) + CORE_REQUIRED_COLUMNS,
    )
    validate_state_contract(input_scan, extra_group_cols)
    validate_unique_state_keys(input_scan, extra_group_cols)
    reference_alpha = validate_reference_contract(input_scan)

    endpoint_columns = [
        column
        for column in (CORE_REQUIRED_COLUMNS + OPTIONAL_ENDPOINT_COLUMNS)
        if column in set(schema_names)
        and column not in {"subject", "aaSeqCDR3", "time"}
    ]
    # Remove exact duplicates while preserving order.
    endpoint_columns = list(dict.fromkeys(endpoint_columns))

    unit_cols = list(extra_group_cols) + ["subject"]
    units_frame = collect_streaming(
        input_scan.select(unit_cols).unique().sort(unit_cols)
    )
    units = units_frame.to_dicts()

    print(f"[STEP5] Processing units: {len(units):,}")
    print(f"[STEP5] reference_alpha={reference_alpha:g}")
    print(f"[STEP5] lags={args.min_dt}..{args.max_dt}")
    print(
        "[STEP5] extra groups:", extra_group_cols if extra_group_cols else "<none>"
    )

    work_directory = args.work_dir or (
        args.out.parent / f".{args.out.stem}_step5_work"
    )
    manifest = build_manifest(args, extra_group_cols, reference_alpha)
    prepare_work_directory(work_directory, manifest, bool(args.restart))

    raw_directory = work_directory / "raw"
    parts_directory = work_directory / "parts"
    raw_directory.mkdir(parents=True, exist_ok=True)
    parts_directory.mkdir(parents=True, exist_ok=True)

    expected_parts: List[Path] = []
    empty_pairs = 0
    prepared_state_rows = 0

    for unit_row in units:
        subject = int(unit_row["subject"])
        unit_values = {column: unit_row[column] for column in extra_group_cols}
        unit_token = unit_identity(unit_values, subject)
        print(f"[STEP5] Preparing unit {unit_token}")

        unit_frame = prepare_unit(
            trajectories=args.trajectories,
            separator=args.file_sep,
            subject=subject,
            unit_values=unit_values,
            extra_group_cols=extra_group_cols,
            endpoint_columns=endpoint_columns,
        )
        prepared_state_rows += int(unit_frame.height)
        if unit_frame.is_empty():
            continue

        times = sorted(
            int(value) for value in unit_frame.get_column("time").unique().to_list()
        )

        for index, t0 in enumerate(times[:-1]):
            for t1 in times[index + 1 :]:
                dt_value = int(t1 - t0)
                if dt_value < int(args.min_dt) or dt_value > int(args.max_dt):
                    continue

                stem = f"{unit_token}__t{t0:03d}_t{t1:03d}_all"
                raw_path = raw_directory / f"{stem}.raw.parquet"
                part_path = parts_directory / f"{stem}.parquet"

                if pair_is_complete(part_path, bool(args.resume)):
                    if part_path.exists():
                        expected_parts.append(part_path)
                        print(f"[STEP5] Reusing completed part: {part_path.name}")
                    else:
                        empty_pairs += 1
                    continue

                transitions = build_temporal_pair(
                    unit_frame=unit_frame,
                    subject=subject,
                    unit_values=unit_values,
                    t0=t0,
                    t1=t1,
                    reference_alpha=reference_alpha,
                )

                marker = empty_marker_path(part_path)
                remove_if_exists(marker)
                remove_if_exists(raw_path)

                raw_rows = write_raw_pair(
                    transitions=transitions,
                    raw_path=raw_path,
                    compression=args.parquet_compression,
                    row_group_size=int(args.parquet_row_group_size),
                )
                del transitions
                gc.collect()

                if raw_rows == 0:
                    write_empty_marker(marker, subject, unit_values, t0, t1)
                    empty_pairs += 1
                    print(
                        f"[STEP5] Empty pair {unit_token} {t0}->{t1}"
                    )
                else:
                    rows = finalize_pair_part(
                        raw_path=raw_path,
                        part_path=part_path,
                        args=args,
                        subject=subject,
                        unit_values=unit_values,
                        t0=t0,
                        t1=t1,
                    )
                    expected_parts.append(part_path)
                    print(
                        f"[STEP5] Completed {unit_token} {t0}->{t1}: {rows:,} rows"
                    )
                gc.collect()

        del unit_frame
        gc.collect()

    completed_parts = sorted({path for path in expected_parts if path.exists()})
    print(f"[STEP5] Combining {len(completed_parts):,} completed parts")
    combine_parts(
        parts=completed_parts,
        output=args.out,
        compression=args.parquet_compression,
        batch_size=int(args.posterior_chunk_size),
        row_group_size=int(args.parquet_row_group_size),
    )

    if args.write_csv_compat:
        csv_path = args.out.with_suffix(".csv")
        print(f"[STEP5] Writing large CSV compatibility copy: {csv_path}")
        csv_lazy = pl.scan_parquet(args.out)
        try:
            csv_lazy.sink_csv(csv_path)
        except (AttributeError, TypeError):
            collect_streaming(csv_lazy).write_csv(csv_path)

    output_summary = summarize_output(args.out, extra_group_cols)
    output_schema = pl.scan_parquet(args.out).collect_schema().names()

    report_payload: Dict[str, Any] = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "trajectories": str(args.trajectories),
        "output": str(args.out),
        "extra_group_cols": extra_group_cols,
        "processing_units": len(units),
        "prepared_state_rows": int(prepared_state_rows),
        "min_dt": int(args.min_dt),
        "max_dt": int(args.max_dt),
        "reference_alpha": float(reference_alpha),
        "transition_mode": "all_temporal_pairs",
        "observation_class_filtering": False,
        "structural_weights": False,
        "posterior_propagation": args.posterior_dir is not None,
        "completed_parts": len(completed_parts),
        "empty_pairs": int(empty_pairs),
        "output_columns": output_schema,
        **output_summary,
    }

    report_path = args.report_md or (
        args.out.parent / "transition_assembly_report.md"
    )
    write_report(report_path, report_payload)

    output_manifest = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "canonical_step4_source": "4-multirepresentation_trajectory_assembly.py",
        "canonical_output": str(args.out),
        "extra_group_cols": extra_group_cols,
        "reference_alpha": float(reference_alpha),
        "transition_universe": (
            "inner join of canonical Step-4 states by aaSeqCDR3 for all temporal "
            "pairs within requested lag range"
        ),
        "state_layers": {
            "model_based_consensus": [
                "x0_latent",
                "x1_latent",
                "dx_latent",
                "xmid_latent",
                "xstar_latent",
            ],
            "replicate_resolved_observed": [
                "x_observed_rep1_t0",
                "x_observed_rep1_t1",
                "dx_observed_rep1",
                "x_observed_rep2_t0",
                "x_observed_rep2_t1",
                "dx_observed_rep2",
            ],
            "observation_annotations": [
                "p_value_t0",
                "p_value_t1",
                "observable_reference_t0",
                "observable_reference_t1",
                "obs_class_reference",
                "p_detect_state_t0",
                "p_detect_state_t1",
            ],
        },
        "eligibility_flags": {
            "forward_ab_eligible": (
                "rep1 positive at t0 AND rep2 positive at t0 and t1"
            ),
            "forward_ba_eligible": (
                "rep2 positive at t0 AND rep1 positive at t0 and t1"
            ),
            "common4": "both replicates positive at both endpoints",
        },
        "reference_observation_classes_are_biological_states": False,
        "observation_class_filtering": False,
        "structural_weights": False,
        "dynamic_estimands_defined_here": False,
        "primary_downstream_estimands": {
            "forward": "observed replicate-decoupled AB/BA",
            "fluctuations": (
                "cross-replicate covariance of dx_observed_rep1 and "
                "dx_observed_rep2 on common4"
            ),
            "fluctuation_conditioning": "xmid_latent",
        },
        "optional_model_based_posterior_propagation": args.posterior_dir is not None,
    }
    manifest_path = args.out.parent / "transition_assembly_manifest.json"
    manifest_path.write_text(
        json.dumps(output_manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print(f"[STEP5] Wrote transitions: {args.out}")
    print(f"[STEP5] Wrote report: {report_path}")
    print(f"[STEP5] Wrote manifest: {manifest_path}")

    if not args.keep_work_dir:
        shutil.rmtree(work_directory, ignore_errors=True)

    print("[STEP5] Completed. No estimand-specific filtering or weighting was applied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
