#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
7-pseudo_forward_technical_null_compact.py
==========================================

ClonoDynamics Step 7 — compact-native pseudo 1x12 technical-null benchmark.

This script is written specifically for the 14-column compact files generated by:

    pseudo_1x12_build_upstream_multirepresentation_streaming.py
        --compact-step7-cache
        --compact-step7-dt 1
        --cleanup-after-compact

Expected input layout
---------------------
<ensemble-root>/
    C000001/step7_cache/step7_dt1.parquet
    C000002/step7_cache/step7_dt1.parquet
    ...
    C002000/step7_cache/step7_dt1.parquet

Required compact schema (and ONLY schema used by this analyzer)
---------------------------------------------------------------
    configuration_id
    subject
    dt
    x0_latent
    xmid_latent
    xstar_latent
    dx_latent
    x_observed_rep1_t0
    x_observed_rep2_t0
    dx_observed_rep1
    dx_observed_rep2
    forward_ab_eligible
    forward_ba_eligible
    common4

Statistical design
------------------
The ensemble contains ONE biological source subject measured 12 times and
reassembled into many randomized 6-timepoint x 2-replicate pseudo-longitudinal
configurations.

`configuration_id` is a randomization realization, NOT a biological subject.
Therefore:
    - no subject bootstrap is performed;
    - configuration percentiles are RANDOMIZATION intervals, not biological CIs;
    - no nested pseudo-time permutation is performed.

Primary observed replicate-decoupled forward estimator
-------------------------------------------------------
For each configuration, AB and BA are estimated SEPARATELY:

    AB:
        conditioning  = x_observed_rep1_t0
        displacement  = dx_observed_rep2
        eligibility   = forward_ab_eligible

    BA:
        conditioning  = x_observed_rep2_t0
        displacement  = dx_observed_rep1
        eligibility   = forward_ba_eligible

AB and BA are NEVER concatenated to estimate the primary curve.

Instead, after binning on the SAME fixed global abundance bins:

    cross_combined(bin)
        = 0.5 * cross_AB(bin)
        + 0.5 * cross_BA(bin)

for mean displacement, median-displacement descriptor and P(dx>0).

Thus AB and BA have exactly equal fold weight in every combined bin,
independently of their row counts.

The global forward bin edges are also derived with equal AB/BA influence:
within every selected configuration the edge-estimation sample contains the
same number of AB-eligible and BA-eligible conditioning values.

Matched same-measure coupling control
-------------------------------------
On the shared `common4` support:

    same_A:
        x_observed_rep1_t0 -> dx_observed_rep1

    cross_AB_matched:
        x_observed_rep1_t0 -> dx_observed_rep2

    same_B:
        x_observed_rep2_t0 -> dx_observed_rep2

    cross_BA_matched:
        x_observed_rep2_t0 -> dx_observed_rep1

Again:

    same_combined
        = 0.5 * same_A + 0.5 * same_B

    cross_combined_matched
        = 0.5 * cross_AB_matched + 0.5 * cross_BA_matched

bin by bin.

Secondary latent conditioning-geometry diagnostic
-------------------------------------------------
The compact cache also permits a descriptive comparison of:

    x0_latent
    xmid_latent
    xstar_latent

against the same `dx_latent`.

Because the compact cache does NOT retain `obs_class_reference`,
this block is explicitly UNRESTRICTED with respect to TT/TF/FT/FF and must not
be described as the historical TT-only conditioning benchmark.

No universal conditioning-coordinate "winner" is selected here.

Resume safety
-------------
Each configuration checkpoint is tied to an analysis signature containing:
    - selected configuration IDs and compact-file identities;
    - all analysis parameters;
    - the exact global bin edges;
    - script version.

Changing from --max-configs 3 to the full ensemble changes the signature, so
test checkpoints are automatically invalidated.

Typical smoke test
------------------
python code/dynamics_4/7-pseudo_forward_technical_null_compact.py \
  --ensemble-root ./results_4/pseudo/ensemble_results_v3 \
  --outdir ./results_4/7-pseudo_forward_technical_null_compact \
  --expected-configs 2000 \
  --max-configs 3 \
  --dt 1 \
  --seed 123

Production
----------
Run the same command without --max-configs 3.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from itertools import combinations
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


SCRIPT_VERSION = "v1-compact-native-equal-weight-ABBA-2026-09-17"

COMPACT_REL = Path("step7_cache") / "step7_dt1.parquet"

COMPACT_COLUMNS = [
    "configuration_id",
    "subject",
    "dt",
    "x0_latent",
    "xmid_latent",
    "xstar_latent",
    "dx_latent",
    "x_observed_rep1_t0",
    "x_observed_rep2_t0",
    "dx_observed_rep1",
    "dx_observed_rep2",
    "forward_ab_eligible",
    "forward_ba_eligible",
    "common4",
]

LATENT_CANDIDATES = ["x0_latent", "xmid_latent", "xstar_latent"]


# -----------------------------------------------------------------------------
# Basic utilities
# -----------------------------------------------------------------------------

def json_safe(value):
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return None if np.isnan(value) else float(value)
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, dict):
        return {str(k): json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(v) for v in value]
    return value


def stable_hash(payload: Dict[str, object]) -> str:
    raw = json.dumps(
        json_safe(payload),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def path_identity(path: Path) -> Dict[str, object]:
    p = path.expanduser().resolve(strict=True)
    st = p.stat()
    return {
        "path": str(p),
        "size_bytes": int(st.st_size),
        "mtime_ns": int(st.st_mtime_ns),
    }


def parquet_columns(path: Path) -> List[str]:
    try:
        import pyarrow.parquet as pq
        return list(pq.ParquetFile(path).schema.names)
    except Exception:
        return list(pd.read_parquet(path).columns)


def normalize_bool(series: pd.Series) -> np.ndarray:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).to_numpy(dtype=bool)
    if pd.api.types.is_numeric_dtype(series):
        return (
            pd.to_numeric(series, errors="coerce")
            .fillna(0)
            .ne(0)
            .to_numpy(dtype=bool)
        )
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .isin(["true", "t", "1", "yes", "y"])
        .to_numpy(dtype=bool)
    )


def finite_array(values) -> np.ndarray:
    x = pd.to_numeric(pd.Series(values), errors="coerce").to_numpy(dtype=float)
    return x[np.isfinite(x)]


def safe_slope_intercept(
    x: np.ndarray,
    y: np.ndarray,
) -> Tuple[float, float, float]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    if int(ok.sum()) < 2:
        return np.nan, np.nan, np.nan
    x = x[ok]
    y = y[ok]
    if np.ptp(x) <= 0:
        return np.nan, np.nan, np.nan
    slope, intercept = np.polyfit(x, y, 1)
    slope = float(slope)
    intercept = float(intercept)
    zero = -intercept / slope if np.isfinite(slope) and abs(slope) > 1e-15 else np.nan
    return slope, intercept, float(zero) if np.isfinite(zero) else np.nan


def safe_pearson(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    if int(ok.sum()) < 2:
        return np.nan
    x = x[ok]
    y = y[ok]
    if np.std(x) <= 0 or np.std(y) <= 0:
        return np.nan
    return float(np.corrcoef(x, y)[0, 1])


def sample_without_replacement(
    x: np.ndarray,
    n: int,
    rng: np.random.Generator,
) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if x.size <= int(n):
        return x
    idx = rng.choice(x.size, size=int(n), replace=False)
    return x[idx]


# -----------------------------------------------------------------------------
# Input discovery and validation
# -----------------------------------------------------------------------------

def discover_configurations(
    ensemble_root: Path,
    expected_configs: int,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for cdir in sorted(ensemble_root.glob("C*")):
        if not cdir.is_dir():
            continue
        compact = cdir / COMPACT_REL
        if compact.is_file() and compact.stat().st_size > 0:
            rows.append(
                {
                    "configuration_id": cdir.name,
                    "configuration_dir": str(cdir.resolve()),
                    "compact": str(compact.resolve()),
                }
            )

    if not rows:
        raise FileNotFoundError(
            f"No compact Step-7 files found under {ensemble_root}. "
            f"Expected Cxxxxxx/{COMPACT_REL}."
        )

    manifest = (
        pd.DataFrame(rows)
        .sort_values("configuration_id")
        .reset_index(drop=True)
    )

    if int(expected_configs) > 0:
        n = int(expected_configs)
        expected_ids = [f"C{i:06d}" for i in range(1, n + 1)]
        got_ids = manifest["configuration_id"].astype(str).tolist()

        if got_ids != expected_ids:
            missing = [x for x in expected_ids if x not in set(got_ids)][:10]
            extra = [x for x in got_ids if x not in set(expected_ids)][:10]
            raise ValueError(
                f"Expected contiguous C000001..C{n:06d}; "
                f"found {len(got_ids)} compact configurations. "
                f"First missing={missing}; first unexpected={extra}"
            )

    return manifest


def validate_compact(
    path: Path,
    cid: str,
    dt: int,
    require_exact_schema: bool,
) -> Dict[str, object]:
    cols = parquet_columns(path)
    colset = set(cols)

    missing = sorted(set(COMPACT_COLUMNS) - colset)
    if missing:
        raise ValueError(
            f"{cid}: compact cache missing required columns {missing}"
        )

    extras = sorted(colset - set(COMPACT_COLUMNS))
    if require_exact_schema and extras:
        raise ValueError(
            f"{cid}: compact cache contains unexpected extra columns {extras}"
        )

    d = pd.read_parquet(
        path,
        columns=[
            "configuration_id",
            "subject",
            "dt",
            "forward_ab_eligible",
            "forward_ba_eligible",
            "common4",
        ],
    )

    if d.empty:
        raise ValueError(f"{cid}: compact cache is empty")

    ids = set(d["configuration_id"].astype(str).dropna().unique())
    if ids != {cid}:
        raise ValueError(
            f"{cid}: cache contains configuration_id values {sorted(ids)}"
        )

    subjects = set(
        pd.to_numeric(d["subject"], errors="coerce")
        .dropna()
        .astype(int)
        .unique()
    )
    if subjects != {1}:
        raise ValueError(
            f"{cid}: expected biological source subject {{1}}, found {subjects}"
        )

    dts = sorted(
        pd.to_numeric(d["dt"], errors="coerce")
        .dropna()
        .astype(int)
        .unique()
        .tolist()
    )
    if dts != [int(dt)]:
        raise ValueError(
            f"{cid}: expected compact dt={dt}, found {dts}"
        )

    ab = normalize_bool(d["forward_ab_eligible"])
    ba = normalize_bool(d["forward_ba_eligible"])
    c4 = normalize_bool(d["common4"])

    audit = {
        "n_rows": int(len(d)),
        "n_forward_ab_eligible": int(ab.sum()),
        "n_forward_ba_eligible": int(ba.sum()),
        "n_common4": int(c4.sum()),
    }

    if min(
        audit["n_forward_ab_eligible"],
        audit["n_forward_ba_eligible"],
        audit["n_common4"],
    ) <= 0:
        raise RuntimeError(
            f"{cid}: one or more required support sets are empty: {audit}"
        )

    return audit


# -----------------------------------------------------------------------------
# Global fixed-bin construction
# -----------------------------------------------------------------------------

def quantile_edges(
    x: np.ndarray,
    n_bins: int,
    q_low: float,
    q_high: float,
) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if x.size == 0:
        raise ValueError("No finite values available for bin-edge construction")

    probs = np.linspace(float(q_low), float(q_high), int(n_bins) + 1)
    edges = np.unique(np.quantile(x, probs).astype(float))

    if edges.size < 3 or not np.all(np.diff(edges) > 0):
        raise ValueError(
            "Could not construct enough strictly increasing quantile edges"
        )
    return edges


def equal_width_edges(
    low: float,
    high: float,
    n_bins: int,
) -> np.ndarray:
    if not np.isfinite(low) or not np.isfinite(high) or low >= high:
        raise ValueError(f"Invalid abundance range: low={low}, high={high}")
    return np.linspace(float(low), float(high), int(n_bins) + 1)


def derive_forward_edges_equal_fold_weight(
    manifest: pd.DataFrame,
    args: argparse.Namespace,
) -> Tuple[np.ndarray, Dict[str, object]]:
    """
    Derive global forward bin edges from an equal-weight AB/BA sample.

    For every configuration:
        m = min(target_per_fold, n_AB, n_BA)

    and exactly m AB conditioning values + m BA conditioning values are added
    to the edge-estimation pool.

    Therefore:
        - AB and BA have equal influence within every configuration;
        - configurations have equal influence whenever both folds contain at
          least target_per_fold finite eligible rows (true in the production
          dataset under normal settings).
    """
    pooled: List[np.ndarray] = []
    per_config_rows: List[Dict[str, object]] = []

    target_per_fold = max(1, int(args.edge_sample_per_config) // 2)

    for i, row in manifest.reset_index(drop=True).iterrows():
        path = Path(row["compact"])
        d = pd.read_parquet(
            path,
            columns=[
                "x_observed_rep1_t0",
                "x_observed_rep2_t0",
                "forward_ab_eligible",
                "forward_ba_eligible",
            ],
        )

        ab_mask = normalize_bool(d["forward_ab_eligible"])
        ba_mask = normalize_bool(d["forward_ba_eligible"])

        x_ab = finite_array(d.loc[ab_mask, "x_observed_rep1_t0"])
        x_ba = finite_array(d.loc[ba_mask, "x_observed_rep2_t0"])

        m = min(target_per_fold, len(x_ab), len(x_ba))
        if m <= 0:
            raise RuntimeError(
                f"{row['configuration_id']}: cannot build equal-weight "
                "forward edge sample because one fold is empty"
            )

        rng_ab = np.random.default_rng(int(args.seed) + 2 * i)
        rng_ba = np.random.default_rng(int(args.seed) + 2 * i + 1)

        s_ab = sample_without_replacement(x_ab, m, rng_ab)
        s_ba = sample_without_replacement(x_ba, m, rng_ba)

        # Enforce equality exactly, even in pathological sampling cases.
        m2 = min(len(s_ab), len(s_ba))
        s_ab = s_ab[:m2]
        s_ba = s_ba[:m2]

        pooled.extend([s_ab, s_ba])
        per_config_rows.append(
            {
                "configuration_id": str(row["configuration_id"]),
                "n_edge_AB": int(len(s_ab)),
                "n_edge_BA": int(len(s_ba)),
                "equal_AB_BA": bool(len(s_ab) == len(s_ba)),
            }
        )

    x = np.concatenate(pooled)
    if args.forward_binning == "quantile":
        edges = quantile_edges(
            x,
            args.forward_n_bins,
            args.forward_q_low,
            args.forward_q_high,
        )
    else:
        lo = float(np.quantile(x, args.forward_q_low))
        hi = float(np.quantile(x, args.forward_q_high))
        edges = equal_width_edges(lo, hi, args.forward_n_bins)

    audit = {
        "policy": "equal AB/BA rows per configuration",
        "target_rows_per_fold_per_configuration": int(target_per_fold),
        "n_edge_pool_rows": int(len(x)),
        "n_bins": int(len(edges) - 1),
        "x_min": float(edges[0]),
        "x_max": float(edges[-1]),
        "binning": str(args.forward_binning),
        "q_low": float(args.forward_q_low),
        "q_high": float(args.forward_q_high),
        "all_configurations_equal_AB_BA_edge_weight": bool(
            all(r["equal_AB_BA"] for r in per_config_rows)
        ),
    }

    return edges, audit


def derive_conditioning_edges(
    manifest: pd.DataFrame,
    args: argparse.Namespace,
) -> Tuple[np.ndarray, Dict[str, object]]:
    """
    Derive a common absolute x-range for x0/xmid/xstar.

    Equal numbers of finite complete-case rows are sampled from every
    configuration, so the randomization configurations contribute equally to
    this descriptive secondary diagnostic.
    """
    sampled: Dict[str, List[np.ndarray]] = {
        c: [] for c in LATENT_CANDIDATES
    }

    target = int(args.conditioning_edge_sample_per_config)

    for i, row in manifest.reset_index(drop=True).iterrows():
        d = pd.read_parquet(
            Path(row["compact"]),
            columns=LATENT_CANDIDATES + ["dx_latent"],
        )

        keep = np.isfinite(
            pd.to_numeric(d["dx_latent"], errors="coerce").to_numpy(float)
        )
        for c in LATENT_CANDIDATES:
            keep &= np.isfinite(
                pd.to_numeric(d[c], errors="coerce").to_numpy(float)
            )

        d = d.loc[keep, LATENT_CANDIDATES].copy()
        if d.empty:
            raise RuntimeError(
                f"{row['configuration_id']}: no complete latent conditioning rows"
            )

        m = min(target, len(d))
        rng = np.random.default_rng(int(args.seed) + 100000 + i)
        if len(d) > m:
            idx = rng.choice(len(d), size=m, replace=False)
            d = d.iloc[idx]

        for c in LATENT_CANDIDATES:
            sampled[c].append(
                pd.to_numeric(d[c], errors="coerce").to_numpy(float)
            )

    pooled = {c: np.concatenate(sampled[c]) for c in LATENT_CANDIDATES}

    lows = [
        float(np.quantile(pooled[c], args.conditioning_q_low))
        for c in LATENT_CANDIDATES
    ]
    highs = [
        float(np.quantile(pooled[c], args.conditioning_q_high))
        for c in LATENT_CANDIDATES
    ]

    lo = max(lows)
    hi = min(highs)
    edges = equal_width_edges(lo, hi, args.conditioning_n_bins)

    return edges, {
        "policy": "equal configuration sampling; common candidate support",
        "rows_per_configuration_target": int(target),
        "n_bins": int(len(edges) - 1),
        "x_min": float(edges[0]),
        "x_max": float(edges[-1]),
        "q_low": float(args.conditioning_q_low),
        "q_high": float(args.conditioning_q_high),
    }


def write_edges(path: Path, edges: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(
        {
            "bin": np.arange(1, len(edges), dtype=int),
            "x_lo": edges[:-1],
            "x_hi": edges[1:],
            "x_center": 0.5 * (edges[:-1] + edges[1:]),
        }
    ).to_csv(path, index=False)


# -----------------------------------------------------------------------------
# Per-configuration curves
# -----------------------------------------------------------------------------

def assign_bins(x: np.ndarray, edges: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    out = np.zeros(x.size, dtype=np.int32)

    finite = np.isfinite(x)
    if not finite.any():
        return out

    xx = x[finite]
    idx = np.searchsorted(edges, xx, side="right") - 1
    idx[xx == edges[-1]] = len(edges) - 2

    valid = (idx >= 0) & (idx < len(edges) - 1)
    positions = np.where(finite)[0]
    out[positions[valid]] = idx[valid] + 1
    return out


def binned_curve(
    frame: pd.DataFrame,
    x_col: str,
    y_col: str,
    mask: np.ndarray,
    edges: np.ndarray,
    min_n: int,
    section: str,
    representation: str,
) -> pd.DataFrame:
    x = pd.to_numeric(frame[x_col], errors="coerce").to_numpy(float)
    y = pd.to_numeric(frame[y_col], errors="coerce").to_numpy(float)

    keep = (
        np.asarray(mask, dtype=bool)
        & np.isfinite(x)
        & np.isfinite(y)
    )

    x = x[keep]
    y = y[keep]

    if len(x) == 0:
        return pd.DataFrame()

    bins = assign_bins(x, edges)
    within = bins > 0
    x = x[within]
    y = y[within]
    bins = bins[within]

    rows: List[Dict[str, object]] = []

    for b in range(1, len(edges)):
        sel = bins == b
        n = int(sel.sum())
        if n == 0:
            continue

        yy = y[sel]
        xx = x[sel]

        rows.append(
            {
                "section": section,
                "representation": representation,
                "bin": int(b),
                "x_lo": float(edges[b - 1]),
                "x_hi": float(edges[b]),
                "x_center": float(0.5 * (edges[b - 1] + edges[b])),
                "x_median": float(np.median(xx)),
                "n_rows": n,
                "mean_dx": float(np.mean(yy)),
                "median_dx": float(np.median(yy)),
                "p_dx_gt0": float(np.mean(yy > 0)),
                "meets_min_n": bool(n >= int(min_n)),
            }
        )

    return pd.DataFrame(rows)


def combine_equal_fold_weight(
    fold_a: pd.DataFrame,
    fold_b: pd.DataFrame,
    section: str,
    representation: str,
    fold_a_name: str,
    fold_b_name: str,
) -> pd.DataFrame:
    """
    Combine two already-binned folds with EXACT 0.5 / 0.5 weight.

    Row counts are retained for audit only and NEVER used as weights.
    A combined bin is inferentially valid only when both component folds meet
    the fold-specific minimum-n threshold.
    """
    if fold_a.empty or fold_b.empty:
        return pd.DataFrame()

    a = fold_a[
        [
            "bin",
            "x_lo",
            "x_hi",
            "x_center",
            "x_median",
            "n_rows",
            "mean_dx",
            "median_dx",
            "p_dx_gt0",
            "meets_min_n",
        ]
    ].rename(
        columns={
            "x_median": "x_median_A",
            "n_rows": "n_rows_A",
            "mean_dx": "mean_dx_A",
            "median_dx": "median_dx_A",
            "p_dx_gt0": "p_dx_gt0_A",
            "meets_min_n": "valid_A",
        }
    )

    b = fold_b[
        [
            "bin",
            "x_median",
            "n_rows",
            "mean_dx",
            "median_dx",
            "p_dx_gt0",
            "meets_min_n",
        ]
    ].rename(
        columns={
            "x_median": "x_median_B",
            "n_rows": "n_rows_B",
            "mean_dx": "mean_dx_B",
            "median_dx": "median_dx_B",
            "p_dx_gt0": "p_dx_gt0_B",
            "meets_min_n": "valid_B",
        }
    )

    m = a.merge(b, on="bin", how="inner")
    rows: List[Dict[str, object]] = []

    for r in m.itertuples(index=False):
        rows.append(
            {
                "section": section,
                "representation": representation,
                "bin": int(r.bin),
                "x_lo": float(r.x_lo),
                "x_hi": float(r.x_hi),
                "x_center": float(r.x_center),
                "x_median": float(
                    0.5 * float(r.x_median_A)
                    + 0.5 * float(r.x_median_B)
                ),
                # Audit only; not an estimator weight.
                "n_rows": int(r.n_rows_A + r.n_rows_B),
                "n_rows_fold_A": int(r.n_rows_A),
                "n_rows_fold_B": int(r.n_rows_B),
                "mean_dx": float(
                    0.5 * float(r.mean_dx_A)
                    + 0.5 * float(r.mean_dx_B)
                ),
                # Equal-weight fold descriptor, NOT pooled-row median.
                "median_dx": float(
                    0.5 * float(r.median_dx_A)
                    + 0.5 * float(r.median_dx_B)
                ),
                "p_dx_gt0": float(
                    0.5 * float(r.p_dx_gt0_A)
                    + 0.5 * float(r.p_dx_gt0_B)
                ),
                "meets_min_n": bool(r.valid_A and r.valid_B),
                "fold_A": fold_a_name,
                "fold_B": fold_b_name,
                "fold_A_weight": 0.5,
                "fold_B_weight": 0.5,
                "row_count_weighting_used": False,
            }
        )

    return pd.DataFrame(rows)


def curve_metrics(
    curve: pd.DataFrame,
    min_valid_bins: int,
) -> Dict[str, object]:
    if curve.empty:
        return {
            "n_bins_valid": 0,
            "mean_bin_mean_dx": np.nan,
            "mean_abs_bin_mean_dx": np.nan,
            "rms_bin_mean_dx": np.nan,
            "max_abs_bin_mean_dx": np.nan,
            "mean_abs_probability_bias": np.nan,
            "slope_mean_dx_vs_x": np.nan,
            "intercept_mean_dx_vs_x": np.nan,
            "zero_crossing_x": np.nan,
        }

    valid = curve[curve["meets_min_n"].astype(bool)].copy()

    if len(valid) < int(min_valid_bins):
        return {
            "n_bins_valid": int(len(valid)),
            "mean_bin_mean_dx": np.nan,
            "mean_abs_bin_mean_dx": np.nan,
            "rms_bin_mean_dx": np.nan,
            "max_abs_bin_mean_dx": np.nan,
            "mean_abs_probability_bias": np.nan,
            "slope_mean_dx_vs_x": np.nan,
            "intercept_mean_dx_vs_x": np.nan,
            "zero_crossing_x": np.nan,
        }

    x = pd.to_numeric(valid["x_center"], errors="coerce").to_numpy(float)
    y = pd.to_numeric(valid["mean_dx"], errors="coerce").to_numpy(float)
    p = pd.to_numeric(valid["p_dx_gt0"], errors="coerce").to_numpy(float)

    slope, intercept, zero = safe_slope_intercept(x, y)

    return {
        "n_bins_valid": int(len(valid)),
        "mean_bin_mean_dx": float(np.mean(y)),
        "mean_abs_bin_mean_dx": float(np.mean(np.abs(y))),
        "rms_bin_mean_dx": float(np.sqrt(np.mean(y * y))),
        "max_abs_bin_mean_dx": float(np.max(np.abs(y))),
        "mean_abs_probability_bias": float(np.mean(np.abs(p - 0.5))),
        "slope_mean_dx_vs_x": slope,
        "intercept_mean_dx_vs_x": intercept,
        "zero_crossing_x": zero,
    }


def metric_records(
    section: str,
    representation: str,
    metrics: Dict[str, object],
) -> List[Dict[str, object]]:
    return [
        {
            "section": section,
            "representation": representation,
            "metric": metric,
            "value": value,
        }
        for metric, value in metrics.items()
    ]


def fold_concordance(
    ab: pd.DataFrame,
    ba: pd.DataFrame,
) -> Dict[str, object]:
    if ab.empty or ba.empty:
        return {
            "n_matched_valid_bins": 0,
            "pearson_r_AB_BA": np.nan,
            "mean_abs_AB_BA_difference": np.nan,
            "rms_AB_BA_difference": np.nan,
            "max_abs_AB_BA_difference": np.nan,
        }

    a = ab[ab["meets_min_n"].astype(bool)][
        ["bin", "mean_dx"]
    ].rename(columns={"mean_dx": "AB"})

    b = ba[ba["meets_min_n"].astype(bool)][
        ["bin", "mean_dx"]
    ].rename(columns={"mean_dx": "BA"})

    m = a.merge(b, on="bin", how="inner").dropna()

    if m.empty:
        return {
            "n_matched_valid_bins": 0,
            "pearson_r_AB_BA": np.nan,
            "mean_abs_AB_BA_difference": np.nan,
            "rms_AB_BA_difference": np.nan,
            "max_abs_AB_BA_difference": np.nan,
        }

    x = m["AB"].to_numpy(float)
    y = m["BA"].to_numpy(float)
    d = x - y

    return {
        "n_matched_valid_bins": int(len(m)),
        "pearson_r_AB_BA": safe_pearson(x, y),
        "mean_abs_AB_BA_difference": float(np.mean(np.abs(d))),
        "rms_AB_BA_difference": float(np.sqrt(np.mean(d * d))),
        "max_abs_AB_BA_difference": float(np.max(np.abs(d))),
    }


# -----------------------------------------------------------------------------
# One compact configuration
# -----------------------------------------------------------------------------

def analyze_configuration(
    path: Path,
    cid: str,
    args: argparse.Namespace,
    forward_edges: np.ndarray,
    conditioning_edges: np.ndarray,
) -> Dict[str, object]:
    d = pd.read_parquet(path, columns=COMPACT_COLUMNS)

    if len(d) == 0:
        raise RuntimeError(f"{cid}: empty compact cache")

    ab_eligible = normalize_bool(d["forward_ab_eligible"])
    ba_eligible = normalize_bool(d["forward_ba_eligible"])
    common4 = normalize_bool(d["common4"])

    # ------------------------------------------------------------------
    # 1. PRIMARY OBSERVED REPLICATE-DECOUPLED FORWARD NULL
    # ------------------------------------------------------------------
    cross_ab = binned_curve(
        d,
        x_col="x_observed_rep1_t0",
        y_col="dx_observed_rep2",
        mask=ab_eligible,
        edges=forward_edges,
        min_n=args.min_n_fold,
        section="primary_forward",
        representation="cross_AB",
    )

    cross_ba = binned_curve(
        d,
        x_col="x_observed_rep2_t0",
        y_col="dx_observed_rep1",
        mask=ba_eligible,
        edges=forward_edges,
        min_n=args.min_n_fold,
        section="primary_forward",
        representation="cross_BA",
    )

    cross_combined = combine_equal_fold_weight(
        cross_ab,
        cross_ba,
        section="primary_forward",
        representation="cross_combined",
        fold_a_name="cross_AB",
        fold_b_name="cross_BA",
    )

    # ------------------------------------------------------------------
    # 2. MATCHED SAME-vs-CROSS CONTROL ON common4
    # ------------------------------------------------------------------
    same_a = binned_curve(
        d,
        x_col="x_observed_rep1_t0",
        y_col="dx_observed_rep1",
        mask=common4,
        edges=forward_edges,
        min_n=args.matched_min_n_fold,
        section="matched_same_vs_cross",
        representation="same_A",
    )

    same_b = binned_curve(
        d,
        x_col="x_observed_rep2_t0",
        y_col="dx_observed_rep2",
        mask=common4,
        edges=forward_edges,
        min_n=args.matched_min_n_fold,
        section="matched_same_vs_cross",
        representation="same_B",
    )

    cross_ab_matched = binned_curve(
        d,
        x_col="x_observed_rep1_t0",
        y_col="dx_observed_rep2",
        mask=common4,
        edges=forward_edges,
        min_n=args.matched_min_n_fold,
        section="matched_same_vs_cross",
        representation="cross_AB_matched",
    )

    cross_ba_matched = binned_curve(
        d,
        x_col="x_observed_rep2_t0",
        y_col="dx_observed_rep1",
        mask=common4,
        edges=forward_edges,
        min_n=args.matched_min_n_fold,
        section="matched_same_vs_cross",
        representation="cross_BA_matched",
    )

    same_combined = combine_equal_fold_weight(
        same_a,
        same_b,
        section="matched_same_vs_cross",
        representation="same_combined",
        fold_a_name="same_A",
        fold_b_name="same_B",
    )

    cross_combined_matched = combine_equal_fold_weight(
        cross_ab_matched,
        cross_ba_matched,
        section="matched_same_vs_cross",
        representation="cross_combined_matched",
        fold_a_name="cross_AB_matched",
        fold_b_name="cross_BA_matched",
    )

    # ------------------------------------------------------------------
    # 3. SECONDARY UNRESTRICTED LATENT CONDITIONING GEOMETRY
    # ------------------------------------------------------------------
    latent_complete = np.isfinite(
        pd.to_numeric(d["dx_latent"], errors="coerce").to_numpy(float)
    )
    for c in LATENT_CANDIDATES:
        latent_complete &= np.isfinite(
            pd.to_numeric(d[c], errors="coerce").to_numpy(float)
        )

    conditioning_curves: Dict[str, pd.DataFrame] = {}
    for c in LATENT_CANDIDATES:
        conditioning_curves[c] = binned_curve(
            d,
            x_col=c,
            y_col="dx_latent",
            mask=latent_complete,
            edges=conditioning_edges,
            min_n=args.conditioning_min_n,
            section="conditioning_geometry_unrestricted",
            representation=c,
        )

    curve_tables = [
        cross_ab,
        cross_ba,
        cross_combined,
        same_a,
        same_b,
        same_combined,
        cross_ab_matched,
        cross_ba_matched,
        cross_combined_matched,
        *conditioning_curves.values(),
    ]
    curve_tables = [x for x in curve_tables if not x.empty]

    curves = (
        pd.concat(curve_tables, ignore_index=True, sort=False)
        if curve_tables else pd.DataFrame()
    )

    metrics: List[Dict[str, object]] = []

    primary_metrics = {}
    for rep, curve in [
        ("cross_AB", cross_ab),
        ("cross_BA", cross_ba),
        ("cross_combined", cross_combined),
    ]:
        cm = curve_metrics(curve, args.min_valid_bins)
        primary_metrics[rep] = cm
        metrics += metric_records("primary_forward", rep, cm)

    matched_metrics = {}
    for rep, curve in [
        ("same_A", same_a),
        ("same_B", same_b),
        ("same_combined", same_combined),
        ("cross_AB_matched", cross_ab_matched),
        ("cross_BA_matched", cross_ba_matched),
        ("cross_combined_matched", cross_combined_matched),
    ]:
        cm = curve_metrics(curve, args.matched_min_valid_bins)
        matched_metrics[rep] = cm
        metrics += metric_records("matched_same_vs_cross", rep, cm)

    conditioning_metrics = {}
    for rep, curve in conditioning_curves.items():
        cm = curve_metrics(curve, args.conditioning_min_valid_bins)
        conditioning_metrics[rep] = cm
        metrics += metric_records(
            "conditioning_geometry_unrestricted",
            rep,
            cm,
        )

    # Direct matched decoupling effect.
    same_abs = matched_metrics["same_combined"]["mean_abs_bin_mean_dx"]
    cross_abs = matched_metrics["cross_combined_matched"]["mean_abs_bin_mean_dx"]

    if (
        np.isfinite(same_abs)
        and np.isfinite(cross_abs)
        and float(same_abs) > 0
    ):
        retained = float(cross_abs) / float(same_abs)
        reduction = 100.0 * (1.0 - retained)
    else:
        retained = np.nan
        reduction = np.nan

    matched_effect = {
        "same_mean_abs_bin_mean_dx": same_abs,
        "cross_mean_abs_bin_mean_dx": cross_abs,
        "cross_retained_fraction_of_same": retained,
        "percent_reduction_after_decoupling": reduction,
        "same_slope": matched_metrics["same_combined"]["slope_mean_dx_vs_x"],
        "cross_slope": matched_metrics["cross_combined_matched"]["slope_mean_dx_vs_x"],
    }

    support = {
        "n_rows": int(len(d)),
        "n_forward_ab_eligible": int(ab_eligible.sum()),
        "n_forward_ba_eligible": int(ba_eligible.sum()),
        "n_common4": int(common4.sum()),
        "forward_ab_fraction": float(ab_eligible.mean()),
        "forward_ba_fraction": float(ba_eligible.mean()),
        "common4_fraction": float(common4.mean()),
    }

    return {
        "metrics": metrics,
        "curves": curves.to_dict(orient="records"),
        "AB_BA_concordance": fold_concordance(cross_ab, cross_ba),
        "matched_decoupling_effect": matched_effect,
        "support": support,
        "conditioning_metrics": conditioning_metrics,
    }


# -----------------------------------------------------------------------------
# Ensemble summaries
# -----------------------------------------------------------------------------

def summarize_metric_distribution(metrics: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for keys, g in metrics.groupby(
        ["section", "representation", "metric"],
        sort=True,
    ):
        x = finite_array(g["value"])
        if x.size == 0:
            continue

        rows.append(
            {
                "section": keys[0],
                "representation": keys[1],
                "metric": keys[2],
                "n_configurations": int(x.size),
                "mean": float(np.mean(x)),
                "median": float(np.median(x)),
                "sd": float(np.std(x, ddof=0)),
                "randomization_q025": float(np.quantile(x, 0.025)),
                "randomization_q975": float(np.quantile(x, 0.975)),
                "min": float(np.min(x)),
                "max": float(np.max(x)),
            }
        )

    return pd.DataFrame(rows)


def curve_randomization_envelope(curves: pd.DataFrame) -> pd.DataFrame:
    if curves.empty:
        return pd.DataFrame()

    rows: List[Dict[str, object]] = []

    for keys, g in curves.groupby(
        ["section", "representation", "bin"],
        sort=True,
    ):
        row: Dict[str, object] = {
            "section": keys[0],
            "representation": keys[1],
            "bin": int(keys[2]),
            "n_configurations": int(
                g["configuration_id"].nunique()
            ),
        }

        for col in [
            "x_lo",
            "x_hi",
            "x_center",
            "x_median",
            "n_rows",
            "n_rows_fold_A",
            "n_rows_fold_B",
            "mean_dx",
            "median_dx",
            "p_dx_gt0",
        ]:
            if col not in g.columns:
                continue
            x = finite_array(g[col])
            if x.size == 0:
                continue

            row[col + "_median"] = float(np.median(x))
            row[col + "_randomization_q025"] = float(
                np.quantile(x, 0.025)
            )
            row[col + "_randomization_q975"] = float(
                np.quantile(x, 0.975)
            )

        rows.append(row)

    return pd.DataFrame(rows)


def summarize_simple_table(
    frame: pd.DataFrame,
    id_col: str = "configuration_id",
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for col in frame.columns:
        if col == id_col:
            continue
        x = finite_array(frame[col])
        if x.size == 0:
            continue

        rows.append(
            {
                "metric": col,
                "n_configurations": int(x.size),
                "mean": float(np.mean(x)),
                "median": float(np.median(x)),
                "sd": float(np.std(x, ddof=0)),
                "randomization_q025": float(np.quantile(x, 0.025)),
                "randomization_q975": float(np.quantile(x, 0.975)),
                "min": float(np.min(x)),
                "max": float(np.max(x)),
            }
        )

    return pd.DataFrame(rows)


def randomization_pairwise_effects(
    metrics: pd.DataFrame,
) -> pd.DataFrame:
    """
    Paired configuration-level differences.

    This does NOT declare a universal winner. It reports how often one
    representation is numerically lower/higher than another for the same
    metric across the same randomized configurations.
    """
    rows: List[Dict[str, object]] = []

    for (section, metric), g in metrics.groupby(
        ["section", "metric"],
        sort=True,
    ):
        pivot = g.pivot_table(
            index="configuration_id",
            columns="representation",
            values="value",
            aggfunc="first",
        )

        reps = list(pivot.columns)
        for a, b in combinations(reps, 2):
            pair = pivot[[a, b]].dropna()
            if pair.empty:
                continue

            delta = (
                pair[a].to_numpy(float)
                - pair[b].to_numpy(float)
            )

            rows.append(
                {
                    "section": section,
                    "metric": metric,
                    "representation_a": a,
                    "representation_b": b,
                    "n_configurations": int(len(delta)),
                    "median_delta_a_minus_b": float(np.median(delta)),
                    "randomization_q025": float(np.quantile(delta, 0.025)),
                    "randomization_q975": float(np.quantile(delta, 0.975)),
                    "fraction_a_lt_b": float(np.mean(delta < 0)),
                    "fraction_a_gt_b": float(np.mean(delta > 0)),
                    "fraction_equal": float(np.mean(delta == 0)),
                }
            )

    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Resume-safe checkpointing
# -----------------------------------------------------------------------------

def load_checkpoint(
    path: Path,
    analysis_signature: str,
) -> Optional[Dict[str, object]]:
    if not path.is_file():
        return None
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

    if obj.get("status") != "complete":
        return None
    if obj.get("analysis_signature") != analysis_signature:
        return None
    return obj


# -----------------------------------------------------------------------------
# Output helpers
# -----------------------------------------------------------------------------

def write_pipeline_manifest(outdir: Path) -> None:
    rows = []

    for p in sorted(outdir.rglob("*")):
        if (
            p.is_file()
            and "configuration_checkpoints" not in p.parts
        ):
            rows.append(
                {
                    "relative_path": str(p.relative_to(outdir)),
                    "suffix": p.suffix.lower(),
                    "size_bytes": int(p.stat().st_size),
                }
            )

    pd.DataFrame(rows).to_csv(
        outdir / "00_pipeline_manifest.csv",
        index=False,
    )


def write_readme(outdir: Path) -> None:
    text = """# ClonoDynamics Step 7 — compact pseudo technical-null benchmark

Input: one `step7_cache/step7_dt1.parquet` per randomized pseudo configuration.

## Primary forward technical null

- AB = `x_observed_rep1_t0 -> dx_observed_rep2` on `forward_ab_eligible`
- BA = `x_observed_rep2_t0 -> dx_observed_rep1` on `forward_ba_eligible`
- AB and BA are analyzed separately.
- `cross_combined` is formed bin-by-bin as exactly `0.5*AB + 0.5*BA`.
- Row counts are never used as AB/BA weights.
- Global forward bin edges are themselves derived from equal-size AB/BA samples within every configuration.

## Matched same-vs-cross control

Restricted to `common4`:
- same_A vs cross_AB_matched
- same_B vs cross_BA_matched
- both same and cross combined curves use exact 0.5/0.5 fold weight.

## Secondary conditioning geometry

`x0_latent`, `xmid_latent`, and `xstar_latent` are compared against the same
`dx_latent` on their common finite support.

This block is **unrestricted with respect to operational observation class**
because the compact cache intentionally does not contain `obs_class_reference`.

## Inferential unit

There is one biological source subject. `configuration_id` is a randomization
index, not biological N. Randomization Q2.5–Q97.5 intervals are therefore
ensemble/randomization intervals and not biological confidence intervals.
"""
    (outdir / "README_outputs.md").write_text(
        text,
        encoding="utf-8",
    )


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "ClonoDynamics Step 7 compact-native pseudo technical-null "
            "benchmark with exact equal-weight AB/BA combination."
        ),
    )

    p.add_argument(
        "--ensemble-root",
        required=True,
        type=Path,
        help="ensemble_results_v3 directory containing Cxxxxxx/step7_cache/",
    )
    p.add_argument("--outdir", required=True, type=Path)

    p.add_argument("--expected-configs", type=int, default=2000)
    p.add_argument(
        "--max-configs",
        type=int,
        default=None,
        help="Testing only. Omit for the full selected ensemble.",
    )

    p.add_argument("--dt", type=int, default=1)

    p.add_argument("--forward-n-bins", type=int, default=20)
    p.add_argument(
        "--forward-binning",
        choices=["quantile", "equal_width"],
        default="quantile",
    )
    p.add_argument("--forward-q-low", type=float, default=0.005)
    p.add_argument("--forward-q-high", type=float, default=0.995)
    p.add_argument("--min-n-fold", type=int, default=50)
    p.add_argument("--min-valid-bins", type=int, default=6)
    p.add_argument(
        "--edge-sample-per-config",
        type=int,
        default=2000,
        help=(
            "Total target rows per configuration for forward-edge derivation; "
            "split exactly 50/50 between AB and BA."
        ),
    )

    p.add_argument("--matched-min-n-fold", type=int, default=50)
    p.add_argument("--matched-min-valid-bins", type=int, default=6)

    p.add_argument("--conditioning-n-bins", type=int, default=30)
    p.add_argument("--conditioning-q-low", type=float, default=0.01)
    p.add_argument("--conditioning-q-high", type=float, default=0.99)
    p.add_argument("--conditioning-min-n", type=int, default=50)
    p.add_argument("--conditioning-min-valid-bins", type=int, default=6)
    p.add_argument(
        "--conditioning-edge-sample-per-config",
        type=int,
        default=2000,
    )

    p.add_argument("--seed", type=int, default=123)

    p.add_argument(
        "--require-exact-14-column-schema",
        action="store_true",
        help=(
            "Fail if a compact file contains columns in addition to the "
            "14-column production contract."
        ),
    )

    p.add_argument(
        "--restart",
        action="store_true",
        help="Delete existing configuration checkpoints before running.",
    )
    p.add_argument("--continue-on-error", action="store_true")

    return p


def validate_args(args: argparse.Namespace) -> None:
    if args.expected_configs < 0:
        raise ValueError("--expected-configs must be >=0")
    if args.max_configs is not None and args.max_configs < 1:
        raise ValueError("--max-configs must be >=1")
    if args.dt < 1:
        raise ValueError("--dt must be >=1")

    if args.forward_n_bins < 3:
        raise ValueError("--forward-n-bins must be >=3")
    if args.conditioning_n_bins < 3:
        raise ValueError("--conditioning-n-bins must be >=3")

    if not (0 <= args.forward_q_low < args.forward_q_high <= 1):
        raise ValueError("Invalid forward quantile range")
    if not (
        0
        <= args.conditioning_q_low
        < args.conditioning_q_high
        <= 1
    ):
        raise ValueError("Invalid conditioning quantile range")

    if args.edge_sample_per_config < 2:
        raise ValueError("--edge-sample-per-config must be >=2")


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main() -> int:
    args = build_parser().parse_args()
    validate_args(args)

    ensemble_root = (
        args.ensemble_root.expanduser().resolve(strict=True)
    )
    outdir = args.outdir.expanduser().resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    checkpoint_dir = outdir / "configuration_checkpoints"

    if args.restart:
        shutil.rmtree(checkpoint_dir, ignore_errors=True)

    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    full_manifest = discover_configurations(
        ensemble_root,
        int(args.expected_configs),
    )

    if args.max_configs is None:
        manifest = full_manifest.copy()
    else:
        manifest = (
            full_manifest.iloc[: int(args.max_configs)]
            .copy()
            .reset_index(drop=True)
        )

    print("[INFO] compact configurations discovered :", len(full_manifest))
    print("[INFO] configurations selected          :", len(manifest))
    print("[INFO] biological source subjects       : 1")
    print("[INFO] configuration_id as biological N : NO")
    print("[INFO] compact schema columns used       : 14")
    print("[INFO] primary estimator                 : observed cross AB/BA")
    print("[INFO] AB/BA combination                 : exact 0.5 / 0.5 after binning")
    print("[INFO] row-count AB/BA weighting         : NEVER")

    # Validate a small leading subset before doing any edge work.
    for r in manifest.head(min(3, len(manifest))).itertuples(index=False):
        validate_compact(
            Path(r.compact),
            str(r.configuration_id),
            int(args.dt),
            bool(args.require_exact_14_column_schema),
        )

    # Global fixed bins.
    forward_edges, forward_edge_audit = (
        derive_forward_edges_equal_fold_weight(manifest, args)
    )
    conditioning_edges, conditioning_edge_audit = (
        derive_conditioning_edges(manifest, args)
    )

    forward_edges_path = (
        outdir / "01_primary_forward" / "forward_bin_edges.csv"
    )
    conditioning_edges_path = (
        outdir
        / "03_conditioning_geometry_unrestricted"
        / "conditioning_bin_edges.csv"
    )

    write_edges(forward_edges_path, forward_edges)
    write_edges(conditioning_edges_path, conditioning_edges)

    manifest.to_csv(
        outdir / "00_configuration_manifest.csv",
        index=False,
    )

    # Signature deliberately depends on the selected ensemble, inputs, params,
    # and exact numeric bin edges.
    signature_payload = {
        "script_version": SCRIPT_VERSION,
        "selected_configuration_ids":
            manifest["configuration_id"].astype(str).tolist(),
        "input_identities": [
            {
                "configuration_id": str(r.configuration_id),
                "compact": path_identity(Path(r.compact)),
            }
            for r in manifest.itertuples(index=False)
        ],
        "parameters": {
            "dt": int(args.dt),
            "forward_n_bins": int(args.forward_n_bins),
            "forward_binning": str(args.forward_binning),
            "forward_q_low": float(args.forward_q_low),
            "forward_q_high": float(args.forward_q_high),
            "min_n_fold": int(args.min_n_fold),
            "min_valid_bins": int(args.min_valid_bins),
            "edge_sample_per_config": int(args.edge_sample_per_config),
            "matched_min_n_fold": int(args.matched_min_n_fold),
            "matched_min_valid_bins": int(args.matched_min_valid_bins),
            "conditioning_n_bins": int(args.conditioning_n_bins),
            "conditioning_q_low": float(args.conditioning_q_low),
            "conditioning_q_high": float(args.conditioning_q_high),
            "conditioning_min_n": int(args.conditioning_min_n),
            "conditioning_min_valid_bins":
                int(args.conditioning_min_valid_bins),
            "conditioning_edge_sample_per_config":
                int(args.conditioning_edge_sample_per_config),
            "seed": int(args.seed),
        },
        "forward_edges": [float(x) for x in forward_edges],
        "conditioning_edges": [float(x) for x in conditioning_edges],
        "AB_BA_combination_policy": "exact_equal_fold_weight_after_binning",
        "AB_BA_row_count_weighting": False,
    }

    analysis_signature = stable_hash(signature_payload)

    (outdir / "00_run_signature.json").write_text(
        json.dumps(
            {
                "analysis_signature": analysis_signature,
                "signature_payload": signature_payload,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    print("[INFO] analysis signature:", analysis_signature[:16] + "...")

    statuses: List[Dict[str, object]] = []

    for i, row in manifest.reset_index(drop=True).iterrows():
        cid = str(row["configuration_id"])
        path = Path(row["compact"])
        checkpoint = checkpoint_dir / f"{cid}.json"

        previous = (
            None
            if args.restart
            else load_checkpoint(checkpoint, analysis_signature)
        )

        if previous is not None:
            print("[resume-safe]", cid)
            statuses.append(
                {
                    "configuration_id": cid,
                    "status": "complete",
                    "execution": "resumed",
                }
            )
            pd.DataFrame(statuses).to_csv(
                outdir / "00_run_status.csv",
                index=False,
            )
            continue

        if checkpoint.exists():
            print("[stale checkpoint -> recompute]", cid)
            checkpoint.unlink()

        print(f"[config {i+1}/{len(manifest)}] {cid}")

        try:
            audit = validate_compact(
                path,
                cid,
                int(args.dt),
                bool(args.require_exact_14_column_schema),
            )

            result = analyze_configuration(
                path,
                cid,
                args,
                forward_edges,
                conditioning_edges,
            )

            payload = {
                "configuration_id": cid,
                "analysis_signature": analysis_signature,
                "input_identity": path_identity(path),
                "input_audit": audit,
                "metrics": result["metrics"],
                "curves": result["curves"],
                "AB_BA_concordance": result["AB_BA_concordance"],
                "matched_decoupling_effect":
                    result["matched_decoupling_effect"],
                "support": result["support"],
                "conditioning_metrics": result["conditioning_metrics"],
                "status": "complete",
            }

            checkpoint.write_text(
                json.dumps(
                    json_safe(payload),
                    indent=2,
                    sort_keys=True,
                )
                + "\n",
                encoding="utf-8",
            )

            statuses.append(
                {
                    "configuration_id": cid,
                    "status": "complete",
                    "execution": "computed",
                }
            )

        except Exception as exc:
            statuses.append(
                {
                    "configuration_id": cid,
                    "status": "failed",
                    "execution": "computed",
                    "message": f"{type(exc).__name__}: {exc}",
                }
            )

            pd.DataFrame(statuses).to_csv(
                outdir / "00_run_status.csv",
                index=False,
            )

            if not args.continue_on_error:
                raise

            print("[ERROR]", cid, exc, file=sys.stderr)

        pd.DataFrame(statuses).to_csv(
            outdir / "00_run_status.csv",
            index=False,
        )

    # Reassemble only checkpoints matching the current exact signature.
    metric_rows: List[Dict[str, object]] = []
    curve_rows: List[Dict[str, object]] = []
    concordance_rows: List[Dict[str, object]] = []
    matched_rows: List[Dict[str, object]] = []
    support_rows: List[Dict[str, object]] = []

    n_complete = 0

    for row in manifest.itertuples(index=False):
        cid = str(row.configuration_id)
        obj = load_checkpoint(
            checkpoint_dir / f"{cid}.json",
            analysis_signature,
        )

        if obj is None:
            continue

        n_complete += 1

        for rec in obj.get("metrics", []):
            metric_rows.append(
                {"configuration_id": cid, **rec}
            )

        for rec in obj.get("curves", []):
            curve_rows.append(
                {"configuration_id": cid, **rec}
            )

        concordance_rows.append(
            {
                "configuration_id": cid,
                **obj.get("AB_BA_concordance", {}),
            }
        )

        matched_rows.append(
            {
                "configuration_id": cid,
                **obj.get("matched_decoupling_effect", {}),
            }
        )

        support_rows.append(
            {
                "configuration_id": cid,
                **obj.get("support", {}),
            }
        )

    if n_complete == 0:
        raise RuntimeError(
            "No completed configuration matches the current analysis signature"
        )

    metrics = pd.DataFrame(metric_rows)
    curves = pd.DataFrame(curve_rows)
    concordance = pd.DataFrame(concordance_rows)
    matched = pd.DataFrame(matched_rows)
    support = pd.DataFrame(support_rows)

    # Top-level outputs.
    metrics.to_csv(
        outdir / "01_configuration_metrics_long.csv",
        index=False,
    )

    ensemble_metrics = summarize_metric_distribution(metrics)
    ensemble_metrics.to_csv(
        outdir / "02_ensemble_metric_summary.csv",
        index=False,
    )

    # Curves can be moderately large, so retain Parquet plus ensemble CSV.
    curves.to_parquet(
        outdir / "03_configuration_curves_long.parquet",
        index=False,
        compression="zstd",
    )

    envelope = curve_randomization_envelope(curves)
    envelope.to_csv(
        outdir / "04_curve_randomization_envelope.csv",
        index=False,
    )

    concordance.to_csv(
        outdir / "05_AB_BA_concordance_by_configuration.csv",
        index=False,
    )
    summarize_simple_table(concordance).to_csv(
        outdir / "06_AB_BA_concordance_ensemble_summary.csv",
        index=False,
    )

    matched.to_csv(
        outdir / "07_matched_same_vs_cross_by_configuration.csv",
        index=False,
    )
    summarize_simple_table(matched).to_csv(
        outdir / "08_matched_same_vs_cross_ensemble_summary.csv",
        index=False,
    )

    support.to_csv(
        outdir / "09_support_by_configuration.csv",
        index=False,
    )
    summarize_simple_table(support).to_csv(
        outdir / "10_support_ensemble_summary.csv",
        index=False,
    )

    randomization_pairwise_effects(metrics).to_csv(
        outdir / "11_randomization_pairwise_effects.csv",
        index=False,
    )

    # Stage-specific manuscript-friendly outputs.
    primary_env = envelope[
        envelope["section"].astype(str).eq("primary_forward")
    ].copy()
    primary_env.to_csv(
        outdir
        / "01_primary_forward"
        / "ensemble_primary_forward_curves.csv",
        index=False,
    )

    matched_env = envelope[
        envelope["section"].astype(str).eq("matched_same_vs_cross")
    ].copy()
    matched_dir = outdir / "02_matched_same_vs_cross"
    matched_dir.mkdir(parents=True, exist_ok=True)
    matched_env.to_csv(
        matched_dir / "ensemble_matched_same_vs_cross_curves.csv",
        index=False,
    )

    conditioning_env = envelope[
        envelope["section"].astype(str).eq(
            "conditioning_geometry_unrestricted"
        )
    ].copy()
    conditioning_env.to_csv(
        outdir
        / "03_conditioning_geometry_unrestricted"
        / "ensemble_conditioning_curves.csv",
        index=False,
    )

    # Compact manuscript-oriented summary uses the randomization median, not a
    # pooled analysis across configurations.
    compat = ensemble_metrics[
        [
            "section",
            "representation",
            "metric",
            "median",
            "randomization_q025",
            "randomization_q975",
            "n_configurations",
        ]
    ].rename(columns={"median": "value"})
    compat.to_csv(
        outdir / "00_benchmark_summary.csv",
        index=False,
    )

    run_config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "analysis_signature": analysis_signature,
        "ensemble_root": str(ensemble_root),
        "outdir": str(outdir),
        "n_complete_configurations_discovered": int(len(full_manifest)),
        "n_configurations_selected": int(len(manifest)),
        "n_current_signature_checkpoints": int(n_complete),
        "source_biological_subjects": 1,
        "configuration_id_is_biological_subject": False,
        "subject_bootstrap_used": False,
        "nested_pseudo_time_permutation_used": False,
        "randomization_interval_is_biological_CI": False,
        "compact_input_contract": COMPACT_COLUMNS,
        "primary_forward": {
            "AB": {
                "conditioning": "x_observed_rep1_t0",
                "displacement": "dx_observed_rep2",
                "eligibility": "forward_ab_eligible",
            },
            "BA": {
                "conditioning": "x_observed_rep2_t0",
                "displacement": "dx_observed_rep1",
                "eligibility": "forward_ba_eligible",
            },
            "combined_policy": "0.5*AB + 0.5*BA after binning",
            "row_count_weighting": False,
            "global_edge_policy": forward_edge_audit,
        },
        "matched_same_vs_cross": {
            "support": "common4",
            "same_combined_policy": "0.5*same_A + 0.5*same_B",
            "cross_combined_policy":
                "0.5*cross_AB_matched + 0.5*cross_BA_matched",
            "row_count_weighting": False,
        },
        "conditioning_geometry": {
            "role": "secondary descriptive diagnostic",
            "operational_observation_class_restriction": None,
            "reason":
                "obs_class_reference is not retained in the 14-column compact cache",
            "candidates": LATENT_CANDIDATES,
            "displacement": "dx_latent",
            "global_edge_policy": conditioning_edge_audit,
        },
        "seed": int(args.seed),
    }

    (outdir / "00_run_config.json").write_text(
        json.dumps(
            json_safe(run_config),
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    write_readme(outdir)
    write_pipeline_manifest(outdir)

    print("\n[DONE] Step 7 compact pseudo technical-null benchmark")
    print("Selected configurations          :", len(manifest))
    print("Completed configurations         :", n_complete)
    print("Biological source subjects       : 1")
    print("configuration_id as biological N : NO")
    print("AB/BA equal fold weight          : YES (0.5 / 0.5)")
    print("AB/BA row-count weighting        : NO")
    print("Nested pseudo-time permutation   : NO")
    print("Subject bootstrap                : NO")
    print("Summary                          :", outdir / "02_ensemble_metric_summary.csv")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
