#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
plot_step06_transition_support.py
============================================

Plot-only companion to ClonoDynamics Step 6:

    6-transition_support_characterization.py

Purpose
-------
Visualize the descriptive structure and estimand support of the generic
longitudinal transition universe generated by Step 5 and characterized in
Step 6.

This plotter is deliberately estimand-aware but inference-free. It does not
reconstruct transitions, refit latent states, re-threshold observation status,
filter transitions, estimate drift or fluctuation dynamics, or perform
statistical tests. It reads only Step-6 summary tables.

The plotting contract follows the replicate-resolved ClonoDynamics framework:

    * latent quantities are model-based representations/conditioning variables;
    * observed technical replicates remain separate for primary dynamics;
    * AB/BA/common4 are support/eligibility definitions, not biological states;
    * TT/TF/FT/FF are operational observation classes at a reference alpha.

Required Step-6 inputs
----------------------
--analysis-dir must contain:

    02_subject_interval_coverage.csv
    04_coverage_summary_by_dt.csv
    06_reference_observation_class_composition_by_dt.csv
    08_estimand_support_by_dt.csv

Optional audit inputs, read when present:

    09_estimand_support_overall.csv
    14_dataset_overview.csv

Generated single-panel figures
------------------------------

    transition_support_A_longitudinal_coverage_by_dt
        Median number of transitions per available subject-specific interval,
        with interquartile range and the number of contributing
        subject-interval units shown for each temporal lag.

    transition_support_B_subject_interval_coverage_heatmap
        Subject x nominal interval-pair coverage for the primary longitudinal
        dataset. The plotter refuses to collapse extra-group configurations
        into biological subjects.

    transition_support_C_estimand_support_by_dt
        Fractions of transitions eligible for replicate-decoupled forward AB,
        reciprocal BA, and cross-replicate fluctuation analysis (common4).

    transition_support_D_reference_observation_classes_by_dt
        Relative TT/TF/FT/FF composition at the stored reference operational
        observation threshold.

No multipanel figure is assembled here. Editorial figure numbering and panel
assembly are intentionally kept outside the analysis plotter.

Input audits
------------
Before plotting, the script checks that:

    * lag-level transition counts agree between coverage and support tables;
    * support fractions are finite and lie in [0, 1];
    * observation-class fractions lie in [0, 1] and sum to 1 within each lag;
    * a single reference_alpha is represented;
    * observation classes are restricted to TT/TF/FT/FF;
    * the subject x interval table has one row per subject/t0/t1/dt unit;
    * the subject heatmap is not asked to merge extra-group configurations.

These are plotting-input consistency checks only; the full production gate is
implemented by Step 6 itself.

Example
-------
python3 code/plotting/plot_step06_transition_support.py \
    --analysis-dir results/6-transition_support_characterization/p_05 \
    --figures-dir results/6-transition_support_characterization/p_05/figures

PDF and high-resolution PNG outputs are generated by default. SVG can be added
with --svg. Use --no-pdf or --no-png to disable a default format.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


OBS_CLASSES: Tuple[str, ...] = ("TT", "TF", "FT", "FF")

PANEL_STEMS: Dict[str, str] = {
    "A": "transition_support_A_longitudinal_coverage_by_dt",
    "B": "transition_support_B_subject_interval_coverage_heatmap",
    "C": "transition_support_C_estimand_support_by_dt",
    "D": "transition_support_D_reference_observation_classes_by_dt",
}

FIGURE_SIZES_INCHES: Dict[str, Tuple[float, float]] = {
    PANEL_STEMS["A"]: (3.6, 2.2),
    PANEL_STEMS["B"]: (7.2, 3.2),
    PANEL_STEMS["C"]: (3.6, 2.4),
    PANEL_STEMS["D"]: (3.6, 2.4),
}

# Centralized axis customization. Leave values as None for data-driven limits.
AXIS_CONFIG: Dict[str, Dict[str, object]] = {
    PANEL_STEMS["A"]: {
        "xlim": None,
        "ylim": None,
        "xticks": None,
        "yticks": None,
        "right_ylim": None,
        "right_yticks": None,
    },
    PANEL_STEMS["B"]: {
        "xlim": None,
        "ylim": None,
        "xticks": None,
        "yticks": None,
    },
    PANEL_STEMS["C"]: {
        "xlim": None,
        "ylim": (0.0, 1.0),
        "xticks": None,
        "yticks": None,
    },
    PANEL_STEMS["D"]: {
        "xlim": None,
        "ylim": (0.0, 1.0),
        "xticks": None,
        "yticks": None,
    },
}


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required Step-6 table not found: {path}")
    return pd.read_csv(path)


def read_optional(path: Path) -> Optional[pd.DataFrame]:
    if not path.exists():
        return None
    return pd.read_csv(path)


def require_columns(df: pd.DataFrame, required: Iterable[str], source: str) -> None:
    missing = sorted(set(required).difference(df.columns))
    if missing:
        raise ValueError(f"{source} is missing required columns: {', '.join(missing)}")


def numeric(df: pd.DataFrame, columns: Iterable[str]) -> pd.DataFrame:
    out = df.copy()
    for column in columns:
        out[column] = pd.to_numeric(out[column], errors="coerce")
    return out


def assert_fraction(values: pd.Series, label: str) -> None:
    arr = pd.to_numeric(values, errors="coerce").to_numpy(float)
    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{label} contains non-finite values")
    if np.any((arr < -1e-12) | (arr > 1.0 + 1e-12)):
        raise ValueError(f"{label} contains values outside [0, 1]")


def apply_rcparams(args: argparse.Namespace) -> None:
    plt.rcParams.update(
        {
            "font.family": args.font_family,
            "font.size": args.font_size,
            "axes.labelsize": args.font_size,
            "xtick.labelsize": args.font_size,
            "ytick.labelsize": args.font_size,
            "legend.fontsize": args.legend_fontsize,
            "axes.linewidth": args.axes_w,
            "xtick.major.width": args.tick_w,
            "ytick.major.width": args.tick_w,
            "xtick.major.size": args.tick_len,
            "ytick.major.size": args.tick_len,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": False,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "savefig.dpi": args.dpi,
        }
    )


def clean_axes(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def apply_axis_config(ax: plt.Axes, stem: str, right_ax: Optional[plt.Axes] = None) -> None:
    cfg = AXIS_CONFIG.get(stem, {})
    if cfg.get("xlim") is not None:
        ax.set_xlim(*cfg["xlim"])
    if cfg.get("ylim") is not None:
        ax.set_ylim(*cfg["ylim"])
    if cfg.get("xticks") is not None:
        ax.set_xticks(cfg["xticks"])
    if cfg.get("yticks") is not None:
        ax.set_yticks(cfg["yticks"])
    if right_ax is not None:
        if cfg.get("right_ylim") is not None:
            right_ax.set_ylim(*cfg["right_ylim"])
        if cfg.get("right_yticks") is not None:
            right_ax.set_yticks(cfg["right_yticks"])


def output_suffixes(args: argparse.Namespace) -> List[str]:
    suffixes: List[str] = []
    if args.pdf:
        suffixes.append(".pdf")
    if args.png:
        suffixes.append(".png")
    if args.svg:
        suffixes.append(".svg")
    return suffixes


def clear_generated_outputs(fig_dir: Path, args: argparse.Namespace) -> None:
    for stem in PANEL_STEMS.values():
        for suffix in (".pdf", ".png", ".svg"):
            path = fig_dir / f"{stem}{suffix}"
            if path.exists():
                path.unlink()
    for name in ("figure_manifest.csv", "plotter_input_audit.csv"):
        path = fig_dir / name
        if path.exists():
            path.unlink()


def save_figure(fig: plt.Figure, base: Path, args: argparse.Namespace) -> None:
    kwargs = {"bbox_inches": "tight", "pad_inches": args.pad_inches}
    if args.pdf:
        path = base.with_suffix(".pdf")
        fig.savefig(path, **kwargs)
        print(f"[SAVED] {path}")
    if args.png:
        path = base.with_suffix(".png")
        fig.savefig(path, dpi=args.dpi, **kwargs)
        print(f"[SAVED] {path}")
    if args.svg:
        path = base.with_suffix(".svg")
        fig.savefig(path, **kwargs)
        print(f"[SAVED] {path}")


# -----------------------------------------------------------------------------
# Step-6 input preparation and audits
# -----------------------------------------------------------------------------


def prepare_dt_coverage(df: pd.DataFrame) -> pd.DataFrame:
    source = "04_coverage_summary_by_dt.csv"
    required = {
        "dt",
        "n_transitions",
        "n_biological_subjects",
        "n_group_subject_units",
        "n_group_subject_interval_pairs",
        "median_transitions_per_group_subject_interval",
        "q25_transitions_per_group_subject_interval",
        "q75_transitions_per_group_subject_interval",
    }
    require_columns(df, required, source)
    out = numeric(df, required)
    if out[list(required)].isna().any().any():
        raise ValueError(f"{source} contains non-numeric or missing required values")
    if out["dt"].duplicated().any():
        raise ValueError(f"{source} contains duplicate dt rows")
    if (out["n_transitions"] <= 0).any():
        raise ValueError(f"{source} contains non-positive transition counts")
    return out.sort_values("dt").reset_index(drop=True)


def prepare_subject_interval(df: pd.DataFrame) -> pd.DataFrame:
    source = "02_subject_interval_coverage.csv"
    required = {"subject", "t0", "t1", "dt", "n_transitions"}
    require_columns(df, required, source)
    out = numeric(df, ["t0", "t1", "dt", "n_transitions"])
    if out[list(required)].isna().any().any():
        raise ValueError(f"{source} contains missing required values")
    duplicate_key = out.duplicated(subset=["subject", "t0", "t1", "dt"], keep=False)
    if duplicate_key.any():
        raise ValueError(
            f"{source} contains duplicate subject/t0/t1/dt units. "
            "This plotter will not collapse extra-group configurations into biological subjects."
        )
    if (out["n_transitions"] <= 0).any():
        raise ValueError(f"{source} contains non-positive transition counts")
    return out.sort_values(["subject", "dt", "t0", "t1"]).reset_index(drop=True)


def prepare_estimand_support(df: pd.DataFrame) -> pd.DataFrame:
    source = "08_estimand_support_by_dt.csv"
    required = {
        "dt",
        "n_transitions",
        "fraction_forward_ab_eligible",
        "fraction_forward_ba_eligible",
        "fraction_common4",
    }
    require_columns(df, required, source)
    out = numeric(df, required)
    if out[list(required)].isna().any().any():
        raise ValueError(f"{source} contains non-numeric or missing required values")
    if out["dt"].duplicated().any():
        raise ValueError(f"{source} contains duplicate dt rows")
    for col in (
        "fraction_forward_ab_eligible",
        "fraction_forward_ba_eligible",
        "fraction_common4",
    ):
        assert_fraction(out[col], f"{source}:{col}")
    return out.sort_values("dt").reset_index(drop=True)


def prepare_reference_classes(df: pd.DataFrame) -> Tuple[pd.DataFrame, float]:
    source = "06_reference_observation_class_composition_by_dt.csv"
    required = {
        "dt",
        "obs_class_reference",
        "n_transitions",
        "transition_fraction",
        "reference_alpha",
    }
    require_columns(df, required, source)
    out = numeric(df, ["dt", "n_transitions", "transition_fraction", "reference_alpha"])
    out["obs_class_reference"] = out["obs_class_reference"].astype(str).str.upper()
    if out[list(required)].isna().any().any():
        raise ValueError(f"{source} contains missing required values")
    invalid = sorted(set(out["obs_class_reference"]).difference(OBS_CLASSES))
    if invalid:
        raise ValueError(f"{source} contains invalid reference classes: {invalid}")
    if out.duplicated(subset=["dt", "obs_class_reference"]).any():
        raise ValueError(f"{source} contains duplicate dt/class rows")
    assert_fraction(out["transition_fraction"], f"{source}:transition_fraction")

    alphas = np.sort(out["reference_alpha"].unique())
    if len(alphas) != 1 or not np.isfinite(alphas[0]) or not (0.0 < alphas[0] < 1.0):
        raise ValueError(f"{source} must contain exactly one valid reference_alpha")
    alpha = float(alphas[0])

    sums = out.groupby("dt", sort=True)["transition_fraction"].sum()
    if not np.allclose(sums.to_numpy(float), 1.0, atol=1e-8, rtol=1e-8):
        bad = sums.loc[~np.isclose(sums, 1.0, atol=1e-8, rtol=1e-8)]
        raise ValueError(
            f"{source} class fractions do not sum to 1 for dt values: {bad.to_dict()}"
        )

    return out.sort_values(["dt", "obs_class_reference"]).reset_index(drop=True), alpha


def audit_cross_table_consistency(
    dt_coverage: pd.DataFrame,
    estimand_support: pd.DataFrame,
    class_by_dt: pd.DataFrame,
    subject_interval: pd.DataFrame,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    cov = dt_coverage.set_index("dt").sort_index()
    sup = estimand_support.set_index("dt").sort_index()
    same_lags = cov.index.equals(sup.index)
    rows.append(
        {
            "check": "coverage_vs_estimand_same_dt_set",
            "passed": bool(same_lags),
            "detail": f"coverage={list(cov.index)}; support={list(sup.index)}",
        }
    )
    if not same_lags:
        raise ValueError("Coverage and estimand-support tables contain different dt sets")

    same_counts = np.array_equal(
        cov["n_transitions"].to_numpy(np.int64),
        sup["n_transitions"].to_numpy(np.int64),
    )
    rows.append(
        {
            "check": "coverage_vs_estimand_transition_counts",
            "passed": bool(same_counts),
            "detail": "n_transitions agrees by dt" if same_counts else "n_transitions differs by dt",
        }
    )
    if not same_counts:
        raise ValueError("Coverage and estimand-support transition counts disagree")

    class_totals = (
        class_by_dt.groupby("dt", sort=True)["n_transitions"].sum().astype(np.int64)
    )
    class_matches = np.array_equal(
        class_totals.reindex(cov.index).to_numpy(np.int64),
        cov["n_transitions"].to_numpy(np.int64),
    )
    rows.append(
        {
            "check": "reference_classes_vs_coverage_transition_counts",
            "passed": bool(class_matches),
            "detail": "class counts sum to transition universe by dt" if class_matches else "class counts disagree",
        }
    )
    if not class_matches:
        raise ValueError("Reference observation-class counts do not match transition counts by dt")

    interval_totals = (
        subject_interval.groupby("dt", sort=True)["n_transitions"].sum().astype(np.int64)
    )
    interval_matches = np.array_equal(
        interval_totals.reindex(cov.index).to_numpy(np.int64),
        cov["n_transitions"].to_numpy(np.int64),
    )
    rows.append(
        {
            "check": "subject_interval_vs_coverage_transition_counts",
            "passed": bool(interval_matches),
            "detail": "subject-interval counts sum to transition universe by dt" if interval_matches else "subject-interval counts disagree",
        }
    )
    if not interval_matches:
        raise ValueError("Subject-interval transition counts do not match coverage counts by dt")

    no_extra_group_collapse = bool(
        np.allclose(
            dt_coverage["n_biological_subjects"].to_numpy(float),
            dt_coverage["n_group_subject_units"].to_numpy(float),
            equal_nan=False,
        )
    )
    rows.append(
        {
            "check": "heatmap_has_no_extra_group_subject_multiplicity",
            "passed": no_extra_group_collapse,
            "detail": (
                "group-subject units equal biological subjects"
                if no_extra_group_collapse
                else "extra grouping creates multiple group-subject units per biological subject"
            ),
        }
    )
    if not no_extra_group_collapse:
        raise ValueError(
            "The subject heatmap would collapse extra-group configurations into biological subjects. "
            "Use this plotter on the primary longitudinal Step-6 output without extra grouping, or create a configuration-aware plotter."
        )

    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Panels
# -----------------------------------------------------------------------------


def panel_A(
    ax: plt.Axes,
    dt_coverage: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    """Plot transition support per available subject-specific interval.

    Total transition counts necessarily decrease with temporal lag because
    fewer nominal interval pairs exist at larger dt. Panel A therefore
    summarizes support within each available subject-specific interval rather
    than plotting total transition-universe size.

    Points show the median across available subject-interval units; vertical
    error bars span the interquartile range. The number of contributing
    subject-interval units is annotated above each point.
    """
    stem = PANEL_STEMS["A"]
    d = dt_coverage

    x = d["dt"].to_numpy(float)
    median = d[
        "median_transitions_per_group_subject_interval"
    ].to_numpy(float)
    q25 = d[
        "q25_transitions_per_group_subject_interval"
    ].to_numpy(float)
    q75 = d[
        "q75_transitions_per_group_subject_interval"
    ].to_numpy(float)
    n_units = d["n_group_subject_interval_pairs"].to_numpy(int)

    lower = np.maximum(median - q25, 0.0)
    upper = np.maximum(q75 - median, 0.0)

    ax.errorbar(
        x,
        median,
        yerr=np.vstack([lower, upper]),
        marker="o",
        linestyle="none",
        markersize=args.marker_size,
        capsize=args.errorbar_capsize,
        elinewidth=args.errorbar_w,
)

    ax.set_xlabel(r"Temporal lag, $\Delta t$ (weeks)")
    ax.set_ylabel("Transitions per subject–interval")
    ax.set_xticks(x)
    ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
    clean_axes(ax)

    span = float(np.nanmax(q75) - np.nanmin(q25))
    offset = 0.045 * span if np.isfinite(span) and span > 0 else 1.0
    for xi, upper_q, n_unit in zip(x, q75, n_units):
        ax.text(
            xi,
            upper_q + offset,
            f"n={int(n_unit)}",
            ha="center",
            va="bottom",
            fontsize=args.annotation_fontsize,
        )

    cfg = AXIS_CONFIG.get(stem, {})
    if cfg.get("ylim") is None:
        ymax = float(np.nanmax(q75) + 4.0 * offset)
        ymin = max(0.0, float(np.nanmin(q25) - 1.5 * offset))
        if np.isfinite(ymin) and np.isfinite(ymax) and ymax > ymin:
            ax.set_ylim(ymin, ymax)

    apply_axis_config(ax, stem)

def interval_order(subject_interval: pd.DataFrame) -> List[Tuple[float, float, float]]:
    keys = (
        subject_interval[["t0", "t1", "dt"]]
        .drop_duplicates()
        .sort_values(["dt", "t0", "t1"])
    )
    return [tuple(map(float, row)) for row in keys.to_numpy()]


def panel_B(
    ax: plt.Axes,
    subject_interval: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    stem = PANEL_STEMS["B"]
    d = subject_interval
    keys = interval_order(d)
    subjects = sorted(d["subject"].drop_duplicates().tolist())

    key_index = {key: idx for idx, key in enumerate(keys)}
    subject_index = {subject: idx for idx, subject in enumerate(subjects)}
    matrix = np.full((len(subjects), len(keys)), np.nan, dtype=float)

    for row in d.itertuples(index=False):
        key = (float(row.t0), float(row.t1), float(row.dt))
        matrix[subject_index[row.subject], key_index[key]] = float(row.n_transitions)

    display = np.log10(matrix + 1.0)
    image = ax.imshow(display, aspect="auto", interpolation="nearest")

    labels = [
        f"{int(t0) if float(t0).is_integer() else t0}→"
        f"{int(t1) if float(t1).is_integer() else t1}\n"
        f"Δt={int(dt) if float(dt).is_integer() else dt}"
        for t0, t1, dt in keys
    ]
    ax.set_xticks(np.arange(len(keys)))
    ax.set_xticklabels(labels, rotation=40, ha="right")
    ax.set_yticks(np.arange(len(subjects)))
    ax.set_yticklabels([str(subject) for subject in subjects])
    ax.set_xlabel("Nominal sampling-time pair")
    ax.set_ylabel("Subject")

    colorbar = ax.figure.colorbar(image, ax=ax, fraction=0.035, pad=0.03)
    colorbar.set_label(r"$\log_{10}$(transitions + 1)")

    apply_axis_config(ax, stem)


def panel_C(
    ax: plt.Axes,
    estimand_support: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    stem = PANEL_STEMS["C"]
    d = estimand_support
    x = d["dt"].to_numpy(float)

    series = [
        ("fraction_forward_ab_eligible", "Forward AB eligible"),
        ("fraction_forward_ba_eligible", "Forward BA eligible"),
        ("fraction_common4", "Four-measure support (common4)"),
    ]
    for column, label in series:
        ax.plot(
            x,
            d[column].to_numpy(float),
            marker="o",
            linewidth=args.line_w,
            markersize=args.marker_size,
            label=label,
        )

    ax.set_xlabel(r"Temporal lag, $\Delta t$ (weeks)")
    ax.set_ylabel("Fraction of transition universe")
    ax.set_xticks(x)
    clean_axes(ax)
    apply_axis_config(ax, stem)
    ax.legend(
        frameon=False,
        loc="upper left",
        bbox_to_anchor=(1.02, 1.0),
        borderaxespad=0.0,
    )


def panel_D(
    ax: plt.Axes,
    class_by_dt: pd.DataFrame,
    reference_alpha: float,
    args: argparse.Namespace,
) -> None:
    stem = PANEL_STEMS["D"]
    dts = sorted(class_by_dt["dt"].drop_duplicates().tolist())
    pivot = (
        class_by_dt.pivot_table(
            index="dt",
            columns="obs_class_reference",
            values="transition_fraction",
            aggfunc="first",
        )
        .reindex(index=dts, columns=list(OBS_CLASSES))
        .fillna(0.0)
    )

    x = np.arange(len(pivot), dtype=float)
    bottom = np.zeros(len(pivot), dtype=float)
    for obs_class in OBS_CLASSES:
        values = pivot[obs_class].to_numpy(float)
        ax.bar(
            x,
            values,
            bottom=bottom,
            width=0.72,
            label=obs_class,
            linewidth=0,
        )
        bottom += values

    ax.set_xticks(x)
    ax.set_xticklabels(
        [str(int(dt)) if float(dt).is_integer() else str(dt) for dt in pivot.index]
    )
    ax.set_xlabel(r"Temporal lag, $\Delta t$ (weeks)")
    ax.set_ylabel("Fraction of transitions")
    clean_axes(ax)
    apply_axis_config(ax, stem)
    ax.legend(
        frameon=False,
        loc="upper left",
        bbox_to_anchor=(1.02, 1.0),
        borderaxespad=0.0,
        title=rf"Operational class ($\alpha={reference_alpha:g}$)",
    )


# -----------------------------------------------------------------------------
# Output metadata
# -----------------------------------------------------------------------------


def write_manifest(fig_dir: Path, reference_alpha: float) -> None:
    rows = [
        {
            "panel": "A",
            "stem": PANEL_STEMS["A"],
            "source_table": "04_coverage_summary_by_dt.csv",
            "purpose": "Median transition count per available subject-specific interval across temporal lags, with IQR.",
            "interpretation": "Support per available interval; n annotations report contributing subject-interval units. Not temporal dynamical scaling.",
        },
        {
            "panel": "B",
            "stem": PANEL_STEMS["B"],
            "source_table": "02_subject_interval_coverage.csv",
            "purpose": "Biological-subject by nominal-interval transition coverage.",
            "interpretation": "Coverage geometry only; no biological phenotype is inferred.",
        },
        {
            "panel": "C",
            "stem": PANEL_STEMS["C"],
            "source_table": "08_estimand_support_by_dt.csv",
            "purpose": "Support fractions for observed replicate-decoupled forward AB/BA and common4 fluctuations.",
            "interpretation": "Eligibility/support only; no drift or fluctuation magnitude is estimated.",
        },
        {
            "panel": "D",
            "stem": PANEL_STEMS["D"],
            "source_table": "06_reference_observation_class_composition_by_dt.csv",
            "purpose": f"TT/TF/FT/FF composition at reference alpha={reference_alpha:g}.",
            "interpretation": "Operational observation classes, not biological presence/absence states.",
        },
    ]
    pd.DataFrame(rows).to_csv(fig_dir / "figure_manifest.csv", index=False)


# -----------------------------------------------------------------------------
# CLI and main
# -----------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Plot ClonoDynamics Step-6 transition/support characterization outputs."
    )
    parser.add_argument("--analysis-dir", type=Path, required=True)
    parser.add_argument(
        "--figures-dir",
        type=Path,
        default=None,
        help="Output directory. Default: <analysis-dir>/figures",
    )

    parser.add_argument("--font-family", default="Arial")
    parser.add_argument("--font-size", type=float, default=7.0)
    parser.add_argument("--legend-fontsize", type=float, default=7.0)
    parser.add_argument("--dpi", type=int, default=600)

    parser.add_argument("--axes-w", type=float, default=0.7)
    parser.add_argument("--tick-w", type=float, default=0.7)
    parser.add_argument("--tick-len", type=float, default=2.5)
    parser.add_argument("--line-w", type=float, default=1.0)
    parser.add_argument("--marker-size", type=float, default=4.0)
    parser.add_argument(
        "--annotation-fontsize",
        type=float,
        default=7.0,
        help="Font size for Panel-A subject-interval n labels.",
    )
    parser.add_argument(
        "--errorbar-w",
        type=float,
        default=0.9,
        help="Line width of Panel-A IQR error bars.",
    )
    parser.add_argument(
        "--errorbar-capsize",
        type=float,
        default=3.0,
        help="Cap size of Panel-A IQR error bars.",
    )
    parser.add_argument("--pad-inches", type=float, default=0.05)

    parser.add_argument(
        "--pdf",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument(
        "--png",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument(
        "--svg",
        action=argparse.BooleanOptionalAction,
        default=False,
    )
    parser.add_argument(
        "--clear-existing",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Remove only outputs generated by this plotter before plotting.",
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    analysis_dir = args.analysis_dir.expanduser().resolve()
    if not analysis_dir.exists():
        raise FileNotFoundError(f"Analysis directory not found: {analysis_dir}")
    figures_dir = ensure_dir(
        (args.figures_dir if args.figures_dir is not None else analysis_dir / "figures")
        .expanduser()
        .resolve()
    )

    apply_rcparams(args)
    if args.clear_existing:
        clear_generated_outputs(figures_dir, args)

    subject_interval = prepare_subject_interval(
        read_required(analysis_dir / "02_subject_interval_coverage.csv")
    )
    dt_coverage = prepare_dt_coverage(
        read_required(analysis_dir / "04_coverage_summary_by_dt.csv")
    )
    class_by_dt, reference_alpha = prepare_reference_classes(
        read_required(
            analysis_dir / "06_reference_observation_class_composition_by_dt.csv"
        )
    )
    estimand_support = prepare_estimand_support(
        read_required(analysis_dir / "08_estimand_support_by_dt.csv")
    )

    # Optional tables are intentionally not used to create new estimates.
    support_overall = read_optional(analysis_dir / "09_estimand_support_overall.csv")
    dataset_overview = read_optional(analysis_dir / "14_dataset_overview.csv")

    audit = audit_cross_table_consistency(
        dt_coverage=dt_coverage,
        estimand_support=estimand_support,
        class_by_dt=class_by_dt,
        subject_interval=subject_interval,
    )
    audit["reference_alpha"] = reference_alpha
    audit["optional_support_overall_present"] = support_overall is not None
    audit["optional_dataset_overview_present"] = dataset_overview is not None
    audit.to_csv(figures_dir / "plotter_input_audit.csv", index=False)

    # A
    stem = PANEL_STEMS["A"]
    fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
    panel_A(ax, dt_coverage, args)
    fig.subplots_adjust(left=0.16, right=0.97, bottom=0.20, top=0.95)
    save_figure(fig, figures_dir / stem, args)
    plt.close(fig)

    # B
    stem = PANEL_STEMS["B"]
    fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
    panel_B(ax, subject_interval, args)
    fig.subplots_adjust(left=0.10, right=0.92, bottom=0.28, top=0.97)
    save_figure(fig, figures_dir / stem, args)
    plt.close(fig)

    # C
    stem = PANEL_STEMS["C"]
    fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
    panel_C(ax, estimand_support, args)
    fig.subplots_adjust(right=0.70, bottom=0.20)
    save_figure(fig, figures_dir / stem, args)
    plt.close(fig)

    # D
    stem = PANEL_STEMS["D"]
    fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
    panel_D(ax, class_by_dt, reference_alpha, args)
    fig.subplots_adjust(right=0.68, bottom=0.20)
    save_figure(fig, figures_dir / stem, args)
    plt.close(fig)

    write_manifest(figures_dir, reference_alpha)

    print("[Step 6 plotter] Completed successfully.")
    print(f"[DATA] {analysis_dir}")
    print(f"[FIGS] {figures_dir}")
    print(f"[REFERENCE ALPHA] {reference_alpha:g}")
    print("[AUDIT] all required plotting-input consistency checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
