#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
1-plot_repertoire_characterization_vs2.py
=========================================

Plot-only companion to ClonoDynamics Step 1:

    1-repertoire_characterization.py

Role in the pipeline
--------------------
This script visualizes the descriptive repertoire-characterization outputs
generated by Step 1. It does not perform QC, does not classify samples as
PASS/FAIL, and does not alter any repertoire or downstream ClonoDynamics input.

Analysis inputs
---------------
Required analysis directory (--analysis-dir):

    repertoire_characteristics.csv
        Main Step-1 repertoire-level table.

    repertoire_tail_model_scan.csv
        Step-1 threshold-dependent power-law versus lower-truncated-lognormal
        model-comparison table.

Optional raw repertoire directory (--repertoires-dir):

    Original clonotype repertoire tables used by Step 1.

This optional input is used only for the empirical pooled CCDF panel. A raw
table must provide either:

    readFraction

or:

    readCount

Technical-replicate filenames follow the same default convention as Step 1:

    subject_time-replicate.ext

Generated figures
-----------------
Single-panel outputs:

    figA_ccdf_pooled
    figB_model_compare_density   # stacked threshold summary; name kept for compatibility
    figC_threshold_stability
    figD_gamma_replicate_concordance

Combined output:

    fig1_repertoire_characterization_multipanel

PDF export is enabled by default. PNG and SVG can be enabled from the CLI.

Figure customization
--------------------
Two dictionaries near the top of this file provide the primary manual
publication-layout controls:

    FIGURE_SIZES_INCHES
        Per-figure (width, height) in inches.

    AXIS_CONFIG
        Per-panel axis configuration. Supported keys are:
            xlim
            ylim
            xscale
            yscale
            xticks
            yticks

Editing these dictionaries changes individual panels without changing the
analysis or data-selection logic.

The historical --fig_w/--fig_h and --multi_fig_w/--multi_fig_h options are
retained as optional global overrides for compatibility.

Example
-------
python3 ./code/plotting/1-plot_repertoire_characterization_vs2.py \
    --analysis-dir \
    ./dataset_longitudinal_clonodynamics_results/longitudinal/1-repertoire_characterization \
    --figures-dir ./figures/1-repertoire-characterization \
    --repertoires-dir ./dataset_longitudinal \
    --png
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Callable, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


PATTERN_DEFAULT = (
    r"^(?P<subject>\d+)_(?P<time>\d+)-(?P<replica>[12])"
    r"(?:\.(?:csv|tsv|txt|parquet|pq|feather|arrow))?$"
)


# =============================================================================
# Figure geometry and axes
# =============================================================================

# Individual figure dimensions in inches. Edit one entry to resize only that
# output. The multipanel size is controlled independently.
FIGURE_SIZES_INCHES = {
    "figA_ccdf_pooled": (3.2, 2.4),
    "figB_model_compare_density": (4.0, 2.4),
    "figC_threshold_stability": (4.6, 2.6),
    "figD_gamma_replicate_concordance": (3.2, 2.4),
    "fig1_repertoire_characterization_multipanel": (6.0, 3.5),
}


# Per-panel axis customization. Keep values as None to retain data-driven
# limits/scales established by the plotting function.
AXIS_CONFIG = {
    "figA_ccdf_pooled": {
        "xlim": None,
        "ylim": None,
        "xscale": None,
        "yscale": None,
        "xticks": None,
        "yticks": None,
    },
    "figB_model_compare_density": {
        "xlim": None,
        "ylim": None,
        "xscale": None,
        "yscale": None,
        "xticks": None,
        "yticks": None,
    },
    "figC_threshold_stability": {
        "xlim": None,
        "ylim": None,
        "xscale": None,
        "yscale": None,
        "xticks": None,
        "yticks": None,
    },
    "figD_gamma_replicate_concordance": {
        "xlim": None,
        "ylim": None,
        "xscale": None,
        "yscale": None,
        "xticks": None,
        "yticks": None,
    },
}


# =============================================================================
# IO helpers
# =============================================================================


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_csv_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")
    return pd.read_csv(path)


def parse_lim(value: str) -> Optional[Tuple[float, float]]:
    value = (value or "").strip()
    if not value:
        return None

    parts = [x.strip() for x in value.split(",")]
    if len(parts) != 2:
        raise ValueError(
            f"Axis limit must contain exactly two comma-separated values: {value}"
        )

    return float(parts[0]), float(parts[1])


def maybe_apply_limits(
    ax: plt.Axes,
    xlim: Optional[Tuple[float, float]],
    ylim: Optional[Tuple[float, float]],
) -> None:
    if xlim is not None:
        ax.set_xlim(*xlim)
    if ylim is not None:
        ax.set_ylim(*ylim)



def apply_axis_config(
    ax: plt.Axes,
    stem: str,
) -> None:
    """Apply the optional manual axis settings defined in AXIS_CONFIG."""
    cfg = AXIS_CONFIG.get(stem, {})

    if cfg.get("xscale"):
        ax.set_xscale(str(cfg["xscale"]))
    if cfg.get("yscale"):
        ax.set_yscale(str(cfg["yscale"]))
    if cfg.get("xlim") is not None:
        ax.set_xlim(*cfg["xlim"])
    if cfg.get("ylim") is not None:
        ax.set_ylim(*cfg["ylim"])
    if cfg.get("xticks") is not None:
        ax.set_xticks(cfg["xticks"])
    if cfg.get("yticks") is not None:
        ax.set_yticks(cfg["yticks"])


def resolve_figure_size(
    stem: str,
    args: argparse.Namespace,
    *,
    multipanel: bool = False,
) -> Tuple[float, float]:
    """Return dictionary size unless an explicit CLI override was supplied."""
    if multipanel:
        if args.multi_fig_w is not None and args.multi_fig_h is not None:
            return float(args.multi_fig_w), float(args.multi_fig_h)
    else:
        if args.fig_w is not None and args.fig_h is not None:
            return float(args.fig_w), float(args.fig_h)

    return tuple(FIGURE_SIZES_INCHES[stem])


# =============================================================================
# Style helpers
# =============================================================================


def apply_rcparams(args: argparse.Namespace) -> None:
    plt.rcParams.update(
        {
            "font.family": args.font_family,
            "font.size": args.font_size,
            "axes.labelsize": args.font_size,
            "axes.titlesize": args.font_size,
            "xtick.labelsize": args.font_size,
            "ytick.labelsize": args.font_size,
            "legend.fontsize": args.legend_fontsize,
            "axes.labelpad": args.label_pad,
            "xtick.major.pad": args.tick_pad,
            "ytick.major.pad": args.tick_pad,
            "axes.linewidth": args.axes_w,
            "xtick.major.width": args.tick_w,
            "ytick.major.width": args.tick_w,
            "xtick.major.size": args.tick_len,
            "ytick.major.size": args.tick_len,
            "figure.dpi": 150,
            "savefig.dpi": args.dpi,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": False,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def apply_legend(ax: plt.Axes, args: argparse.Namespace) -> None:
    handles, _ = ax.get_legend_handles_labels()
    if not handles or args.legend_mode == "none":
        return


    # Figure 2B deliberately keeps all explanatory material outside the axes.
    # This prevents overlap with the stacked bars in both single-panel and
    # multipanel exports, even if an upstream caller requests inside legends.
    force_outside = bool(getattr(ax, "_force_legend_outside", False))
    legend_mode = "outside" if force_outside else args.legend_mode

    common_kwargs = dict(
        frameon=False if force_outside else bool(args.legend_frame),
        fontsize=args.legend_fontsize,
        handlelength=1.0,
        borderpad=0.15,
        labelspacing=0.25,
        handletextpad=0.35,
    )

    if legend_mode == "outside":
        loc = args.legend_loc
        if loc == "best":
            loc = "upper left"
        ax.legend(
            loc=loc,
            bbox_to_anchor=(args.legend_bbox_x, args.legend_bbox_y),
            borderaxespad=0.0,
            **common_kwargs,
        )
    else:
        ax.legend(loc=args.legend_loc, **common_kwargs)


def apply_layout(fig: plt.Figure) -> None:
    fig.tight_layout()


def save_fig(
    fig: plt.Figure,
    path_base: Path,
    args: argparse.Namespace,
) -> None:
    path_base.parent.mkdir(parents=True, exist_ok=True)

    save_kwargs = dict(
        bbox_inches="tight",
        pad_inches=float(args.legend_pad_inches),
    )

    if args.pdf:
        pdf_path = path_base.with_suffix(".pdf")
        fig.savefig(pdf_path, **save_kwargs)
        print(f"[SAVED FIGURE] {pdf_path}")

    if args.png:
        png_path = path_base.with_suffix(".png")
        fig.savefig(png_path, dpi=int(args.dpi), **save_kwargs)
        print(f"[SAVED FIGURE] {png_path}")

    if args.svg:
        svg_path = path_base.with_suffix(".svg")
        fig.savefig(svg_path, **save_kwargs)
        print(f"[SAVED FIGURE] {svg_path}")


def label_panel(
    ax: plt.Axes,
    label: str,
    args: argparse.Namespace,
) -> None:
    ax.text(
        args.panel_label_x,
        args.panel_label_y,
        label,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=args.panel_label_fontsize,
        fontweight="bold",
    )


# =============================================================================
# Colors
# =============================================================================


COLOR_POOLED = "black"
COLOR_SINGLE = "0.80"
COLOR_DELTA_LL = "C0"
COLOR_THRESHOLD = "C1"
COLOR_GAMMA = "C2"
COLOR_REF = "black"


# =============================================================================
# Raw repertoire reading for panel A
# =============================================================================


def read_repertoire_table(path: Path, file_sep: str) -> pd.DataFrame:
    suffix = path.suffix.lower()

    if suffix in {".parquet", ".pq"}:
        return pd.read_parquet(path)

    if suffix in {".feather", ".arrow"}:
        return pd.read_feather(path)

    try:
        df = pd.read_csv(path, sep=file_sep)
        if df.shape[1] > 1:
            return df
    except Exception:
        pass

    last_err = None
    for sep in ["\t", ",", ";", "|"]:
        try:
            df = pd.read_csv(path, sep=sep)
            if df.shape[1] > 1:
                return df
        except Exception as exc:
            last_err = exc

    try:
        df = pd.read_csv(path, sep=None, engine="python")
        if df.shape[1] > 1:
            return df
    except Exception as exc:
        last_err = exc

    raise ValueError(f"Could not parse repertoire file: {path}") from last_err


def frequencies_from_repertoire(
    df: pd.DataFrame,
    source_name: str = "",
) -> np.ndarray:
    cols_lower = {str(c).strip().lower(): c for c in df.columns}

    if "readfraction" in cols_lower:
        freqs = pd.to_numeric(
            df[cols_lower["readfraction"]],
            errors="coerce",
        ).to_numpy(float)
        freqs = freqs[np.isfinite(freqs) & (freqs > 0)]
        if freqs.size > 0:
            return freqs

    if "readcount" in cols_lower:
        counts = pd.to_numeric(
            df[cols_lower["readcount"]],
            errors="coerce",
        ).to_numpy(float)
        counts = counts[np.isfinite(counts) & (counts > 0)]
        if counts.size > 0:
            return counts / counts.sum()

    raise ValueError(
        f"{source_name}: missing readFraction/readCount columns. "
        f"Found: {list(df.columns)}"
    )


def read_freqs(path: Path, file_sep: str) -> np.ndarray:
    df = read_repertoire_table(path, file_sep=file_sep)
    return frequencies_from_repertoire(df, source_name=path.name)


def list_valid_repertoire_files(
    repertoires_dir: Path,
    pattern_str: str,
    file_sep: str,
) -> List[Path]:
    pattern = re.compile(pattern_str)
    files: List[Path] = []

    for path in sorted(repertoires_dir.iterdir()):
        if not path.is_file() or path.name.startswith("."):
            continue
        if not pattern.match(path.name):
            continue

        try:
            read_freqs(path, file_sep=file_sep)
            files.append(path)
        except Exception as exc:
            print(f"[WARN] Skipping {path.name}: {exc}")

    return files


def empirical_ccdf(x: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    x = np.sort(np.asarray(x, dtype=float))
    x = x[np.isfinite(x) & (x > 0)]
    n = len(x)

    if n == 0:
        return np.array([]), np.array([])

    ccdf = (n - np.arange(n)) / n
    return x, ccdf


# =============================================================================
# Analysis-table helpers
# =============================================================================


def coerce_bool_series(series: pd.Series) -> pd.Series:
    """Robust boolean parser for mixed-type CSV columns."""
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .isin(["true", "1", "yes", "y", "ok", "pass", "passed"])
    )


def clean_repertoire_characteristics(
    characteristics: pd.DataFrame,
) -> pd.DataFrame:
    required = {
        "subject",
        "time",
        "replica",
        "pl_fit_success",
        "pl_gamma_hat",
    }
    missing = required.difference(characteristics.columns)

    if missing:
        raise ValueError(
            "repertoire_characteristics.csv is missing columns: "
            + ", ".join(sorted(missing))
        )

    df = characteristics.copy()

    for col in [
        "subject",
        "time",
        "replica",
        "pl_gamma_hat",
    ]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # This is not a QC filter. A failed fit simply has no valid gamma estimate
    # and therefore cannot contribute to gamma-based plots.
    df["pl_fit_success"] = coerce_bool_series(df["pl_fit_success"])

    return df


def build_gamma_pairs(characteristics: pd.DataFrame) -> pd.DataFrame:
    """
    Reconstruct complete replicate pairs directly from repertoire-level fits.

    Only pairs with a successful finite gamma estimate in both replicas are
    included. No concordance threshold or QC decision is applied.
    """
    df = clean_repertoire_characteristics(characteristics)

    df = df[
        df["pl_fit_success"]
        & np.isfinite(df["subject"])
        & np.isfinite(df["time"])
        & df["replica"].isin([1, 2])
        & np.isfinite(df["pl_gamma_hat"])
    ].copy()

    if df.empty:
        return pd.DataFrame(
            columns=[
                "subject",
                "time",
                "gamma_rep1",
                "gamma_rep2",
                "delta_gamma",
            ]
        )

    # Detect duplicate repertoire rows before pivoting; silently choosing one
    # would make the replicate-concordance panel ambiguous.
    duplicate_mask = df.duplicated(
        subset=["subject", "time", "replica"],
        keep=False,
    )
    if duplicate_mask.any():
        dup = df.loc[
            duplicate_mask,
            ["subject", "time", "replica"],
        ].drop_duplicates()
        raise ValueError(
            "repertoire_characteristics.csv contains duplicate rows for "
            "subject/time/replica combinations; cannot construct unique "
            "gamma pairs. Examples:\n"
            + dup.head(10).to_string(index=False)
        )

    wide = df.pivot(
        index=["subject", "time"],
        columns="replica",
        values="pl_gamma_hat",
    )

    if 1 not in wide.columns or 2 not in wide.columns:
        return pd.DataFrame(
            columns=[
                "subject",
                "time",
                "gamma_rep1",
                "gamma_rep2",
                "delta_gamma",
            ]
        )

    wide = wide.dropna(subset=[1, 2]).reset_index()
    wide = wide.rename(columns={1: "gamma_rep1", 2: "gamma_rep2"})
    wide["delta_gamma"] = (
        wide["gamma_rep1"] - wide["gamma_rep2"]
    ).abs()

    return wide[
        [
            "subject",
            "time",
            "gamma_rep1",
            "gamma_rep2",
            "delta_gamma",
        ]
    ]


# =============================================================================
# Panel functions
# =============================================================================


def panel_A_ccdf(
    ax: plt.Axes,
    files: List[Path],
    args: argparse.Namespace,
) -> None:
    pooled_list: List[np.ndarray] = []

    for path in files:
        x = read_freqs(path, file_sep=args.file_sep)
        pooled_list.append(x)
        xx, yy = empirical_ccdf(x)

        if xx.size > 0:
            ax.plot(
                xx,
                yy,
                color=COLOR_SINGLE,
                alpha=args.single_alpha,
                linewidth=args.single_lw,
            )

    if pooled_list:
        pooled = np.concatenate(pooled_list)
        xx, yy = empirical_ccdf(pooled)
        ax.plot(
            xx,
            yy,
            color=COLOR_POOLED,
            linewidth=args.pooled_lw,
            label="Pooled",
        )
    else:
        ax.text(
            0.5,
            0.5,
            "No raw repertoire files",
            ha="center",
            va="center",
            transform=ax.transAxes,
        )

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Clone frequency")
    ax.set_ylabel("CCDF")


def _prepare_tail_model_categories(
    scan_df: pd.DataFrame,
) -> Tuple[pd.DataFrame, pd.DataFrame, List[str]]:
    """Validate the corrected Step-1 scan and summarize AICc categories."""
    needed = {
        "threshold_quantile",
        "tln_fit_success",
        "tln_at_powerlaw_boundary",
        "pl_preferred_aicc",
        "pl_preferred_bic",
    }
    missing = needed.difference(scan_df.columns)

    if missing:
        raise ValueError(
            "repertoire_tail_model_scan.csv is missing columns required "
            "for the corrected PL-vs-TLN panel: "
            + ", ".join(sorted(missing))
        )

    df = scan_df.copy()
    df["threshold_quantile"] = pd.to_numeric(
        df["threshold_quantile"],
        errors="coerce",
    )

    for col in [
        "tln_fit_success",
        "tln_at_powerlaw_boundary",
        "pl_preferred_aicc",
        "pl_preferred_bic",
    ]:
        df[col] = coerce_bool_series(df[col])

    df = df[
        np.isfinite(df["threshold_quantile"])
        & df["tln_fit_success"]
    ].copy()

    category_boundary = "TLN optimum at PL boundary"
    category_pl = "Interior TLN; PL retained by AICc"
    category_tln = "Interior TLN favored by AICc"
    category_order = [category_boundary, category_pl, category_tln]

    if df.empty:
        return df, pd.DataFrame(columns=category_order), category_order

    df["model_category"] = np.where(
        df["tln_at_powerlaw_boundary"],
        category_boundary,
        np.where(
            df["pl_preferred_aicc"],
            category_pl,
            category_tln,
        ),
    )

    summary = (
        df.groupby(["threshold_quantile", "model_category"])
        .size()
        .unstack(fill_value=0)
        .reindex(columns=category_order, fill_value=0)
        .sort_index()
    )

    return df, summary, category_order


def panel_B_model_compare(
    ax: plt.Axes,
    scan_df: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    """Plot the corrected Figure 2B AICc-based model comparison.

    Each bar partitions one threshold-specific set of repertoire evaluations
    into three mutually exclusive categories:

      1. the jointly fitted TLN reaches its optimum at the PL boundary;
      2. the TLN has an interior optimum, but AICc retains the PL;
      3. the TLN has an interior optimum and is favored by AICc.

    No explanatory summary box is drawn inside the plotting area. Overall
    counts are printed to the console and belong in the figure legend/caption.
    """
    needed = {
        "threshold_quantile",
        "tln_fit_success",
        "tln_at_powerlaw_boundary",
        "pl_preferred_aicc",
        "pl_preferred_bic",
    }
    missing = needed.difference(scan_df.columns)

    if missing:
        raise ValueError(
            "repertoire_tail_model_scan.csv is missing columns: "
            + ", ".join(sorted(missing))
        )

    df = scan_df.copy()
    df["threshold_quantile"] = pd.to_numeric(
        df["threshold_quantile"],
        errors="coerce",
    )
    for col in [
        "tln_fit_success",
        "tln_at_powerlaw_boundary",
        "pl_preferred_aicc",
        "pl_preferred_bic",
    ]:
        df[col] = coerce_bool_series(df[col])

    df = df[
        np.isfinite(df["threshold_quantile"])
        & df["tln_fit_success"]
    ].copy()

    if df.empty:
        ax.text(
            0.5,
            0.5,
            "No successful TLN comparison rows",
            ha="center",
            va="center",
            transform=ax.transAxes,
        )
        ax.set_axis_off()
        return

    category_boundary = "PL boundary"
    category_pl = "Interior TLN; PL by AICc"
    category_tln = "Interior TLN; TLN by AICc"
    category_order = [category_boundary, category_pl, category_tln]

    df["panel_b_category"] = np.where(
        df["tln_at_powerlaw_boundary"],
        category_boundary,
        np.where(df["pl_preferred_aicc"], category_pl, category_tln),
    )

    color_map = {
        category_boundary: "0.78",
        category_pl: "0.48",
        category_tln: COLOR_THRESHOLD,
    }

    summary = (
        df.groupby(["threshold_quantile", "panel_b_category"])
        .size()
        .unstack(fill_value=0)
        .reindex(columns=category_order, fill_value=0)
        .sort_index()
    )

    thresholds = summary.index.to_numpy(dtype=float)
    totals = summary.sum(axis=1).to_numpy(dtype=float)
    if np.any(totals <= 0):
        raise ValueError("At least one threshold has no valid model comparisons.")

    percentages = summary.div(totals, axis=0) * 100.0
    x = np.arange(len(thresholds), dtype=float)
    bottom = np.zeros(len(thresholds), dtype=float)

    bar_handles = {}
    for category in category_order:
        heights = percentages[category].to_numpy(dtype=float)
        bars = ax.bar(
            x,
            heights,
            bottom=bottom,
            width=0.70,
            color=color_map[category],
            edgecolor="white",
            linewidth=0.55,
            label=category,
        )
        bar_handles[category] = bars
        bottom += heights

    # Minimal data labels: retain the dominant boundary count and the number
    # of AICc-favored interior TLN fits. The very small middle-category counts
    # are intentionally left to the source table/caption to avoid clutter.
    boundary_counts = summary[category_boundary].to_numpy(dtype=int)
    boundary_heights = percentages[category_boundary].to_numpy(dtype=float)
    for xpos, count, height in zip(x, boundary_counts, boundary_heights):
        if count > 0 and height >= 12.0:
            ax.text(
                xpos,
                height / 2.0,
                str(int(count)),
                ha="center",
                va="center",
                fontsize=max(args.font_size - 0.5, 5.5),
            )

    tln_counts = summary[category_tln].to_numpy(dtype=int)
    tln_heights = percentages[category_tln].to_numpy(dtype=float)
    tln_bottom = (
        percentages[category_boundary].to_numpy(dtype=float)
        + percentages[category_pl].to_numpy(dtype=float)
    )
    for xpos, count, height, y0 in zip(x, tln_counts, tln_heights, tln_bottom):
        if count <= 0:
            continue
        if height >= 4.5:
            y = y0 + height / 2.0
            va = "center"
        else:
            y = 101.0
            va = "bottom"
        ax.text(
            xpos,
            y,
            str(int(count)),
            ha="center",
            va=va,
            fontsize=max(args.font_size - 0.5, 5.5),
            clip_on=False,
        )

    # The legend is always external for this panel; no explanatory inset is
    # placed over the data.
    ax._force_legend_outside = True

    unique_totals = np.unique(totals.astype(int))
    if unique_totals.size != 1:
        print(
            "[WARN] Figure 2B threshold totals differ: "
            + ", ".join(map(str, unique_totals.tolist()))
        )

    overall_n = int(len(df))
    overall_boundary = int(df["tln_at_powerlaw_boundary"].sum())
    overall_pl_aicc = int(df["pl_preferred_aicc"].sum())
    overall_pl_bic = int(df["pl_preferred_bic"].sum())
    print(
        "[FIGURE 2B] evaluations={}; PL-boundary={}; "
        "PL-by-AICc={}; PL-by-BIC={}".format(
            overall_n,
            overall_boundary,
            overall_pl_aicc,
            overall_pl_bic,
        )
    )

    ax.set_xticks(x)
    ax.set_xticklabels([f"{q:.2f}" for q in thresholds])
    ax.set_xlim(-0.55, len(thresholds) - 0.45)
    ax.set_ylim(0, 104)
    ax.set_yticks([0, 25, 50, 75, 100])
    ax.set_xlabel("Tail threshold quantile")
    ax.set_ylabel("Repertoires (%)")

def panel_C_threshold(
    ax: plt.Axes,
    scan_df: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    """Backward-compatible output alias for the corrected Figure 2B panel.

    Historically, the final manuscript assembler used
    ``figC_threshold_stability`` as Figure 2B. Keeping this wrapper ensures
    that both the old output stem and the canonical model-comparison stem now
    render the corrected AICc-based stacked-bar panel.
    """
    panel_B_model_compare(ax, scan_df, args)


def panel_D_gamma_concordance(
    ax: plt.Axes,
    characteristics: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    pairs = build_gamma_pairs(characteristics)

    if pairs.empty:
        ax.text(
            0.5,
            0.5,
            "No complete fitted replicate pairs",
            ha="center",
            va="center",
            transform=ax.transAxes,
        )
        ax.set_xlabel(r"$\gamma$ rep. 1")
        ax.set_ylabel(r"$\gamma$ rep. 2")
        return

    ax.scatter(
        pairs["gamma_rep1"],
        pairs["gamma_rep2"],
        s=args.marker_s,
        alpha=args.marker_alpha,
        color=COLOR_GAMMA,
        edgecolors="none",
        label=f"Replicate pairs (n={len(pairs)})",
    )

    x = pairs["gamma_rep1"].to_numpy(float)
    y = pairs["gamma_rep2"].to_numpy(float)

    lo = float(min(np.nanmin(x), np.nanmin(y)))
    hi = float(max(np.nanmax(x), np.nanmax(y)))
    pad = 0.05 * max(hi - lo, 1e-6)

    ax.plot(
        [lo - pad, hi + pad],
        [lo - pad, hi + pad],
        linewidth=args.ref_lw,
        color=COLOR_REF,
        linestyle="--",
    )

    ax.set_xlabel(r"$\gamma$ rep. 1")
    ax.set_ylabel(r"$\gamma$ rep. 2")


# =============================================================================
# Figure wrappers
# =============================================================================


def make_single_panel(
    panel_fn: Callable[[plt.Axes], None],
    fig_dir: Path,
    name: str,
    args: argparse.Namespace,
    title: str = "",
    xlim: Optional[Tuple[float, float]] = None,
    ylim: Optional[Tuple[float, float]] = None,
) -> None:
    fig = plt.figure(figsize=resolve_figure_size(name, args))
    ax = fig.add_subplot(111)

    panel_fn(ax)
    ax.tick_params(
        width=args.tick_w,
        length=args.tick_len,
        pad=args.tick_pad,
    )

    if title and not args.no_titles:
        ax.set_title(title)

    maybe_apply_limits(ax, xlim, ylim)
    apply_axis_config(ax, name)
    apply_legend(ax, args)
    apply_layout(fig)
    save_fig(fig, fig_dir / name, args)
    plt.close(fig)


def make_multipanel(
    fig_dir: Path,
    files: List[Path],
    characteristics: pd.DataFrame,
    scan_df: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    fig, axes = plt.subplots(
        2,
        2,
        figsize=resolve_figure_size("fig1_repertoire_characterization_multipanel", args, multipanel=True),
        constrained_layout=False,
    )
    axes = axes.ravel()

    panel_A_ccdf(axes[0], files, args)
    panel_B_model_compare(axes[1], scan_df, args)
    panel_D_gamma_concordance(axes[2], characteristics, args)
    axes[3].axis("off")

    panel_stems = [
        "figA_ccdf_pooled",
        "figB_model_compare_density",
        "figD_gamma_replicate_concordance",
    ]

    for ax, label, stem in zip(axes[:3], ["A", "B", "C"], panel_stems):
        ax.tick_params(
            width=args.tick_w,
            length=args.tick_len,
            pad=args.tick_pad,
        )
        apply_axis_config(ax, stem)
        label_panel(ax, label, args)
        apply_legend(ax, args)

    fig.subplots_adjust(
        left=args.multi_left,
        right=args.multi_right,
        bottom=args.multi_bottom,
        top=args.multi_top,
        wspace=args.multi_wspace,
        hspace=args.multi_hspace,
    )

    save_fig(
        fig,
        fig_dir / "fig1_repertoire_characterization_multipanel",
        args,
    )
    plt.close(fig)


# =============================================================================
# CLI
# =============================================================================


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot companion for 1-repertoire_characterization.py outputs. "
            "No QC input or PASS/FAIL classification is used."
        )
    )

    parser.add_argument(
        "--analysis-dir",
        "--data_dir",
        dest="analysis_dir",
        required=True,
        help="Directory produced by 1-repertoire_characterization.py.",
    )
    parser.add_argument(
        "--figures-dir",
        "--fig_dir",
        dest="figures_dir",
        required=True,
        help="Directory where figures will be saved.",
    )
    parser.add_argument(
        "--repertoires-dir",
        "--repertoires_dir",
        dest="repertoires_dir",
        default="",
        help="Optional original repertoire directory for panel A CCDF.",
    )
    parser.add_argument(
        "--file-sep",
        "--file_sep",
        dest="file_sep",
        default="\t",
        help="Separator used for raw repertoire files. Default: tab.",
    )
    parser.add_argument(
        "--pattern",
        default=PATTERN_DEFAULT,
        help="Regex for repertoire filenames.",
    )

    parser.add_argument("--font_family", default="Arial")
    parser.add_argument("--font_size", type=float, default=8.0)
    parser.add_argument("--fig_w", type=float, default=None, help="Optional global single-panel width override.")
    parser.add_argument("--fig_h", type=float, default=None, help="Optional global single-panel height override.")
    parser.add_argument("--multi_fig_w", type=float, default=None, help="Optional multipanel width override.")
    parser.add_argument("--multi_fig_h", type=float, default=None, help="Optional multipanel height override.")
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument(
        "--pdf",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument(
        "--png",
        action=argparse.BooleanOptionalAction,
        default=False,
    )
    parser.add_argument(
        "--svg",
        action=argparse.BooleanOptionalAction,
        default=False,
    )

    parser.add_argument("--axes_w", type=float, default=0.6)
    parser.add_argument("--tick_w", type=float, default=0.6)
    parser.add_argument("--tick_len", type=float, default=2.0)
    parser.add_argument("--label_pad", type=float, default=1.0)
    parser.add_argument("--tick_pad", type=float, default=1.0)
    parser.add_argument("--line_w", type=float, default=0.75)
    parser.add_argument("--ref_lw", type=float, default=0.6)
    parser.add_argument("--marker_size", type=float, default=2.3)
    parser.add_argument("--marker_s", type=float, default=12.0)
    parser.add_argument("--marker_alpha", type=float, default=0.85)
    parser.add_argument("--single_alpha", type=float, default=0.20)
    parser.add_argument("--single_lw", type=float, default=0.35)
    parser.add_argument("--pooled_lw", type=float, default=0.9)
    parser.add_argument("--hist_bins", type=int, default=25)

    parser.add_argument(
        "--legend_mode",
        choices=["inside", "outside", "none"],
        default="outside",
    )
    parser.add_argument("--legend_loc", default="best")
    parser.add_argument("--legend_frame", type=int, default=0)
    parser.add_argument("--legend_fontsize", type=float, default=7.0)
    parser.add_argument("--legend_bbox_x", type=float, default=1.005)
    parser.add_argument("--legend_bbox_y", type=float, default=1.0)
    parser.add_argument("--legend_pad_inches", type=float, default=0.05)

    parser.add_argument("--panel_label_fontsize", type=float, default=9.0)
    parser.add_argument("--panel_label_x", type=float, default=-0.18)
    parser.add_argument("--panel_label_y", type=float, default=1.05)

    parser.add_argument("--multi_left", type=float, default=0.10)
    parser.add_argument("--multi_right", type=float, default=0.98)
    parser.add_argument("--multi_bottom", type=float, default=0.10)
    parser.add_argument("--multi_top", type=float, default=0.96)
    parser.add_argument("--multi_wspace", type=float, default=0.36)
    parser.add_argument("--multi_hspace", type=float, default=0.42)

    parser.add_argument(
        "--no_titles",
        action="store_true",
        default=True,
    )
    parser.add_argument(
        "--make_multipanel",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument(
        "--make_single_panels",
        action=argparse.BooleanOptionalAction,
        default=True,
    )

    parser.add_argument("--xlim_gamma", default="", help="Compatibility override applied before AXIS_CONFIG.")
    parser.add_argument("--ylim_gamma", default="", help="Compatibility override applied before AXIS_CONFIG.")

    return parser.parse_args()


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    args = parse_args()

    data_dir = Path(args.analysis_dir).expanduser().resolve()
    fig_dir = ensure_dir(Path(args.figures_dir).expanduser().resolve())

    apply_rcparams(args)

    characteristics = read_csv_required(
        data_dir / "repertoire_characteristics.csv"
    )
    scan_df = read_csv_required(
        data_dir / "repertoire_tail_model_scan.csv"
    )

    # Validate the main analysis table early so schema mismatches fail clearly.
    characteristics_clean = clean_repertoire_characteristics(characteristics)
    gamma_pairs = build_gamma_pairs(characteristics_clean)

    files: List[Path] = []
    if args.repertoires_dir:
        repertoire_dir = Path(args.repertoires_dir).expanduser().resolve()

        if repertoire_dir.exists():
            files = list_valid_repertoire_files(
                repertoire_dir,
                args.pattern,
                args.file_sep,
            )
        else:
            print(f"[WARN] repertoires_dir not found: {repertoire_dir}")

    outputs: List[str] = []

    if args.make_single_panels:
        if files:
            make_single_panel(
                lambda ax: panel_A_ccdf(ax, files, args),
                fig_dir,
                "figA_ccdf_pooled",
                args,
                title="Heavy-tailed clone-size structure",
            )
            outputs.append("figA_ccdf_pooled")
        else:
            print(
                "[WARN] No valid repertoire files found for panel A. "
                "Provide --repertoires_dir to enable CCDF plotting."
            )

        make_single_panel(
            lambda ax: panel_B_model_compare(ax, scan_df, args),
            fig_dir,
            "figB_model_compare_density",
            args,
            title="Complexity-adjusted PL vs TLN comparison",
        )
        outputs.append("figB_model_compare_density")

        make_single_panel(
            lambda ax: panel_C_threshold(ax, scan_df, args),
            fig_dir,
            "figC_threshold_stability",
            args,
            title="Complexity-adjusted PL vs TLN comparison",
        )
        outputs.append("figC_threshold_stability")

        make_single_panel(
            lambda ax: panel_D_gamma_concordance(
                ax,
                characteristics_clean,
                args,
            ),
            fig_dir,
            "figD_gamma_replicate_concordance",
            args,
            title="Replicate concordance of the power-law exponent",
            xlim=parse_lim(args.xlim_gamma),
            ylim=parse_lim(args.ylim_gamma),
        )
        outputs.append("figD_gamma_replicate_concordance")

    if args.make_multipanel:
        make_multipanel(
            fig_dir=fig_dir,
            files=files,
            characteristics=characteristics_clean,
            scan_df=scan_df,
            args=args,
        )
        outputs.append("fig1_repertoire_characterization_multipanel")

    print(
        "✅ Completed plotting with 1-plot_repertoire_characterization_vs2.py."
    )
    print(f"[DATA] {data_dir}")
    print(
        "[DATA] repertoires: {}; successful primary fits: {}; "
        "complete gamma replicate pairs: {}".format(
            len(characteristics_clean),
            int(characteristics_clean["pl_fit_success"].sum()),
            len(gamma_pairs),
        )
    )
    print(f"[FIGS] {fig_dir}")

    for output in outputs:
        print(f"[OUT]  {output}")


if __name__ == "__main__":
    main()
