#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
10-plot_longitudinal_vs_pseudo_forward_drift.py
===============================================

Plot-only companion to ClonoDynamics Step 10:

    10-longitudinal_vs_pseudo_forward_drift.py

Scientific role
---------------
Step 10 compares the genuine longitudinal replicate-decoupled forward-drift
profile from Step 9 with the pseudo-longitudinal technical-null distribution
generated by Step 7.

The primary estimand is:

    E[Delta x_latent | x0]

using the replicate-decoupled:

    cross_combined

representation in both datasets.

The comparison preserves each dataset's native absolute latent-abundance
geometry. Step 10 does not impose common bin edges, convert abundance to ranks
or percentiles, or extrapolate outside observed support. Instead, already
estimated curves are compared on their shared absolute-abundance support.

This plotting script reads ONLY Step-10 outputs. It does not directly reload
Step-7 or Step-9 analysis directories and does not recompute the Step-10 shared
grid, empirical null metrics, or P-values.

The plotter does not:

    - interpolate native curves;
    - recompute shared support;
    - recalculate pseudo order/reverse metrics;
    - recompute empirical P-values;
    - modify the Step-10 comparison estimand;
    - redefine abundance geometry.

Position in the pipeline
------------------------
    Step 7 pseudo conditioning / ordering benchmark
                       \
                        \
                         v
                      Step 10
                         ^
                        /
                       /
    Step 9 genuine replicate-decoupled forward drift

Step 8 is not a direct input to Step 10.

Analysis input
--------------
Required:

    --analysis-dir

pointing to the output directory generated by:

    10-longitudinal_vs_pseudo_forward_drift.py

Required Step-10 tables
-----------------------
    01_native_forward_drift_curves.csv
        Native longitudinal and pseudo curves before shared-support
        interpolation.

    02_shared_support_grid.csv
        Primary pointwise genuine-versus-pseudo comparison on the shared
        absolute abundance grid.

    03_pseudo_overlap_null_metrics.csv
        One row per pseudo reverse-pair curve with shared-support summary
        metrics.

    04_empirical_tests.csv
        Precomputed empirical tests for slope, centered drift magnitude and
        mean offset.

    05_support_summary.csv
        Native and shared absolute-support metadata.

    09_comparison_summary.csv
        Manuscript-oriented Step-10 comparison summary.

Propagated Step-9 robustness tables
-----------------------------------
Step 10 also writes:

    06_longitudinal_fold_concordance.csv
    07_longitudinal_subject_drift.csv
    08_longitudinal_loso_drift.csv

These are carried forward for provenance and convenience. They are not
replotted here because the dedicated Step-9 plotter is the canonical
visualization layer for genuine-longitudinal robustness diagnostics.

Generated figures
-----------------
Main composite:

    00_main_longitudinal_vs_pseudo_forward_drift_ABC

        A  longitudinal forward drift versus pseudo median/95% envelope
        B  longitudinal slope relative to the pseudo empirical null
        C  longitudinal centered mean absolute drift relative to the pseudo null

Supplementary comparison composite:

    Sx_longitudinal_vs_pseudo_comparison_diagnostics

        A  native longitudinal and pseudo curves before shared-grid interpolation
        B  longitudinal-minus-pseudo drift on the shared grid
        C  centered RMS drift relative to the pseudo null
        D  mean drift offset relative to the pseudo null

Standalone figures:

    01_longitudinal_vs_pseudo_forward_drift
    02_slope_pseudo_null
    03_centered_mean_abs_drift_pseudo_null
    04_native_forward_drift_curves
    05_longitudinal_minus_pseudo
    06_centered_rms_drift_pseudo_null
    07_mean_drift_offset_pseudo_null

Non-figure outputs
------------------
Only graphical provenance is written:

    figure_manifest.csv
    plot_config.json

No new scientific summary or inferential table is produced by this plotter.

Rendering policy
----------------
Null-distribution figures use the already-computed values in:

    03_pseudo_overlap_null_metrics.csv

and the already-computed longitudinal statistic and empirical P-value in:

    04_empirical_tests.csv.

Random jitter, controlled by --seed, is used only to prevent overplotting of
points in the one-dimensional null-distribution display. It has no analytical
role.

Figure customization
--------------------
Edit:

    FIGURE_SIZES_INCHES

for per-figure dimensions in inches, and:

    AXIS_CONFIG

for per-panel:

    xlim
    ylim
    xscale
    yscale
    xtick_step
    ytick_step

Example
-------
python3 ./code/plotting/10-plot_longitudinal_vs_pseudo_forward_drift.py \
    --analysis-dir \
    ./comparison_results/10-longitudinal-vs-pseudo-forward-drift \
    --figures-dir ./figures/10-longitudinal-vs-pseudo-forward-drift \
    --formats pdf,png
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
import pandas as pd


SCRIPT_VERSION = "v1-step10-public-plotter-2026-08-25"


# =============================================================================
# Figure configuration
# =============================================================================

FIGURE_SIZES_INCHES: Dict[str, Tuple[float, float]] = {
    "00_main_longitudinal_vs_pseudo_forward_drift_ABC": (9.6, 2.6),
    "Sx_longitudinal_vs_pseudo_comparison_diagnostics": (7.2, 6.0),

    "01_longitudinal_vs_pseudo_forward_drift": (3.2, 2.4),
    "02_slope_pseudo_null": (3.2, 2.4),
    "03_centered_mean_abs_drift_pseudo_null": (3.2, 2.4),
    "04_native_forward_drift_curves": (3.2, 2.4),
    "05_longitudinal_minus_pseudo": (3.2, 2.4),
    "06_centered_rms_drift_pseudo_null": (3.2, 2.4),
    "07_mean_drift_offset_pseudo_null": (3.2, 2.4),
}


def _axis_cfg(
    xlim=None,
    ylim=None,
    xscale=None,
    yscale=None,
    xtick_step=None,
    ytick_step=None,
) -> Dict[str, object]:
    return {
        "xlim": xlim,
        "ylim": ylim,
        "xscale": xscale,
        "yscale": yscale,
        "xtick_step": xtick_step,
        "ytick_step": ytick_step,
    }


AXIS_CONFIG = {
    # Main composite
    "MainA": _axis_cfg(),
    "MainB": _axis_cfg(),
    "MainC": _axis_cfg(),

    # Supplementary composite
    "SxA": _axis_cfg(),
    "SxB": _axis_cfg(),
    "SxC": _axis_cfg(),
    "SxD": _axis_cfg(),

    # Standalone
    "01_longitudinal_vs_pseudo_forward_drift": _axis_cfg(),
    "02_slope_pseudo_null": _axis_cfg(),
    "03_centered_mean_abs_drift_pseudo_null": _axis_cfg(),
    "04_native_forward_drift_curves": _axis_cfg(),
    "05_longitudinal_minus_pseudo": _axis_cfg(),
    "06_centered_rms_drift_pseudo_null": _axis_cfg(),
    "07_mean_drift_offset_pseudo_null": _axis_cfg(),
}


PLOT_STYLE_DEFAULTS = {
    "dpi": 300,
    "font_size": 8.0,
    "line_width": 1.15,
    "marker_size": 2.8,
    "ci_alpha": 0.16,
}


REQUIRED_FILES = {
    "native": "01_native_forward_drift_curves.csv",
    "shared_grid": "02_shared_support_grid.csv",
    "pseudo_null": "03_pseudo_overlap_null_metrics.csv",
    "empirical_tests": "04_empirical_tests.csv",
    "support": "05_support_summary.csv",
    "summary": "09_comparison_summary.csv",
}


# =============================================================================
# Helpers
# =============================================================================

def eprint(*args, **kwargs) -> None:
    print(*args, file=sys.stderr, **kwargs)


def setup_style(font_size: float) -> str:
    try:
        from matplotlib import font_manager
        font_manager.findfont("Arial", fallback_to_default=False)
        family = "Arial"
    except Exception:
        family = "DejaVu Sans"
        eprint("[WARN] Arial not found; using DejaVu Sans.")

    tick_font = max(float(font_size) - 1.0, 5.0)
    plt.rcParams.update(
        {
            "font.family": family,
            "font.size": float(font_size),
            "axes.labelsize": float(font_size),
            "axes.titlesize": float(font_size),
            "xtick.labelsize": tick_font,
            "ytick.labelsize": tick_font,
            "legend.fontsize": tick_font,
            "legend.title_fontsize": tick_font,
            "axes.linewidth": 0.7,
            "xtick.major.width": 0.7,
            "ytick.major.width": 0.7,
            "xtick.major.size": 2.5,
            "ytick.major.size": 2.5,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    return family


def style_axes(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(direction="out")


def apply_axis_config(ax: plt.Axes, key: str) -> None:
    cfg = AXIS_CONFIG.get(key, {})
    if cfg.get("xscale"):
        ax.set_xscale(str(cfg["xscale"]))
    if cfg.get("yscale"):
        ax.set_yscale(str(cfg["yscale"]))
    if cfg.get("xlim") is not None:
        ax.set_xlim(*cfg["xlim"])
    if cfg.get("ylim") is not None:
        ax.set_ylim(*cfg["ylim"])
    if cfg.get("xtick_step") is not None:
        ax.xaxis.set_major_locator(MultipleLocator(float(cfg["xtick_step"])))
    if cfg.get("ytick_step") is not None:
        ax.yaxis.set_major_locator(MultipleLocator(float(cfg["ytick_step"])))


def add_panel_label(ax: plt.Axes, label: str, font_size: float) -> None:
    ax.text(
        -0.14,
        1.08,
        label,
        transform=ax.transAxes,
        fontsize=max(float(font_size) + 1.0, 8.0),
        fontweight="bold",
        va="top",
        ha="left",
    )


def annotation_box(ax: plt.Axes, text: str) -> None:
    ax.text(
        0.03,
        0.97,
        text,
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontsize=max(float(plt.rcParams["font.size"]) - 1.0, 6.0),
        bbox=dict(facecolor="white", edgecolor="0.82", linewidth=0.45, alpha=0.82),
    )


def read_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError("Required Step-10 table not found: {}".format(path))
    df = pd.read_csv(path)
    if df.empty:
        raise ValueError("Required Step-10 table is empty: {}".format(path))
    return df


def load_tables(analysis_dir: Path) -> Dict[str, pd.DataFrame]:
    return {
        key: read_required(analysis_dir / filename)
        for key, filename in REQUIRED_FILES.items()
    }


def require_columns(df: pd.DataFrame, columns: Sequence[str], label: str) -> None:
    missing = [c for c in columns if c not in df.columns]
    if missing:
        raise ValueError(
            "{} missing required columns {}. Available: {}".format(
                label, missing, list(df.columns)
            )
        )


def parse_formats(text: str) -> List[str]:
    values = [v.strip().lower() for v in str(text).split(",") if v.strip()]
    allowed = {"pdf", "png", "svg"}
    invalid = [v for v in values if v not in allowed]
    if invalid:
        raise ValueError("Unsupported formats: {}".format(invalid))
    out: List[str] = []
    for value in values:
        if value not in out:
            out.append(value)
    if not out:
        raise ValueError("At least one output format is required.")
    return out


def save_figure(
    fig: plt.Figure,
    outdir: Path,
    stem: str,
    formats: Sequence[str],
    dpi: int,
) -> List[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for fmt in formats:
        path = outdir / "{}.{}".format(stem, fmt)
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if fmt == "png":
            kwargs["dpi"] = int(dpi)
        fig.savefig(path, **kwargs)
        written.append(path)
        print("[SAVED] {}".format(path))
    plt.close(fig)
    return written


def empirical_row(tests: pd.DataFrame, metric: str) -> pd.Series:
    require_columns(
        tests,
        ["metric", "longitudinal_value", "empirical_p", "tail"],
        "04_empirical_tests.csv",
    )
    d = tests.loc[tests["metric"].astype(str) == metric]
    if d.empty:
        raise ValueError("Metric {!r} not found in 04_empirical_tests.csv".format(metric))
    return d.iloc[0]


def p_label(value: float) -> str:
    if not np.isfinite(value):
        return "P = NA"
    if value < 0.001:
        return "P < 0.001"
    return "P = {:.3f}".format(value)


# =============================================================================
# Plot primitives
# =============================================================================

def draw_shared_grid(
    ax: plt.Axes,
    shared: pd.DataFrame,
    line_width: float,
    marker_size: float,
    ci_alpha: float,
    axis_key: str,
) -> None:
    require_columns(
        shared,
        [
            "x",
            "longitudinal_mean_dx",
            "longitudinal_ci025",
            "longitudinal_ci975",
            "pseudo_median_dx",
            "pseudo_q025",
            "pseudo_q975",
        ],
        "02_shared_support_grid.csv",
    )
    d = shared.sort_values("x")
    x = pd.to_numeric(d["x"], errors="coerce").to_numpy(float)

    long_y = pd.to_numeric(d["longitudinal_mean_dx"], errors="coerce").to_numpy(float)
    long_lo = pd.to_numeric(d["longitudinal_ci025"], errors="coerce").to_numpy(float)
    long_hi = pd.to_numeric(d["longitudinal_ci975"], errors="coerce").to_numpy(float)
    pseudo_y = pd.to_numeric(d["pseudo_median_dx"], errors="coerce").to_numpy(float)
    pseudo_lo = pd.to_numeric(d["pseudo_q025"], errors="coerce").to_numpy(float)
    pseudo_hi = pd.to_numeric(d["pseudo_q975"], errors="coerce").to_numpy(float)

    ok_l = np.isfinite(x) & np.isfinite(long_y)
    line_l = ax.plot(
        x[ok_l], long_y[ok_l],
        marker="o", markersize=marker_size,
        linewidth=line_width, label="Longitudinal"
    )[0]
    ok_lci = np.isfinite(x) & np.isfinite(long_lo) & np.isfinite(long_hi)
    if ok_lci.any():
        ax.fill_between(
            x[ok_lci], long_lo[ok_lci], long_hi[ok_lci],
            color=line_l.get_color(), alpha=ci_alpha, linewidth=0
        )

    ok_p = np.isfinite(x) & np.isfinite(pseudo_y)
    line_p = ax.plot(
        x[ok_p], pseudo_y[ok_p],
        linewidth=line_width, label="Pseudo median"
    )[0]
    ok_pci = np.isfinite(x) & np.isfinite(pseudo_lo) & np.isfinite(pseudo_hi)
    if ok_pci.any():
        ax.fill_between(
            x[ok_pci], pseudo_lo[ok_pci], pseudo_hi[ok_pci],
            color=line_p.get_color(), alpha=ci_alpha, linewidth=0
        )

    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    ax.legend(frameon=False)


def draw_null_distribution(
    ax: plt.Axes,
    pseudo_null: pd.DataFrame,
    tests: pd.DataFrame,
    metric: str,
    xlabel: str,
    axis_key: str,
    seed: int,
) -> None:
    require_columns(pseudo_null, [metric], "03_pseudo_overlap_null_metrics.csv")
    values = pd.to_numeric(pseudo_null[metric], errors="coerce").dropna().to_numpy(float)
    if values.size == 0:
        raise ValueError("No finite pseudo values for {}".format(metric))

    row = empirical_row(tests, metric)
    observed = float(pd.to_numeric(pd.Series([row["longitudinal_value"]]), errors="coerce").iloc[0])
    p = float(pd.to_numeric(pd.Series([row["empirical_p"]]), errors="coerce").iloc[0])

    rng = np.random.default_rng(int(seed))
    y = rng.normal(0.0, 0.035, size=values.size)
    ax.scatter(values, y, s=9, alpha=0.35, linewidths=0)
    ax.axvline(np.median(values), linewidth=1.0, linestyle="--", color="0.35", label="Pseudo median")
    ax.axvline(observed, linewidth=1.3, color="0.1", label="Longitudinal")

    ax.set_yticks([])
    ax.set_xlabel(xlabel)
    ax.set_ylabel("")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    annotation_box(ax, "{}\nn = {} pseudo curves".format(p_label(p), values.size))
    ax.legend(frameon=False, loc="best")


def draw_native_curves(
    ax: plt.Axes,
    native: pd.DataFrame,
    line_width: float,
    marker_size: float,
    axis_key: str,
) -> None:
    require_columns(
        native,
        ["dataset", "x_center", "mean_dx"],
        "01_native_forward_drift_curves.csv",
    )
    for dataset, label in [("longitudinal", "Longitudinal native"), ("pseudo", "Pseudo native")]:
        d = native.loc[native["dataset"].astype(str) == dataset].sort_values("x_center")
        if d.empty:
            continue
        x = pd.to_numeric(d["x_center"], errors="coerce").to_numpy(float)
        y = pd.to_numeric(d["mean_dx"], errors="coerce").to_numpy(float)
        ok = np.isfinite(x) & np.isfinite(y)
        if ok.any():
            ax.plot(
                x[ok], y[ok],
                marker="o", markersize=marker_size,
                linewidth=line_width, label=label
            )
    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Native absolute latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    ax.legend(frameon=False)


def draw_difference(
    ax: plt.Axes,
    shared: pd.DataFrame,
    line_width: float,
    marker_size: float,
    axis_key: str,
) -> None:
    require_columns(
        shared,
        ["x", "longitudinal_minus_pseudo"],
        "02_shared_support_grid.csv",
    )
    d = shared.sort_values("x")
    x = pd.to_numeric(d["x"], errors="coerce").to_numpy(float)
    y = pd.to_numeric(d["longitudinal_minus_pseudo"], errors="coerce").to_numpy(float)
    ok = np.isfinite(x) & np.isfinite(y)
    ax.plot(
        x[ok], y[ok],
        marker="o", markersize=marker_size,
        linewidth=line_width
    )
    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Shared latent abundance, $x_0$")
    ax.set_ylabel("Longitudinal − pseudo mean drift")
    style_axes(ax)
    apply_axis_config(ax, axis_key)


# =============================================================================
# Figure builders
# =============================================================================

def plot_main(
    tables: Dict[str, pd.DataFrame],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    fig, axes = plt.subplots(
        1, 3,
        figsize=FIGURE_SIZES_INCHES["00_main_longitudinal_vs_pseudo_forward_drift_ABC"],
    )

    draw_shared_grid(
        axes[0], tables["shared_grid"], args.line_width,
        args.marker_size, args.ci_alpha, "MainA"
    )
    draw_null_distribution(
        axes[1], tables["pseudo_null"], tables["empirical_tests"],
        "slope", r"Slope of $E[\Delta x\mid x_0]$", "MainB", args.seed
    )
    draw_null_distribution(
        axes[2], tables["pseudo_null"], tables["empirical_tests"],
        "centered_mean_abs_drift", "Centered mean absolute drift",
        "MainC", args.seed + 1
    )

    for ax, label in zip(axes, ["A", "B", "C"]):
        add_panel_label(ax, label, args.font_size)

    fig.subplots_adjust(wspace=0.42)
    return save_figure(
        fig, outdir,
        "00_main_longitudinal_vs_pseudo_forward_drift_ABC",
        formats, args.dpi,
    )


def plot_supplementary(
    tables: Dict[str, pd.DataFrame],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    fig, axes = plt.subplots(
        2, 2,
        figsize=FIGURE_SIZES_INCHES["Sx_longitudinal_vs_pseudo_comparison_diagnostics"],
    )
    axA, axB, axC, axD = axes.ravel()

    draw_native_curves(
        axA, tables["native"], args.line_width, args.marker_size, "SxA"
    )
    draw_difference(
        axB, tables["shared_grid"], args.line_width, args.marker_size, "SxB"
    )
    draw_null_distribution(
        axC, tables["pseudo_null"], tables["empirical_tests"],
        "centered_rms_drift", "Centered RMS drift", "SxC", args.seed + 2
    )
    draw_null_distribution(
        axD, tables["pseudo_null"], tables["empirical_tests"],
        "mean_dx", "Mean drift offset", "SxD", args.seed + 3
    )

    for ax, label in zip(axes.ravel(), ["A", "B", "C", "D"]):
        add_panel_label(ax, label, args.font_size)

    fig.subplots_adjust(wspace=0.42, hspace=0.42)
    return save_figure(
        fig, outdir,
        "Sx_longitudinal_vs_pseudo_comparison_diagnostics",
        formats, args.dpi,
    )


def plot_standalones(
    tables: Dict[str, pd.DataFrame],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    written: List[Path] = []

    specs = [
        ("01_longitudinal_vs_pseudo_forward_drift", "shared"),
        ("02_slope_pseudo_null", "slope"),
        ("03_centered_mean_abs_drift_pseudo_null", "centered_mean_abs_drift"),
        ("04_native_forward_drift_curves", "native"),
        ("05_longitudinal_minus_pseudo", "difference"),
        ("06_centered_rms_drift_pseudo_null", "centered_rms_drift"),
        ("07_mean_drift_offset_pseudo_null", "mean_dx"),
    ]

    for i, (stem, kind) in enumerate(specs):
        fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])

        if kind == "shared":
            draw_shared_grid(
                ax, tables["shared_grid"], args.line_width,
                args.marker_size, args.ci_alpha, stem
            )
        elif kind == "native":
            draw_native_curves(
                ax, tables["native"], args.line_width, args.marker_size, stem
            )
        elif kind == "difference":
            draw_difference(
                ax, tables["shared_grid"], args.line_width, args.marker_size, stem
            )
        else:
            labels = {
                "slope": r"Slope of $E[\Delta x\mid x_0]$",
                "centered_mean_abs_drift": "Centered mean absolute drift",
                "centered_rms_drift": "Centered RMS drift",
                "mean_dx": "Mean drift offset",
            }
            draw_null_distribution(
                ax, tables["pseudo_null"], tables["empirical_tests"],
                kind, labels[kind], stem, args.seed + i
            )

        written.extend(save_figure(fig, outdir, stem, formats, args.dpi))

    return written


# =============================================================================
# CLI
# =============================================================================

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Plot ClonoDynamics Step-10 longitudinal-versus-pseudo forward-drift outputs.",
    )
    parser.add_argument(
        "--analysis-dir",
        required=True,
        type=Path,
        help="Output directory produced by 10-longitudinal_vs_pseudo_forward_drift.py.",
    )
    parser.add_argument(
        "--figures-dir",
        type=Path,
        default=None,
        help=(
            "Figure output directory. Default: "
            "<analysis-dir>/figures_longitudinal_vs_pseudo_forward_drift"
        ),
    )
    parser.add_argument(
        "--figure-set",
        choices=["all", "main", "supplementary", "standalone"],
        default="all",
    )
    parser.add_argument("--formats", default="pdf,png")
    parser.add_argument("--dpi", type=int, default=PLOT_STYLE_DEFAULTS["dpi"])
    parser.add_argument("--font-size", type=float, default=PLOT_STYLE_DEFAULTS["font_size"])
    parser.add_argument("--line-width", type=float, default=PLOT_STYLE_DEFAULTS["line_width"])
    parser.add_argument("--marker-size", type=float, default=PLOT_STYLE_DEFAULTS["marker_size"])
    parser.add_argument("--ci-alpha", type=float, default=PLOT_STYLE_DEFAULTS["ci_alpha"])
    parser.add_argument("--seed", type=int, default=123)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    analysis_dir = args.analysis_dir.expanduser().resolve()
    if not analysis_dir.is_dir():
        raise NotADirectoryError(analysis_dir)

    figures_dir = (
        args.figures_dir.expanduser().resolve()
        if args.figures_dir is not None
        else analysis_dir / "figures_longitudinal_vs_pseudo_forward_drift"
    )
    figures_dir.mkdir(parents=True, exist_ok=True)

    formats = parse_formats(args.formats)
    font_used = setup_style(args.font_size)
    tables = load_tables(analysis_dir)

    written: List[Path] = []

    if args.figure_set in {"all", "main"}:
        written.extend(plot_main(tables, figures_dir, formats, args))
    if args.figure_set in {"all", "supplementary"}:
        written.extend(plot_supplementary(tables, figures_dir, formats, args))
    if args.figure_set in {"all", "standalone"}:
        written.extend(plot_standalones(tables, figures_dir, formats, args))

    manifest = pd.DataFrame(
        {
            "file": [p.name for p in written],
            "figure": [p.stem for p in written],
            "format": [p.suffix.lstrip(".") for p in written],
        }
    )
    manifest.to_csv(figures_dir / "figure_manifest.csv", index=False)

    config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "analysis_source": "10-longitudinal_vs_pseudo_forward_drift.py",
        "analysis_dir": str(analysis_dir),
        "figures_dir": str(figures_dir),
        "figure_set": args.figure_set,
        "formats": formats,
        "dpi": int(args.dpi),
        "font_size": float(args.font_size),
        "font_family_used": font_used,
        "line_width": float(args.line_width),
        "marker_size": float(args.marker_size),
        "ci_alpha": float(args.ci_alpha),
        "seed_display_jitter": int(args.seed),
        "figure_sizes_inches": FIGURE_SIZES_INCHES,
        "axis_config": AXIS_CONFIG,
        "analysis_recomputed": False,
        "shared_support_recomputed": False,
        "empirical_tests_recomputed": False,
    }
    (figures_dir / "plot_config.json").write_text(
        json.dumps(config, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print("[DONE] Step-10 plotting complete")
    print("[INFO] Analysis: {}".format(analysis_dir))
    print("[INFO] Figures: {}".format(figures_dir))
    print("[INFO] {} rendered files".format(len(written)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
