#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
11-plot_longitudinal_fluctuation_dynamics.py
============================================

Plot-only companion to ClonoDynamics Step 11:

    11-longitudinal_fluctuation_dynamics.py

Role in the pipeline
--------------------
Step 11 quantifies abundance-resolved genuine longitudinal clonotype
fluctuations on the frozen primary latent/xstar architecture and preserves
separate temporal lags on one shared absolute abundance grid.

This script visualizes the tables already generated by Step 11. It does not:

    - read the Step-5 transition table;
    - rebuild or filter transitions;
    - redefine shared abundance bins;
    - recompute bootstrap confidence intervals;
    - refit transition-weighted or equal-subject estimators;
    - recompute leave-one-subject-out analyses;
    - fit temporal scaling models;
    - compare longitudinal data with the pseudo-longitudinal reference.

Those responsibilities remain separated in the current public pipeline:

    Step 11
        longitudinal fluctuation dynamics

    Step 12
        longitudinal-versus-pseudo fluctuation baseline

    Step 13
        temporal fluctuation scaling

    Step 14
        interval-position / calendar-composition sensitivity

    Step 15
        detectability-boundary sensitivity.

The former legacy plotter mixed several of these roles. This version is
restricted to Step-11 outputs.

Analysis input
--------------
Required:

    --analysis-dir

pointing to the output directory generated by:

    11-longitudinal_fluctuation_dynamics.py

Required Step-11 tables
-----------------------
    10_binned_dynamics_long.csv / .parquet
        Primary abundance-resolved fluctuation curves.

    07_temporal_comparability_by_dt.csv / .parquet
        Dataset-wide temporal coverage and composition by lag.

    06_temporal_comparability_by_dt_bin.csv / .parquet
        Temporal comparability by lag x shared abundance bin.

    08_subject_availability_by_dt.csv / .parquet
        Subject-specific structural availability by lag.

Optional Step-11 sensitivity tables
-----------------------------------
    13_weighting_sensitivity_curves_long.csv / .parquet
        Transition-weighted and equal-subject-weighted curves.

    14_weighting_sensitivity_comparison_long.csv / .parquet
        Pointwise equal-subject minus transition-weighted differences.

    16_leave_one_subject_out_summary.csv / .parquet
        Leave-one-subject-out robustness envelopes.

Optional metadata
-----------------
    00_analysis_metadata.json
    00_run_config.json

Metadata are used only for provenance and labels. Plotting does not alter the
analytical estimand.

Generated figures
-----------------
Main fluctuation panels:

    01_multidt_var_dx
    01_multidt_msd
    01_multidt_mad_dx

Descriptive Step-11 directional diagnostics:

    01_multidt_mean_dx
    01_multidt_median_dx
    01_multidt_ppos

Temporal-coverage panels:

    02_temporal_coverage_n_transitions
    02_temporal_coverage_n_subjects
    02_temporal_coverage_n_subject_interval_pairs
    02_temporal_coverage_n_interval_pairs

Shared-bin comparability panels:

    03_shared_bin_n_transitions
    03_shared_bin_n_subjects
    03_shared_bin_n_subject_interval_pairs
    03_shared_bin_mean_effective_dt_minus_nominal

Detectability / posterior-uncertainty panels, when the corresponding columns
are present in the Step-11 primary curve table:

    04_detectability_median_p_detect
    04_detectability_median_p_dropout
    04_uncertainty_median_dx_post_sd
    04_uncertainty_median_dx_post_95_width

Optional sensitivity figures:

    05_weighting_sensitivity_<metric>
    06_weighting_difference_<metric>
    07_loo_robustness_<metric>_<estimator>

A figure manifest is written as:

    figure_manifest.csv

Rendering policy
----------------
No statistical quantity is recomputed from transition-level data. The script
may select requested temporal lags and metrics from Step-11 summary tables,
but plotted point estimates, uncertainty intervals and sensitivity envelopes
are read directly from Step-11 outputs.

Figure customization
--------------------
Two dictionaries near the top of this file are the main manual publication
controls:

    FIGURE_SIZES_INCHES
        Per-figure (width, height) in inches.

    AXIS_CONFIG
        Per-figure axis controls:
            xlim
            ylim
            xscale
            yscale
            xtick_step
            ytick_step

Values set to None preserve the automatic limits defined by the plotted data.
More specific keys can be added for individual metrics if required.

Example
-------
python3 ./code/plotting/11-plot_longitudinal_fluctuation_dynamics.py \
    --analysis-dir \
    ./dataset_longitudinal_clonodynamics_results/longitudinal/11-longitudinal_fluctuation_dynamics \
    --figures-dir ./figures/11-longitudinal-fluctuation-dynamics \
    --dt-values 1,2,3,4,5 \
    --png
"""

from __future__ import annotations

import argparse
import json
import math
import warnings
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
import pandas as pd


# =============================================================================
# Figure dimensions in inches
# =============================================================================

FIGURE_SIZES_INCHES: Dict[str, Tuple[float, float]] = {
    # Primary and descriptive multi-dt curves
    "01_multidt_var_dx": (3.2, 2.4),
    "01_multidt_msd": (3.2, 2.4),
    "01_multidt_mad_dx": (3.2, 2.4),
    "01_multidt_mean_dx": (3.2, 2.4),
    "01_multidt_median_dx": (3.2, 2.4),
    "01_multidt_ppos": (3.2, 2.4),

    # Temporal coverage
    "02_temporal_coverage_n_transitions": (3.2, 2.4),
    "02_temporal_coverage_n_subjects": (3.2, 2.4),
    "02_temporal_coverage_n_subject_interval_pairs": (3.2, 2.4),
    "02_temporal_coverage_n_interval_pairs": (3.2, 2.4),

    # Shared-bin comparability
    "03_shared_bin_n_transitions": (3.2, 2.4),
    "03_shared_bin_n_subjects": (3.2, 2.4),
    "03_shared_bin_n_subject_interval_pairs": (3.2, 2.4),
    "03_shared_bin_mean_effective_dt_minus_nominal": (3.2, 2.4),

    # Detectability / posterior uncertainty
    "04_detectability_median_p_detect": (3.2, 2.4),
    "04_detectability_median_p_dropout": (3.2, 2.4),
    "04_uncertainty_median_dx_post_sd": (3.2, 2.4),
    "04_uncertainty_median_dx_post_95_width": (3.2, 2.4),

    # Sensitivity families: generic metric-level fallbacks
    "05_weighting_sensitivity": (3.2, 2.4),
    "06_weighting_difference": (3.2, 2.4),
    "07_loo_robustness": (3.2, 2.4),
}


# =============================================================================
# Per-figure axis controls
# =============================================================================

AXIS_CONFIG: Dict[str, Dict[str, object]] = {
    "01_multidt_var_dx": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "01_multidt_msd": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "01_multidt_mad_dx": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "01_multidt_mean_dx": {
        "xlim": None, "ylim": (-1.0, 1.0), "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "01_multidt_median_dx": {
        "xlim": None, "ylim": (-1.0, 1.0), "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "01_multidt_ppos": {
        "xlim": None, "ylim": (0.0, 1.0), "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": 0.2,
    },

    "02_temporal_coverage_n_transitions": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": 1.0, "ytick_step": None,
    },
    "02_temporal_coverage_n_subjects": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": 1.0, "ytick_step": 1.0,
    },
    "02_temporal_coverage_n_subject_interval_pairs": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": 1.0, "ytick_step": None,
    },
    "02_temporal_coverage_n_interval_pairs": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": 1.0, "ytick_step": 1.0,
    },

    "03_shared_bin_n_transitions": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "03_shared_bin_n_subjects": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": 1.0,
    },
    "03_shared_bin_n_subject_interval_pairs": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "03_shared_bin_mean_effective_dt_minus_nominal": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },

    "04_detectability_median_p_detect": {
        "xlim": None, "ylim": (0.0, 1.0), "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": 0.2,
    },
    "04_detectability_median_p_dropout": {
        "xlim": None, "ylim": (0.0, 1.0), "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": 0.2,
    },
    "04_uncertainty_median_dx_post_sd": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "04_uncertainty_median_dx_post_95_width": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },

    "05_weighting_sensitivity": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "06_weighting_difference": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
    "07_loo_robustness": {
        "xlim": None, "ylim": None, "xscale": None, "yscale": None,
        "xtick_step": None, "ytick_step": None,
    },
}


# =============================================================================
# Constants
# =============================================================================

PRIMARY_METRICS = ("var_dx", "msd", "mad_dx")
DESCRIPTIVE_METRICS = ("mean_dx", "median_dx", "ppos")
ALL_CURVE_METRICS = PRIMARY_METRICS + DESCRIPTIVE_METRICS

SENSITIVITY_METRICS = (
    "var_dx",
    "msd",
    "mad_dx",
    "mean_dx",
    "median_dx",
    "ppos",
)

LOO_METRICS = ("var_dx", "msd", "mean_dx", "ppos")
LOO_ESTIMATORS = ("transition_weighted", "equal_subject_weighted")

METRIC_LABELS = {
    "var_dx": r"Var($\Delta x$)",
    "msd": r"MSD, E[$(\Delta x)^2$]",
    "mad_dx": r"MAD($\Delta x$)",
    "mean_dx": r"Mean $\Delta x$",
    "median_dx": r"Median $\Delta x$",
    "ppos": r"P($\Delta x>0$)",
}

BASELINE_BY_METRIC = {
    "mean_dx": 0.0,
    "median_dx": 0.0,
    "ppos": 0.5,
}


# =============================================================================
# I/O
# =============================================================================

def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_table(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Input table not found: {path}")

    suffix = path.suffix.lower()
    if suffix in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix in {".tsv", ".txt"}:
        return pd.read_csv(path, sep="\t")

    raise ValueError(f"Unsupported table format: {path}")


def find_table(
    analysis_dir: Path,
    stem: str,
    *,
    required: bool,
) -> Optional[Path]:
    for suffix in (".parquet", ".csv", ".tsv", ".txt"):
        candidate = analysis_dir / f"{stem}{suffix}"
        if candidate.exists():
            return candidate

    if required:
        raise FileNotFoundError(
            f"Required Step-11 output '{stem}' not found in: {analysis_dir}"
        )
    return None


def load_required_table(analysis_dir: Path, stem: str) -> pd.DataFrame:
    path = find_table(analysis_dir, stem, required=True)
    assert path is not None
    frame = read_table(path)
    if frame.empty:
        raise ValueError(f"Required Step-11 table is empty: {path}")
    return frame


def load_optional_table(analysis_dir: Path, stem: str) -> pd.DataFrame:
    path = find_table(analysis_dir, stem, required=False)
    if path is None:
        return pd.DataFrame()

    frame = read_table(path)
    if frame.empty:
        warnings.warn(f"Optional Step-11 table is empty: {path}")
    return frame


def load_metadata(analysis_dir: Path) -> Dict[str, object]:
    for name in ("00_analysis_metadata.json", "00_run_config.json"):
        path = analysis_dir / name
        if path.exists():
            with path.open("r", encoding="utf-8") as handle:
                data = json.load(handle)
            if isinstance(data, dict):
                return data
    return {}


def write_manifest(rows: List[Dict[str, object]], path: Path) -> None:
    pd.DataFrame(rows).to_csv(path, index=False)


# =============================================================================
# Validation and selection
# =============================================================================

def require_columns(df: pd.DataFrame, columns: Iterable[str], label: str) -> None:
    missing = [column for column in columns if column not in df.columns]
    if missing:
        raise ValueError(
            f"{label} is missing required columns: {missing}. "
            f"Available columns: {list(df.columns)}"
        )


def numeric(df: pd.DataFrame, columns: Iterable[str]) -> pd.DataFrame:
    out = df.copy()
    for column in columns:
        if column in out.columns:
            out[column] = pd.to_numeric(out[column], errors="coerce")
    return out.replace([np.inf, -np.inf], np.nan)


def parse_csv(text: str) -> List[str]:
    return [value.strip() for value in str(text or "").split(",") if value.strip()]


def parse_dt_values(text: str, available: Sequence[float]) -> List[float]:
    available_values = sorted({float(v) for v in available if np.isfinite(v)})
    if not str(text or "").strip():
        return available_values

    requested = [float(v) for v in parse_csv(text)]
    missing = [v for v in requested if v not in available_values]
    if missing:
        warnings.warn(f"Requested dt values not available and ignored: {missing}")
    return [v for v in requested if v in available_values]


def format_dt(value: float) -> str:
    value = float(value)
    return str(int(value)) if value.is_integer() else f"{value:g}"


def dt_label(value: float) -> str:
    return rf"$\Delta t={format_dt(value)}$"


def validate_primary_curves(curves: pd.DataFrame) -> None:
    required = [
        "dt",
        "bin_id",
        "bin_mid",
        "n",
        "n_subjects",
        "mean_dx",
        "median_dx",
        "ppos",
        "msd",
        "var_dx",
        "mad_dx",
    ]
    require_columns(curves, required, "10_binned_dynamics_long")

    keys = [column for column in ("representation", "conditioning", "mode") if column in curves]
    for column in keys:
        values = sorted(curves[column].dropna().astype(str).unique())
        if len(values) > 1:
            raise ValueError(
                "10_binned_dynamics_long contains multiple values for "
                f"{column}: {values}. A Step-11 analysis directory should "
                "represent one analysis configuration."
            )


def filter_dt(df: pd.DataFrame, dt_values: Sequence[float]) -> pd.DataFrame:
    if df.empty or "dt" not in df.columns:
        return df.copy()
    dt = pd.to_numeric(df["dt"], errors="coerce")
    return df[dt.isin([float(v) for v in dt_values])].copy()


# =============================================================================
# Plot style
# =============================================================================

def setup_style(args: argparse.Namespace) -> None:
    plt.rcParams.update(
        {
            "font.family": args.font_family,
            "font.size": args.font_size,
            "axes.labelsize": args.font_size,
            "axes.titlesize": args.font_size,
            "xtick.labelsize": max(args.font_size - 1.0, 5.0),
            "ytick.labelsize": max(args.font_size - 1.0, 5.0),
            "legend.fontsize": max(args.font_size - 1.0, 5.0),
            "axes.linewidth": args.axes_width,
            "xtick.major.width": args.tick_width,
            "ytick.major.width": args.tick_width,
            "xtick.major.size": args.tick_length,
            "ytick.major.size": args.tick_length,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": False,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "savefig.dpi": args.dpi,
        }
    )


def style_axes(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(direction="out")


def resolve_figure_size(stem: str) -> Tuple[float, float]:
    if stem in FIGURE_SIZES_INCHES:
        return FIGURE_SIZES_INCHES[stem]

    for prefix in (
        "05_weighting_sensitivity",
        "06_weighting_difference",
        "07_loo_robustness",
    ):
        if stem.startswith(prefix):
            return FIGURE_SIZES_INCHES[prefix]

    raise KeyError(f"No FIGURE_SIZES_INCHES entry for: {stem}")


def resolve_axis_config(stem: str) -> Dict[str, object]:
    if stem in AXIS_CONFIG:
        return dict(AXIS_CONFIG[stem])

    for prefix in (
        "05_weighting_sensitivity",
        "06_weighting_difference",
        "07_loo_robustness",
    ):
        if stem.startswith(prefix):
            return dict(AXIS_CONFIG[prefix])

    return {
        "xlim": None,
        "ylim": None,
        "xscale": None,
        "yscale": None,
        "xtick_step": None,
        "ytick_step": None,
    }


def apply_axis_config(ax: plt.Axes, stem: str) -> None:
    cfg = resolve_axis_config(stem)

    if cfg.get("xscale"):
        ax.set_xscale(str(cfg["xscale"]))
    if cfg.get("yscale"):
        ax.set_yscale(str(cfg["yscale"]))

    if cfg.get("xlim") is not None:
        ax.set_xlim(*cfg["xlim"])
    if cfg.get("ylim") is not None:
        ax.set_ylim(*cfg["ylim"])

    if cfg.get("xtick_step") is not None:
        ax.xaxis.set_major_locator(MultipleLocator(float(cfg["xtick_step"])))
    if cfg.get("ytick_step") is not None:
        ax.yaxis.set_major_locator(MultipleLocator(float(cfg["ytick_step"])))


def apply_legend(ax: plt.Axes, args: argparse.Namespace, title: str) -> None:
    handles, labels = ax.get_legend_handles_labels()
    if not handles:
        return

    if args.legend_mode == "none":
        return

    kwargs = {
        "frameon": False,
        "title": title,
        "title_fontsize": max(args.font_size - 1.0, 5.0),
        "handlelength": 1.2,
        "labelspacing": 0.25,
        "handletextpad": 0.4,
    }

    if args.legend_mode == "outside":
        ax.legend(
            handles,
            labels,
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            borderaxespad=0.0,
            **kwargs,
        )
    else:
        ax.legend(handles, labels, loc="best", **kwargs)


def formats_to_run(args: argparse.Namespace) -> List[str]:
    formats = []
    if args.pdf:
        formats.append("pdf")
    if args.png:
        formats.append("png")
    if args.svg:
        formats.append("svg")
    if not formats:
        raise ValueError("At least one output format must be enabled.")
    return formats


def save_figure(
    fig: plt.Figure,
    figures_dir: Path,
    stem: str,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[str]:
    figures_dir.mkdir(parents=True, exist_ok=True)
    outputs: List[str] = []

    for fmt in formats:
        path = figures_dir / f"{stem}.{fmt}"
        kwargs = {
            "bbox_inches": "tight",
            "pad_inches": args.pad_inches,
        }
        if fmt == "png":
            kwargs["dpi"] = args.dpi
        fig.savefig(path, **kwargs)
        outputs.append(path.name)
        print(f"[SAVED] {path}")

    plt.close(fig)
    return outputs


# =============================================================================
# Generic curve helpers
# =============================================================================

def metric_label(metric: str) -> str:
    return METRIC_LABELS.get(metric, metric)


def plot_curve_with_optional_ci(
    ax: plt.Axes,
    data: pd.DataFrame,
    metric: str,
    label: str,
    args: argparse.Namespace,
) -> bool:
    if data.empty or metric not in data.columns:
        return False

    d = numeric(data, ["bin_mid", metric]).sort_values("bin_mid")
    x = d["bin_mid"].to_numpy(float)
    y = d[metric].to_numpy(float)
    valid = np.isfinite(x) & np.isfinite(y)
    if not valid.any():
        return False

    line = ax.plot(
        x[valid],
        y[valid],
        marker="o",
        linewidth=args.line_width,
        markersize=args.marker_size,
        label=label,
    )[0]

    low_col = f"{metric}_ci_low"
    high_col = f"{metric}_ci_high"
    if args.show_ci and low_col in d.columns and high_col in d.columns:
        low = pd.to_numeric(d[low_col], errors="coerce").to_numpy(float)
        high = pd.to_numeric(d[high_col], errors="coerce").to_numpy(float)
        ok = valid & np.isfinite(low) & np.isfinite(high)
        if ok.any():
            ax.fill_between(
                x[ok],
                low[ok],
                high[ok],
                color=line.get_color(),
                alpha=args.ci_alpha,
                linewidth=0,
            )

    return True


def add_metric_baseline(ax: plt.Axes, metric: str) -> None:
    baseline = BASELINE_BY_METRIC.get(metric)
    if baseline is not None:
        ax.axhline(baseline, linewidth=0.8, linestyle="--", color="0.35")


# =============================================================================
# Family 01: abundance-resolved multi-dt Step-11 curves
# =============================================================================

def plot_multidt_curves(
    curves: pd.DataFrame,
    dt_values: Sequence[float],
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []

    for metric in ALL_CURVE_METRICS:
        stem = f"01_multidt_{metric}"
        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        any_plot = False

        for dt in dt_values:
            d = curves[
                pd.to_numeric(curves["dt"], errors="coerce") == float(dt)
            ].copy()
            any_plot = (
                plot_curve_with_optional_ci(
                    ax, d, metric, dt_label(dt), args
                )
                or any_plot
            )

        if not any_plot:
            plt.close(fig)
            warnings.warn(f"No finite data for {stem}; skipped.")
            continue

        add_metric_baseline(ax, metric)
        ax.set_xlabel(r"Latent abundance, $x^*$")
        ax.set_ylabel(metric_label(metric))
        apply_axis_config(ax, stem)
        style_axes(ax)
        apply_legend(ax, args, title="Lag")
        fig.tight_layout()

        files = save_figure(fig, figures_dir, stem, formats, args)
        rows.extend(
            {
                "figure": name,
                "family": "multidt",
                "metric": metric,
                "source_table": "10_binned_dynamics_long",
            }
            for name in files
        )

    return rows


# =============================================================================
# Family 02: temporal coverage
# =============================================================================

def plot_temporal_coverage(
    by_dt: pd.DataFrame,
    subject_availability: pd.DataFrame,
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []

    require_columns(by_dt, ["dt"], "07_temporal_comparability_by_dt")
    by_dt = numeric(
        by_dt,
        [
            "dt",
            "n_transitions",
            "n_subjects_available",
            "n_subject_interval_pairs",
            "n_interval_pairs",
        ],
    ).sort_values("dt")

    panels = [
        (
            "n_transitions",
            "02_temporal_coverage_n_transitions",
            "Transitions",
        ),
        (
            "n_subjects_available",
            "02_temporal_coverage_n_subjects",
            "Subjects available",
        ),
        (
            "n_subject_interval_pairs",
            "02_temporal_coverage_n_subject_interval_pairs",
            "Subject–interval pairs",
        ),
        (
            "n_interval_pairs",
            "02_temporal_coverage_n_interval_pairs",
            "Nominal interval pairs",
        ),
    ]

    for column, stem, ylabel in panels:
        if column not in by_dt.columns:
            warnings.warn(f"{column} absent from Step-11 by-dt table; {stem} skipped.")
            continue

        d = by_dt[["dt", column]].dropna()
        if d.empty:
            continue

        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        ax.plot(
            d["dt"],
            d[column],
            marker="o",
            linewidth=args.line_width,
            markersize=args.marker_size,
        )
        ax.set_xlabel(r"Temporal lag, $\Delta t$")
        ax.set_ylabel(ylabel)
        apply_axis_config(ax, stem)
        style_axes(ax)
        fig.tight_layout()

        files = save_figure(fig, figures_dir, stem, formats, args)
        rows.extend(
            {
                "figure": name,
                "family": "temporal_coverage",
                "metric": column,
                "source_table": "07_temporal_comparability_by_dt",
            }
            for name in files
        )

    # The subject-availability table is not re-aggregated into new scientific
    # outputs. It is used only to report provenance in the console.
    if not subject_availability.empty and "subject" in subject_availability.columns:
        print(
            "[INFO] Step-11 subject availability table loaded: "
            f"{subject_availability['subject'].astype(str).nunique()} unique subjects."
        )

    return rows


# =============================================================================
# Family 03: shared-bin comparability
# =============================================================================

def plot_shared_bin_comparability(
    by_dt_bin: pd.DataFrame,
    dt_values: Sequence[float],
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    require_columns(
        by_dt_bin,
        ["dt", "bin_mid"],
        "06_temporal_comparability_by_dt_bin",
    )

    d0 = numeric(
        by_dt_bin,
        [
            "dt",
            "bin_mid",
            "n_transitions",
            "n_subjects",
            "n_subject_interval_pairs",
            "mean_effective_dt",
        ],
    )

    rows: List[Dict[str, object]] = []
    panels = [
        (
            "n_transitions",
            "03_shared_bin_n_transitions",
            "Transitions",
        ),
        (
            "n_subjects",
            "03_shared_bin_n_subjects",
            "Subjects",
        ),
        (
            "n_subject_interval_pairs",
            "03_shared_bin_n_subject_interval_pairs",
            "Subject–interval pairs",
        ),
    ]

    for column, stem, ylabel in panels:
        if column not in d0.columns:
            continue

        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        any_plot = False

        for dt in dt_values:
            d = d0[d0["dt"] == float(dt)].sort_values("bin_mid")
            if d.empty:
                continue
            x = d["bin_mid"].to_numpy(float)
            y = d[column].to_numpy(float)
            ok = np.isfinite(x) & np.isfinite(y)
            if not ok.any():
                continue
            ax.plot(
                x[ok],
                y[ok],
                marker="o",
                linewidth=args.line_width,
                markersize=args.marker_size,
                label=dt_label(dt),
            )
            any_plot = True

        if not any_plot:
            plt.close(fig)
            continue

        ax.set_xlabel(r"Latent abundance, $x^*$")
        ax.set_ylabel(ylabel)
        apply_axis_config(ax, stem)
        style_axes(ax)
        apply_legend(ax, args, title="Lag")
        fig.tight_layout()

        files = save_figure(fig, figures_dir, stem, formats, args)
        rows.extend(
            {
                "figure": name,
                "family": "shared_bin_comparability",
                "metric": column,
                "source_table": "06_temporal_comparability_by_dt_bin",
            }
            for name in files
        )

    if "mean_effective_dt" in d0.columns:
        stem = "03_shared_bin_mean_effective_dt_minus_nominal"
        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        any_plot = False

        for dt in dt_values:
            d = d0[d0["dt"] == float(dt)].sort_values("bin_mid")
            if d.empty:
                continue
            x = d["bin_mid"].to_numpy(float)
            y = d["mean_effective_dt"].to_numpy(float) - float(dt)
            ok = np.isfinite(x) & np.isfinite(y)
            if not ok.any():
                continue
            ax.plot(
                x[ok],
                y[ok],
                marker="o",
                linewidth=args.line_width,
                markersize=args.marker_size,
                label=dt_label(dt),
            )
            any_plot = True

        if any_plot:
            ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
            ax.set_xlabel(r"Latent abundance, $x^*$")
            ax.set_ylabel(r"Mean effective $\Delta t$ − nominal $\Delta t$")
            apply_axis_config(ax, stem)
            style_axes(ax)
            apply_legend(ax, args, title="Lag")
            fig.tight_layout()
            files = save_figure(fig, figures_dir, stem, formats, args)
            rows.extend(
                {
                    "figure": name,
                    "family": "shared_bin_comparability",
                    "metric": "mean_effective_dt_minus_nominal",
                    "source_table": "06_temporal_comparability_by_dt_bin",
                }
                for name in files
            )
        else:
            plt.close(fig)

    return rows


# =============================================================================
# Family 04: detectability and posterior uncertainty
# =============================================================================

def plot_detectability_uncertainty(
    curves: pd.DataFrame,
    dt_values: Sequence[float],
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    candidates = [
        (
            "median_p_detect",
            "04_detectability_median_p_detect",
            "Median state detectability",
        ),
        (
            "median_p_dropout",
            "04_detectability_median_p_dropout",
            "Median state dropout",
        ),
        (
            "median_dx_post_sd",
            "04_uncertainty_median_dx_post_sd",
            r"Median posterior SD($\Delta x$)",
        ),
        (
            "median_dx_post_95_width",
            "04_uncertainty_median_dx_post_95_width",
            r"Median posterior 95% width($\Delta x$)",
        ),
    ]

    rows: List[Dict[str, object]] = []

    for column, stem, ylabel in candidates:
        if column not in curves.columns:
            continue

        d0 = numeric(curves, ["dt", "bin_mid", column])
        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        any_plot = False

        for dt in dt_values:
            d = d0[d0["dt"] == float(dt)].sort_values("bin_mid")
            if d.empty:
                continue
            x = d["bin_mid"].to_numpy(float)
            y = d[column].to_numpy(float)
            ok = np.isfinite(x) & np.isfinite(y)
            if not ok.any():
                continue
            ax.plot(
                x[ok],
                y[ok],
                marker="o",
                linewidth=args.line_width,
                markersize=args.marker_size,
                label=dt_label(dt),
            )
            any_plot = True

        if not any_plot:
            plt.close(fig)
            continue

        ax.set_xlabel(r"Latent abundance, $x^*$")
        ax.set_ylabel(ylabel)
        apply_axis_config(ax, stem)
        style_axes(ax)
        apply_legend(ax, args, title="Lag")
        fig.tight_layout()

        files = save_figure(fig, figures_dir, stem, formats, args)
        rows.extend(
            {
                "figure": name,
                "family": "detectability_uncertainty",
                "metric": column,
                "source_table": "10_binned_dynamics_long",
            }
            for name in files
        )

    return rows


# =============================================================================
# Family 05: weighting sensitivity
# =============================================================================

def plot_weighting_sensitivity(
    weighting: pd.DataFrame,
    dt_values: Sequence[float],
    metrics: Sequence[str],
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    if weighting.empty:
        return []

    require_columns(
        weighting,
        ["estimator", "dt", "bin_mid"],
        "13_weighting_sensitivity_curves_long",
    )
    d0 = numeric(weighting, ["dt", "bin_mid"] + list(metrics))
    estimators = [
        value
        for value in LOO_ESTIMATORS
        if value in set(d0["estimator"].dropna().astype(str))
    ]

    rows: List[Dict[str, object]] = []

    for metric in metrics:
        if metric not in d0.columns:
            continue

        stem = f"05_weighting_sensitivity_{metric}"
        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        any_plot = False

        for dt in dt_values:
            for estimator in estimators:
                d = d0[
                    (d0["dt"] == float(dt))
                    & (d0["estimator"].astype(str) == estimator)
                ].sort_values("bin_mid")
                if d.empty:
                    continue

                x = d["bin_mid"].to_numpy(float)
                y = pd.to_numeric(d[metric], errors="coerce").to_numpy(float)
                ok = np.isfinite(x) & np.isfinite(y)
                if not ok.any():
                    continue

                linestyle = "-" if estimator == "transition_weighted" else "--"
                label = (
                    f"{dt_label(dt)}, "
                    + ("transition-weighted" if estimator == "transition_weighted" else "equal-subject")
                )
                ax.plot(
                    x[ok],
                    y[ok],
                    marker="o",
                    linewidth=args.line_width,
                    markersize=args.marker_size,
                    linestyle=linestyle,
                    label=label,
                )
                any_plot = True

        if not any_plot:
            plt.close(fig)
            continue

        add_metric_baseline(ax, metric)
        ax.set_xlabel(r"Latent abundance, $x^*$")
        ax.set_ylabel(metric_label(metric))
        apply_axis_config(ax, stem)
        style_axes(ax)
        apply_legend(ax, args, title="Lag / estimator")
        fig.tight_layout()

        files = save_figure(fig, figures_dir, stem, formats, args)
        rows.extend(
            {
                "figure": name,
                "family": "weighting_sensitivity",
                "metric": metric,
                "source_table": "13_weighting_sensitivity_curves_long",
            }
            for name in files
        )

    return rows


# =============================================================================
# Family 06: weighting-estimator difference
# =============================================================================

def plot_weighting_difference(
    comparison: pd.DataFrame,
    dt_values: Sequence[float],
    metrics: Sequence[str],
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    if comparison.empty:
        return []

    require_columns(
        comparison,
        ["metric", "dt", "bin_mid", "difference_equal_minus_transition"],
        "14_weighting_sensitivity_comparison_long",
    )

    d0 = numeric(
        comparison,
        ["dt", "bin_mid", "difference_equal_minus_transition"],
    )

    rows: List[Dict[str, object]] = []

    for metric in metrics:
        dm = d0[d0["metric"].astype(str) == metric].copy()
        if dm.empty:
            continue

        stem = f"06_weighting_difference_{metric}"
        fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
        any_plot = False

        for dt in dt_values:
            d = dm[dm["dt"] == float(dt)].sort_values("bin_mid")
            if d.empty:
                continue
            x = d["bin_mid"].to_numpy(float)
            y = d["difference_equal_minus_transition"].to_numpy(float)
            ok = np.isfinite(x) & np.isfinite(y)
            if not ok.any():
                continue
            ax.plot(
                x[ok],
                y[ok],
                marker="o",
                linewidth=args.line_width,
                markersize=args.marker_size,
                label=dt_label(dt),
            )
            any_plot = True

        if not any_plot:
            plt.close(fig)
            continue

        ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
        ax.set_xlabel(r"Latent abundance, $x^*$")
        ax.set_ylabel(
            "Equal-subject − transition-weighted\n" + metric_label(metric)
        )
        apply_axis_config(ax, stem)
        style_axes(ax)
        apply_legend(ax, args, title="Lag")
        fig.tight_layout()

        files = save_figure(fig, figures_dir, stem, formats, args)
        rows.extend(
            {
                "figure": name,
                "family": "weighting_difference",
                "metric": metric,
                "source_table": "14_weighting_sensitivity_comparison_long",
            }
            for name in files
        )

    return rows


# =============================================================================
# Family 07: leave-one-subject-out robustness
# =============================================================================

def plot_loo_robustness(
    loo: pd.DataFrame,
    dt_values: Sequence[float],
    metrics: Sequence[str],
    estimators: Sequence[str],
    figures_dir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    if loo.empty:
        return []

    require_columns(
        loo,
        [
            "estimator",
            "metric",
            "dt",
            "bin_mid",
            "full_value",
            "loo_min",
            "loo_max",
        ],
        "16_leave_one_subject_out_summary",
    )

    d0 = numeric(
        loo,
        ["dt", "bin_mid", "full_value", "loo_min", "loo_max"],
    )

    rows: List[Dict[str, object]] = []

    for estimator in estimators:
        de = d0[d0["estimator"].astype(str) == estimator]
        if de.empty:
            continue

        for metric in metrics:
            dm = de[de["metric"].astype(str) == metric]
            if dm.empty:
                continue

            stem = f"07_loo_robustness_{metric}_{estimator}"
            fig, ax = plt.subplots(figsize=resolve_figure_size(stem))
            any_plot = False

            for dt in dt_values:
                d = dm[dm["dt"] == float(dt)].sort_values("bin_mid")
                if d.empty:
                    continue

                x = d["bin_mid"].to_numpy(float)
                full = d["full_value"].to_numpy(float)
                low = d["loo_min"].to_numpy(float)
                high = d["loo_max"].to_numpy(float)

                valid = np.isfinite(x) & np.isfinite(full)
                if not valid.any():
                    continue

                line = ax.plot(
                    x[valid],
                    full[valid],
                    marker="o",
                    linewidth=args.line_width,
                    markersize=args.marker_size,
                    label=dt_label(dt),
                )[0]

                band_ok = valid & np.isfinite(low) & np.isfinite(high)
                if band_ok.any():
                    ax.fill_between(
                        x[band_ok],
                        low[band_ok],
                        high[band_ok],
                        color=line.get_color(),
                        alpha=args.loo_alpha,
                        linewidth=0,
                    )

                any_plot = True

            if not any_plot:
                plt.close(fig)
                continue

            add_metric_baseline(ax, metric)
            ax.set_xlabel(r"Latent abundance, $x^*$")
            ax.set_ylabel(metric_label(metric))
            apply_axis_config(ax, stem)
            style_axes(ax)
            apply_legend(ax, args, title="Lag")
            fig.tight_layout()

            files = save_figure(fig, figures_dir, stem, formats, args)
            rows.extend(
                {
                    "figure": name,
                    "family": "loo_robustness",
                    "metric": metric,
                    "estimator": estimator,
                    "source_table": "16_leave_one_subject_out_summary",
                }
                for name in files
            )

    return rows


# =============================================================================
# CLI
# =============================================================================

def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Plot ClonoDynamics Step-11 longitudinal fluctuation-dynamics outputs."
        ),
    )

    parser.add_argument(
        "--analysis-dir",
        required=True,
        help="Output directory produced by 11-longitudinal_fluctuation_dynamics.py.",
    )
    parser.add_argument(
        "--figures-dir",
        default="",
        help=(
            "Figure output directory. Default: "
            "<analysis-dir>/figures_longitudinal_fluctuation_dynamics"
        ),
    )
    parser.add_argument(
        "--dt-values",
        default="",
        help="Comma-separated temporal lags. Empty uses every lag in the Step-11 curve table.",
    )

    parser.add_argument(
        "--sensitivity-metrics",
        default="var_dx,msd,mad_dx,mean_dx,median_dx,ppos",
        help="Metrics shown in weighting-sensitivity figures.",
    )
    parser.add_argument(
        "--loo-metrics",
        default="var_dx,msd,mean_dx,ppos",
        help="Metrics shown in leave-one-subject-out figures.",
    )
    parser.add_argument(
        "--loo-estimators",
        default="transition_weighted,equal_subject_weighted",
        help="Estimators shown in leave-one-subject-out figures.",
    )
    parser.add_argument(
        "--no-sensitivity",
        action="store_true",
        help="Skip optional weighting and leave-one-subject-out figures.",
    )

    parser.add_argument(
        "--pdf",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Export PDF figures.",
    )
    parser.add_argument("--png", action="store_true", help="Also export PNG figures.")
    parser.add_argument("--svg", action="store_true", help="Also export SVG figures.")
    parser.add_argument("--dpi", type=int, default=300)

    parser.add_argument("--font-family", default="Arial")
    parser.add_argument("--font-size", type=float, default=8.0)
    parser.add_argument("--axes-width", type=float, default=0.7)
    parser.add_argument("--tick-width", type=float, default=0.7)
    parser.add_argument("--tick-length", type=float, default=2.5)
    parser.add_argument("--line-width", type=float, default=1.1)
    parser.add_argument("--marker-size", type=float, default=2.5)
    parser.add_argument("--ci-alpha", type=float, default=0.14)
    parser.add_argument("--loo-alpha", type=float, default=0.14)
    parser.add_argument("--pad-inches", type=float, default=0.04)
    parser.add_argument(
        "--legend-mode",
        choices=["outside", "inside", "none"],
        default="outside",
    )
    parser.add_argument(
        "--show-ci",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Show Step-11 bootstrap intervals when available.",
    )

    return parser


# =============================================================================
# Main
# =============================================================================

def main() -> int:
    args = build_argparser().parse_args()

    if not (0.0 <= args.ci_alpha <= 1.0):
        raise ValueError("--ci-alpha must be between 0 and 1.")
    if not (0.0 <= args.loo_alpha <= 1.0):
        raise ValueError("--loo-alpha must be between 0 and 1.")

    analysis_dir = Path(args.analysis_dir).expanduser().resolve()
    if not analysis_dir.is_dir():
        raise NotADirectoryError(f"Step-11 analysis directory not found: {analysis_dir}")

    figures_dir = (
        Path(args.figures_dir).expanduser().resolve()
        if args.figures_dir
        else analysis_dir / "figures_longitudinal_fluctuation_dynamics"
    )
    ensure_dir(figures_dir)

    setup_style(args)
    formats = formats_to_run(args)

    curves = load_required_table(analysis_dir, "10_binned_dynamics_long")
    by_dt = load_required_table(analysis_dir, "07_temporal_comparability_by_dt")
    by_dt_bin = load_required_table(
        analysis_dir, "06_temporal_comparability_by_dt_bin"
    )
    subject_availability = load_required_table(
        analysis_dir, "08_subject_availability_by_dt"
    )

    weighting = load_optional_table(
        analysis_dir, "13_weighting_sensitivity_curves_long"
    )
    weighting_difference = load_optional_table(
        analysis_dir, "14_weighting_sensitivity_comparison_long"
    )
    loo = load_optional_table(
        analysis_dir, "16_leave_one_subject_out_summary"
    )
    metadata = load_metadata(analysis_dir)

    validate_primary_curves(curves)
    curves = numeric(curves, ["dt", "bin_id", "bin_mid"])

    available_dt = pd.to_numeric(curves["dt"], errors="coerce").dropna().unique()
    dt_values = parse_dt_values(args.dt_values, available_dt)
    if not dt_values:
        raise ValueError("No requested temporal lags are available.")

    curves = filter_dt(curves, dt_values)
    by_dt = filter_dt(by_dt, dt_values)
    by_dt_bin = filter_dt(by_dt_bin, dt_values)
    subject_availability = filter_dt(subject_availability, dt_values)
    weighting = filter_dt(weighting, dt_values)
    weighting_difference = filter_dt(weighting_difference, dt_values)
    loo = filter_dt(loo, dt_values)

    sensitivity_metrics = parse_csv(args.sensitivity_metrics)
    invalid = [m for m in sensitivity_metrics if m not in SENSITIVITY_METRICS]
    if invalid:
        raise ValueError(
            f"Unsupported sensitivity metrics: {invalid}. "
            f"Use: {', '.join(SENSITIVITY_METRICS)}"
        )

    loo_metrics = parse_csv(args.loo_metrics)
    invalid = [m for m in loo_metrics if m not in LOO_METRICS]
    if invalid:
        raise ValueError(
            f"Unsupported LOO metrics: {invalid}. "
            f"Use: {', '.join(LOO_METRICS)}"
        )

    loo_estimators = parse_csv(args.loo_estimators)
    invalid = [m for m in loo_estimators if m not in LOO_ESTIMATORS]
    if invalid:
        raise ValueError(
            f"Unsupported LOO estimators: {invalid}. "
            f"Use: {', '.join(LOO_ESTIMATORS)}"
        )

    figure_rows: List[Dict[str, object]] = []

    figure_rows.extend(
        plot_multidt_curves(
            curves, dt_values, figures_dir, formats, args
        )
    )
    figure_rows.extend(
        plot_temporal_coverage(
            by_dt, subject_availability, figures_dir, formats, args
        )
    )
    figure_rows.extend(
        plot_shared_bin_comparability(
            by_dt_bin, dt_values, figures_dir, formats, args
        )
    )
    figure_rows.extend(
        plot_detectability_uncertainty(
            curves, dt_values, figures_dir, formats, args
        )
    )

    if not args.no_sensitivity:
        if weighting.empty:
            warnings.warn(
                "13_weighting_sensitivity_curves_long not found; "
                "weighting-sensitivity figures skipped."
            )
        else:
            figure_rows.extend(
                plot_weighting_sensitivity(
                    weighting,
                    dt_values,
                    sensitivity_metrics,
                    figures_dir,
                    formats,
                    args,
                )
            )

        if weighting_difference.empty:
            warnings.warn(
                "14_weighting_sensitivity_comparison_long not found; "
                "weighting-difference figures skipped."
            )
        else:
            figure_rows.extend(
                plot_weighting_difference(
                    weighting_difference,
                    dt_values,
                    sensitivity_metrics,
                    figures_dir,
                    formats,
                    args,
                )
            )

        if loo.empty:
            warnings.warn(
                "16_leave_one_subject_out_summary not found; "
                "LOSO figures skipped."
            )
        else:
            figure_rows.extend(
                plot_loo_robustness(
                    loo,
                    dt_values,
                    loo_metrics,
                    loo_estimators,
                    figures_dir,
                    formats,
                    args,
                )
            )

    manifest_path = figures_dir / "figure_manifest.csv"
    write_manifest(figure_rows, manifest_path)

    print("\n[DONE] Step-11 plotting completed")
    print(f"[ANALYSIS] {analysis_dir}")
    print(f"[FIGURES]  {figures_dir}")
    print(f"[DT]       {dt_values}")
    print(f"[FILES]    {len(figure_rows)} rendered files")

    if metadata:
        print(
            "[PROVENANCE] representation={!r}; conditioning={!r}; mode={!r}".format(
                metadata.get("representation"),
                metadata.get("conditioning"),
                metadata.get("mode"),
            )
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
