#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
12-plot_longitudinal_vs_pseudo_fluctuation_baseline.py
======================================================

Plot-only companion to ClonoDynamics Step 12:

    12-longitudinal_vs_pseudo_fluctuation_baseline.py

Scientific role
---------------
Step 12 compares genuine longitudinal fluctuation magnitude with the
pseudo-longitudinal technical baseline on shared ABSOLUTE latent-abundance
support.

The primary comparison is:

    Var(Delta x_latent | xstar_latent)

for longitudinal TT transitions at one selected lag, normally dt = 1.

The complementary comparison is:

    MSD = E[(Delta x_latent)^2 | xstar_latent].

MAD is retained as a descriptive robust comparison only.

Step 12 preserves the native absolute xstar geometry of the longitudinal and
pseudo datasets. It does not convert abundance to percentiles/ranks, force
common clonotype-level binning across datasets, or extrapolate outside the
support represented by both datasets.

The pseudo reference is generated from arbitrary pseudo-time configurations.
For Var and MSD, each global ordering/reversal equivalence class is represented
once because global reversal changes the sign of dx but leaves xstar, dx^2 and
sample variance unchanged.

Analysis / plotting boundary
----------------------------
This script reads ONLY Step-12 output files. It does not directly reload Step 11,
Step 8 or pseudo Step-4 trajectories and does not:

    - rebuild pseudo directed-pair sufficient statistics;
    - regenerate pseudo-time configurations;
    - recompute the stable pseudo abundance support;
    - interpolate longitudinal or pseudo curves;
    - recompute empirical null distributions;
    - recompute empirical P-values;
    - redefine the cross-dataset abundance geometry;
    - subtract the pseudo baseline before temporal-scaling analysis.

The term "excess" is used only for the descriptive Step-12 quantity:

    longitudinal value - pseudo technical-reference median.

It must not be interpreted as pure biological variance/noise.

Position in the pipeline
------------------------
Step 12 is a cross-dataset comparison:

    Step 11 genuine longitudinal fluctuations
                    \
                     \
                      v
                   Step 12
                      ^
                     /
                    /
    Step 8 pseudo representation assessment
        +
    pseudo Step-4 trajectories

Step 12 does NOT feed Step 13 computationally. Step 13 fits temporal models to
the genuine longitudinal Step-11 fluctuation data; the Step-12 technical
baseline is not subtracted beforehand.

Analysis input
--------------
Required:

    --analysis-dir

pointing to the output directory generated by:

    12-longitudinal_vs_pseudo_fluctuation_baseline.py

Core required Step-12 tables
----------------------------
    07_shared_grid_comparison.csv
        Primary pointwise comparison on shared absolute xstar support. Contains
        longitudinal Var/MSD curves and confidence intervals, pseudo medians and
        95% configuration envelopes, descriptive excess/ratio quantities, and
        the optional fixed-reference MAD comparison.

    08_pseudo_shared_grid_configuration_metrics.csv
        Configuration-level integrated pseudo-null metrics on the Step-12 shared
        grid.

    09_empirical_tests.csv
        Precomputed empirical tests for integrated Var and MSD.

Optional provenance / descriptive tables
----------------------------------------
    01_longitudinal_dt1_native_curve.csv
    05_pseudo_native_envelope.csv
    06_shared_absolute_support_summary.csv
    10_comparison_summary.csv
    11_pseudo_fixed_reference_curve.csv

The fixed pseudo MAD reference is optional in the analysis. The MAD panel is
drawn only when finite fixed-reference MAD values are already present in
`07_shared_grid_comparison.csv`.

Metadata
--------
When present, the plotter reads:

    00_run_config.json
    12_fluctuation_baseline_report.json

for provenance and display labels only.

Generated figures
-----------------
Main composite:

    00_main_longitudinal_vs_pseudo_fluctuation_baseline_ABC

        A  conditional variance: longitudinal versus pseudo technical baseline
        B  MSD: longitudinal versus pseudo technical baseline
        C  empirical pseudo-null distribution of mean conditional variance over
           shared support, with the longitudinal statistic overlaid

Supplementary composite:

    Sx_fluctuation_baseline_diagnostics_ABCD

        A  empirical pseudo-null distribution of mean MSD over shared support
        B  MAD: longitudinal versus fixed pseudo reference, descriptive only
        C  excess conditional variance = longitudinal - pseudo median
        D  excess MSD = longitudinal - pseudo median

Standalone figures:

    01_variance_longitudinal_vs_pseudo
    02_msd_longitudinal_vs_pseudo
    03_variance_integrated_pseudo_null
    04_msd_integrated_pseudo_null
    05_mad_longitudinal_vs_pseudo          [when available]
    06_excess_variance
    07_excess_msd

Non-figure outputs
------------------
Only graphical provenance is written:

    figure_manifest.csv
    plot_config.json

No new inferential/scientific summary table is created by the plotting layer.

Rendering policy
----------------
The 101-point shared grid is an evaluation/interpolation grid created by Step 12,
not a set of 101 independently estimated abundance bins. The longitudinal curve
therefore uses sparse display markers while the full interpolated curve is
retained.

Integrated pseudo-null panels use the already-computed configuration metrics in:

    08_pseudo_shared_grid_configuration_metrics.csv

and the longitudinal statistics/P-values already computed in:

    09_empirical_tests.csv.

Figure customization
--------------------
Edit:

    FIGURE_SIZES_INCHES

for per-figure dimensions in inches, and:

    AXIS_CONFIG

for per-panel:

    xlim
    ylim
    xscale
    yscale
    xtick_step
    ytick_step

All default axis limits are data-driven so that current Step-12 confidence
intervals are not silently clipped. Manuscript-specific ranges can be imposed
later by editing `AXIS_CONFIG`.

Example
-------
python3 ./code/plotting/12-plot_longitudinal_vs_pseudo_fluctuation_baseline.py \
    --analysis-dir \
    ./clonodynamics_longitudinal_vs_pseudo_results/12-longitudinal-vs-pseudo-fluctuation-baseline \
    --figures-dir ./figures/12-longitudinal-vs-pseudo-fluctuation-baseline \
    --formats pdf,png
"""

from __future__ import annotations

import argparse
import json
import sys
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
import pandas as pd


SCRIPT_VERSION = "v1-step12-public-plotter-2026-08-25"


# =============================================================================
# Figure sizes and axes
# =============================================================================

FIGURE_SIZES_INCHES: Dict[str, Tuple[float, float]] = {
    "00_main_longitudinal_vs_pseudo_fluctuation_baseline_ABC": (9.6, 2.6),
    "Sx_fluctuation_baseline_diagnostics_ABCD": (7.2, 6.0),

    "01_variance_longitudinal_vs_pseudo": (3.2, 2.4),
    "02_msd_longitudinal_vs_pseudo": (3.2, 2.4),
    "03_variance_integrated_pseudo_null": (3.2, 2.4),
    "04_msd_integrated_pseudo_null": (3.2, 2.4),
    "05_mad_longitudinal_vs_pseudo": (3.2, 2.4),
    "06_excess_variance": (3.2, 2.4),
    "07_excess_msd": (3.2, 2.4),
}


def _axis_cfg(
    xlim=None,
    ylim=None,
    xscale=None,
    yscale=None,
    xtick_step=None,
    ytick_step=None,
) -> Dict[str, object]:
    return {
        "xlim": xlim,
        "ylim": ylim,
        "xscale": xscale,
        "yscale": yscale,
        "xtick_step": xtick_step,
        "ytick_step": ytick_step,
    }


# Default limits remain data-driven. This avoids clipping genuine Step-12
# confidence intervals; manuscript-specific ranges can be set here later.
AXIS_CONFIG: Dict[str, Dict[str, object]] = {
    # Main composite
    "MainA": _axis_cfg(),
    "MainB": _axis_cfg(),
    "MainC": _axis_cfg(),

    # Supplementary composite
    "SxA": _axis_cfg(),
    "SxB": _axis_cfg(),
    "SxC": _axis_cfg(),
    "SxD": _axis_cfg(),

    # Standalone panels
    "01_variance_longitudinal_vs_pseudo": _axis_cfg(),
    "02_msd_longitudinal_vs_pseudo": _axis_cfg(),
    "03_variance_integrated_pseudo_null": _axis_cfg(),
    "04_msd_integrated_pseudo_null": _axis_cfg(),
    "05_mad_longitudinal_vs_pseudo": _axis_cfg(),
    "06_excess_variance": _axis_cfg(),
    "07_excess_msd": _axis_cfg(),
}


PLOT_STYLE_DEFAULTS = {
    "dpi": 300,
    "font_size": 8.0,
    "line_width": 1.15,
    "marker_size": 2.8,
    "ci_alpha": 0.14,
    "pseudo_alpha": 0.16,
}


CORE_REQUIRED_FILES = {
    "shared_grid": "07_shared_grid_comparison.csv",
    "pseudo_metrics": "08_pseudo_shared_grid_configuration_metrics.csv",
    "empirical_tests": "09_empirical_tests.csv",
}

OPTIONAL_FILES = {
    "longitudinal_native": "01_longitudinal_dt1_native_curve.csv",
    "pseudo_envelope": "05_pseudo_native_envelope.csv",
    "support": "06_shared_absolute_support_summary.csv",
    "summary": "10_comparison_summary.csv",
    "pseudo_fixed": "11_pseudo_fixed_reference_curve.csv",
}


# =============================================================================
# I/O and validation
# =============================================================================

def eprint(*args, **kwargs) -> None:
    print(*args, file=sys.stderr, **kwargs)


def read_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError("Required Step-12 output not found: {}".format(path))
    df = pd.read_csv(path)
    if df.empty:
        raise ValueError("Required Step-12 output is empty: {}".format(path))
    return df


def read_optional(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def load_tables(analysis_dir: Path) -> Dict[str, pd.DataFrame]:
    tables = {
        key: read_required(analysis_dir / filename)
        for key, filename in CORE_REQUIRED_FILES.items()
    }
    tables.update(
        {
            key: read_optional(analysis_dir / filename)
            for key, filename in OPTIONAL_FILES.items()
        }
    )
    return tables


def load_json_optional(path: Path) -> Dict[str, object]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def load_metadata(analysis_dir: Path) -> Dict[str, object]:
    config = load_json_optional(analysis_dir / "00_run_config.json")
    report = load_json_optional(analysis_dir / "12_fluctuation_baseline_report.json")
    return {
        "config": config,
        "report": report,
    }


def require_columns(
    df: pd.DataFrame,
    columns: Sequence[str],
    label: str,
) -> None:
    missing = [column for column in columns if column not in df.columns]
    if missing:
        raise ValueError(
            "{} missing required columns {}. Available: {}".format(
                label, missing, list(df.columns)
            )
        )


def numeric_array(series: pd.Series) -> np.ndarray:
    return pd.to_numeric(series, errors="coerce").to_numpy(dtype=float)


def parse_formats(text: str) -> List[str]:
    values = [value.strip().lower() for value in str(text).split(",") if value.strip()]
    allowed = {"pdf", "png", "svg"}
    invalid = [value for value in values if value not in allowed]
    if invalid:
        raise ValueError(
            "Unsupported figure format(s): {}. Use pdf,png,svg.".format(invalid)
        )

    out: List[str] = []
    for value in values:
        if value not in out:
            out.append(value)

    if not out:
        raise ValueError("At least one figure format is required.")
    return out


def resolve_longitudinal_dt(
    tables: Dict[str, pd.DataFrame],
    metadata: Dict[str, object],
) -> Optional[float]:
    config = metadata.get("config", {})
    if isinstance(config, dict) and config.get("longitudinal_dt") is not None:
        try:
            return float(config["longitudinal_dt"])
        except Exception:
            pass

    summary = tables.get("summary", pd.DataFrame())
    if not summary.empty and "longitudinal_dt" in summary.columns:
        values = pd.to_numeric(summary["longitudinal_dt"], errors="coerce").dropna()
        if not values.empty:
            return float(values.iloc[0])

    native = tables.get("longitudinal_native", pd.DataFrame())
    if not native.empty and "dt" in native.columns:
        values = pd.to_numeric(native["dt"], errors="coerce").dropna()
        if not values.empty:
            return float(values.iloc[0])

    return None


def dt_text(value: Optional[float]) -> str:
    if value is None or not np.isfinite(value):
        return "selected lag"
    value = float(value)
    if value.is_integer():
        return r"$\Delta t={}$".format(int(value))
    return r"$\Delta t={:g}$".format(value)


def validate_step12_schema(tables: Dict[str, pd.DataFrame]) -> None:
    require_columns(
        tables["shared_grid"],
        [
            "xstar",
            "longitudinal_var_dx",
            "longitudinal_var_dx_ci_low",
            "longitudinal_var_dx_ci_high",
            "pseudo_var_dx_median",
            "pseudo_var_dx_q025",
            "pseudo_var_dx_q975",
            "excess_var_dx",
            "longitudinal_msd",
            "longitudinal_msd_ci_low",
            "longitudinal_msd_ci_high",
            "pseudo_msd_median",
            "pseudo_msd_q025",
            "pseudo_msd_q975",
            "excess_msd",
        ],
        "07_shared_grid_comparison.csv",
    )

    require_columns(
        tables["pseudo_metrics"],
        [
            "mean_var_dx_shared",
            "mean_msd_shared",
            "valid_for_integrated_test",
        ],
        "08_pseudo_shared_grid_configuration_metrics.csv",
    )

    require_columns(
        tables["empirical_tests"],
        [
            "metric",
            "longitudinal_mean_over_shared_support",
            "pseudo_median",
            "empirical_p_upper",
        ],
        "09_empirical_tests.csv",
    )


# =============================================================================
# Style helpers
# =============================================================================

def setup_style(font_size: float) -> str:
    try:
        from matplotlib import font_manager

        font_manager.findfont("Arial", fallback_to_default=False)
        family = "Arial"
    except Exception:
        family = "DejaVu Sans"
        eprint("[WARN] Arial not found; using DejaVu Sans.")

    tick_font = max(float(font_size) - 1.0, 5.0)

    plt.rcParams.update(
        {
            "font.family": family,
            "font.size": float(font_size),
            "axes.labelsize": float(font_size),
            "axes.titlesize": float(font_size),
            "xtick.labelsize": tick_font,
            "ytick.labelsize": tick_font,
            "legend.fontsize": tick_font,
            "legend.title_fontsize": tick_font,
            "axes.linewidth": 0.7,
            "xtick.major.width": 0.7,
            "ytick.major.width": 0.7,
            "xtick.major.size": 2.5,
            "ytick.major.size": 2.5,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    return family


def style_axes(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(direction="out")


def reference_horizontal(ax: plt.Axes, value: float) -> None:
    ax.axhline(
        value,
        linewidth=0.8,
        linestyle="--",
        color=ax.spines["bottom"].get_edgecolor(),
    )


def add_panel_label(ax: plt.Axes, label: str, font_size: float) -> None:
    ax.text(
        -0.14,
        1.08,
        label,
        transform=ax.transAxes,
        fontsize=max(float(font_size) + 1.0, 8.0),
        fontweight="bold",
        va="top",
        ha="left",
    )


def annotation_box(ax: plt.Axes, text: str) -> None:
    ax.text(
        0.03,
        0.97,
        text,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=max(float(plt.rcParams["font.size"]) - 0.5, 5.0),
    )


def apply_axis_config(ax: plt.Axes, key: str) -> None:
    cfg = AXIS_CONFIG.get(key, {})

    if cfg.get("xscale"):
        ax.set_xscale(str(cfg["xscale"]))
    if cfg.get("yscale"):
        ax.set_yscale(str(cfg["yscale"]))

    if cfg.get("xlim") is not None:
        lo, hi = cfg["xlim"]
        old_lo, old_hi = ax.get_xlim()
        ax.set_xlim(old_lo if lo is None else lo, old_hi if hi is None else hi)

    if cfg.get("ylim") is not None:
        lo, hi = cfg["ylim"]
        old_lo, old_hi = ax.get_ylim()
        ax.set_ylim(old_lo if lo is None else lo, old_hi if hi is None else hi)

    if cfg.get("xtick_step") is not None:
        ax.xaxis.set_major_locator(MultipleLocator(float(cfg["xtick_step"])))
    if cfg.get("ytick_step") is not None:
        ax.yaxis.set_major_locator(MultipleLocator(float(cfg["ytick_step"])))


def apply_legend(ax: plt.Axes, mode: str) -> None:
    handles, labels = ax.get_legend_handles_labels()
    if not handles or mode == "none":
        return

    if mode == "outside":
        ax.legend(
            handles,
            labels,
            frameon=False,
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            borderaxespad=0.0,
        )
    else:
        ax.legend(handles, labels, frameon=False, loc="best")


def save_figure(
    fig: plt.Figure,
    outdir: Path,
    stem: str,
    formats: Sequence[str],
    dpi: int,
) -> List[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []

    for fmt in formats:
        path = outdir / "{}.{}".format(stem, fmt)
        kwargs = {
            "bbox_inches": "tight",
            "pad_inches": 0.04,
        }
        if fmt == "png":
            kwargs["dpi"] = int(dpi)
        fig.savefig(path, **kwargs)
        written.append(path)
        print("[SAVED] {}".format(path))

    plt.close(fig)
    return written


# =============================================================================
# Step-12 plotting primitives
# =============================================================================

def empirical_row(tests: pd.DataFrame, metric: str) -> pd.Series:
    d = tests.loc[tests["metric"].astype(str) == metric]
    if len(d) != 1:
        raise ValueError(
            "Expected one empirical-test row for {!r}; found {}".format(
                metric, len(d)
            )
        )
    return d.iloc[0]


def p_label(value: float) -> str:
    if not np.isfinite(value):
        return r"$P_{\mathrm{emp}}$ = NA"
    if value < 0.001:
        return r"$P_{\mathrm{emp}}<0.001$"
    return r"$P_{\mathrm{emp}}={:.3f}$".format(value)


def draw_metric_curve(
    ax: plt.Axes,
    shared: pd.DataFrame,
    metric: str,
    axis_key: str,
    longitudinal_dt: Optional[float],
    args: argparse.Namespace,
) -> None:
    prefix = "var_dx" if metric == "var_dx" else "msd"

    long_col = "longitudinal_{}".format(prefix)
    long_lo = "longitudinal_{}_ci_low".format(prefix)
    long_hi = "longitudinal_{}_ci_high".format(prefix)

    pseudo_col = "pseudo_{}_median".format(prefix)
    pseudo_lo = "pseudo_{}_q025".format(prefix)
    pseudo_hi = "pseudo_{}_q975".format(prefix)

    d = shared.sort_values("xstar").copy()

    x = numeric_array(d["xstar"])
    yl = numeric_array(d[long_col])
    yllo = numeric_array(d[long_lo])
    ylhi = numeric_array(d[long_hi])

    yp = numeric_array(d[pseudo_col])
    yplo = numeric_array(d[pseudo_lo])
    yphi = numeric_array(d[pseudo_hi])

    valid_l = np.isfinite(x) & np.isfinite(yl)
    valid_lb = valid_l & np.isfinite(yllo) & np.isfinite(ylhi)

    valid_p = np.isfinite(x) & np.isfinite(yp)
    valid_pb = valid_p & np.isfinite(yplo) & np.isfinite(yphi)

    line_long = ax.plot(
        x[valid_l],
        yl[valid_l],
        linewidth=args.line_width,
        label="Longitudinal, {}".format(dt_text(longitudinal_dt)),
    )[0]

    if args.show_ci and valid_lb.any():
        ax.fill_between(
            x[valid_lb],
            yllo[valid_lb],
            ylhi[valid_lb],
            color=line_long.get_color(),
            alpha=args.ci_alpha,
            linewidth=0,
        )

    line_pseudo = ax.plot(
        x[valid_p],
        yp[valid_p],
        linewidth=args.line_width,
        linestyle="--",
        label="Pseudo technical baseline",
    )[0]

    if args.show_ci and valid_pb.any():
        ax.fill_between(
            x[valid_pb],
            yplo[valid_pb],
            yphi[valid_pb],
            color=line_pseudo.get_color(),
            alpha=args.pseudo_alpha,
            linewidth=0,
        )

    # Sparse markers emphasize that the shared grid is an interpolation/evaluation
    # grid generated by Step 12 rather than a set of independently estimated bins.
    idx = np.flatnonzero(valid_l)
    if idx.size:
        step = max(1, int(np.ceil(idx.size / float(args.max_display_markers))))
        take = idx[::step]
        ax.plot(
            x[take],
            yl[take],
            linestyle="none",
            marker="o",
            markersize=args.marker_size,
            color=line_long.get_color(),
        )

    ax.set_xlabel(r"Transition-centred latent abundance, $x^\star$")
    ax.set_ylabel(
        r"$\mathrm{Var}(\Delta x\mid x^\star)$"
        if metric == "var_dx"
        else r"$\mathrm{MSD}(\Delta x\mid x^\star)$"
    )

    style_axes(ax)
    apply_axis_config(ax, axis_key)
    apply_legend(ax, args.legend_mode)


def draw_integrated_null(
    ax: plt.Axes,
    pseudo_metrics: pd.DataFrame,
    tests: pd.DataFrame,
    metric: str,
    axis_key: str,
) -> None:
    pseudo_col = (
        "mean_var_dx_shared"
        if metric == "var_dx"
        else "mean_msd_shared"
    )

    valid_flag = pseudo_metrics["valid_for_integrated_test"].astype(bool)
    values = pd.to_numeric(
        pseudo_metrics.loc[valid_flag, pseudo_col],
        errors="coerce",
    ).to_numpy(dtype=float)
    values = values[np.isfinite(values)]

    if values.size < 2:
        raise ValueError(
            "Too few valid pseudo configurations for metric {}".format(metric)
        )

    row = empirical_row(tests, metric)
    longitudinal = float(row["longitudinal_mean_over_shared_support"])
    pseudo_median = float(row["pseudo_median"])
    pval = float(row["empirical_p_upper"])

    parts = ax.violinplot(
        [values],
        positions=[0.0],
        vert=False,
        widths=0.50,
        showmeans=False,
        showmedians=False,
        showextrema=False,
    )
    for body in parts["bodies"]:
        body.set_alpha(0.30)
        body.set_linewidth(0.7)

    ax.plot(
        pseudo_median,
        0.0,
        marker="|",
        markersize=9,
        markeredgewidth=1.2,
        linestyle="none",
        label="Pseudo median",
    )
    ax.plot(
        longitudinal,
        0.0,
        marker="D",
        markersize=4.5,
        linestyle="none",
        label="Longitudinal",
        zorder=5,
    )

    ax.set_ylim(-0.42, 0.42)
    ax.set_yticks([])
    ax.set_xlabel(
        r"Mean $\mathrm{Var}(\Delta x\mid x^\star)$ over shared support"
        if metric == "var_dx"
        else r"Mean MSD over shared support"
    )

    style_axes(ax)
    ax.spines["left"].set_visible(False)
    apply_axis_config(ax, axis_key)

    annotation_box(
        ax,
        "Longitudinal = {:.3f}\nPseudo median = {:.3f}\n{}\nPseudo configurations = {:,}".format(
            longitudinal,
            pseudo_median,
            p_label(pval),
            int(values.size),
        ),
    )
    apply_legend(ax, "inside")


def mad_available(shared: pd.DataFrame) -> bool:
    required = {
        "xstar",
        "longitudinal_mad_dx",
        "pseudo_mad_dx_fixed_reference",
    }
    if not required.issubset(shared.columns):
        return False

    long_values = pd.to_numeric(
        shared["longitudinal_mad_dx"], errors="coerce"
    ).to_numpy(dtype=float)
    pseudo_values = pd.to_numeric(
        shared["pseudo_mad_dx_fixed_reference"], errors="coerce"
    ).to_numpy(dtype=float)

    return bool(np.isfinite(long_values).any() and np.isfinite(pseudo_values).any())


def draw_mad_curve(
    ax: plt.Axes,
    shared: pd.DataFrame,
    axis_key: str,
    longitudinal_dt: Optional[float],
    args: argparse.Namespace,
) -> bool:
    if not mad_available(shared):
        ax.axis("off")
        ax.text(
            0.5,
            0.5,
            "Fixed pseudo MAD reference\nnot available",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        return False

    d = shared.sort_values("xstar")
    x = numeric_array(d["xstar"])
    y_long = numeric_array(d["longitudinal_mad_dx"])
    y_pseudo = numeric_array(d["pseudo_mad_dx_fixed_reference"])

    valid_long = np.isfinite(x) & np.isfinite(y_long)
    valid_pseudo = np.isfinite(x) & np.isfinite(y_pseudo)

    ax.plot(
        x[valid_long],
        y_long[valid_long],
        linewidth=args.line_width,
        marker="o",
        markersize=args.marker_size,
        label="Longitudinal, {}".format(dt_text(longitudinal_dt)),
    )
    ax.plot(
        x[valid_pseudo],
        y_pseudo[valid_pseudo],
        linewidth=args.line_width,
        linestyle="--",
        label="Pseudo fixed reference",
    )

    ax.set_xlabel(r"Transition-centred latent abundance, $x^\star$")
    ax.set_ylabel(r"MAD($\Delta x\mid x^\star$)")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    apply_legend(ax, args.legend_mode)
    return True


def draw_excess_curve(
    ax: plt.Axes,
    shared: pd.DataFrame,
    metric: str,
    axis_key: str,
    args: argparse.Namespace,
) -> None:
    column = "excess_var_dx" if metric == "var_dx" else "excess_msd"

    d = shared.sort_values("xstar")
    x = numeric_array(d["xstar"])
    y = numeric_array(d[column])
    valid = np.isfinite(x) & np.isfinite(y)

    ax.plot(
        x[valid],
        y[valid],
        linewidth=args.line_width,
        marker="o",
        markersize=args.marker_size,
    )
    reference_horizontal(ax, 0.0)

    ax.set_xlabel(r"Transition-centred latent abundance, $x^\star$")
    ax.set_ylabel(
        "Longitudinal - pseudo median\n"
        + (
            r"Var($\Delta x\mid x^\star$)"
            if metric == "var_dx"
            else r"MSD($\Delta x\mid x^\star$)"
        )
    )

    style_axes(ax)
    apply_axis_config(ax, axis_key)


# =============================================================================
# Composite figures
# =============================================================================

def plot_main(
    tables: Dict[str, pd.DataFrame],
    longitudinal_dt: Optional[float],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    stem = "00_main_longitudinal_vs_pseudo_fluctuation_baseline_ABC"

    fig, axes = plt.subplots(
        1,
        3,
        figsize=FIGURE_SIZES_INCHES[stem],
    )

    draw_metric_curve(
        axes[0],
        tables["shared_grid"],
        "var_dx",
        "MainA",
        longitudinal_dt,
        args,
    )
    draw_metric_curve(
        axes[1],
        tables["shared_grid"],
        "msd",
        "MainB",
        longitudinal_dt,
        args,
    )
    draw_integrated_null(
        axes[2],
        tables["pseudo_metrics"],
        tables["empirical_tests"],
        "var_dx",
        "MainC",
    )

    for ax, label in zip(axes, "ABC"):
        add_panel_label(ax, label, args.font_size)

    fig.subplots_adjust(wspace=0.42)

    return save_figure(
        fig,
        outdir,
        stem,
        formats,
        args.dpi,
    )


def plot_supplementary(
    tables: Dict[str, pd.DataFrame],
    longitudinal_dt: Optional[float],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    stem = "Sx_fluctuation_baseline_diagnostics_ABCD"

    fig, axes = plt.subplots(
        2,
        2,
        figsize=FIGURE_SIZES_INCHES[stem],
    )
    axA, axB, axC, axD = axes.ravel()

    draw_integrated_null(
        axA,
        tables["pseudo_metrics"],
        tables["empirical_tests"],
        "msd",
        "SxA",
    )
    draw_mad_curve(
        axB,
        tables["shared_grid"],
        "SxB",
        longitudinal_dt,
        args,
    )
    draw_excess_curve(
        axC,
        tables["shared_grid"],
        "var_dx",
        "SxC",
        args,
    )
    draw_excess_curve(
        axD,
        tables["shared_grid"],
        "msd",
        "SxD",
        args,
    )

    for ax, label in zip(axes.ravel(), "ABCD"):
        add_panel_label(ax, label, args.font_size)

    fig.subplots_adjust(wspace=0.42, hspace=0.46)

    return save_figure(
        fig,
        outdir,
        stem,
        formats,
        args.dpi,
    )


# =============================================================================
# Standalone figures
# =============================================================================

def plot_standalones(
    tables: Dict[str, pd.DataFrame],
    longitudinal_dt: Optional[float],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    written: List[Path] = []

    for stem, metric in [
        ("01_variance_longitudinal_vs_pseudo", "var_dx"),
        ("02_msd_longitudinal_vs_pseudo", "msd"),
    ]:
        fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
        draw_metric_curve(
            ax,
            tables["shared_grid"],
            metric,
            stem,
            longitudinal_dt,
            args,
        )
        written.extend(save_figure(fig, outdir, stem, formats, args.dpi))

    for stem, metric in [
        ("03_variance_integrated_pseudo_null", "var_dx"),
        ("04_msd_integrated_pseudo_null", "msd"),
    ]:
        fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
        draw_integrated_null(
            ax,
            tables["pseudo_metrics"],
            tables["empirical_tests"],
            metric,
            stem,
        )
        written.extend(save_figure(fig, outdir, stem, formats, args.dpi))

    if mad_available(tables["shared_grid"]):
        stem = "05_mad_longitudinal_vs_pseudo"
        fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
        draw_mad_curve(
            ax,
            tables["shared_grid"],
            stem,
            longitudinal_dt,
            args,
        )
        written.extend(save_figure(fig, outdir, stem, formats, args.dpi))
    else:
        warnings.warn(
            "No finite fixed pseudo MAD reference in 07_shared_grid_comparison.csv; "
            "standalone MAD panel skipped."
        )

    for stem, metric in [
        ("06_excess_variance", "var_dx"),
        ("07_excess_msd", "msd"),
    ]:
        fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])
        draw_excess_curve(
            ax,
            tables["shared_grid"],
            metric,
            stem,
            args,
        )
        written.extend(save_figure(fig, outdir, stem, formats, args.dpi))

    return written


# =============================================================================
# CLI and main
# =============================================================================

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Plot ClonoDynamics Step-12 longitudinal-versus-pseudo fluctuation "
            "baseline outputs."
        ),
    )

    parser.add_argument(
        "--analysis-dir",
        required=True,
        type=Path,
        help=(
            "Output directory produced by "
            "12-longitudinal_vs_pseudo_fluctuation_baseline.py."
        ),
    )
    parser.add_argument(
        "--figures-dir",
        type=Path,
        default=None,
        help=(
            "Figure output directory. Default: "
            "<analysis-dir>/figures_longitudinal_vs_pseudo_fluctuation_baseline"
        ),
    )
    parser.add_argument(
        "--figure-set",
        choices=["all", "main", "supplementary", "standalone"],
        default="all",
    )
    parser.add_argument(
        "--formats",
        default="pdf,png",
        help="Comma-separated formats from: pdf,png,svg.",
    )

    parser.add_argument("--dpi", type=int, default=PLOT_STYLE_DEFAULTS["dpi"])
    parser.add_argument(
        "--font-size",
        type=float,
        default=PLOT_STYLE_DEFAULTS["font_size"],
    )
    parser.add_argument(
        "--line-width",
        type=float,
        default=PLOT_STYLE_DEFAULTS["line_width"],
    )
    parser.add_argument(
        "--marker-size",
        type=float,
        default=PLOT_STYLE_DEFAULTS["marker_size"],
    )
    parser.add_argument(
        "--ci-alpha",
        type=float,
        default=PLOT_STYLE_DEFAULTS["ci_alpha"],
    )
    parser.add_argument(
        "--pseudo-alpha",
        type=float,
        default=PLOT_STYLE_DEFAULTS["pseudo_alpha"],
    )
    parser.add_argument(
        "--legend-mode",
        choices=["outside", "inside", "none"],
        default="inside",
    )
    parser.add_argument(
        "--show-ci",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument(
        "--max-display-markers",
        type=int,
        default=12,
        help=(
            "Maximum approximate number of longitudinal markers shown on each "
            "shared-grid curve. Display-only; the full Step-12 curve is retained."
        ),
    )

    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    if not 0.0 <= args.ci_alpha <= 1.0:
        raise ValueError("--ci-alpha must be between 0 and 1.")
    if not 0.0 <= args.pseudo_alpha <= 1.0:
        raise ValueError("--pseudo-alpha must be between 0 and 1.")
    if args.max_display_markers < 1:
        raise ValueError("--max-display-markers must be >= 1.")

    analysis_dir = args.analysis_dir.expanduser().resolve()
    if not analysis_dir.is_dir():
        raise NotADirectoryError(
            "Step-12 analysis directory not found: {}".format(analysis_dir)
        )

    figures_dir = (
        args.figures_dir.expanduser().resolve()
        if args.figures_dir is not None
        else analysis_dir / "figures_longitudinal_vs_pseudo_fluctuation_baseline"
    )
    figures_dir.mkdir(parents=True, exist_ok=True)

    formats = parse_formats(args.formats)
    font_family_used = setup_style(args.font_size)

    tables = load_tables(analysis_dir)
    metadata = load_metadata(analysis_dir)
    validate_step12_schema(tables)

    longitudinal_dt = resolve_longitudinal_dt(tables, metadata)

    written: List[Path] = []

    if args.figure_set in {"all", "main"}:
        written.extend(
            plot_main(
                tables,
                longitudinal_dt,
                figures_dir,
                formats,
                args,
            )
        )

    if args.figure_set in {"all", "supplementary"}:
        written.extend(
            plot_supplementary(
                tables,
                longitudinal_dt,
                figures_dir,
                formats,
                args,
            )
        )

    if args.figure_set in {"all", "standalone"}:
        written.extend(
            plot_standalones(
                tables,
                longitudinal_dt,
                figures_dir,
                formats,
                args,
            )
        )

    pd.DataFrame(
        {
            "file": [path.name for path in written],
            "figure": [path.stem for path in written],
            "format": [path.suffix.lstrip(".") for path in written],
        }
    ).to_csv(figures_dir / "figure_manifest.csv", index=False)

    config = metadata.get("config", {})
    summary = tables.get("summary", pd.DataFrame())

    plot_config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "analysis_source": "12-longitudinal_vs_pseudo_fluctuation_baseline.py",
        "analysis_dir": str(analysis_dir),
        "figures_dir": str(figures_dir),
        "figure_set": args.figure_set,
        "formats": formats,
        "font_family_used": font_family_used,
        "font_size": float(args.font_size),
        "line_width": float(args.line_width),
        "marker_size": float(args.marker_size),
        "ci_alpha": float(args.ci_alpha),
        "pseudo_alpha": float(args.pseudo_alpha),
        "legend_mode": args.legend_mode,
        "show_ci": bool(args.show_ci),
        "max_display_markers": int(args.max_display_markers),
        "longitudinal_dt": longitudinal_dt,
        "primary_metric": "var_dx",
        "complementary_metric": "msd",
        "mad_role": "descriptive_fixed_pseudo_reference_only",
        "mad_panel_available": bool(mad_available(tables["shared_grid"])),
        "figure_sizes_inches": FIGURE_SIZES_INCHES,
        "axis_config": AXIS_CONFIG,
        "analysis_recomputed": False,
        "shared_support_recomputed": False,
        "pseudo_configurations_recomputed": False,
        "empirical_tests_recomputed": False,
        "pseudo_baseline_subtracted_before_step13": False,
        "source_analysis_script_version": (
            config.get("script_version")
            if isinstance(config, dict)
            else None
        ),
        "comparison_summary_available": bool(not summary.empty),
    }

    (figures_dir / "plot_config.json").write_text(
        json.dumps(plot_config, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print("[DONE] Step-12 plotting complete")
    print("[INFO] Analysis directory: {}".format(analysis_dir))
    print("[INFO] Figures directory: {}".format(figures_dir))
    print("[INFO] Longitudinal lag: {}".format(longitudinal_dt))
    print("[INFO] MAD fixed reference available: {}".format(
        mad_available(tables["shared_grid"])
    ))
    print("[INFO] {} rendered files".format(len(written)))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
