#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
9-plot_replicate_decoupled_forward_drift.py
===========================================

Plot-only companion to ClonoDynamics Step 9:

    9-replicate_decoupled_forward_drift.py

Scientific role
---------------
Step 9 estimates genuine longitudinal abundance-dependent forward displacement
using replicate-decoupled AB/BA conditioning. The primary estimator is:

    cross_combined

the equal-weight bin-wise combination of the reciprocal cross-fitted folds:

    AB:
        condition on replicate A at t0;
        calculate displacement from replicate B.

    BA:
        condition on replicate B at t0;
        calculate displacement from replicate A.

This plotting script visualizes the genuine-longitudinal Step-9 results only.
It does not read pseudo-longitudinal data and does not perform the Step-10
technical-null comparison.

The plotter is analysis-free. It does not:

    - read Step-4 trajectories;
    - rebuild specialized Step-9 transitions;
    - redefine observability or TT inclusion;
    - redefine abundance bins;
    - recompute subject bootstrap confidence intervals;
    - recompute AB/BA fold concordance;
    - recompute subject-level or leave-one-subject-out estimates;
    - compare the genuine curve with the pseudo technical null.

Position in the pipeline
------------------------
Relevant branch:

    Step 4
    latent trajectory construction
        |
        v
    Step 9
    replicate-decoupled genuine longitudinal forward drift
        |
        v
    Step 10
    longitudinal-versus-pseudo forward-drift comparison

Step 9 reads Step-4 trajectories directly because replicate-specific posterior
summaries are required for AB/BA decoupling.

Analysis input
--------------
Required:

    --analysis-dir

pointing to the output directory generated by:

    9-replicate_decoupled_forward_drift.py

Required Step-9 tables
----------------------
    forward_drift_by_bin.csv
        Cohort-level binned curves, including the primary `cross_combined`
        estimator and diagnostic comparators.

    forward_drift_by_fold.csv
        Separate AB/BA, same-replicate and other fold-level curves.

    forward_drift_matched_same_vs_cross.csv
        Matched same-replicate versus replicate-decoupled comparisons.

    forward_drift_reliability_by_bin.csv
        Technical-reliability summaries by fold and abundance bin.

    forward_drift_subject_by_bin.csv
        Subject-specific `cross_combined` curves.

    forward_drift_loso_by_bin.csv
        Leave-one-subject-out `cross_combined` curves.

    forward_drift_fold_concordance.csv
        Precomputed AB/BA concordance summary.

Optional Step-9 table
---------------------
    forward_drift_sensitivity_by_fold.csv
        Posterior-median and observed-frequency cross-fit sensitivity curves.
        The posterior-mean versus posterior-median panel is skipped if the
        required sensitivity representations are unavailable.

Other Step-9 analysis outputs
-----------------------------
The analysis may also write:

    forward_drift_bin_edges.csv
    forward_drift_global_summary.csv
    forward_drift_subject_bin_sufficient.parquet
    forward_longitudinal_transitions_wide.parquet
    forward_longitudinal_report.json
    00_run_config.json

These remain analysis-layer products and are not reconstructed here.

Generated figures
-----------------
Main composite:

    00_main_replicate_decoupled_forward_drift_ABCD

        A  primary `cross_combined` genuine forward-drift curve
        B  reciprocal AB versus BA folds
        C  matched same-replicate versus replicate-decoupled conditioning
        D  posterior-mean versus posterior-median cross-fit sensitivity

Supplementary composite:

    Sx_forward_drift_robustness

        A  reciprocal replicate-decoupled AB versus BA folds
        B  matched same-replicate versus replicate-decoupled conditioning
        C  subject-specific replicate-decoupled curves with the cohort estimate
        D  leave-one-subject-out curves with the full-cohort estimate

The technical-reliability diagnostics remain available as standalone figures
07_conditioning_posterior_sd, 08_four_positive_fraction and
09_minimum_count_four.

Standalone figures:

    01_primary_cross_combined_forward_drift
    02_AB_vs_BA_concordance
    03_same_vs_replicate_decoupled
    04_posterior_mean_vs_median_sensitivity
    05_subject_level_forward_drift
    06_LOSO_forward_drift
    07_conditioning_posterior_sd
    08_four_positive_fraction
    09_minimum_count_four

Non-figure outputs
------------------
Only graphical provenance is written:

    figure_manifest.csv
    plot_config.json

No new inferential summary table is created by the plotting layer.

Rendering policy
----------------
A display-only minimum support can be applied to subject-specific curves with:

    --subject-min-n

The default is 20 transitions in BOTH AB and BA for a displayed subject/bin.
This affects only rendering and never changes Step-9 analysis outputs.

Figure customization
--------------------
Edit:

    FIGURE_SIZES_INCHES

for per-figure dimensions in inches, and:

    AXIS_CONFIG

for per-panel:

    xlim
    ylim
    xscale
    yscale
    xtick_step
    ytick_step

Composite-panel keys are independent from standalone figure keys.

Example
-------
python3 ./code/plotting/9-plot_replicate_decoupled_forward_drift.py \
    --analysis-dir \
    ./dataset_longitudinal_clonodynamics_results/longitudinal/9-replicate_decoupled_forward_drift \
    --figures-dir ./figures/9-replicate-decoupled-forward-drift \
    --formats pdf,png
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
import pandas as pd


SCRIPT_VERSION = "v2-step9-public-plotter-S7-2026-08-27"
PRIMARY_REPRESENTATION = "cross_combined"


# =============================================================================
# Figure configuration
# =============================================================================

FIGURE_SIZES_INCHES: Dict[str, Tuple[float, float]] = {
    "00_main_replicate_decoupled_forward_drift_ABCD": (7.2, 6.0),
    "Sx_forward_drift_robustness": (7.2, 6.0),

    "01_primary_cross_combined_forward_drift": (3.2, 2.4),
    "02_AB_vs_BA_concordance": (3.2, 2.4),
    "03_same_vs_replicate_decoupled": (3.2, 2.4),
    "04_posterior_mean_vs_median_sensitivity": (3.2, 2.4),
    "05_subject_level_forward_drift": (3.2, 2.4),
    "06_LOSO_forward_drift": (3.2, 2.4),
    "07_conditioning_posterior_sd": (3.2, 2.4),
    "08_four_positive_fraction": (3.2, 2.4),
    "09_minimum_count_four": (3.2, 2.4),
}


def _axis_cfg(
    xlim=None,
    ylim=None,
    xscale=None,
    yscale=None,
    xtick_step=None,
    ytick_step=None,
) -> Dict[str, object]:
    return {
        "xlim": xlim,
        "ylim": ylim,
        "xscale": xscale,
        "yscale": yscale,
        "xtick_step": xtick_step,
        "ytick_step": ytick_step,
    }


AXIS_CONFIG = {
    # Main composite
    "MainA": _axis_cfg(),
    "MainB": _axis_cfg(),
    "MainC": _axis_cfg(),
    "MainD": _axis_cfg(),

    # Supplementary composite
    "SxA": _axis_cfg(),
    "SxB": _axis_cfg(),
    "SxC": _axis_cfg(),
    "SxD": _axis_cfg(),

    # Standalone panels
    "01_primary_cross_combined_forward_drift": _axis_cfg(),
    "02_AB_vs_BA_concordance": _axis_cfg(),
    "03_same_vs_replicate_decoupled": _axis_cfg(),
    "04_posterior_mean_vs_median_sensitivity": _axis_cfg(),
    "05_subject_level_forward_drift": _axis_cfg(),
    "06_LOSO_forward_drift": _axis_cfg(),
    "07_conditioning_posterior_sd": _axis_cfg(),
    "08_four_positive_fraction": _axis_cfg(ylim=(0.0, 1.02), ytick_step=0.2),
    "09_minimum_count_four": _axis_cfg(),
}


PLOT_STYLE_DEFAULTS = {
    "dpi": 300,
    "font_size": 8.0,
    "line_width": 1.15,
    "marker_size": 2.8,
    "ci_alpha": 0.16,
    "panel_label_size": 10.0,
}


REQUIRED_FILES = {
    "by_bin": "forward_drift_by_bin.csv",
    "by_fold": "forward_drift_by_fold.csv",
    "matched": "forward_drift_matched_same_vs_cross.csv",
    "reliability": "forward_drift_reliability_by_bin.csv",
    "subjects": "forward_drift_subject_by_bin.csv",
    "loso": "forward_drift_loso_by_bin.csv",
    "fold_concordance": "forward_drift_fold_concordance.csv",
}

OPTIONAL_FILES = {
    "sensitivity": "forward_drift_sensitivity_by_fold.csv",
}


# =============================================================================
# General helpers
# =============================================================================

def eprint(*args, **kwargs) -> None:
    print(*args, file=sys.stderr, **kwargs)


def setup_style(font_size: float) -> str:
    try:
        from matplotlib import font_manager
        font_manager.findfont("Arial", fallback_to_default=False)
        family = "Arial"
    except Exception:
        family = "DejaVu Sans"
        eprint("[WARN] Arial not found; using DejaVu Sans.")

    tick_font = max(float(font_size) - 1.0, 5.0)
    plt.rcParams.update(
        {
            "font.family": family,
            "font.size": float(font_size),
            "axes.labelsize": float(font_size),
            "axes.titlesize": float(font_size),
            "xtick.labelsize": tick_font,
            "ytick.labelsize": tick_font,
            "legend.fontsize": tick_font,
            "legend.title_fontsize": tick_font,
            "axes.linewidth": 0.7,
            "xtick.major.width": 0.7,
            "ytick.major.width": 0.7,
            "xtick.major.size": 2.5,
            "ytick.major.size": 2.5,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    return family


def style_axes(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(direction="out")


def apply_axis_config(ax: plt.Axes, key: str) -> None:
    cfg = AXIS_CONFIG.get(key, {})
    if cfg.get("xscale"):
        ax.set_xscale(str(cfg["xscale"]))
    if cfg.get("yscale"):
        ax.set_yscale(str(cfg["yscale"]))
    if cfg.get("xlim") is not None:
        ax.set_xlim(*cfg["xlim"])
    if cfg.get("ylim") is not None:
        ax.set_ylim(*cfg["ylim"])
    if cfg.get("xtick_step") is not None:
        ax.xaxis.set_major_locator(MultipleLocator(float(cfg["xtick_step"])))
    if cfg.get("ytick_step") is not None:
        ax.yaxis.set_major_locator(MultipleLocator(float(cfg["ytick_step"])))


def add_panel_label(ax: plt.Axes, label: str, font_size: float) -> None:
    ax.text(
        -0.14,
        1.08,
        label,
        transform=ax.transAxes,
        fontsize=max(float(font_size) + 1.0, 8.0),
        fontweight="bold",
        va="top",
        ha="left",
    )


def annotation_box(ax: plt.Axes, text: str) -> None:
    ax.text(
        0.03,
        0.97,
        text,
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontsize=max(float(plt.rcParams["font.size"]) - 1.0, 6.0),
        bbox=dict(facecolor="white", edgecolor="0.82", linewidth=0.45, alpha=0.82),
    )


def read_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError("Required Step-9 table not found: {}".format(path))
    df = pd.read_csv(path)
    if df.empty:
        raise ValueError("Required Step-9 table is empty: {}".format(path))
    return df


def read_optional(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def load_tables(analysis_dir: Path) -> Dict[str, pd.DataFrame]:
    tables = {
        key: read_required(analysis_dir / filename)
        for key, filename in REQUIRED_FILES.items()
    }
    tables.update(
        {
            key: read_optional(analysis_dir / filename)
            for key, filename in OPTIONAL_FILES.items()
        }
    )
    return tables


def require_columns(df: pd.DataFrame, columns: Sequence[str], label: str) -> None:
    missing = [c for c in columns if c not in df.columns]
    if missing:
        raise ValueError(
            "{} missing required columns {}. Available: {}".format(
                label, missing, list(df.columns)
            )
        )


def finite_xy(df: pd.DataFrame, x_col: str, y_col: str) -> Tuple[np.ndarray, np.ndarray]:
    x = pd.to_numeric(df[x_col], errors="coerce").to_numpy(float)
    y = pd.to_numeric(df[y_col], errors="coerce").to_numpy(float)
    keep = np.isfinite(x) & np.isfinite(y)
    return x[keep], y[keep]


def parse_formats(text: str) -> List[str]:
    values = [v.strip().lower() for v in str(text).split(",") if v.strip()]
    allowed = {"pdf", "png", "svg"}
    invalid = [v for v in values if v not in allowed]
    if invalid:
        raise ValueError("Unsupported formats: {}".format(invalid))
    out: List[str] = []
    for value in values:
        if value not in out:
            out.append(value)
    if not out:
        raise ValueError("At least one output format is required.")
    return out


def save_figure(
    fig: plt.Figure,
    outdir: Path,
    stem: str,
    formats: Sequence[str],
    dpi: int,
) -> List[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for fmt in formats:
        path = outdir / "{}.{}".format(stem, fmt)
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.04}
        if fmt == "png":
            kwargs["dpi"] = int(dpi)
        fig.savefig(path, **kwargs)
        written.append(path)
        print("[SAVED] {}".format(path))
    plt.close(fig)
    return written


def cohort_curve(by_bin: pd.DataFrame, representation: str = PRIMARY_REPRESENTATION) -> pd.DataFrame:
    require_columns(by_bin, ["representation", "x_center", "mean_dx"], "forward_drift_by_bin.csv")
    d = by_bin.loc[by_bin["representation"].astype(str) == representation].copy()
    if d.empty:
        raise ValueError("{} not found in forward_drift_by_bin.csv".format(representation))
    return d.sort_values("x_center")


def fold_curve(by_fold: pd.DataFrame, representation: str) -> pd.DataFrame:
    require_columns(by_fold, ["representation", "x_center", "mean_dx"], "forward_drift_by_fold.csv")
    d = by_fold.loc[by_fold["representation"].astype(str) == representation].copy()
    if d.empty:
        raise ValueError("{} not found in forward_drift_by_fold.csv".format(representation))
    return d.sort_values("x_center")


def combined_fold_curve(
    table: pd.DataFrame,
    representations: Sequence[str],
) -> pd.DataFrame:
    require_columns(table, ["representation", "bin", "x_center", "mean_dx"], "fold sensitivity table")
    d = table.loc[table["representation"].astype(str).isin(list(representations))].copy()
    if d.empty:
        return pd.DataFrame()
    return (
        d.groupby(["bin", "x_center"], as_index=False)["mean_dx"]
        .mean()
        .sort_values("x_center")
    )


# =============================================================================
# Plot primitives
# =============================================================================

def draw_primary_curve(
    ax: plt.Axes,
    by_bin: pd.DataFrame,
    line_width: float,
    marker_size: float,
    ci_alpha: float,
    axis_key: str,
) -> None:
    d = cohort_curve(by_bin)
    x, y = finite_xy(d, "x_center", "mean_dx")
    line = ax.plot(
        x, y, marker="o", markersize=marker_size,
        linewidth=line_width, label="cross_combined"
    )[0]

    if {"mean_dx_ci025", "mean_dx_ci975"}.issubset(d.columns):
        low = pd.to_numeric(d["mean_dx_ci025"], errors="coerce").to_numpy(float)
        high = pd.to_numeric(d["mean_dx_ci975"], errors="coerce").to_numpy(float)
        xx = pd.to_numeric(d["x_center"], errors="coerce").to_numpy(float)
        ok = np.isfinite(xx) & np.isfinite(low) & np.isfinite(high)
        if ok.any():
            ax.fill_between(
                xx[ok], low[ok], high[ok],
                color=line.get_color(), alpha=ci_alpha, linewidth=0
            )

    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)


def draw_ab_ba(
    ax: plt.Axes,
    by_fold: pd.DataFrame,
    concordance: pd.DataFrame,
    line_width: float,
    marker_size: float,
    axis_key: str,
) -> None:
    for representation, label in [("cross_AB", "AB"), ("cross_BA", "BA")]:
        d = fold_curve(by_fold, representation)
        x, y = finite_xy(d, "x_center", "mean_dx")
        ax.plot(
            x, y, marker="o", markersize=marker_size,
            linewidth=line_width, label=label
        )

    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    ax.legend(frameon=False)

    if not concordance.empty:
        row = concordance.iloc[0]
        r = pd.to_numeric(pd.Series([row.get("pearson_r_AB_BA")]), errors="coerce").iloc[0]
        n = pd.to_numeric(pd.Series([row.get("n_matched_bins")]), errors="coerce").iloc[0]
        if np.isfinite(r):
            annotation_box(
                ax,
                "AB/BA Pearson r = {:.3f}\nmatched bins = {}".format(
                    float(r), int(n) if np.isfinite(n) else "NA"
                ),
            )


def matched_same_cross(matched: pd.DataFrame) -> pd.DataFrame:
    require_columns(
        matched,
        ["bin", "x_center", "mean_dx_same", "mean_dx_cross"],
        "forward_drift_matched_same_vs_cross.csv",
    )
    return (
        matched.groupby(["bin", "x_center"], as_index=False)
        .agg(
            mean_dx_same=("mean_dx_same", "mean"),
            mean_dx_cross=("mean_dx_cross", "mean"),
        )
        .sort_values("x_center")
    )


def draw_same_cross(
    ax: plt.Axes,
    matched: pd.DataFrame,
    line_width: float,
    marker_size: float,
    axis_key: str,
) -> None:
    d = matched_same_cross(matched)
    ax.plot(
        d["x_center"], d["mean_dx_same"],
        marker="o", markersize=marker_size,
        linewidth=line_width, label="Same-replicate"
    )
    ax.plot(
        d["x_center"], d["mean_dx_cross"],
        marker="o", markersize=marker_size,
        linewidth=line_width, label="Replicate-decoupled"
    )
    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    ax.legend(frameon=False)


def draw_mean_median_sensitivity(
    ax: plt.Axes,
    by_bin: pd.DataFrame,
    sensitivity: pd.DataFrame,
    line_width: float,
    marker_size: float,
    axis_key: str,
) -> bool:
    primary = cohort_curve(by_bin)
    median = combined_fold_curve(
        sensitivity,
        ["cross_median_AB", "cross_median_BA"],
    )
    if median.empty:
        ax.axis("off")
        ax.text(
            0.5, 0.5,
            "Posterior-median sensitivity\nnot available",
            ha="center", va="center", transform=ax.transAxes
        )
        return False

    ax.plot(
        primary["x_center"], primary["mean_dx"],
        marker="o", markersize=marker_size,
        linewidth=line_width, label="Posterior-mean outcome"
    )
    ax.plot(
        median["x_center"], median["mean_dx"],
        marker="o", markersize=marker_size,
        linewidth=line_width, label="Posterior-median outcome"
    )
    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    ax.legend(frameon=False)
    return True


def draw_subjects(
    ax: plt.Axes,
    subjects: pd.DataFrame,
    by_bin: pd.DataFrame,
    subject_min_n: int,
    line_width: float,
    marker_size: float,
    axis_key: str,
) -> None:
    require_columns(
        subjects,
        ["subject", "representation", "x_center", "mean_dx", "n_AB", "n_BA"],
        "forward_drift_subject_by_bin.csv",
    )
    d = subjects.loc[subjects["representation"].astype(str) == PRIMARY_REPRESENTATION].copy()
    d["n_AB"] = pd.to_numeric(d["n_AB"], errors="coerce")
    d["n_BA"] = pd.to_numeric(d["n_BA"], errors="coerce")
    if subject_min_n > 0:
        d = d.loc[(d["n_AB"] >= subject_min_n) & (d["n_BA"] >= subject_min_n)].copy()

    subjects_present = sorted(d["subject"].dropna().unique().tolist(), key=lambda x: str(x))
    first = True
    for subject in subjects_present:
        s = d.loc[d["subject"] == subject].sort_values("x_center")
        x, y = finite_xy(s, "x_center", "mean_dx")
        if x.size == 0:
            continue
        ax.plot(
            x, y,
            linewidth=max(line_width * 0.65, 0.5),
            marker="o",
            markersize=max(marker_size * 0.55, 1.0),
            alpha=0.5,
            label="Individual subjects" if first else "_nolegend_",
        )
        first = False

    cohort = cohort_curve(by_bin)
    x, y = finite_xy(cohort, "x_center", "mean_dx")
    ax.plot(x, y, linewidth=max(line_width * 1.4, 1.2), color="0.1", label="Cohort")

    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    annotation_box(ax, "Displayed subjects = {}".format(len(subjects_present)))
    ax.legend(frameon=False)


def draw_loso(
    ax: plt.Axes,
    loso: pd.DataFrame,
    by_bin: pd.DataFrame,
    line_width: float,
    axis_key: str,
) -> None:
    require_columns(
        loso,
        ["omitted_subject", "representation", "x_center", "mean_dx"],
        "forward_drift_loso_by_bin.csv",
    )
    d = loso.loc[loso["representation"].astype(str) == PRIMARY_REPRESENTATION].copy()
    omitted = sorted(d["omitted_subject"].dropna().unique().tolist(), key=lambda x: str(x))
    first = True
    for subject in omitted:
        s = d.loc[d["omitted_subject"] == subject].sort_values("x_center")
        x, y = finite_xy(s, "x_center", "mean_dx")
        if x.size == 0:
            continue
        ax.plot(
            x, y,
            linewidth=max(line_width * 0.6, 0.45),
            alpha=0.45,
            color="0.55",
            label="LOSO curves" if first else "_nolegend_",
        )
        first = False

    cohort = cohort_curve(by_bin)
    x, y = finite_xy(cohort, "x_center", "mean_dx")
    ax.plot(x, y, linewidth=max(line_width * 1.4, 1.2), color="0.1", label="Full cohort")
    ax.axhline(0.0, linewidth=0.8, linestyle="--", color="0.35")
    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(r"Mean latent displacement")
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    annotation_box(ax, "LOSO profiles = {}".format(len(omitted)))
    ax.legend(frameon=False)


def draw_reliability(
    ax: plt.Axes,
    reliability: pd.DataFrame,
    metric: str,
    ylabel: str,
    axis_key: str,
    line_width: float,
    marker_size: float,
) -> bool:
    require_columns(reliability, ["fold", "x_center"], "forward_drift_reliability_by_bin.csv")
    if metric not in reliability.columns:
        ax.axis("off")
        ax.text(0.5, 0.5, "{}\nnot available".format(metric), ha="center", va="center", transform=ax.transAxes)
        return False

    any_line = False
    for fold in ("AB", "BA"):
        d = reliability.loc[reliability["fold"].astype(str) == fold].sort_values("x_center")
        if d.empty:
            continue
        x = pd.to_numeric(d["x_center"], errors="coerce").to_numpy(float)
        y = pd.to_numeric(d[metric], errors="coerce").to_numpy(float)
        ok = np.isfinite(x) & np.isfinite(y)
        if not ok.any():
            continue
        ax.plot(
            x[ok], y[ok],
            marker="o", markersize=marker_size,
            linewidth=line_width, label=fold
        )
        any_line = True

    if not any_line:
        ax.axis("off")
        return False

    ax.set_xlabel(r"Initial latent abundance, $x_0$")
    ax.set_ylabel(ylabel)
    style_axes(ax)
    apply_axis_config(ax, axis_key)
    ax.legend(frameon=False)
    return True


# =============================================================================
# Figure builders
# =============================================================================

def plot_main(
    tables: Dict[str, pd.DataFrame],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    fig, axes = plt.subplots(
        2, 2,
        figsize=FIGURE_SIZES_INCHES["00_main_replicate_decoupled_forward_drift_ABCD"],
    )
    axA, axB, axC, axD = axes.ravel()

    draw_primary_curve(
        axA, tables["by_bin"], args.line_width, args.marker_size,
        args.ci_alpha, "MainA"
    )
    draw_ab_ba(
        axB, tables["by_fold"], tables["fold_concordance"],
        args.line_width, args.marker_size, "MainB"
    )
    draw_same_cross(
        axC, tables["matched"], args.line_width, args.marker_size, "MainC"
    )
    draw_mean_median_sensitivity(
        axD, tables["by_bin"], tables["sensitivity"],
        args.line_width, args.marker_size, "MainD"
    )

    for ax, label in zip(axes.ravel(), ["A", "B", "C", "D"]):
        add_panel_label(ax, label, args.font_size)

    fig.subplots_adjust(wspace=0.42, hspace=0.42)
    return save_figure(
        fig, outdir,
        "00_main_replicate_decoupled_forward_drift_ABCD",
        formats, args.dpi,
    )


def plot_supplementary(
    tables: Dict[str, pd.DataFrame],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    """
    Manuscript supplementary robustness composite.

    A: reciprocal AB/BA replicate-decoupled folds
    B: matched same-replicate versus replicate-decoupled conditioning
    C: subject-specific replicate-decoupled curves plus cohort estimate
    D: leave-one-subject-out curves plus full-cohort estimate

    No analysis is recomputed here; every panel is drawn from Step-9 output
    tables already loaded by this plotter.
    """
    fig, axes = plt.subplots(
        2, 2,
        figsize=FIGURE_SIZES_INCHES["Sx_forward_drift_robustness"],
    )
    axA, axB, axC, axD = axes.ravel()

    draw_ab_ba(
        axA,
        tables["by_fold"],
        tables["fold_concordance"],
        args.line_width,
        args.marker_size,
        "SxA",
    )
    draw_same_cross(
        axB,
        tables["matched"],
        args.line_width,
        args.marker_size,
        "SxB",
    )
    draw_subjects(
        axC,
        tables["subjects"],
        tables["by_bin"],
        args.subject_min_n,
        args.line_width,
        args.marker_size,
        "SxC",
    )
    draw_loso(
        axD,
        tables["loso"],
        tables["by_bin"],
        args.line_width,
        "SxD",
    )

    for ax, label in zip(axes.ravel(), ["A", "B", "C", "D"]):
        add_panel_label(ax, label, args.font_size)

    fig.subplots_adjust(wspace=0.42, hspace=0.42)
    return save_figure(
        fig, outdir, "Sx_forward_drift_robustness", formats, args.dpi
    )


def plot_standalones(
    tables: Dict[str, pd.DataFrame],
    outdir: Path,
    formats: Sequence[str],
    args: argparse.Namespace,
) -> List[Path]:
    written: List[Path] = []

    specs = [
        ("01_primary_cross_combined_forward_drift", "primary"),
        ("02_AB_vs_BA_concordance", "abba"),
        ("03_same_vs_replicate_decoupled", "samecross"),
        ("04_posterior_mean_vs_median_sensitivity", "sensitivity"),
        ("05_subject_level_forward_drift", "subjects"),
        ("06_LOSO_forward_drift", "loso"),
        ("07_conditioning_posterior_sd", "rel_sd"),
        ("08_four_positive_fraction", "rel_four"),
        ("09_minimum_count_four", "rel_count"),
    ]

    for stem, kind in specs:
        fig, ax = plt.subplots(figsize=FIGURE_SIZES_INCHES[stem])

        if kind == "primary":
            draw_primary_curve(
                ax, tables["by_bin"], args.line_width, args.marker_size,
                args.ci_alpha, stem
            )
        elif kind == "abba":
            draw_ab_ba(
                ax, tables["by_fold"], tables["fold_concordance"],
                args.line_width, args.marker_size, stem
            )
        elif kind == "samecross":
            draw_same_cross(
                ax, tables["matched"], args.line_width, args.marker_size, stem
            )
        elif kind == "sensitivity":
            draw_mean_median_sensitivity(
                ax, tables["by_bin"], tables["sensitivity"],
                args.line_width, args.marker_size, stem
            )
        elif kind == "subjects":
            draw_subjects(
                ax, tables["subjects"], tables["by_bin"], args.subject_min_n,
                args.line_width, args.marker_size, stem
            )
        elif kind == "loso":
            draw_loso(
                ax, tables["loso"], tables["by_bin"], args.line_width, stem
            )
        elif kind == "rel_sd":
            draw_reliability(
                ax, tables["reliability"], "median_cond_sd",
                "Median conditioning posterior SD", stem,
                args.line_width, args.marker_size
            )
        elif kind == "rel_four":
            draw_reliability(
                ax, tables["reliability"], "fraction_four_positive",
                "Fraction four-positive", stem,
                args.line_width, args.marker_size
            )
        elif kind == "rel_count":
            draw_reliability(
                ax, tables["reliability"], "median_min_count_four",
                "Median minimum count", stem,
                args.line_width, args.marker_size
            )

        written.extend(save_figure(fig, outdir, stem, formats, args.dpi))

    return written


# =============================================================================
# CLI
# =============================================================================

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Plot ClonoDynamics Step-9 replicate-decoupled forward-drift outputs.",
    )
    parser.add_argument(
        "--analysis-dir",
        required=True,
        type=Path,
        help="Output directory produced by 9-replicate_decoupled_forward_drift.py.",
    )
    parser.add_argument(
        "--figures-dir",
        type=Path,
        default=None,
        help=(
            "Figure output directory. Default: "
            "<analysis-dir>/figures_replicate_decoupled_forward_drift"
        ),
    )
    parser.add_argument(
        "--figure-set",
        choices=["all", "main", "supplementary", "standalone"],
        default="all",
    )
    parser.add_argument("--formats", default="pdf,png")
    parser.add_argument("--dpi", type=int, default=PLOT_STYLE_DEFAULTS["dpi"])
    parser.add_argument("--font-size", type=float, default=PLOT_STYLE_DEFAULTS["font_size"])
    parser.add_argument("--line-width", type=float, default=PLOT_STYLE_DEFAULTS["line_width"])
    parser.add_argument("--marker-size", type=float, default=PLOT_STYLE_DEFAULTS["marker_size"])
    parser.add_argument("--ci-alpha", type=float, default=PLOT_STYLE_DEFAULTS["ci_alpha"])
    parser.add_argument(
        "--subject-min-n",
        type=int,
        default=20,
        help="Display-only minimum n required in BOTH AB and BA for a subject/bin.",
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    analysis_dir = args.analysis_dir.expanduser().resolve()
    if not analysis_dir.is_dir():
        raise NotADirectoryError(analysis_dir)

    figures_dir = (
        args.figures_dir.expanduser().resolve()
        if args.figures_dir is not None
        else analysis_dir / "figures_replicate_decoupled_forward_drift"
    )
    figures_dir.mkdir(parents=True, exist_ok=True)

    formats = parse_formats(args.formats)
    font_used = setup_style(args.font_size)
    tables = load_tables(analysis_dir)

    written: List[Path] = []

    if args.figure_set in {"all", "main"}:
        written.extend(plot_main(tables, figures_dir, formats, args))

    if args.figure_set in {"all", "supplementary"}:
        written.extend(plot_supplementary(tables, figures_dir, formats, args))

    if args.figure_set in {"all", "standalone"}:
        written.extend(plot_standalones(tables, figures_dir, formats, args))

    manifest = pd.DataFrame(
        {
            "file": [p.name for p in written],
            "figure": [p.stem for p in written],
            "format": [p.suffix.lstrip(".") for p in written],
        }
    )
    manifest.to_csv(figures_dir / "figure_manifest.csv", index=False)

    config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "analysis_source": "9-replicate_decoupled_forward_drift.py",
        "analysis_dir": str(analysis_dir),
        "figures_dir": str(figures_dir),
        "figure_set": args.figure_set,
        "formats": formats,
        "dpi": int(args.dpi),
        "font_size": float(args.font_size),
        "font_family_used": font_used,
        "line_width": float(args.line_width),
        "marker_size": float(args.marker_size),
        "ci_alpha": float(args.ci_alpha),
        "subject_min_n_display_only": int(args.subject_min_n),
        "primary_representation": PRIMARY_REPRESENTATION,
        "figure_sizes_inches": FIGURE_SIZES_INCHES,
        "axis_config": AXIS_CONFIG,
        "analysis_recomputed": False,
    }
    (figures_dir / "plot_config.json").write_text(
        json.dumps(config, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print("[DONE] Step-9 plotting complete")
    print("[INFO] Analysis: {}".format(analysis_dir))
    print("[INFO] Figures: {}".format(figures_dir))
    print("[INFO] {} rendered files".format(len(written)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
