#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
10-longitudinal_vs_pseudo_forward_drift.py
===========================================

Comparison of genuine longitudinal replicate-decoupled forward drift with the
pseudo-longitudinal technical null for ClonoDynamics.

Overview
--------
This script implements Step 10 of the ClonoDynamics pipeline.

It compares the genuine longitudinal forward-drift profile estimated in Step 9
with the pseudo-longitudinal technical-null distribution generated in Step 7.

The primary estimand is

    E[Delta x_latent | x0]

with replicate-decoupled initial-state conditioning.

For both genuine longitudinal and pseudo-longitudinal analyses, the primary
representation is:

    cross_combined,

the equal-weight bin-wise average of the reciprocal AB and BA cross-fitted
estimators.

The comparison is performed on the ABSOLUTE latent log-frequency scale.

The script deliberately does not:

    - convert abundance to percentiles or ranks;
    - impose common bin edges across genuine and pseudo datasets;
    - re-bin clonotype-level observations;
    - extrapolate either curve outside its observed abundance support.

Instead, each dataset retains its native abundance bins. The already-estimated
curves are interpolated only within the absolute-abundance interval represented
by BOTH datasets.

Within that shared support, the genuine longitudinal profile is compared with
the empirical pseudo order/reverse null using slope, centered drift magnitude
and mean-offset statistics.

Longitudinal AB/BA fold concordance, subject-specific forward-drift profiles and
leave-one-subject-out profiles are propagated as robustness diagnostics.


Position in the ClonoDynamics pipeline
--------------------------------------
The relevant public workflow is:

    Step 4
    4-latent_trajectory_construction.py
                |
                +-------------------------------+
                |                               |
                v                               v

    Step 7                              Step 9
    7-pseudo_longitudinal_              9-replicate_decoupled_
    conditioning_benchmark.py           forward_drift.py
                |                               |
                | pseudo technical null         | genuine longitudinal
                | ordering distribution         | cross_combined drift
                |                               |
                +---------------+---------------+
                                |
                                v

    Step 10
    10-longitudinal_vs_pseudo_forward_drift.py

        native genuine curve
                +
        pseudo order/reverse null
                |
                v
        shared absolute-abundance support
                |
                v
        empirical longitudinal-versus-null tests


Step 8 (`8-pseudo_longitudinal_representation_assessment.py`) provides the
representation-level technical assessment used elsewhere in the framework but
is not a direct file input to this script.


Primary scientific question
---------------------------
Step 10 asks:

    "Does the abundance-dependent forward-drift structure observed in the
     genuine longitudinal cohort exceed the structure expected under the
     pseudo-longitudinal technical null?"

The comparison is therefore between:

    genuine biological longitudinal structure

and:

    technical-null structure generated by replicate measurement,
    pseudo-time assignment and conditioning geometry.


Primary representation
----------------------
The default representation is:

    cross_combined.

It can be changed with:

    --representation

but the intended ClonoDynamics primary analysis uses the same replicate-
decoupled `cross_combined` estimator in both genuine and pseudo datasets.


Inputs
------
Two analysis directories are required.


1. --longitudinal-dir
---------------------
This must be the output directory generated by Step 9:

    9-replicate_decoupled_forward_drift.py

and is expected to contain:

    forward_drift_by_bin.csv
    forward_drift_by_fold.csv
    forward_drift_fold_concordance.csv
    forward_drift_subject_by_bin.csv
    forward_drift_loso_by_bin.csv.


2. --pseudo-benchmark-dir
-------------------------
This must be the Step-7 pseudo-longitudinal benchmark directory:

    7-pseudo_longitudinal_conditioning_benchmark.py

or directly its:

    03_ordering_robustness/

subdirectory.

The ordering-robustness directory must contain:

    pseudo_reverse_pair_envelope.csv
    pseudo_reverse_pair_curves.csv.

The following file is recognized as an optional manifest/cross-check input:

    pseudo_reverse_pair_metrics.csv.


Absolute-abundance comparison principle
---------------------------------------
Let the native genuine longitudinal curve be defined at abundance-bin centers:

    x_H,1, ..., x_H,m

and the native pseudo curve at:

    x_P,1, ..., x_P,n.

The two datasets retain these native binning schemes.

No rank transformation is applied and no percentile normalization is applied.

No common bin edges are imposed before curve estimation.


Shared absolute support
-----------------------
Let:

    H_min = min(x_H)
    H_max = max(x_H)

and:

    P_min = min(x_P)
    P_max = max(x_P).

The shared absolute-abundance support is:

    x_min_shared = max(H_min, P_min)

    x_max_shared = min(H_max, P_max).

The comparison is valid only if:

    x_max_shared > x_min_shared.

If the two native supports do not overlap, the script stops.


Shared comparison grid
----------------------
Within the shared support, the script constructs a regular grid:

    x_g,  g = 1, ..., G

where:

    G = --n-grid-points

and the default is:

    G = 101.

The grid spans:

    [x_min_shared, x_max_shared].


Curve-level interpolation
-------------------------
The already-estimated native curves are linearly interpolated onto the shared
grid.

For the genuine longitudinal curve:

    mu_H(x_g)

is obtained by linear interpolation of the Step-9 `cross_combined` binned
mean-drift estimates.

The associated subject-bootstrap confidence limits are interpolated separately:

    CI_H,0.025(x_g)
    CI_H,0.975(x_g).

For the pseudo benchmark:

    mu_P,median(x_g)

is obtained by interpolating the median pseudo envelope.

The pseudo 95% envelope is interpolated as:

    Q_P,0.025(x_g)
    Q_P,0.975(x_g).

Interpolation is performed only inside the native support of each curve.

There is NO extrapolation and no clonotype-level re-binning in Step 10.


Pointwise longitudinal-minus-pseudo difference
----------------------------------------------
At each shared grid point:

    Delta_mu(x_g)
        = mu_H(x_g) - mu_P,median(x_g).

The output also records whether the genuine longitudinal mean-drift estimate
lies outside the pseudo 95% envelope:

    longitudinal_outside_pseudo_95(x_g) = True

when:

    mu_H(x_g) < Q_P,0.025(x_g)

or:

    mu_H(x_g) > Q_P,0.975(x_g).


Curve-level summary metrics
---------------------------
For a curve evaluated at shared-grid coordinates x_g with values y_g, define:

    y_bar = mean_g(y_g)

and:

    y_g^c = y_g - y_bar.


1. Mean curve offset

    mean_dx = mean_g(y_g).


2. Linear slope

The script fits:

    y_g = a + b*x_g

and reports:

    slope = b.


3. Centered mean absolute drift

    centered_mean_abs_drift
        = mean_g |y_g - y_bar|.


4. Centered RMS drift

    centered_rms_drift
        = sqrt[mean_g (y_g - y_bar)^2].


Pseudo empirical null
---------------------
For each pseudo:

    reverse_pair_id,

the corresponding pseudo `cross_combined` curve is interpolated independently
onto the same Step-10 shared grid.

The four curve-level metrics are then recalculated:

    mean_dx
    slope
    centered_mean_abs_drift
    centered_rms_drift.

Thus, the Step-10 pseudo-null distribution is defined specifically on the
absolute abundance range shared with the genuine longitudinal data.


Empirical null summaries
------------------------
For each pseudo metric distribution the script reports:

    n
    mean
    standard deviation
    0.5th percentile
    2.5th percentile
    median
    97.5th percentile
    99.5th percentile.


Empirical P-values
------------------
Finite-sample empirical P-values use a +1 correction.


Lower-tail test:

    p_lower
        = [1 + sum_j I(T_j <= T_obs)] / (N + 1).


Upper-tail test:

    p_upper
        = [1 + sum_j I(T_j >= T_obs)] / (N + 1).


Two-sided test about the pseudo median:

    m_P = median_j(T_j)

    d_obs = |T_obs - m_P|

    d_j = |T_j - m_P|

    p_two-sided
        = [1 + sum_j I(d_j >= d_obs)] / (N + 1).


Prespecified empirical tests
----------------------------
The script performs four comparisons.


1. Slope

Alternative:

    genuine longitudinal slope is more negative than the pseudo null.

Tail:

    lower.


2. Centered mean absolute drift

Alternative:

    genuine longitudinal centered mean-absolute drift exceeds the pseudo null.

Tail:

    upper.


3. Centered RMS drift

Alternative:

    genuine longitudinal centered RMS drift exceeds the pseudo null.

Tail:

    upper.


4. Mean drift offset

Alternative:

    genuine longitudinal mean offset differs from the pseudo-null median.

Tail:

    two-sided about the pseudo median.


Longitudinal robustness diagnostics
-----------------------------------
The script carries forward three Step-9 robustness outputs.

AB/BA fold concordance
~~~~~~~~~~~~~~~~~~~~~~
`forward_drift_fold_concordance.csv` is propagated directly.

Subject-level curves
~~~~~~~~~~~~~~~~~~~~
`forward_drift_subject_by_bin.csv` is filtered to the selected representation.

Leave-one-subject-out curves
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`forward_drift_loso_by_bin.csv` is filtered to the selected representation.

These diagnostics are retained separately from the empirical pseudo-null tests.


Outputs
-------
The Step-10 output directory contains:


00_run_config.json

    Run configuration, input directories, representation, shared-grid size,
    conditioning/displacement definitions and normalization/binning policy.


00_input_manifest.csv

    Manifest of expected input files and their availability.


01_native_forward_drift_curves.csv

    Native genuine and pseudo curves before interpolation onto shared support.


02_shared_support_grid.csv

    Shared-grid comparison containing:

        x
        longitudinal_mean_dx
        longitudinal_ci025
        longitudinal_ci975
        pseudo_median_dx
        pseudo_q025
        pseudo_q975
        longitudinal_minus_pseudo
        longitudinal_outside_pseudo_95.


03_pseudo_overlap_null_metrics.csv

    One row per pseudo reverse-pair curve, with metrics recalculated on the
    shared absolute-abundance support.


04_empirical_tests.csv

    Genuine-versus-pseudo tests with longitudinal statistic, pseudo-null
    summaries, empirical P-value, tail definition and interpretation.


05_support_summary.csv

    Native and shared absolute-abundance support metadata.


06_longitudinal_fold_concordance.csv

    Step-9 AB/BA concordance diagnostics.


07_longitudinal_subject_drift.csv

    Subject-specific genuine longitudinal forward-drift profiles.


08_longitudinal_loso_drift.csv

    Leave-one-subject-out genuine longitudinal forward-drift profiles.


09_comparison_summary.csv

    One-row manuscript-oriented summary containing genuine statistics, pseudo
    medians, empirical P-values, shared-support information, fraction of shared
    grid points outside the pseudo 95% envelope and fold-concordance quantities.


10_longitudinal_vs_pseudo_report.json

    Machine-readable report containing the primary estimand, representation,
    comparison method, support limits, overlap metrics, number of pseudo reverse
    pairs and longitudinal robustness counts.


Typical usage
-------------
A standard Step-10 analysis is:

    python3 10-longitudinal_vs_pseudo_forward_drift.py \
        --longitudinal-dir \
        ./results/9-replicate_decoupled_forward_drift \
        --pseudo-benchmark-dir \
        ./results_pseudo/7-pseudo_longitudinal_conditioning_benchmark \
        --outdir \
        ./results/10-longitudinal_vs_pseudo_forward_drift \
        --representation cross_combined \
        --n-grid-points 101


Interpretation
--------------
Step 10 does not ask whether the longitudinal curve is merely non-zero.

It asks whether the STRUCTURE of the genuine replicate-decoupled forward-drift
curve is stronger or more directional than expected from the pseudo-longitudinal
technical null when both are compared on the same absolute latent-abundance
support.

Accordingly:

    - native abundance scales are preserved;
    - no rank normalization is introduced;
    - no common binning is forced;
    - only curve-level interpolation within shared support is used;
    - empirical significance is defined relative to the pseudo order/reverse
      distribution.

This Step provides the direct technical-null comparison required before the
genuine forward-drift profile is interpreted as biological longitudinal
structure.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


SCRIPT_VERSION = "v1-step10-absolute-forward-drift-comparison-2026-08-24"
PRIMARY_REPRESENTATION = "cross_combined"


# =============================================================================
# I/O and validation
# =============================================================================


def ensure_dir(path: Path) -> Path:
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_csv(path: Path, label: str, usecols: Optional[Sequence[str]] = None) -> pd.DataFrame:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError("{} not found: {}".format(label, path))
    df = pd.read_csv(path, usecols=usecols)
    if df.empty:
        raise ValueError("{} is empty: {}".format(label, path))
    return df


def require_columns(df: pd.DataFrame, required: Sequence[str], label: str) -> None:
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            "{} is missing required columns {}. Available: {}".format(
                label, missing, list(df.columns)
            )
        )


def resolve_ordering_dir(pseudo_benchmark_dir: Path) -> Path:
    root = Path(pseudo_benchmark_dir)
    candidate = root / "03_ordering_robustness"
    if candidate.is_dir():
        return candidate
    # Permit the ordering directory itself for convenient isolated reruns.
    required = [
        root / "pseudo_reverse_pair_envelope.csv",
        root / "pseudo_reverse_pair_curves.csv",
    ]
    if all(p.exists() for p in required):
        return root
    raise FileNotFoundError(
        "Could not locate pseudo ordering-robustness outputs. Expected "
        "<pseudo-benchmark-dir>/03_ordering_robustness/ containing "
        "pseudo_reverse_pair_envelope.csv and pseudo_reverse_pair_curves.csv."
    )


def select_representation(df: pd.DataFrame, representation: str, label: str) -> pd.DataFrame:
    require_columns(df, ["representation"], label)
    available = sorted(df["representation"].dropna().astype(str).unique().tolist())
    if representation not in available:
        raise ValueError(
            "Representation {!r} not present in {}. Available: {}".format(
                representation, label, available
            )
        )
    return df.loc[df["representation"].astype(str) == representation].copy()


def finite_xy(df: pd.DataFrame, x_col: str, y_col: str) -> pd.DataFrame:
    out = df.copy()
    out[x_col] = pd.to_numeric(out[x_col], errors="coerce")
    out[y_col] = pd.to_numeric(out[y_col], errors="coerce")
    out = out.loc[np.isfinite(out[x_col]) & np.isfinite(out[y_col])].copy()
    out = out.sort_values(x_col)
    if out[x_col].duplicated().any():
        numeric_cols = [
            c for c in out.columns
            if c != x_col and pd.api.types.is_numeric_dtype(out[c])
        ]
        agg: Dict[str, str] = {c: "mean" for c in numeric_cols}
        for c in out.columns:
            if c not in agg and c != x_col:
                agg[c] = "first"
        out = out.groupby(x_col, as_index=False).agg(agg)
    return out


# =============================================================================
# Numerical helpers
# =============================================================================


def interpolate_curve(x: np.ndarray, y: np.ndarray, grid: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    grid = np.asarray(grid, dtype=float)
    keep = np.isfinite(x) & np.isfinite(y)
    x = x[keep]
    y = y[keep]
    if x.size < 2:
        return np.full(grid.shape, np.nan, dtype=float)
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    ux, inverse = np.unique(x, return_inverse=True)
    if ux.size != x.size:
        sy = np.zeros(ux.size, dtype=float)
        nn = np.zeros(ux.size, dtype=float)
        for i, group in enumerate(inverse):
            if np.isfinite(y[i]):
                sy[group] += y[i]
                nn[group] += 1.0
        yy = np.full(ux.size, np.nan, dtype=float)
        ok = nn > 0
        yy[ok] = sy[ok] / nn[ok]
        x = ux[ok]
        y = yy[ok]
    if x.size < 2:
        return np.full(grid.shape, np.nan, dtype=float)
    out = np.full(grid.shape, np.nan, dtype=float)
    inside = (grid >= x.min()) & (grid <= x.max())
    out[inside] = np.interp(grid[inside], x, y)
    return out


def curve_metrics(x: np.ndarray, y: np.ndarray) -> Dict[str, float]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    keep = np.isfinite(x) & np.isfinite(y)
    x = x[keep]
    y = y[keep]
    if y.size < 3:
        return {
            "mean_dx": float("nan"),
            "slope": float("nan"),
            "centered_mean_abs_drift": float("nan"),
            "centered_rms_drift": float("nan"),
            "n_points": int(y.size),
        }
    mean_y = float(np.mean(y))
    centered = y - mean_y
    slope = float(np.polyfit(x, y, 1)[0]) if np.ptp(x) > 0 else float("nan")
    return {
        "mean_dx": mean_y,
        "slope": slope,
        "centered_mean_abs_drift": float(np.mean(np.abs(centered))),
        "centered_rms_drift": float(np.sqrt(np.mean(centered ** 2))),
        "n_points": int(y.size),
    }


def summarize_null(values: np.ndarray) -> Dict[str, float]:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if values.size == 0:
        return {
            "n": 0,
            "mean": float("nan"),
            "sd": float("nan"),
            "q005": float("nan"),
            "q025": float("nan"),
            "median": float("nan"),
            "q975": float("nan"),
            "q995": float("nan"),
        }
    q = np.quantile(values, [0.005, 0.025, 0.5, 0.975, 0.995])
    return {
        "n": int(values.size),
        "mean": float(np.mean(values)),
        "sd": float(np.std(values, ddof=1)) if values.size > 1 else 0.0,
        "q005": float(q[0]),
        "q025": float(q[1]),
        "median": float(q[2]),
        "q975": float(q[3]),
        "q995": float(q[4]),
    }


def empirical_p_lower(null_values: np.ndarray, observed: float) -> float:
    v = np.asarray(null_values, dtype=float)
    v = v[np.isfinite(v)]
    if v.size == 0 or not np.isfinite(observed):
        return float("nan")
    return float((1.0 + np.sum(v <= observed)) / (v.size + 1.0))


def empirical_p_upper(null_values: np.ndarray, observed: float) -> float:
    v = np.asarray(null_values, dtype=float)
    v = v[np.isfinite(v)]
    if v.size == 0 or not np.isfinite(observed):
        return float("nan")
    return float((1.0 + np.sum(v >= observed)) / (v.size + 1.0))


def empirical_p_two_sided_about_median(null_values: np.ndarray, observed: float) -> float:
    v = np.asarray(null_values, dtype=float)
    v = v[np.isfinite(v)]
    if v.size == 0 or not np.isfinite(observed):
        return float("nan")
    median = float(np.median(v))
    d_obs = abs(float(observed) - median)
    d_null = np.abs(v - median)
    return float((1.0 + np.sum(d_null >= d_obs)) / (v.size + 1.0))


# =============================================================================
# Native curves and shared support
# =============================================================================


def prepare_longitudinal_native(by_bin: pd.DataFrame, representation: str) -> pd.DataFrame:
    h = select_representation(by_bin, representation, "longitudinal forward drift")
    require_columns(
        h,
        ["x_center", "mean_dx", "mean_dx_ci025", "mean_dx_ci975"],
        "longitudinal forward drift",
    )
    h = finite_xy(h, "x_center", "mean_dx")
    out = pd.DataFrame({
        "dataset": "longitudinal",
        "representation": representation,
        "x_center": pd.to_numeric(h["x_center"], errors="coerce"),
        "mean_dx": pd.to_numeric(h["mean_dx"], errors="coerce"),
        "lower": pd.to_numeric(h["mean_dx_ci025"], errors="coerce"),
        "upper": pd.to_numeric(h["mean_dx_ci975"], errors="coerce"),
    })
    for c in ["bin", "x_left", "x_right", "n", "n_subjects", "x_mean"]:
        out[c] = pd.to_numeric(h[c], errors="coerce") if c in h.columns else np.nan
    return out.sort_values("x_center").reset_index(drop=True)


def prepare_pseudo_native(envelope: pd.DataFrame, representation: str) -> pd.DataFrame:
    p = select_representation(envelope, representation, "pseudo ordering envelope")
    require_columns(
        p,
        ["x_center", "mean_dx_median", "mean_dx_q025", "mean_dx_q975"],
        "pseudo ordering envelope",
    )
    p = finite_xy(p, "x_center", "mean_dx_median")
    out = pd.DataFrame({
        "dataset": "pseudo",
        "representation": representation,
        "x_center": pd.to_numeric(p["x_center"], errors="coerce"),
        "mean_dx": pd.to_numeric(p["mean_dx_median"], errors="coerce"),
        "lower": pd.to_numeric(p["mean_dx_q025"], errors="coerce"),
        "upper": pd.to_numeric(p["mean_dx_q975"], errors="coerce"),
    })
    for c in ["bin", "x_left", "x_right", "n_orderings"]:
        out[c] = pd.to_numeric(p[c], errors="coerce") if c in p.columns else np.nan
    for c in ["n", "n_subjects", "x_mean"]:
        out[c] = np.nan
    return out.sort_values("x_center").reset_index(drop=True)


def compute_shared_support(
    longitudinal_native: pd.DataFrame,
    pseudo_native: pd.DataFrame,
) -> Tuple[float, float]:
    hmin = float(longitudinal_native["x_center"].min())
    hmax = float(longitudinal_native["x_center"].max())
    pmin = float(pseudo_native["x_center"].min())
    pmax = float(pseudo_native["x_center"].max())
    lo = max(hmin, pmin)
    hi = min(hmax, pmax)
    if not (np.isfinite(lo) and np.isfinite(hi) and hi > lo):
        raise ValueError(
            "Longitudinal and pseudo absolute-abundance supports do not overlap: "
            "longitudinal=[{:.6g}, {:.6g}], pseudo=[{:.6g}, {:.6g}]".format(
                hmin, hmax, pmin, pmax
            )
        )
    return lo, hi


def build_shared_grid(
    longitudinal_native: pd.DataFrame,
    pseudo_native: pd.DataFrame,
    overlap_min: float,
    overlap_max: float,
    n_grid_points: int,
) -> pd.DataFrame:
    grid = np.linspace(overlap_min, overlap_max, int(n_grid_points), dtype=float)
    h_x = longitudinal_native["x_center"].to_numpy(dtype=float)
    p_x = pseudo_native["x_center"].to_numpy(dtype=float)

    out = pd.DataFrame({"x": grid})
    out["longitudinal_mean_dx"] = interpolate_curve(
        h_x, longitudinal_native["mean_dx"].to_numpy(dtype=float), grid
    )
    out["longitudinal_ci025"] = interpolate_curve(
        h_x, longitudinal_native["lower"].to_numpy(dtype=float), grid
    )
    out["longitudinal_ci975"] = interpolate_curve(
        h_x, longitudinal_native["upper"].to_numpy(dtype=float), grid
    )
    out["pseudo_median_dx"] = interpolate_curve(
        p_x, pseudo_native["mean_dx"].to_numpy(dtype=float), grid
    )
    out["pseudo_q025"] = interpolate_curve(
        p_x, pseudo_native["lower"].to_numpy(dtype=float), grid
    )
    out["pseudo_q975"] = interpolate_curve(
        p_x, pseudo_native["upper"].to_numpy(dtype=float), grid
    )
    out["longitudinal_minus_pseudo"] = (
        out["longitudinal_mean_dx"] - out["pseudo_median_dx"]
    )
    out["longitudinal_outside_pseudo_95"] = (
        (out["longitudinal_mean_dx"] < out["pseudo_q025"])
        | (out["longitudinal_mean_dx"] > out["pseudo_q975"])
    )
    return out


# =============================================================================
# Empirical pseudo null on the shared support
# =============================================================================


def pseudo_metrics_on_overlap(
    pseudo_curves: pd.DataFrame,
    representation: str,
    grid: np.ndarray,
) -> pd.DataFrame:
    p = select_representation(pseudo_curves, representation, "pseudo reverse-pair curves")
    require_columns(
        p,
        ["reverse_pair_id", "x_center", "mean_dx"],
        "pseudo reverse-pair curves",
    )

    rows: List[Dict[str, float]] = []
    for reverse_pair_id, group in p.groupby("reverse_pair_id", sort=True):
        gg = finite_xy(group, "x_center", "mean_dx")
        yi = interpolate_curve(
            gg["x_center"].to_numpy(dtype=float),
            gg["mean_dx"].to_numpy(dtype=float),
            grid,
        )
        metrics = curve_metrics(grid, yi)
        row: Dict[str, float] = {"reverse_pair_id": int(reverse_pair_id)}
        row.update(metrics)
        rows.append(row)

    out = pd.DataFrame(rows)
    if out.empty:
        raise ValueError("No pseudo reverse-pair overlap metrics could be computed")
    return out


def empirical_tests(
    longitudinal_metrics: Dict[str, float],
    pseudo_metrics: pd.DataFrame,
) -> pd.DataFrame:
    specs = [
        ("slope", "lower", "Longitudinal slope more negative than pseudo null"),
        (
            "centered_mean_abs_drift",
            "upper",
            "Longitudinal centered mean-absolute drift exceeds pseudo null",
        ),
        (
            "centered_rms_drift",
            "upper",
            "Longitudinal centered RMS drift exceeds pseudo null",
        ),
        (
            "mean_dx",
            "two_sided_about_median",
            "Longitudinal mean offset differs from pseudo-null median",
        ),
    ]

    rows: List[Dict[str, object]] = []
    for metric, tail, interpretation in specs:
        obs = float(longitudinal_metrics.get(metric, float("nan")))
        null_values = pd.to_numeric(
            pseudo_metrics[metric], errors="coerce"
        ).to_numpy(dtype=float)
        summary = summarize_null(null_values)
        if tail == "lower":
            p_emp = empirical_p_lower(null_values, obs)
        elif tail == "upper":
            p_emp = empirical_p_upper(null_values, obs)
        else:
            p_emp = empirical_p_two_sided_about_median(null_values, obs)
        rows.append({
            "metric": metric,
            "longitudinal_value": obs,
            "pseudo_n": int(summary["n"]),
            "pseudo_mean": summary["mean"],
            "pseudo_sd": summary["sd"],
            "pseudo_q005": summary["q005"],
            "pseudo_q025": summary["q025"],
            "pseudo_median": summary["median"],
            "pseudo_q975": summary["q975"],
            "pseudo_q995": summary["q995"],
            "empirical_p": p_emp,
            "tail": tail,
            "interpretation": interpretation,
        })
    return pd.DataFrame(rows)


# =============================================================================
# Longitudinal robustness diagnostics
# =============================================================================


def prepare_subject_drift(df: pd.DataFrame, representation: str) -> pd.DataFrame:
    d = select_representation(df, representation, "longitudinal subject drift")
    require_columns(d, ["subject", "x_center", "mean_dx"], "longitudinal subject drift")
    return d.sort_values(["subject", "x_center"]).reset_index(drop=True)


def prepare_loso_drift(df: pd.DataFrame, representation: str) -> pd.DataFrame:
    d = select_representation(df, representation, "longitudinal LOSO drift")
    require_columns(
        d, ["omitted_subject", "x_center", "mean_dx"], "longitudinal LOSO drift"
    )
    return d.sort_values(["omitted_subject", "x_center"]).reset_index(drop=True)


def build_comparison_summary(
    tests: pd.DataFrame,
    shared: pd.DataFrame,
    support: pd.DataFrame,
    fold_concordance: pd.DataFrame,
) -> pd.DataFrame:
    row: Dict[str, object] = {}

    for _, r in tests.iterrows():
        metric = str(r["metric"])
        row["longitudinal_{}".format(metric)] = float(r["longitudinal_value"])
        row["pseudo_median_{}".format(metric)] = float(r["pseudo_median"])
        row["empirical_p_{}".format(metric)] = float(r["empirical_p"])

    outside = shared["longitudinal_outside_pseudo_95"].astype(bool).to_numpy()
    row["n_shared_grid_points"] = int(len(shared))
    row["n_outside_pseudo_95"] = int(np.sum(outside))
    row["fraction_outside_pseudo_95"] = float(np.mean(outside))

    if not support.empty:
        row["shared_support_min"] = float(support["shared_support_min"].iloc[0])
        row["shared_support_max"] = float(support["shared_support_max"].iloc[0])
        row["shared_support_width"] = float(support["shared_support_width"].iloc[0])

    if not fold_concordance.empty:
        f = fold_concordance.iloc[0]
        for c in fold_concordance.columns:
            val = f[c]
            row["fold_{}".format(c)] = val.item() if hasattr(val, "item") else val

    return pd.DataFrame([row])


# =============================================================================
# CLI
# =============================================================================


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Step 10: compare genuine longitudinal replicate-decoupled forward drift with "
            "the pseudo-longitudinal technical null on shared absolute x0 support."
        ),
    )
    p.add_argument(
        "--longitudinal-dir",
        type=Path,
        required=True,
        help="Output directory from Step 9: 9-replicate_decoupled_forward_drift.py.",
    )
    p.add_argument(
        "--pseudo-benchmark-dir",
        type=Path,
        required=True,
        help="Output directory from Step 7: 7-pseudo_longitudinal_conditioning_benchmark.py.",
    )
    p.add_argument("--outdir", type=Path, required=True)
    p.add_argument("--representation", default=PRIMARY_REPRESENTATION)
    p.add_argument("--n-grid-points", type=int, default=101)
    return p


def main() -> None:
    args = build_parser().parse_args()
    if int(args.n_grid_points) < 11:
        raise ValueError("--n-grid-points must be at least 11")

    longitudinal_dir = Path(args.longitudinal_dir)
    pseudo_root = Path(args.pseudo_benchmark_dir)
    if not longitudinal_dir.is_dir():
        raise NotADirectoryError("Longitudinal directory not found: {}".format(longitudinal_dir))
    if not pseudo_root.is_dir():
        raise NotADirectoryError("Pseudo benchmark directory not found: {}".format(pseudo_root))

    ordering_dir = resolve_ordering_dir(pseudo_root)
    outdir = ensure_dir(args.outdir)

    paths = {
        "longitudinal_by_bin": longitudinal_dir / "forward_drift_by_bin.csv",
        "longitudinal_by_fold": longitudinal_dir / "forward_drift_by_fold.csv",
        "longitudinal_fold_concordance": longitudinal_dir / "forward_drift_fold_concordance.csv",
        "longitudinal_subject": longitudinal_dir / "forward_drift_subject_by_bin.csv",
        "longitudinal_loso": longitudinal_dir / "forward_drift_loso_by_bin.csv",
        "pseudo_envelope": ordering_dir / "pseudo_reverse_pair_envelope.csv",
        "pseudo_curves": ordering_dir / "pseudo_reverse_pair_curves.csv",
        "pseudo_metrics_native": ordering_dir / "pseudo_reverse_pair_metrics.csv",
    }

    print("[INFO] {} | {}".format(Path(__file__).name, SCRIPT_VERSION))
    print("[INFO] ClonoDynamics Step 10")
    print("[INFO] Primary estimand: E[Delta x_latent | x0], replicate-decoupled")
    print("[INFO] Representation: {}".format(args.representation))
    print("[INFO] Percentile/rank normalization: disabled")
    print("[INFO] Common bin edges across datasets: not imposed")

    longitudinal_by_bin = read_csv(paths["longitudinal_by_bin"], "longitudinal by-bin")
    # Read/validate by-fold even though the primary comparison uses the combined curve.
    longitudinal_by_fold = read_csv(paths["longitudinal_by_fold"], "longitudinal by-fold")
    require_columns(
        longitudinal_by_fold,
        ["representation", "x_center", "mean_dx"],
        "longitudinal by-fold",
    )
    fold_concordance = read_csv(
        paths["longitudinal_fold_concordance"], "longitudinal fold concordance"
    )
    subject_raw = read_csv(paths["longitudinal_subject"], "longitudinal subject drift")
    loso_raw = read_csv(paths["longitudinal_loso"], "longitudinal LOSO drift")
    pseudo_envelope = read_csv(paths["pseudo_envelope"], "pseudo ordering envelope")
    pseudo_curves = read_csv(paths["pseudo_curves"], "pseudo reverse-pair curves")

    longitudinal_native = prepare_longitudinal_native(
        longitudinal_by_bin, args.representation
    )
    pseudo_native = prepare_pseudo_native(pseudo_envelope, args.representation)
    native = pd.concat(
        [longitudinal_native, pseudo_native], ignore_index=True, sort=False
    )

    overlap_min, overlap_max = compute_shared_support(
        longitudinal_native, pseudo_native
    )
    print(
        "[INFO] native support: longitudinal=[{:.4f}, {:.4f}], pseudo=[{:.4f}, {:.4f}]".format(
            longitudinal_native.x_center.min(), longitudinal_native.x_center.max(),
            pseudo_native.x_center.min(), pseudo_native.x_center.max(),
        )
    )
    print(
        "[INFO] shared absolute support: [{:.4f}, {:.4f}]".format(
            overlap_min, overlap_max
        )
    )

    shared = build_shared_grid(
        longitudinal_native,
        pseudo_native,
        overlap_min,
        overlap_max,
        int(args.n_grid_points),
    )
    grid = shared["x"].to_numpy(dtype=float)

    longitudinal_metrics = curve_metrics(
        grid, shared["longitudinal_mean_dx"].to_numpy(dtype=float)
    )
    pseudo_overlap_metrics = pseudo_metrics_on_overlap(
        pseudo_curves, args.representation, grid
    )
    tests = empirical_tests(longitudinal_metrics, pseudo_overlap_metrics)

    support_rows = []
    for label, df in [
        ("longitudinal", longitudinal_native),
        ("pseudo", pseudo_native),
    ]:
        support_rows.append({
            "dataset": label,
            "support_min": float(df.x_center.min()),
            "support_max": float(df.x_center.max()),
            "support_width": float(df.x_center.max() - df.x_center.min()),
            "n_native_bins": int(len(df)),
            "shared_support_min": overlap_min,
            "shared_support_max": overlap_max,
            "shared_support_width": float(overlap_max - overlap_min),
            "n_native_centers_in_shared_support": int(
                ((df.x_center >= overlap_min) & (df.x_center <= overlap_max)).sum()
            ),
        })
    support = pd.DataFrame(support_rows)

    subject = prepare_subject_drift(subject_raw, args.representation)
    loso = prepare_loso_drift(loso_raw, args.representation)
    summary = build_comparison_summary(tests, shared, support, fold_concordance)

    outputs = {
        "run_config": outdir / "00_run_config.json",
        "manifest": outdir / "00_input_manifest.csv",
        "native": outdir / "01_native_forward_drift_curves.csv",
        "shared": outdir / "02_shared_support_grid.csv",
        "pseudo_metrics": outdir / "03_pseudo_overlap_null_metrics.csv",
        "tests": outdir / "04_empirical_tests.csv",
        "support": outdir / "05_support_summary.csv",
        "fold": outdir / "06_longitudinal_fold_concordance.csv",
        "subject": outdir / "07_longitudinal_subject_drift.csv",
        "loso": outdir / "08_longitudinal_loso_drift.csv",
        "summary": outdir / "09_comparison_summary.csv",
        "report": outdir / "10_longitudinal_vs_pseudo_report.json",
    }

    native.to_csv(outputs["native"], index=False)
    shared.to_csv(outputs["shared"], index=False)
    pseudo_overlap_metrics.to_csv(outputs["pseudo_metrics"], index=False)
    tests.to_csv(outputs["tests"], index=False)
    support.to_csv(outputs["support"], index=False)
    fold_concordance.to_csv(outputs["fold"], index=False)
    subject.to_csv(outputs["subject"], index=False)
    loso.to_csv(outputs["loso"], index=False)
    summary.to_csv(outputs["summary"], index=False)

    manifest_rows = []
    for key, path in paths.items():
        manifest_rows.append({
            "input": key,
            "path": str(path),
            "required": key != "pseudo_metrics_native",
            "exists": bool(path.exists()),
        })
    pd.DataFrame(manifest_rows).to_csv(outputs["manifest"], index=False)

    run_config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "longitudinal_dir": str(longitudinal_dir),
        "pseudo_benchmark_dir": str(pseudo_root),
        "pseudo_ordering_dir": str(ordering_dir),
        "outdir": str(outdir),
        "representation": args.representation,
        "n_grid_points": int(args.n_grid_points),
        "conditioning_coordinate": "absolute latent initial log-frequency x0",
        "displacement": "latent relative-frequency displacement",
        "estimand": "E[Delta x_latent | x0]",
        "replicate_decoupled": True,
        "rank_or_percentile_normalization": False,
        "common_bin_edges_forced": False,
    }
    with outputs["run_config"].open("w", encoding="utf-8") as handle:
        json.dump(run_config, handle, indent=2, sort_keys=True)

    outside = shared["longitudinal_outside_pseudo_95"].astype(bool).to_numpy()
    report = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "primary_estimand": "E[Delta x_latent | x0]",
        "primary_representation": args.representation,
        "conditioning": "replicate-decoupled initial latent abundance x0",
        "rank_or_percentile_normalization": False,
        "common_bin_edges_forced": False,
        "comparison_method": (
            "native bins retained for each dataset; already-estimated curves "
            "interpolated only within shared absolute-abundance support"
        ),
        "longitudinal_support_min": float(longitudinal_native.x_center.min()),
        "longitudinal_support_max": float(longitudinal_native.x_center.max()),
        "pseudo_support_min": float(pseudo_native.x_center.min()),
        "pseudo_support_max": float(pseudo_native.x_center.max()),
        "shared_support_min": overlap_min,
        "shared_support_max": overlap_max,
        "shared_support_width": float(overlap_max - overlap_min),
        "n_shared_grid_points": int(len(shared)),
        "n_shared_grid_outside_pseudo_95": int(np.sum(outside)),
        "fraction_shared_grid_outside_pseudo_95": float(np.mean(outside)),
        "longitudinal_overlap_metrics": longitudinal_metrics,
        "n_pseudo_reverse_pairs": int(
            pseudo_overlap_metrics["reverse_pair_id"].nunique()
        ),
        "fold_concordance": (
            fold_concordance.iloc[0].to_dict() if not fold_concordance.empty else {}
        ),
        "n_longitudinal_subjects": int(subject["subject"].nunique()),
        "n_loso_profiles": int(loso["omitted_subject"].nunique()),
    }
    with outputs["report"].open("w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, sort_keys=True, default=float)

    for key in [
        "manifest", "native", "shared", "pseudo_metrics", "tests", "support",
        "fold", "subject", "loso", "summary", "run_config", "report",
    ]:
        print("[WRITE] {}".format(outputs[key]))

    print(
        "[RESULT] longitudinal outside pseudo 95% envelope on shared grid: "
        "{}/{} ({:.1f}%)".format(
            int(np.sum(outside)), len(outside), 100.0 * float(np.mean(outside))
        )
    )
    print("[RESULT] empirical tests on shared absolute support:")
    for _, row in tests.iterrows():
        print(
            "  {}: longitudinal={:.6g}, pseudo median={:.6g}, p={:.6g}".format(
                row["metric"], row["longitudinal_value"],
                row["pseudo_median"], row["empirical_p"],
            )
        )
    if not fold_concordance.empty:
        r = fold_concordance.iloc[0]
        if "pearson_r_AB_BA" in r.index:
            print(
                "[RESULT] AB/BA fold concordance: r={:.6f}, mean |difference|={:.6g}".format(
                    float(r["pearson_r_AB_BA"]),
                    float(r.get("mean_abs_difference", np.nan)),
                )
            )
    print("[DONE]")


if __name__ == "__main__":
    main()
