#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
3-latent_posterior_quality_characterization.py

Clonotype-level characterization of latent-posterior inference quality for
ClonoDynamics.

Overview
--------
This script implements Step 3 of the ClonoDynamics pipeline.

It characterizes the statistical quality, uncertainty, detectability and
technical-replicate agreement of the latent clonotype abundance estimates
generated by Step 2 (`2-noise_aware_latent_inference.py`).

The analysis is performed across all available clonotype-timepoint latent
states without applying abundance thresholds, quality classes, composite
scores or posterior-quality filtering.

The script does not re-estimate latent clonotype frequencies and does not fit
the Negative Binomial observation model. Instead, it takes the posterior
quantities generated by Step 2 and derives a standardized set of
clonotype-level diagnostic metrics describing:

    1. posterior uncertainty in latent abundance;

    2. posterior-predictive detectability of the latent clonotype state;

    3. agreement between the two technical-replicate posteriors;

    4. differences between posterior-integrated state detectability and
       detectability calculated algebraically from replicate-specific
       probabilities;

    5. relationships among posterior uncertainty, abundance, detectability
       and replicate agreement;

    6. the numerical completeness and finiteness of posterior diagnostics
       across the full dataset.

The output provides the posterior-quality characterization used in
ClonoDynamics before longitudinal transition construction and dynamical
analysis.

Importantly, this step is diagnostic rather than filtering:

    - no clonotype is removed because of posterior uncertainty;
    - no abundance threshold is imposed;
    - no composite QC score is calculated;
    - no PASS/FAIL clonotype quality class is assigned;
    - all successfully inferred clonotype-timepoint states remain available
      for downstream analysis.


Position in the ClonoDynamics pipeline
--------------------------------------
The first three steps of the pipeline are conceptually:

    Step 1
    1-repertoire_characterization.py

        observed repertoire structure
                    |
                    v
        heavy-tail characterization
        and power-law assessment


    Step 2
    2-noise_aware_latent_inference.py

        paired technical-replicate counts
                    |
                    v
        Negative Binomial observation model
              + power-law prior
                    |
                    v
        posterior latent clonotype abundance
        + uncertainty
        + detectability


    Step 3
    3-latent_posterior_quality_characterization.py

        latent posterior outputs
                    |
                    v
        posterior uncertainty
        + replicate-posterior agreement
        + detectability diagnostics
        + full-dataset quality characterization
                    |
                    v
        validated latent-state representation
        for longitudinal transition analysis


Input
-----
The principal input is the combined clonotype-level latent table generated
by Step 2.

By default, the script expects:

    per_clone_latent_subject.parquet

The input may be provided either:

    - directly as a file path; or
    - as a directory containing exactly one file matching the value of
      `--input-pattern`.

The default input pattern is:

    per_clone_latent_subject.parquet


Supported input formats
-----------------------
The main input table may be:

    .parquet
    .pq
    .csv
    .tsv
    .txt

Parquet is recommended for large clonotype-level datasets because the script
uses lazy/streaming Polars operations to limit memory requirements.


Required input identifiers
--------------------------
The input table must identify each latent clonotype state by:

    subject
        Subject identifier.

    time
        Sampling-time identifier.

    aaSeqCDR3
        Amino-acid CDR3 clonotype identifier.

The clonotype column name can be changed through:

    --clone-col

with default:

    aaSeqCDR3.


Required posterior quantities
-----------------------------
The Step-2 table must contain the following latent-posterior quantities:

    x_latent_sd

        Posterior standard deviation of latent abundance in natural
        log-frequency space.

    x_latent_q025

        2.5th percentile of the latent log-frequency posterior.

    x_latent_q975

        97.5th percentile of the latent log-frequency posterior.

    posterior_entropy

        Shannon entropy of the discrete posterior distribution.

    p_detect_state

        Posterior-predictive probability that the inferred latent state would
        be detected under the paired-replicate observation design.

    p_dropout_state

        Posterior-predictive dropout probability of the latent state.

    p_detect_rep1
    p_detect_rep2

        Replicate-specific posterior-predictive detection probabilities.

    x_rep1_latent_median
    x_rep2_latent_median

        Replicate-specific posterior median latent log-frequencies.

    rep1_x_latent_sd
    rep2_x_latent_sd

        Replicate-specific posterior standard deviations in log-frequency
        space.


Additional contextual variables
-------------------------------
When present in the Step-2 table, the script retains useful contextual
quantities including:

    pair_id

    count_rep1
    count_rep2

    depth_rep1
    depth_rep2

    freq_rep1
    freq_rep2

    f_latent_mean
    f_latent_median
    f_latent_q025
    f_latent_q975

    x_latent_mean
    x_latent_median

    logP
    observable

    p_dropout_rep1
    p_dropout_rep2.

These variables are propagated for interpretation and stratified summaries
but are not required for all posterior-quality calculations.


Optional exact posterior-overlap input
--------------------------------------
Agreement between the replicate-specific posterior distributions is preferably
quantified using the exact Bhattacharyya coefficient calculated directly from
their discrete posterior grids.

Exact posterior overlap can be supplied in either of two ways:

    1. as a column already contained in the Step-2 table; or

    2. through an external table specified with:

           --exact-overlap-table

The script recognizes exact-overlap columns including:

    cqc_replicate_bhattacharyya_exact
    replicate_posterior_bhattacharyya
    posterior_bhattacharyya_exact
    bhattacharyya_exact

or a custom column can be specified through:

    --exact-bc-col.

An external exact-overlap table must contain:

    subject
    time
    <clone-col>
    <exact Bhattacharyya coefficient>

and is joined to the Step-2 table using:

    subject × time × clonotype.


Exact-overlap policy
--------------------
Exact discrete-posterior overlap is the preferred replicate-agreement metric.

If exact overlap is available, it is used directly.

If it is unavailable, the script can calculate a Gaussian approximation from
the replicate-specific posterior medians and standard deviations.

The option

    --require-exact-overlap

forces the analysis to stop if exact overlap is unavailable, preventing use of
the Gaussian fallback.


Optional posterior-support input
--------------------------------
The script can also retain the exact inverse-Simpson effective support of the
discrete posterior:

                         1
    S_Simpson = ---------------------
                  sum_j p_j^2

where p_j is the posterior probability at grid point j.

This quantity cannot be reconstructed exactly from posterior entropy or from
marginal posterior summaries.

It is therefore used only if supplied:

    - as an existing Step-2 column; or
    - through an external table specified with

          --posterior-support-table.

Recognized columns include:

    cqc_effective_posterior_support_simpson
    posterior_inverse_simpson_support
    inverse_simpson_support
    posterior_effective_support_simpson.

A custom column can be specified with:

    --inverse-simpson-col.

The option

    --require-inverse-simpson

forces the script to stop if exact inverse-Simpson support is unavailable.


Mathematical definitions
------------------------

1. Latent log-frequency

Let

    f_i

denote the latent relative frequency of clonotype i inferred in Step 2.

The corresponding latent abundance in natural-log frequency space is

    x_i = ln(f_i).

Because clonotype frequencies span several orders of magnitude, posterior
uncertainty is primarily characterized in x-space.


2. Posterior 95% credible-interval width

Let

    x_i,0.025

and

    x_i,0.975

denote the 2.5th and 97.5th percentiles of the posterior distribution of
latent log-frequency.

The 95% credible-interval width is

    W_i,95
        = x_i,0.975 - x_i,0.025.

The script stores this as:

    cqc_posterior_width95_x.

Smaller values indicate a more concentrated posterior in log-frequency space;
larger values indicate greater uncertainty in the inferred latent abundance.


3. Posterior fold uncertainty range

Because W_i,95 is expressed in natural-log units, it can be converted into a
multiplicative frequency range:

    R_i,95
        = exp(W_i,95).

The script stores this as:

    cqc_posterior_fold_range95.

For example,

    W_i,95 = ln(5)

corresponds to an approximately five-fold range between the lower and upper
limits of the 95% posterior credible interval.


4. Posterior standard deviation

The posterior standard deviation in log-frequency space is retained as

    sigma_x,i

and stored as:

    cqc_posterior_sd_x.

This is inherited directly from the Step-2 posterior summary.


5. Shannon posterior entropy

For a discrete posterior evaluated over K latent-frequency grid points with
probabilities

    p_i1, p_i2, ..., p_iK,

the Shannon entropy is

    H_i
        = - sum_j p_ij ln(p_ij).

The script stores this as:

    cqc_posterior_entropy.

Entropy is expressed in nats because natural logarithms are used.

Higher entropy indicates that posterior probability is distributed across a
larger portion of the latent-frequency grid.


6. Shannon effective posterior support

The entropy can be expressed as an effective number of equally probable
posterior states:

    S_i,Shannon
        = exp(H_i).

This is stored as:

    cqc_effective_posterior_support.

It is an entropy-derived effective support and should not be confused with
the inverse-Simpson support calculated directly from the posterior grid.


7. Normalized posterior entropy

For a posterior grid containing K points, the maximum possible entropy is

    H_max = ln(K).

The normalized entropy is therefore

                  H_i
    H_i,norm = -----------
                 ln(K)

with values constrained to the interval [0,1].

The script stores this as:

    cqc_posterior_entropy_normalized.

The default grid size is:

    K = 500

and can be changed using:

    --grid-size.


8. Posterior-predictive latent-state detectability

The primary detectability variable is:

    D_i,state
        = P(detection | posterior latent state).

It is supplied by Step 2 as

    p_detect_state

and retained as:

    cqc_state_detectability.

It represents the posterior-predictive probability that the clonotype would
be detected in at least one member of the paired-replicate observation design.


9. Posterior-predictive dropout probability

The corresponding state-level dropout probability is

    Q_i,state

and is stored as:

    cqc_state_dropout.

Under the Step-2 observation model, state detectability and dropout are
expected to satisfy approximately:

    D_i,state + Q_i,state = 1.

The script explicitly evaluates the maximum numerical deviation from this
complementarity relation.


10. Algebraic replicate-union detectability

Let

    D_i,1

and

    D_i,2

be the replicate-specific detection probabilities.

If the two replicate-detection events are combined algebraically, their union
probability is

    D_i,union
        = 1 - (1 - D_i,1)(1 - D_i,2).

The script stores this quantity as:

    cqc_union_detectability.

This quantity is a replicate-level construction and is compared with, but not
equated to, the posterior-integrated state detectability.


11. Difference between state and union detectability

The signed difference is

    Delta D_i
        = D_i,state - D_i,union

and is stored as:

    cqc_delta_detectability.

Its absolute magnitude is

    |Delta D_i|
        = |D_i,state - D_i,union|

and is stored as:

    cqc_abs_delta_detectability.

These quantities measure how closely the posterior-integrated latent-state
detectability tracks the simpler algebraic union of the two replicate-specific
detection probabilities.


12. Replicate joint-detection evidence

A descriptive replicate-level detection quantity is calculated as the
geometric mean

    D_i,joint
        = sqrt(D_i,1 D_i,2).

It is stored as:

    cqc_replicate_joint_detection_evidence.

The backward-compatible alias

    cqc_joint_detection_evidence

contains the same quantity.

This is retained as a technical replicate diagnostic and is not used as the
primary measure of biological-state detectability.


13. Replicate detection imbalance

Difference in replicate-specific detectability is quantified as

    I_i
        = |D_i,1 - D_i,2|

and stored as:

    cqc_detection_imbalance.


14. Replicate latent-abundance difference

Let

    x_i,1^med

and

    x_i,2^med

be the median latent log-frequency estimates obtained from the two
replicate-specific posteriors.

Their absolute difference is

    Delta x_i,rep
        = |x_i,1^med - x_i,2^med|

and is stored as:

    cqc_replicate_abs_delta_x.


15. Standardized replicate difference

Let

    sigma_i,1

and

    sigma_i,2

be the standard deviations of the two replicate-specific posterior
distributions.

The absolute replicate difference is standardized by their combined
uncertainty as

                                  |x_i,1^med - x_i,2^med|
    Z_i,rep = ---------------------------------------------------------
               sqrt(sigma_i,1^2 + sigma_i,2^2 + epsilon)

where epsilon is a small numerical stabilizer.

The result is stored as:

    cqc_replicate_standardized_delta.

This metric evaluates the separation of replicate-specific latent estimates
relative to their posterior uncertainty.


16. Bhattacharyya posterior overlap

For two discrete replicate posterior distributions

    P_i = {p_ij}

and

    Q_i = {q_ij}

defined on the same latent-frequency grid, the exact Bhattacharyya coefficient
is

    BC_i
        = sum_j sqrt(p_ij q_ij).

The coefficient lies between 0 and 1:

    BC_i = 1

indicates identical posterior distributions, whereas lower values indicate
progressively weaker overlap.

When an exact discrete-posterior coefficient is available, the script stores
it as:

    cqc_replicate_bhattacharyya_exact

and uses it as the primary replicate-agreement metric:

    cqc_replicate_bhattacharyya.


17. Gaussian Bhattacharyya approximation

If the exact discrete posterior overlap is unavailable, replicate-specific
posteriors are approximated by Gaussian distributions with medians

    mu_1, mu_2

and standard deviations

    sigma_1, sigma_2.

The corresponding Bhattacharyya coefficient is approximated as

                     ______________________
                    / 2 sigma_1 sigma_2
    BC_G =          / -----------------------
                  \/  sigma_1^2 + sigma_2^2

           × exp[
                    -(mu_1 - mu_2)^2
                 -----------------------------
                  4(sigma_1^2 + sigma_2^2)
                ].

This is stored as:

    cqc_replicate_bhattacharyya_gaussian.

The Gaussian value is used only as a fallback when an exact discrete-posterior
coefficient is unavailable.

The source used for each clonotype is explicitly recorded in:

    cqc_replicate_agreement_source

as either:

    EXACT_DISCRETE_POSTERIOR

or

    GAUSSIAN_FALLBACK.


18. Hellinger distance

Posterior disagreement is also expressed through the Hellinger distance:

    H_i
        = sqrt(1 - BC_i),

stored as:

    cqc_replicate_hellinger.

A value close to zero indicates strong replicate-posterior agreement.


19. Relative posterior width in linear-frequency space

When

    f_latent_q025
    f_latent_q975
    f_latent_median

are available, the script also calculates

                         f_i,0.975 - f_i,0.025
    W_i,rel = -----------------------------------------
                             |f_i,median|

and stores it as:

    cqc_posterior_relative_width95_f.

This provides a scale-relative uncertainty measure in linear-frequency space.


Numerical validity
------------------
For every clonotype-timepoint observation, the script verifies that the
principal posterior-quality metrics are finite.

A row is marked:

    cqc_diagnostics_valid = True

when all required diagnostic quantities are finite.

The corresponding status is:

    VALID

or:

    INVALID_NUMERICAL.

This status is diagnostic only.

Regardless of diagnostic status:

    cqc_included_downstream = True.

Thus, posterior-quality characterization does not itself remove observations
from subsequent analyses.


Full-dataset statistical summaries
----------------------------------
All manuscript-level distribution summaries are calculated from the complete
posterior-QC dataset.

For each metric, the script reports:

    n_non_null
    n_finite

    minimum
    1st percentile
    2.5th percentile
    10th percentile
    25th percentile
    median
    75th percentile
    90th percentile
    95th percentile
    97.5th percentile
    99th percentile
    maximum

    mean
    standard deviation.

These summaries are generated without abundance- or quality-based filtering.


Spearman correlation analysis
-----------------------------
Pairwise relationships among the principal posterior-quality metrics are
quantified using Spearman rank correlation.

The core correlation matrix includes:

    posterior credible-interval width
    posterior entropy
    state detectability
    replicate-union detectability
    replicate Bhattacharyya overlap

and, when available:

    inverse-Simpson posterior support.

Additional manuscript-relevant relationships include:

    posterior width
        versus
    |state detectability - union detectability|

and

    state detectability
        versus
    |state detectability - union detectability|.

For each relationship, Spearman correlation is calculated using all rows for
which both metrics are finite.

These statistics are calculated from the full QC dataset rather than from
plotting subsamples.


Abundance-dependent characterization
------------------------------------
Posterior quality is also summarized as a function of latent clonotype
abundance.

The conditioning coordinate is:

    x_latent_median.

The abundance axis is divided into fixed-width bins:

    [x_left, x_right),

with default width:

    1.0 natural-log unit.

For each abundance bin, the script summarizes quantities including:

    posterior 95% credible-interval width;
    posterior entropy;
    state detectability;
    state dropout;
    replicate Bhattacharyya overlap;
    standardized replicate difference.

The script additionally reports the overall:

    2.5th percentile
    median
    97.5th percentile

of latent log-frequency to define the abundance range represented in the
complete dataset.


Detectability-dependent characterization
----------------------------------------
Posterior uncertainty and replicate agreement are summarized across bins of

    cqc_state_detectability.

The default detectability-bin width is:

    0.02.

Within each bin, the script reports:

    number of clonotype-timepoint observations;

    median and interquartile range of
        posterior 95% credible-interval width;

    median and interquartile range of
        replicate Bhattacharyya overlap.


Replicate-difference characterization
-------------------------------------
Posterior uncertainty is also summarized as a function of the standardized
replicate difference

    Z_i,rep.

The default bin width is:

    0.25

with an upper plotting/summary clipping value of:

    5.0.

For each bin, the script reports the median and interquartile range of
posterior credible-interval width.


Output
------
The principal output directory contains:


1. clonotype_latent_posterior_qc.parquet

    Main clonotype-level posterior-quality table.

    One row corresponds to one inferred:

        subject × clonotype × time

    state.

    It contains relevant Step-2 variables together with the derived
    posterior-quality metrics.


2. clonotype_latent_posterior_qc_metric_summary.csv

    Full-dataset descriptive statistics for every posterior-quality metric.

    This table provides the principal numerical values used to report
    medians, interquartile ranges and percentile ranges in the manuscript.


3. clonotype_latent_posterior_qc_status_summary.csv

    Counts and fractions of observations according to:

        cqc_diagnostic_status

    and:

        cqc_replicate_agreement_source.

    It therefore records numerical completeness and the fraction of
    observations supported by exact discrete-posterior overlap.


4. clonotype_latent_posterior_qc_subject_summary.csv

    Posterior-quality summaries grouped by subject.


5. clonotype_latent_posterior_qc_pair_summary.csv

    Posterior-quality summaries grouped by:

        subject × time.

    This provides one summary for each successfully fitted technical-replicate
    pair.


6. clonotype_latent_posterior_qc_abundance_reference.csv

    Global latent-abundance reference containing:

        x_q025
        x_median
        x_q975
        n_clonotype_timepoints.


7. clonotype_latent_posterior_qc_by_abundance.csv

    Posterior-quality summaries stratified by latent log-frequency bin.

    This output supports analyses of posterior uncertainty and replicate
    agreement as functions of latent abundance.


8. clonotype_latent_posterior_qc_by_detection.csv

    Posterior credible-interval width and replicate-posterior overlap
    summarized as functions of posterior-predictive state detectability.


9. clonotype_latent_posterior_qc_by_replicate_difference.csv

    Posterior uncertainty summarized as a function of standardized
    replicate disagreement.


10. state_detectability_validation_summary.csv

    Whole-dataset comparison between posterior-integrated state detectability
    and algebraic replicate-union detectability.

    It contains:

        n_clonotype_timepoints

        mean signed difference
        mean absolute difference
        median absolute difference
        99th percentile absolute difference
        maximum absolute difference

        fraction exceeding selected numerical discrepancy thresholds

        maximum state-detectability/dropout complementarity error

        Pearson correlation between state and union detectability

        Spearman correlation between state and union detectability.


11. qc_metric_spearman_correlations.csv

    Full-dataset Spearman correlation matrix among the principal
    posterior-quality metrics.


12. qc_metric_spearman_n_complete.csv

    Pairwise numbers of finite observations used for each Spearman
    correlation.


13. clonotype_latent_posterior_qc_key_relationships.csv

    Manuscript-focused Spearman statistics for selected relationships,
    including:

        posterior width
        versus
        absolute state-versus-union detectability discrepancy.


14. qc_metric_spearman_metadata.csv

    Metadata documenting:

        correlation definition;
        metrics included;
        full-dataset data scope;
        absence of plotting-subsample use for reported correlations.


15. clonotype_latent_posterior_qc_manifest.json

    Analysis manifest recording:

        input and output paths;
        numerical settings;
        bin widths;
        posterior-quality domains;
        source of exact posterior overlap;
        source of inverse-Simpson support;
        detectability policy;
        replicate-agreement policy;
        statistical-summary policy;
        absence of composite scoring;
        absence of quality classes;
        absence of filtering.


Primary manuscript quantities
-----------------------------
The principal quantities generated or summarized by this step correspond to
the posterior-inference quality characterization reported in the
ClonoDynamics Results.

These include:

    posterior 95% credible-interval width;

    posterior fold uncertainty range;

    posterior Shannon entropy;

    exact replicate-posterior Bhattacharyya coefficient;

    posterior-predictive latent-state detectability;

    replicate-union detectability;

    absolute difference between state and union detectability;

    abundance dependence of posterior uncertainty;

    abundance dependence of replicate-posterior agreement;

    pairwise correlations among posterior-quality metrics.


Typical usage
-------------
Standard analysis using the Step-2 combined latent table:

    python3 3-latent_posterior_quality_characterization.py \
        --input ./results/2-noise_aware_latent_inference/p_05/per_clone_latent_subject.parquet \
        --output-dir ./results/3-latent_posterior_quality_characterization \
        --clone-col aaSeqCDR3 \
        --grid-size 500 \
        --abundance-bin-width 1.0 \
        --detection-bin-width 0.02 \
        --replicate-z-bin-width 0.25 \
        --replicate-z-max 5.0


Analysis requiring exact discrete-posterior overlap:

    python3 3-latent_posterior_quality_characterization.py \
        --input ./results/2-noise_aware_latent_inference/p_05/per_clone_latent_subject.parquet \
        --output-dir ./results/3-latent_posterior_quality_characterization \
        --exact-overlap-table ./replicate_posterior_overlap.parquet \
        --require-exact-overlap


Interpretation
--------------
This step answers a different question from Step 2.

Step 2 asks:

    "What is the posterior distribution of the latent abundance of this
     clonotype?"

Step 3 asks:

    "How precise, reproducible and detectable is that inferred latent state?"

Accordingly, Step 3 does not alter the inferred state. It characterizes the
information content and technical consistency of the posterior representation
that will subsequently be used to construct longitudinal clonotype
transitions.

The result is a full-dataset posterior-quality description in which
uncertainty, detectability and replicate agreement remain continuous
quantities rather than being converted into exclusion criteria.

Important design choice
-----------------------
Exact Bhattacharyya overlap between replicate posterior grids is preferred. It
can be supplied either as a column in the Step-2 table or through an external
per-clonotype overlap table. If exact overlap is unavailable, a Gaussian
approximation is retained only as an explicitly labelled fallback.

Compatible with Python 3.9 and Polars 1.36.x.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Optional, Sequence

import polars as pl

EPS = 1e-12
INVERSE_SIMPSON_CANDIDATES = [
    "cqc_effective_posterior_support_simpson",
    "posterior_inverse_simpson_support",
    "inverse_simpson_support",
    "posterior_effective_support_simpson",
]

EXACT_BC_CANDIDATES = [
    "cqc_replicate_bhattacharyya_exact",
    "replicate_posterior_bhattacharyya",
    "posterior_bhattacharyya_exact",
    "bhattacharyya_exact",
]


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def resolve_input(path: Path, pattern: str) -> Path:
    if path.is_file():
        return path
    if not path.is_dir():
        raise FileNotFoundError("Input does not exist: %s" % path)
    matches = sorted(path.glob(pattern))
    if len(matches) != 1:
        raise FileNotFoundError(
            "Expected exactly one file matching %r in %s; found %d" %
            (pattern, path, len(matches))
        )
    return matches[0]


def scan_table(path: Path) -> pl.LazyFrame:
    suffix = path.suffix.lower()
    if suffix in (".parquet", ".pq"):
        return pl.scan_parquet(path)
    if suffix in (".csv", ".tsv", ".txt"):
        sep = "\t" if suffix in (".tsv", ".txt") else ","
        return pl.scan_csv(path, separator=sep, infer_schema_length=10000)
    raise ValueError("Unsupported input format: %s" % suffix)


def require_columns(names, required) -> None:
    missing = [c for c in required if c not in names]
    if missing:
        raise ValueError("Missing required Step-2 columns: %s" % ", ".join(missing))


def first_present(names, candidates):
    for c in candidates:
        if c in names:
            return c
    return None


def attach_exact_overlap(
    lf: pl.LazyFrame,
    overlap_path: Optional[Path],
    clone_col: str,
    exact_bc_col: Optional[str],
) -> tuple:
    """Attach an exact posterior-overlap scalar when available.

    External table must contain subject, time, clone_col and one exact-BC
    column. The result is normalized to cqc_replicate_bhattacharyya_exact.
    """
    names = lf.collect_schema().names()
    source_col = None
    source_description = None

    if exact_bc_col and exact_bc_col in names:
        source_col = exact_bc_col
        source_description = "input_column:%s" % exact_bc_col
    elif not exact_bc_col:
        source_col = first_present(names, EXACT_BC_CANDIDATES)
        if source_col:
            source_description = "input_column:%s" % source_col

    if source_col:
        if source_col != "cqc_replicate_bhattacharyya_exact":
            lf = lf.with_columns(
                pl.col(source_col).cast(pl.Float64, strict=False)
                .alias("cqc_replicate_bhattacharyya_exact")
            )
        return lf, source_description

    if overlap_path is None:
        return lf, None

    olf = scan_table(overlap_path)
    onames = olf.collect_schema().names()
    require_columns(onames, ["subject", "time", clone_col])
    source_col = exact_bc_col if exact_bc_col else first_present(onames, EXACT_BC_CANDIDATES)
    if source_col is None:
        raise ValueError(
            "Exact-overlap table contains no recognized Bhattacharyya column. "
            "Use --exact-bc-col to identify it."
        )
    olf = olf.select([
        pl.col("subject"), pl.col("time"), pl.col(clone_col),
        pl.col(source_col).cast(pl.Float64, strict=False)
        .alias("cqc_replicate_bhattacharyya_exact"),
    ])
    lf = lf.join(olf, on=["subject", "time", clone_col], how="left")
    return lf, "external_table:%s:%s" % (overlap_path, source_col)



def attach_inverse_simpson_support(
    lf: pl.LazyFrame,
    support_path: Optional[Path],
    clone_col: str,
    support_col: Optional[str],
) -> tuple:
    """Attach exact inverse-Simpson posterior support when available.

    The metric is 1 / sum(p_i^2) on the discrete posterior grid. It cannot be
    reconstructed from entropy or marginal summaries, so it is accepted only
    as an existing Step-2 column or from an external keyed table.
    """
    names = lf.collect_schema().names()
    source_col = None
    source_description = None
    if support_col and support_col in names:
        source_col = support_col
        source_description = "input_column:%s" % support_col
    elif not support_col:
        source_col = first_present(names, INVERSE_SIMPSON_CANDIDATES)
        if source_col:
            source_description = "input_column:%s" % source_col
    if source_col:
        if source_col != "cqc_effective_posterior_support_simpson":
            lf = lf.with_columns(
                pl.col(source_col).cast(pl.Float64, strict=False)
                .alias("cqc_effective_posterior_support_simpson")
            )
        return lf, source_description
    if support_path is None:
        return lf, None
    slf = scan_table(support_path)
    snames = slf.collect_schema().names()
    require_columns(snames, ["subject", "time", clone_col])
    source_col = support_col if support_col else first_present(snames, INVERSE_SIMPSON_CANDIDATES)
    if source_col is None:
        raise ValueError(
            "Posterior-support table contains no recognized inverse-Simpson column. "
            "Use --inverse-simpson-col to identify it."
        )
    slf = slf.select([
        pl.col("subject"), pl.col("time"), pl.col(clone_col),
        pl.col(source_col).cast(pl.Float64, strict=False)
        .alias("cqc_effective_posterior_support_simpson"),
    ])
    lf = lf.join(slf, on=["subject", "time", clone_col], how="left")
    return lf, "external_table:%s:%s" % (support_path, source_col)


def build_diagnostics(
    lf: pl.LazyFrame,
    clone_col: str,
    grid_size: int,
    exact_overlap_path: Optional[Path],
    exact_bc_col: Optional[str],
    require_exact_overlap: bool,
    posterior_support_path: Optional[Path],
    inverse_simpson_col: Optional[str],
    require_inverse_simpson: bool,
) -> tuple:
    names = lf.collect_schema().names()
    required = [
        "subject", "time", clone_col,
        "x_latent_sd", "x_latent_q025", "x_latent_q975",
        "posterior_entropy", "p_detect_state", "p_dropout_state",
        "p_detect_rep1", "p_detect_rep2",
        "x_rep1_latent_median", "x_rep2_latent_median",
        "rep1_x_latent_sd", "rep2_x_latent_sd",
    ]
    require_columns(names, required)

    lf, exact_source = attach_exact_overlap(
        lf, exact_overlap_path, clone_col, exact_bc_col
    )
    lf, support_source = attach_inverse_simpson_support(
        lf, posterior_support_path, clone_col, inverse_simpson_col
    )
    names = lf.collect_schema().names()
    if require_inverse_simpson and "cqc_effective_posterior_support_simpson" not in names:
        raise ValueError(
            "Exact inverse-Simpson posterior support was required but is unavailable. "
            "Supply --posterior-support-table or a recognized input column."
        )
    if require_exact_overlap and "cqc_replicate_bhattacharyya_exact" not in names:
        raise ValueError(
            "Exact posterior overlap was required but is unavailable. Supply "
            "--exact-overlap-table or an exact-BC column from Step 2."
        )

    context = [
        "pair_id", "count_rep1", "count_rep2", "depth_rep1", "depth_rep2",
        "freq_rep1", "freq_rep2", "f_latent_mean", "f_latent_median",
        "f_latent_q025", "f_latent_q975", "x_latent_mean", "x_latent_median",
        "logP", "observable", "p_detect_state", "p_dropout_state",
        "p_detect_rep1", "p_detect_rep2", "p_dropout_rep1", "p_dropout_rep2",
        "cqc_replicate_bhattacharyya_exact",
        "cqc_effective_posterior_support_simpson",
    ]
    selected = ["subject", "time", clone_col] + [c for c in context if c in names] + required[3:]
    selected = list(dict.fromkeys(selected))

    non_numeric = {"subject", "time", clone_col, "pair_id", "observable"}
    numeric = [c for c in selected if c not in non_numeric]
    q = lf.select([pl.col(c) for c in selected]).with_columns([
        pl.col(c).cast(pl.Float64, strict=False) for c in numeric
    ])

    log_grid = math.log(float(grid_size))
    s1 = pl.col("rep1_x_latent_sd").clip(lower_bound=0.0)
    s2 = pl.col("rep2_x_latent_sd").clip(lower_bound=0.0)
    s1sq = s1.pow(2)
    s2sq = s2.pow(2)
    variance_sum = s1sq + s2sq + pl.lit(EPS)
    delta = (pl.col("x_rep1_latent_median") - pl.col("x_rep2_latent_median")).abs()
    width_x = pl.col("x_latent_q975") - pl.col("x_latent_q025")

    expressions = [
        width_x.alias("cqc_posterior_width95_x"),
        width_x.exp().alias("cqc_posterior_fold_range95"),
        pl.col("x_latent_sd").alias("cqc_posterior_sd_x"),
        pl.col("posterior_entropy").alias("cqc_posterior_entropy"),
        pl.col("posterior_entropy").exp().alias("cqc_effective_posterior_support"),
        (pl.col("posterior_entropy") / pl.lit(log_grid))
            .clip(0.0, 1.0).alias("cqc_posterior_entropy_normalized"),
        pl.col("p_detect_state").clip(0.0, 1.0)
            .alias("cqc_state_detectability"),
        pl.col("p_dropout_state").clip(0.0, 1.0)
            .alias("cqc_state_dropout"),
        (
            1.0
            - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
              * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
        ).clip(0.0, 1.0).alias("cqc_union_detectability"),
        (
            pl.col("p_detect_state").clip(0.0, 1.0)
            - (
                1.0
                - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
                  * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
              )
        ).alias("cqc_delta_detectability"),
        (
            pl.col("p_detect_state").clip(0.0, 1.0)
            - (
                1.0
                - (1.0 - pl.col("p_detect_rep1").clip(0.0, 1.0))
                  * (1.0 - pl.col("p_detect_rep2").clip(0.0, 1.0))
              )
        ).abs().alias("cqc_abs_delta_detectability"),
        (
            pl.col("p_detect_rep1").clip(0.0, 1.0)
            * pl.col("p_detect_rep2").clip(0.0, 1.0)
        ).sqrt().alias("cqc_replicate_joint_detection_evidence"),
        # Backward-compatible alias. This remains a replicate-level QC metric,
        # not the primary detectability of the latent biological state.
        (
            pl.col("p_detect_rep1").clip(0.0, 1.0)
            * pl.col("p_detect_rep2").clip(0.0, 1.0)
        ).sqrt().alias("cqc_joint_detection_evidence"),
        (pl.col("p_detect_rep1") - pl.col("p_detect_rep2")).abs()
            .alias("cqc_detection_imbalance"),
        delta.alias("cqc_replicate_abs_delta_x"),
        (delta / variance_sum.sqrt()).alias("cqc_replicate_standardized_delta"),
    ]

    # Relative uncertainty in linear frequency space, where available.
    if all(c in names for c in ["f_latent_q025", "f_latent_q975", "f_latent_median"]):
        expressions.append(
            ((pl.col("f_latent_q975") - pl.col("f_latent_q025")) /
             pl.col("f_latent_median").abs().clip(lower_bound=EPS))
            .alias("cqc_posterior_relative_width95_f")
        )

    q = q.with_columns(expressions)

    # Gaussian fallback retained only when exact overlap is not supplied.
    scale_term = ((2.0 * s1 * s2) / variance_sum).clip(0.0, 1.0).sqrt()
    location_term = (-(delta.pow(2)) / (4.0 * variance_sum)).exp()
    q = q.with_columns(
        (scale_term * location_term).clip(0.0, 1.0)
        .alias("cqc_replicate_bhattacharyya_gaussian")
    )

    has_exact = "cqc_replicate_bhattacharyya_exact" in q.collect_schema().names()
    if has_exact:
        q = q.with_columns([
            pl.col("cqc_replicate_bhattacharyya_exact").clip(0.0, 1.0),
            pl.coalesce([
                pl.col("cqc_replicate_bhattacharyya_exact"),
                pl.col("cqc_replicate_bhattacharyya_gaussian"),
            ]).alias("cqc_replicate_bhattacharyya"),
            pl.when(pl.col("cqc_replicate_bhattacharyya_exact").is_not_null())
              .then(pl.lit("EXACT_DISCRETE_POSTERIOR"))
              .otherwise(pl.lit("GAUSSIAN_FALLBACK"))
              .alias("cqc_replicate_agreement_source"),
        ])
    else:
        q = q.with_columns([
            pl.col("cqc_replicate_bhattacharyya_gaussian")
              .alias("cqc_replicate_bhattacharyya"),
            pl.lit("GAUSSIAN_FALLBACK").alias("cqc_replicate_agreement_source"),
        ])

    q = q.with_columns(
        (1.0 - pl.col("cqc_replicate_bhattacharyya"))
        .clip(0.0, 1.0).sqrt().alias("cqc_replicate_hellinger")
    )

    diagnostic_cols = [
        "cqc_posterior_width95_x",
        "cqc_posterior_fold_range95",
        "cqc_posterior_sd_x",
        "cqc_posterior_entropy",
        "cqc_effective_posterior_support",
        "cqc_state_detectability",
        "cqc_state_dropout",
        "cqc_union_detectability",
        "cqc_delta_detectability",
        "cqc_abs_delta_detectability",
        "cqc_replicate_joint_detection_evidence",
        "cqc_detection_imbalance",
        "cqc_replicate_abs_delta_x",
        "cqc_replicate_standardized_delta",
        "cqc_replicate_bhattacharyya",
        "cqc_replicate_hellinger",
    ]
    qnames = q.collect_schema().names()
    if "cqc_posterior_relative_width95_f" in qnames:
        diagnostic_cols.append("cqc_posterior_relative_width95_f")
    if "cqc_effective_posterior_support_simpson" in qnames:
        diagnostic_cols.append("cqc_effective_posterior_support_simpson")

    valid_expr = pl.all_horizontal([pl.col(c).is_finite() for c in diagnostic_cols])
    q = q.with_columns([
        valid_expr.alias("cqc_diagnostics_valid"),
        pl.when(valid_expr).then(pl.lit("VALID")).otherwise(pl.lit("INVALID_NUMERICAL"))
            .alias("cqc_diagnostic_status"),
        pl.lit(True).alias("cqc_included_downstream"),
    ])
    return q, exact_source, support_source


def write_csv(lf: pl.LazyFrame, path: Path) -> None:
    lf.collect(engine="streaming").write_csv(path)


def metric_summary(lf: pl.LazyFrame, metrics) -> pl.DataFrame:
    rows = []
    for metric in metrics:
        rows.append(lf.select([
            pl.lit(metric).alias("metric"),
            pl.col(metric).is_not_null().sum().alias("n_non_null"),
            pl.col(metric).is_finite().sum().alias("n_finite"),
            pl.col(metric).min().alias("min"),
            pl.col(metric).quantile(0.01).alias("q01"),
            pl.col(metric).quantile(0.025).alias("q025"),
            pl.col(metric).quantile(0.10).alias("q10"),
            pl.col(metric).quantile(0.25).alias("q25"),
            pl.col(metric).median().alias("median"),
            pl.col(metric).quantile(0.75).alias("q75"),
            pl.col(metric).quantile(0.90).alias("q90"),
            pl.col(metric).quantile(0.95).alias("q95"),
            pl.col(metric).quantile(0.975).alias("q975"),
            pl.col(metric).quantile(0.99).alias("q99"),
            pl.col(metric).max().alias("max"),
            pl.col(metric).mean().alias("mean"),
            pl.col(metric).std().alias("sd"),
        ]).collect(engine="streaming"))
    return pl.concat(rows)


def grouped_summary(lf: pl.LazyFrame, group_cols, output_path: Path) -> None:
    names = lf.collect_schema().names()
    aggs = [
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_diagnostics_valid").mean().alias("fraction_valid"),
        pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
        pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
        pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
        pl.col("cqc_posterior_entropy").median().alias("posterior_entropy_median"),
        pl.col("cqc_effective_posterior_support").median().alias("shannon_effective_support_median"),
        pl.col("cqc_state_detectability").median().alias("state_detectability_median"),
        pl.col("cqc_state_detectability").quantile(0.25).alias("state_detectability_q25"),
        pl.col("cqc_state_detectability").quantile(0.75).alias("state_detectability_q75"),
        pl.col("cqc_state_dropout").median().alias("state_dropout_median"),
        pl.col("cqc_union_detectability").median().alias("union_detectability_median"),
        pl.col("cqc_delta_detectability").median().alias("delta_detectability_median"),
        pl.col("cqc_delta_detectability").quantile(0.25).alias("delta_detectability_q25"),
        pl.col("cqc_delta_detectability").quantile(0.75).alias("delta_detectability_q75"),
        pl.col("cqc_abs_delta_detectability").mean().alias("abs_delta_detectability_mean"),
        pl.col("cqc_abs_delta_detectability").max().alias("abs_delta_detectability_max"),
        pl.col("cqc_replicate_joint_detection_evidence").median().alias("replicate_joint_detection_median"),
        pl.col("cqc_replicate_joint_detection_evidence").quantile(0.25).alias("replicate_joint_detection_q25"),
        pl.col("cqc_replicate_joint_detection_evidence").quantile(0.75).alias("replicate_joint_detection_q75"),
        pl.col("cqc_replicate_bhattacharyya").median().alias("replicate_bc_median"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.25).alias("replicate_bc_q25"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.75).alias("replicate_bc_q75"),
        pl.col("cqc_replicate_standardized_delta").median().alias("replicate_z_median"),
        pl.col("cqc_replicate_standardized_delta").quantile(0.25).alias("replicate_z_q25"),
        pl.col("cqc_replicate_standardized_delta").quantile(0.75).alias("replicate_z_q75"),
        pl.col("cqc_detection_imbalance").median().alias("detection_imbalance_median"),
        (pl.col("cqc_replicate_agreement_source") == "EXACT_DISCRETE_POSTERIOR")
            .mean().alias("fraction_exact_posterior_overlap"),
    ]
    if "cqc_effective_posterior_support_simpson" in names:
        aggs.extend([
            pl.col("cqc_effective_posterior_support_simpson").median().alias("inverse_simpson_support_median"),
            pl.col("cqc_effective_posterior_support_simpson").quantile(0.25).alias("inverse_simpson_support_q25"),
            pl.col("cqc_effective_posterior_support_simpson").quantile(0.75).alias("inverse_simpson_support_q75"),
        ])
    write_csv(lf.group_by(group_cols).agg(aggs).sort(group_cols), output_path)


def write_abundance_reference(lf: pl.LazyFrame, output_path: Path) -> None:
    if "x_latent_median" not in lf.collect_schema().names():
        return
    out = lf.select([
        pl.col("x_latent_median").quantile(0.025).alias("x_q025"),
        pl.col("x_latent_median").median().alias("x_median"),
        pl.col("x_latent_median").quantile(0.975).alias("x_q975"),
        pl.len().alias("n_clonotype_timepoints"),
    ]).collect(engine="streaming")
    out.write_csv(output_path)


def write_abundance_summary(lf: pl.LazyFrame, output_path: Path, bin_width: float) -> None:
    if "x_latent_median" not in lf.collect_schema().names():
        return
    binned = lf.with_columns(
        ((pl.col("x_latent_median") / pl.lit(bin_width)).floor() * pl.lit(bin_width))
        .alias("x_bin_left")
    ).with_columns((pl.col("x_bin_left") + pl.lit(bin_width)).alias("x_bin_right"))
    grouped_summary(binned, ["x_bin_left", "x_bin_right"], output_path)



def write_detection_summary(lf: pl.LazyFrame, output_path: Path, bin_width: float) -> None:
    """Summarize posterior width and replicate overlap across state detectability."""
    d = lf.with_columns(
        ((pl.col("cqc_state_detectability").clip(0.0, 1.0 - EPS) / pl.lit(bin_width)).floor() * pl.lit(bin_width))
        .alias("detection_bin_left")
    ).with_columns(
        (pl.col("detection_bin_left") + pl.lit(bin_width)).clip(upper_bound=1.0)
        .alias("detection_bin_right")
    )
    out = d.group_by(["detection_bin_left", "detection_bin_right"]).agg([
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
        pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
        pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
        pl.col("cqc_replicate_bhattacharyya").median().alias("replicate_bc_median"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.25).alias("replicate_bc_q25"),
        pl.col("cqc_replicate_bhattacharyya").quantile(0.75).alias("replicate_bc_q75"),
    ]).sort("detection_bin_left")
    write_csv(out, output_path)


def write_replicate_z_summary(
    lf: pl.LazyFrame, output_path: Path, bin_width: float, z_max: float
) -> None:
    """Summarize posterior uncertainty across standardized replicate differences."""
    z = pl.col("cqc_replicate_standardized_delta").clip(0.0, z_max - EPS)
    d = lf.with_columns(
        ((z / pl.lit(bin_width)).floor() * pl.lit(bin_width)).alias("replicate_z_bin_left")
    ).with_columns(
        (pl.col("replicate_z_bin_left") + pl.lit(bin_width)).clip(upper_bound=z_max)
        .alias("replicate_z_bin_right")
    )
    out = d.group_by(["replicate_z_bin_left", "replicate_z_bin_right"]).agg([
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_posterior_width95_x").median().alias("posterior_width95_median"),
        pl.col("cqc_posterior_width95_x").quantile(0.25).alias("posterior_width95_q25"),
        pl.col("cqc_posterior_width95_x").quantile(0.75).alias("posterior_width95_q75"),
    ]).sort("replicate_z_bin_left")
    write_csv(out, output_path)


SPEARMAN_BASE_METRICS = [
    "cqc_posterior_width95_x",
    "cqc_posterior_entropy",
    "cqc_state_detectability",
    "cqc_union_detectability",
    "cqc_replicate_bhattacharyya",
]


def _full_data_spearman_pair(lf: pl.LazyFrame, a: str, b: str) -> tuple:
    """Return pairwise-finite n and Spearman rho using only two columns in memory."""
    pair = lf.select([a, b]).filter(
        pl.col(a).is_finite() & pl.col(b).is_finite()
    )
    out = pair.select([
        pl.len().alias("n_complete"),
        pl.corr(a, b, method="spearman").alias("spearman_rho"),
    ]).collect()
    return int(out["n_complete"][0]), float(out["spearman_rho"][0])


def write_full_dataset_spearman(lf: pl.LazyFrame, output_dir: Path) -> None:
    """Export manuscript Spearman statistics from the full QC dataset.

    Correlations are computed pairwise from the complete QC parquet. Processing
    one metric pair at a time deliberately limits peak memory use on large
    clonotype-level tables; plotting subsamples are never used for these values.
    """
    names = lf.collect_schema().names()
    matrix_metrics = [c for c in SPEARMAN_BASE_METRICS if c in names]
    if "cqc_effective_posterior_support_simpson" in names:
        matrix_metrics.append("cqc_effective_posterior_support_simpson")

    required_for_key = [
        "cqc_posterior_width95_x",
        "cqc_state_detectability",
        "cqc_abs_delta_detectability",
    ]
    missing = [c for c in required_for_key if c not in names]
    if missing:
        raise ValueError(
            "Cannot compute full-dataset QC correlations; missing columns: %s" %
            ", ".join(missing)
        )

    requested_pairs = []
    for i, a in enumerate(matrix_metrics):
        for j in range(i + 1, len(matrix_metrics)):
            requested_pairs.append((a, matrix_metrics[j]))
    requested_pairs.extend([
        ("cqc_posterior_width95_x", "cqc_abs_delta_detectability"),
        ("cqc_state_detectability", "cqc_abs_delta_detectability"),
    ])

    # Deduplicate without changing deterministic order.
    unique_pairs = []
    seen = set()
    for a, b in requested_pairs:
        key = tuple(sorted((a, b)))
        if key not in seen:
            seen.add(key)
            unique_pairs.append((a, b))

    pair_stats = {}
    total = len(unique_pairs)
    for idx, (a, b) in enumerate(unique_pairs, start=1):
        print("[CQC-v7] Full-data Spearman %d/%d: %s vs %s" % (idx, total, a, b))
        n_complete, rho = _full_data_spearman_pair(lf, a, b)
        pair_stats[(a, b)] = (n_complete, rho)
        pair_stats[(b, a)] = (n_complete, rho)

    matrix_rows = []
    n_rows = []
    for a in matrix_metrics:
        corr_row = {"metric": a}
        n_row = {"metric": a}
        for b in matrix_metrics:
            if a == b:
                # The diagonal is exactly one; n is the finite count for that metric.
                n_diag = int(
                    lf.select(pl.col(a).is_finite().sum().alias("n")).collect()["n"][0]
                )
                corr_row[b] = 1.0
                n_row[b] = n_diag
            else:
                n_complete, rho = pair_stats[(a, b)]
                corr_row[b] = rho
                n_row[b] = n_complete
        matrix_rows.append(corr_row)
        n_rows.append(n_row)

    pl.DataFrame(matrix_rows).write_csv(
        output_dir / "qc_metric_spearman_correlations.csv"
    )
    pl.DataFrame(n_rows).write_csv(
        output_dir / "qc_metric_spearman_n_complete.csv"
    )

    key_pairs = [
        (
            "posterior_width95_vs_abs_delta_detectability",
            "cqc_posterior_width95_x",
            "cqc_abs_delta_detectability",
        ),
        (
            "state_detectability_vs_abs_delta_detectability",
            "cqc_state_detectability",
            "cqc_abs_delta_detectability",
        ),
    ]
    key_rows = []
    for relationship, x_metric, y_metric in key_pairs:
        n_complete, rho = pair_stats[(x_metric, y_metric)]
        key_rows.append({
            "relationship": relationship,
            "x_metric": x_metric,
            "y_metric": y_metric,
            "n_complete": n_complete,
            "spearman_rho": rho,
        })
    pl.DataFrame(key_rows).write_csv(
        output_dir / "clonotype_latent_posterior_qc_key_relationships.csv"
    )

    pl.DataFrame({
        "matrix_metrics": [";".join(matrix_metrics)],
        "correlation_definition": ["Spearman rank correlation"],
        "data_scope": ["full QC parquet; pairwise finite rows"],
        "plotting_sample_used": [False],
    }).write_csv(output_dir / "qc_metric_spearman_metadata.csv")

def write_summaries(parquet_path: Path, output_dir: Path, abundance_bin_width: float, detection_bin_width: float, replicate_z_bin_width: float, replicate_z_max: float) -> None:
    lf = pl.scan_parquet(parquet_path)
    metrics = [
        "cqc_posterior_width95_x", "cqc_posterior_fold_range95",
        "cqc_posterior_sd_x", "cqc_posterior_entropy",
        "cqc_effective_posterior_support", "cqc_posterior_entropy_normalized",
        "cqc_state_detectability", "cqc_state_dropout",
        "cqc_union_detectability", "cqc_delta_detectability",
        "cqc_abs_delta_detectability",
        "cqc_replicate_joint_detection_evidence", "cqc_joint_detection_evidence",
        "cqc_detection_imbalance",
        "cqc_replicate_abs_delta_x", "cqc_replicate_standardized_delta",
        "cqc_replicate_bhattacharyya", "cqc_replicate_hellinger",
        "cqc_replicate_bhattacharyya_gaussian",
    ]
    names = lf.collect_schema().names()
    for optional in ["cqc_posterior_relative_width95_f", "cqc_replicate_bhattacharyya_exact", "cqc_effective_posterior_support_simpson", "logP"]:
        if optional in names:
            metrics.append(optional)
    metric_summary(lf, metrics).write_csv(
        output_dir / "clonotype_latent_posterior_qc_metric_summary.csv"
    )
    write_state_detectability_validation(lf, output_dir)
    write_full_dataset_spearman(lf, output_dir)

    status = (
        lf.group_by(["cqc_diagnostic_status", "cqc_replicate_agreement_source"])
        .agg(pl.len().alias("n"))
        .with_columns((pl.col("n") / pl.col("n").sum()).alias("fraction"))
        .sort("n", descending=True)
    )
    write_csv(status, output_dir / "clonotype_latent_posterior_qc_status_summary.csv")
    grouped_summary(lf, ["subject"], output_dir / "clonotype_latent_posterior_qc_subject_summary.csv")
    grouped_summary(lf, ["subject", "time"], output_dir / "clonotype_latent_posterior_qc_pair_summary.csv")
    write_abundance_reference(
        lf, output_dir / "clonotype_latent_posterior_qc_abundance_reference.csv"
    )
    write_abundance_summary(
        lf, output_dir / "clonotype_latent_posterior_qc_by_abundance.csv", abundance_bin_width
    )
    write_detection_summary(
        lf, output_dir / "clonotype_latent_posterior_qc_by_detection.csv", detection_bin_width
    )
    write_replicate_z_summary(
        lf, output_dir / "clonotype_latent_posterior_qc_by_replicate_difference.csv",
        replicate_z_bin_width, replicate_z_max
    )


def write_state_detectability_validation(lf: pl.LazyFrame, output_dir: Path) -> None:
    """Export whole-dataset validation of posterior-integrated state detectability."""
    finite = lf.filter(
        pl.all_horizontal([
            pl.col("cqc_state_detectability").is_finite(),
            pl.col("cqc_union_detectability").is_finite(),
            pl.col("cqc_delta_detectability").is_finite(),
            pl.col("cqc_abs_delta_detectability").is_finite(),
            pl.col("cqc_state_dropout").is_finite(),
        ])
    )
    summary = finite.select([
        pl.len().alias("n_clonotype_timepoints"),
        pl.col("cqc_delta_detectability").mean().alias("mean_signed_delta_state_minus_union"),
        pl.col("cqc_abs_delta_detectability").mean().alias("mean_absolute_delta"),
        pl.col("cqc_abs_delta_detectability").median().alias("median_absolute_delta"),
        pl.col("cqc_abs_delta_detectability").quantile(0.99).alias("q99_absolute_delta"),
        pl.col("cqc_abs_delta_detectability").max().alias("max_absolute_delta"),
        (pl.col("cqc_abs_delta_detectability") > 1e-12).mean().alias("fraction_abs_delta_gt_1e_12"),
        (pl.col("cqc_abs_delta_detectability") > 1e-6).mean().alias("fraction_abs_delta_gt_1e_6"),
        (pl.col("cqc_abs_delta_detectability") > 1e-3).mean().alias("fraction_abs_delta_gt_1e_3"),
        (pl.col("cqc_state_detectability") + pl.col("cqc_state_dropout") - 1.0)
            .abs().max().alias("max_state_dropout_complementarity_error"),
        pl.corr("cqc_state_detectability", "cqc_union_detectability", method="pearson")
            .alias("pearson_state_vs_union"),
        pl.corr("cqc_state_detectability", "cqc_union_detectability", method="spearman")
            .alias("spearman_state_vs_union"),
    ]).collect(engine="streaming")
    summary.write_csv(output_dir / "state_detectability_validation_summary.csv")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Characterize clonotype-level latent posterior quality without scoring."
    )
    p.add_argument("--input", type=Path, required=True)
    p.add_argument("--input-pattern", default="per_clone_latent_subject.parquet")
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--clone-col", default="aaSeqCDR3")
    p.add_argument("--grid-size", type=int, default=500)
    p.add_argument("--abundance-bin-width", type=float, default=1.0)
    p.add_argument("--compression", default="zstd")
    p.add_argument("--detection-bin-width", type=float, default=0.02,
                   help="Bin width for joint detection evidence summaries.")
    p.add_argument("--replicate-z-bin-width", type=float, default=0.25,
                   help="Bin width for standardized replicate-difference summaries.")
    p.add_argument("--replicate-z-max", type=float, default=5.0,
                   help="Upper clipping bound for standardized-difference summaries.")
    p.add_argument("--exact-overlap-table", type=Path, default=None,
                   help="Optional table keyed by subject,time,clone with exact discrete-posterior BC.")
    p.add_argument("--exact-bc-col", default=None,
                   help="Name of exact BC column in input or --exact-overlap-table.")
    p.add_argument("--require-exact-overlap", action="store_true",
                   help="Fail rather than use Gaussian fallback when exact overlap is unavailable.")
    p.add_argument("--posterior-support-table", type=Path, default=None,
                   help="Optional table keyed by subject,time,clone containing exact inverse-Simpson posterior support.")
    p.add_argument("--inverse-simpson-col", default=None,
                   help="Name of the inverse-Simpson support column in input or support table.")
    p.add_argument("--require-inverse-simpson", action="store_true",
                   help="Fail if exact inverse-Simpson posterior support is unavailable.")
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    if args.grid_size < 8:
        raise ValueError("--grid-size must be >= 8")
    if args.abundance_bin_width <= 0:
        raise ValueError("--abundance-bin-width must be > 0")
    if args.detection_bin_width <= 0 or args.detection_bin_width > 1:
        raise ValueError("--detection-bin-width must be in (0, 1]")
    if args.replicate_z_bin_width <= 0:
        raise ValueError("--replicate-z-bin-width must be > 0")
    if args.replicate_z_max <= 0:
        raise ValueError("--replicate-z-max must be > 0")

    input_path = resolve_input(args.input, args.input_pattern)
    output_dir = ensure_dir(args.output_dir)
    output_path = output_dir / "clonotype_latent_posterior_qc.parquet"

    print("[CQC-v7] Input:", input_path)
    diagnostics, exact_source, support_source = build_diagnostics(
        scan_table(input_path), args.clone_col, args.grid_size,
        args.exact_overlap_table, args.exact_bc_col, args.require_exact_overlap,
        args.posterior_support_table, args.inverse_simpson_col, args.require_inverse_simpson,
    )
    diagnostics.sink_parquet(
        output_path, compression=args.compression, statistics=True, mkdir=True
    )
    write_summaries(output_path, output_dir, args.abundance_bin_width, args.detection_bin_width, args.replicate_z_bin_width, args.replicate_z_max)

    manifest = {
        "script": Path(__file__).name,
        "input": str(input_path),
        "output": str(output_path),
        "grid_size": args.grid_size,
        "abundance_bin_width": args.abundance_bin_width,
        "detection_bin_width": args.detection_bin_width,
        "replicate_z_bin_width": args.replicate_z_bin_width,
        "replicate_z_max": args.replicate_z_max,
        "primary_domains": {
            "posterior_uncertainty": [
                "cqc_posterior_width95_x", "cqc_posterior_fold_range95",
                "cqc_posterior_entropy", "cqc_effective_posterior_support",
                "cqc_effective_posterior_support_simpson",
                "cqc_posterior_relative_width95_f",
            ],
            "state_detectability": [
                "cqc_state_detectability", "cqc_state_dropout",
            ],
            "replicate_detection_qc": [
                "cqc_replicate_joint_detection_evidence",
                "cqc_joint_detection_evidence",
                "cqc_detection_imbalance",
            ],
            "replicate_agreement": [
                "cqc_replicate_bhattacharyya", "cqc_replicate_hellinger",
                "cqc_replicate_standardized_delta",
            ],
            "model_compatibility": ["logP"],
        },
        "exact_overlap_source": exact_source,
        "inverse_simpson_support_source": support_source,
        "state_detectability_policy": (
            "p_detect_state is the primary posterior-predictive detectability of the latent state "
            "under the paired-replicate observation design. Replicate-specific detectabilities and "
            "their geometric mean are retained only as technical/QC diagnostics."
        ),
        "agreement_policy": (
            "Exact discrete-posterior Bhattacharyya overlap is preferred. "
            "Gaussian BC is used only for rows lacking exact overlap and is marked "
            "in cqc_replicate_agreement_source."
        ),
        "inverse_simpson_policy": (
            "Inverse-Simpson support is computed as 1/sum(p_i^2) on the full discrete posterior. "
            "It is never approximated from entropy; the field is present only when supplied by Step 2 or an external keyed table."
        ),
        "manuscript_statistics_policy": (
            "Metric quantiles and Spearman correlations are computed from the full QC parquet. "
            "Plotting subsamples are used only for graphical rendering and smoothing."
        ),
        "composite_score": False,
        "quality_classes": False,
        "filtering": False,
    }
    with open(output_dir / "clonotype_latent_posterior_qc_manifest.json", "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    print("[CQC-v7] Completed. No clonotypes were excluded.")
    if exact_source:
        print("[CQC-v7] Exact posterior overlap source:", exact_source)
    else:
        print("[CQC-v7] WARNING: exact overlap unavailable; Gaussian fallback used.")
    print("[CQC-v7] Main output:", output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())