#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
9-replicate_decoupled_forward_drift.py
=======================================

Replicate-decoupled forward-drift inference for genuine longitudinal
ClonoDynamics data.

Overview
--------
This script implements Step 9 of the ClonoDynamics pipeline.

It estimates abundance-dependent forward displacement from genuine
longitudinal clonotype trajectories using a replicate-decoupled conditioning
strategy established by the pseudo-longitudinal benchmark.

The primary estimand is the conditional mean latent displacement

    E[Delta x | x0],

where the initial abundance used for conditioning and the displacement used as
the outcome are constructed from DIFFERENT technical replicates.

This prevents the same replicate-level measurement error at t0 from entering
both the conditioning variable and the negative initial-state term of

    Delta x = x1 - x0.

Two reciprocal cross-fitted folds are evaluated:

    AB:
        condition on replicate A at t0;
        calculate displacement using replicate B.

    BA:
        condition on replicate B at t0;
        calculate displacement using replicate A.

The primary cohort-level forward-drift curve is the equal-weight, bin-wise
average of the AB and BA estimates:

    cross_combined
        = (cross_AB + cross_BA) / 2.

AB and BA are correlated views of the SAME biological transitions. They are
never concatenated and treated as independent observations.

The script also retains same-replicate controls, conventional joint-latent
comparators, posterior-median sensitivity analyses, observed-frequency
cross-fits when available, technical-reliability diagnostics, subject-level
curves, leave-one-subject-out curves and AB/BA fold-concordance summaries.


Position in the ClonoDynamics pipeline
--------------------------------------
The relevant public workflow is:

    Step 1
    1-repertoire_characterization.py

    Step 2
    2-noise_aware_latent_inference.py

    Step 3
    3-latent_posterior_quality_characterization.py

    Step 4
    4-latent_trajectory_construction.py

        standardized subject x clonotype x time states
                |
                +------------------------------------+
                |                                    |
                v                                    v

    Step 5                              Steps 7-8
    5-latent_transition_construction.py pseudo-longitudinal technical-null
                |                       benchmarking and representation
                v                       assessment
    Step 6                                      |
    6-latent_transition_dataset_                |
    characterization.py                         |
                                                v
                                      Step 9
                                      9-replicate_decoupled_forward_drift.py
                                                |
                                                v
                                      genuine longitudinal
                                      forward-drift inference


Step 9 intentionally reads the Step-4 trajectory table directly rather than
the generic Step-5 transition table.

This is necessary because replicate-decoupled estimation requires the
replicate-specific posterior summaries retained at each trajectory state:

    rep1_x_latent_*
    rep2_x_latent_*.

Step 9 therefore constructs its own TT transition table specialized for the
AB/BA estimand.

The pseudo-longitudinal analyses in Steps 7-8 determine and justify the
conditioning/representation strategy; Step 9 applies the forward estimator to
the genuine longitudinal cohort.


Input
-----
The required input is the standardized genuine-longitudinal trajectory table
generated by Step 4:

    latent_trajectories_long.parquet

supplied through:

    --trajectories.

The current implementation reads Parquet trajectory input.


Required trajectory columns
---------------------------
The trajectory table must contain:

    subject
        Subject identifier.

    aaSeqCDR3
        Amino-acid CDR3 clonotype identifier.

    time
        Longitudinal sampling-time identifier.

    observable
        State-level observability annotation.

    x_latent
        Joint latent log-frequency state.

    rep1_x_latent_mean
    rep1_x_latent_median
    rep1_x_latent_sd

    rep2_x_latent_mean
    rep2_x_latent_median
    rep2_x_latent_sd.

The replicate-specific posterior summaries are essential for construction of
the cross-fitted AB/BA estimator.


Optional trajectory columns
---------------------------
The following quantities are used when available:

    x_latent_sd
    log_freq_sd

        Joint latent-state posterior uncertainty.

    count_rep1
    count_rep2

        Replicate-specific observed read counts.

    depth_rep1
    depth_rep2

        Replicate-specific sequencing depths.

Count and depth columns enable observed-frequency cross-fit sensitivity and
additional technical-reliability diagnostics.


Observability policy
--------------------
The primary forward-drift analysis is TT only.

At each candidate endpoint, the trajectory state must satisfy:

    observable = True.

For subject s and time pair t0 -> t1, the script first selects observable
states at both endpoints and then joins them by:

    aaSeqCDR3.

Thus, a retained row represents a clonotype with an observable latent state at
both longitudinal endpoints.

No TF, FT or FF transitions are included in the primary Step-9 estimator.


Temporal-pair construction
--------------------------
A time lag is specified with:

    --dt

with default:

    dt = 1.

For each subject, the script identifies sampling pairs satisfying exactly:

    t1 = t0 + dt.

It does not use every possible t0 < t1 pair unless those pairs match the
requested lag.

For each eligible subject/time pair, endpoint clonotypes are inner-joined by
CDR3 amino-acid sequence.


Joint latent transition
-----------------------
For the joint latent trajectory state, define:

    x0_joint
        = x_latent(t0)

    x1_joint
        = x_latent(t1)

and:

    dx_joint
        = x1_joint - x0_joint.

The corresponding transition midpoint is:

                       x0_joint + x1_joint
    xmid_joint = --------------------------------.
                                2


Transition-centered xstar comparator
------------------------------------
When joint endpoint posterior standard deviations sigma0 and sigma1 are
available, inverse-variance weights are defined as:

               1
    w0 = ----------------
          sigma0^2 + eps

               1
    w1 = ----------------
          sigma1^2 + eps

with numerical stabilizer:

    eps = 1e-12.

The transition-centered coordinate is:

                     w0*x0_joint + w1*x1_joint
    xstar_joint = --------------------------------.
                              w0 + w1

When valid positive endpoint uncertainties are unavailable:

    xstar_joint = xmid_joint.

The source is recorded as either:

    inverse_variance_weighted

or:

    midpoint_fallback.

For Step 9, xstar is retained as a diagnostic comparator rather than the
primary forward-conditioning coordinate.


Primary replicate-decoupled estimand
------------------------------------
Let replicate A correspond to technical replicate 1 and replicate B to
technical replicate 2.

For each replicate, Step 4 supplies posterior mean, posterior median and
posterior standard deviation of latent log-frequency.


AB fold
-------
The conditioning coordinate is:

    x_cond_AB
        = median[x_A(t0)].

The outcome is calculated entirely from replicate B:

    Delta x_AB
        = mean[x_B(t1)] - mean[x_B(t0)].

The output fields are:

    xcond_cross_AB
    dx_cross_AB.


BA fold
-------
The reciprocal fold is:

    x_cond_BA
        = median[x_B(t0)]

and:

    Delta x_BA
        = mean[x_A(t1)] - mean[x_A(t0)].

The output fields are:

    xcond_cross_BA
    dx_cross_BA.


Why this is replicate-decoupled
-------------------------------
With conventional same-replicate conditioning:

    x_cond = x_A(t0)

and:

    Delta x_A
        = x_A(t1) - x_A(t0),

the same noisy initial measurement contributes positively to the conditioning
coordinate and negatively to the displacement.

This creates direct mathematical coupling between the horizontal and vertical
variables.

In the AB fold:

    conditioning uses A

while:

    displacement uses B only.

The corresponding direct shared-error term is therefore absent.

The BA fold provides the reciprocal construction.


Symmetric primary cohort estimate
---------------------------------
AB and BA are not independent biological observations.

Their binned estimates are first calculated separately.

For abundance bin b:

    mu_AB,b
        = mean(Delta x_AB | bin b)

and:

    mu_BA,b
        = mean(Delta x_BA | bin b).

The primary forward-drift estimate is:

                           mu_AB,b + mu_BA,b
    mu_cross,b = --------------------------------.
                                  2

Likewise:

    median_cross,b
        = [median_AB,b + median_BA,b] / 2

and:

    P_cross,b
        = [P(Delta x_AB > 0) + P(Delta x_BA > 0)] / 2.

This representation is labeled:

    cross_combined.

Equal fold weight is used regardless of the number of rows contributed by the
two folds.


Matched same-replicate controls
-------------------------------
The script constructs controls using IDENTICAL conditioning coordinates but
same-replicate outcomes.


same_A
------
    x_cond_same_A
        = median[x_A(t0)]

    Delta x_same_A
        = mean[x_A(t1)] - mean[x_A(t0)].


same_B
------
    x_cond_same_B
        = median[x_B(t0)]

    Delta x_same_B
        = mean[x_B(t1)] - mean[x_B(t0)].

Comparison of:

    same_A versus cross_AB

and:

    same_B versus cross_BA

therefore isolates the effect of reusing versus decoupling the technical
replicate in the outcome definition while holding the corresponding
conditioning coordinate fixed.


Joint-latent comparators
------------------------
Two additional representations are retained.


naive_x0
--------
    conditioning:
        x0_joint

    outcome:
        dx_joint.


xstar
-----
    conditioning:
        xstar_joint

    outcome:
        dx_joint.

These are diagnostic comparators in Step 9.

The primary forward-drift estimator remains:

    cross_combined.


Posterior-median sensitivity
----------------------------
The primary cross-fit uses posterior MEDIAN for conditioning and posterior MEAN
for the displacement endpoints.

A median-to-median sensitivity is also calculated.


cross_median_AB
---------------
    conditioning:
        median[x_A(t0)]

    outcome:
        median[x_B(t1)] - median[x_B(t0)].


cross_median_BA
---------------
    conditioning:
        median[x_B(t0)]

    outcome:
        median[x_A(t1)] - median[x_A(t0)].

Their symmetric bin-wise combination is written as:

    cross_median_combined.


Observed-frequency cross-fit sensitivity
----------------------------------------
When replicate-specific counts and sequencing depths are available, the script
defines observed replicate log-frequency:

    x_obs,r(t)
        = ln[count_r(t) / depth_r(t)]

only when:

    count_r(t) > 0
    depth_r(t) > 0.

Observed replicate-decoupled folds are then constructed analogously:

    observed_cross_AB
    observed_cross_BA.

Rows lacking the positive count/depth values required by a given fold are
excluded from that fold's statistics.

These observed-frequency representations are sensitivity analyses, not the
primary latent forward-drift estimand.


Transition-level output
-----------------------
The specialized Step-9 transition table contains one row per retained
subject-clonotype-time-pair transition and includes quantities such as:

    subject
    aaSeqCDR3

    t0
    t1
    dt

    x0_joint
    x1_joint
    dx_joint

    xmid_joint
    xstar_joint
    xstar_source

    xcond_cross_AB
    dx_cross_AB

    xcond_cross_BA
    dx_cross_BA

    xcond_same_A
    dx_same_A

    xcond_same_B
    dx_same_B

    xcond_cross_median_AB
    dx_cross_median_AB

    xcond_cross_median_BA
    dx_cross_median_BA

    replicate-specific endpoint means,
    medians and posterior standard deviations

and, when available:

    observed-count/depth quantities
    observed cross-fit coordinates and displacements.


Binning
-------
The number of abundance bins is specified with:

    --n-bins

with default:

    20.

Two modes are supported:

    quantile
    equal_width.

The default is:

    quantile.


Default abundance support
-------------------------
If no external bin-edge file is supplied, edges are estimated from:

    x0_joint

using the quantile interval:

    --q-low  = 0.005
    --q-high = 0.995.

For quantile binning, the requested quantiles between q_low and q_high define
the edges.

For equal-width binning, q_low and q_high define the abundance-range endpoints,
which are then divided into equal-width intervals.

The same resulting bin edges are applied to all representations.

This means that replicate-decoupled folds are compared on a common abundance
grid even though their replicate-specific conditioning values are not
identical to x0_joint.


External bin edges
------------------
A pre-existing edge file can be supplied with:

    --bin-edges-file.

This allows identical conditioning bins to be enforced across datasets or
analyses.

Accepted structured edge formats include columns such as:

    edge

or:

    x_left
    x_right.

The final edge table is always written to:

    forward_drift_bin_edges.csv.


Per-bin point estimates
-----------------------
For representation r and abundance bin b, the script calculates:

    n_b
        Number of contributing transition rows.

    n_subjects_b
        Number of subjects represented.

    x_mean_b
    x_median_b

    mean_dx_b
        Mean longitudinal displacement.

    median_dx_b
        Median longitudinal displacement.

    p_dx_gt0_b
        Fraction of displacements greater than zero.

    sd_dx_b
        Standard deviation of displacement.


Primary forward-drift curve
---------------------------
The primary curve reported for biological interpretation is:

    cross_combined mean_dx

as a function of abundance bin.

Conceptually:

    v(x)
        = E[Delta x | x0 = x, dt]

for the selected finite lag.

The script estimates this quantity nonparametrically through abundance-bin
averages.

It does not fit a predefined parametric drift law.


Subject-cluster bootstrap
-------------------------
Uncertainty in binned mean displacement and positive-displacement probability
is estimated by bootstrap resampling at the SUBJECT level.

The number of bootstrap replicates is controlled by:

    --n-bootstrap

with default:

    2000.

The random seed is controlled by:

    --bootstrap-seed

with default:

    123.


Compact sufficient statistics
------------------------------
For each:

    representation x subject x bin

the script stores:

    n
    sum_dx
    n_pos.

For bootstrap replicate k, subjects are sampled with replacement.

Subject multiplicities are then applied to these sufficient statistics to
reconstruct:

    mean_dx

and:

    P(Delta x > 0)

for every representation and abundance bin.

All representations use the SAME subject bootstrap draw.


AB/BA bootstrap combination
---------------------------
Within each bootstrap draw:

    cross_AB

and:

    cross_BA

are reconstructed separately and then combined as:

    cross_combined
        = (cross_AB + cross_BA) / 2.

Thus the bootstrap preserves the paired AB/BA structure.

The analysis explicitly does NOT assume AB/BA independence.


Bootstrap confidence intervals
------------------------------
For each representation and bin, the script calculates:

    mean_dx_ci025
    mean_dx_ci975

and:

    p_dx_gt0_ci025
    p_dx_gt0_ci975

from the 2.5th and 97.5th percentiles of the subject-bootstrap distributions.

The number of valid bootstrap values is recorded as:

    n_bootstrap_valid.

Important:

    bootstrap confidence intervals are NOT calculated for median_dx.

The median remains a point estimate only.


Matched same-versus-cross analysis
----------------------------------
For each reciprocal fold, the script compares same-replicate and
replicate-decoupled estimates on matched bins:

    same_A versus cross_AB
    same_B versus cross_BA.

It reports quantities including:

    mean_dx_same
    mean_dx_cross

    p_dx_gt0_same
    p_dx_gt0_cross

    delta_mean_same_minus_cross
    delta_p_same_minus_cross.

When bootstrap output is available, confidence intervals for the difference in
mean displacement are also calculated.


Technical reliability by abundance bin
--------------------------------------
For AB and BA separately, the script summarizes posterior uncertainty across
the conditioning abundance bins.

Metrics include:

    median_cond_sd

        Median posterior SD of the replicate used for conditioning.

    median_outcome_sd_t0
    median_outcome_sd_t1

        Median posterior SDs of the replicate used for the outcome.

When all replicate-count columns are available, it additionally reports:

    fraction_four_positive

        Fraction of transitions with positive counts in all four
        replicate-by-endpoint cells.

    median_min_count_four

        Median of the minimum count across those four cells.

These are technical reliability diagnostics and are not used as automatic
filters or weights in the primary forward estimator.


Global directional summaries
----------------------------
For each representation, the script calculates compact descriptors across
valid abundance bins:

    n_bins_valid

    mean_abs_bin_mean_dx
        = mean_b |mean_dx_b|

    max_abs_bin_mean_dx
        = max_b |mean_dx_b|

    rms_bin_mean_dx
        = sqrt(mean_b mean_dx_b^2)

    mean_abs_p_bias
        = mean_b |P(Delta x > 0)_b - 0.5|.

These summarize the magnitude of abundance-dependent directional structure.

They do not replace the full binned forward-drift curve.


Subject-level robustness
------------------------
For the primary `cross_combined` estimator, the script reconstructs one
replicate-decoupled forward curve for each subject.

For subject s and bin b:

    mean_cross,s,b
        = [mean_AB,s,b + mean_BA,s,b] / 2.

The corresponding positive-displacement probabilities are combined in the same
way.

These outputs allow direct assessment of between-subject consistency.


Leave-one-subject-out robustness
--------------------------------
The script also recomputes the primary cross_combined curve after omitting each
subject in turn.

For omitted subject s:

    all other subjects are pooled within AB and BA separately;

    the two folds are then combined with equal weight.

This evaluates whether the cohort-level forward profile is dominated by any
single subject.


AB/BA fold concordance
----------------------
The two reciprocal primary folds are compared across matched abundance bins.

The fold-concordance summary reports:

    n_matched_bins

    Pearson correlation between:
        mean_dx_AB
        mean_dx_BA

    mean_abs_difference

    rms_difference

    max_abs_difference.

Fold concordance is a technical consistency diagnostic.

It does not convert AB and BA into independent replicates.


Memory-bounded transition construction
--------------------------------------
Step 9 builds the specialized cross-fit transition dataset subject by subject
and temporal pair by temporal pair.

Each completed block is written as a Parquet part in:

    .forward_longitudinal_parts_dt<dt>/

and can be reused on subsequent runs.

Use:

    --restart

to delete and rebuild these resumable transition parts.

The final specialized transition table is assembled by streaming concatenation
rather than a global in-memory sort.


Outputs
-------
The output directory contains:


1. forward_longitudinal_transitions_wide.parquet
------------------------------------------------
Specialized TT transition table containing the joint, same-replicate,
cross-fitted and sensitivity representations required by Step 9.


2. forward_drift_bin_edges.csv
------------------------------
Common abundance-bin definition:

    bin
    x_left
    x_right
    x_center.


3. forward_drift_by_bin.csv
---------------------------
Principal binned output containing all available representations, including:

    cross_AB
    cross_BA
    cross_combined

together with comparators and sensitivity representations.

When bootstrap is enabled, mean-displacement and positive-probability
confidence intervals are joined to this table.


4. forward_drift_by_fold.csv
----------------------------
Fold-specific binned results for available AB/BA, same-replicate,
median-sensitivity and observed-frequency representations.


5. forward_drift_sensitivity_by_fold.csv
----------------------------------------
Fold-level sensitivity outputs excluding the two primary cross_AB/cross_BA
rows.


6. forward_drift_matched_same_vs_cross.csv
------------------------------------------
Matched same-replicate versus cross-fitted comparisons for folds A and B.


7. forward_drift_reliability_by_bin.csv
---------------------------------------
Posterior-uncertainty and count-support diagnostics across abundance bins.


8. forward_drift_global_summary.csv
-----------------------------------
Compact global descriptors of binned directional structure for each
representation.


9. forward_drift_subject_bin_sufficient.parquet
-----------------------------------------------
Compact subject-by-bin sufficient statistics used for bootstrap and
robustness calculations.


10. forward_drift_subject_by_bin.csv
------------------------------------
Subject-specific cross_combined forward-drift curves, written when available.


11. forward_drift_loso_by_bin.csv
---------------------------------
Leave-one-subject-out cross_combined forward-drift curves, written when
available.


12. forward_drift_fold_concordance.csv
--------------------------------------
AB/BA matched-bin concordance summary, written when available.


13. forward_drift_bootstrap_draws.parquet
-----------------------------------------
Optional complete subject-bootstrap draws.

This large output is written only when:

    --keep-bootstrap-draws

is specified.


14. 00_run_config.json
----------------------
Compact reproducibility configuration containing:

    script/version;
    dataset label;
    trajectory input;
    output directory;
    dt;
    binning parameters;
    bootstrap parameters;
    primary representation.


15. forward_longitudinal_report.json
------------------------------------
Detailed machine-readable analysis report containing:

    primary estimand;
    primary representation;
    input trajectory table;
    TT observability rule;
    transition count;
    subject count;
    AB/BA construction;
    comparators;
    binning policy;
    bootstrap policy;
    transition-build report;
    output paths.


Primary run
-----------
A standard genuine-longitudinal Step-9 analysis is:

    python3 9-replicate_decoupled_forward_drift.py \
        --trajectories \
        ./results/4-latent_trajectory_construction/latent_trajectories_long.parquet \
        --dataset-label healthy_longitudinal \
        --outdir \
        ./results/9-replicate_decoupled_forward_drift \
        --dt 1 \
        --n-bins 20 \
        --binning quantile \
        --q-low 0.005 \
        --q-high 0.995 \
        --n-bootstrap 2000 \
        --bootstrap-seed 123 \
        --parquet-compression zstd \
        --parquet-row-group-size 100000


Interpretation
--------------
Step 9 asks:

    "After removing direct same-replicate baseline-displacement coupling, does
     genuine longitudinal clonotype displacement retain a systematic
     abundance-dependent forward structure?"

The primary answer is provided by:

    cross_combined

using replicate-decoupled initial-state conditioning.

Same-replicate, naive-x0, xstar, posterior-median and observed-frequency
representations are retained as diagnostics or sensitivity analyses.

This Step estimates forward directional structure only.

It does NOT estimate the full conditional variance, diffusion coefficient,
mean-squared-displacement temporal scaling or a predefined stochastic process.
Those belong to subsequent ClonoDynamics analytical steps.
"""

from __future__ import annotations

import argparse
import gc
import json
import math
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

try:
    import polars as pl
except Exception as exc:
    raise SystemExit(
        "ERROR: polars is required. Activate the project venv and install polars."
    ) from exc


SCRIPT_VERSION = "v1-replicate-decoupled-forward-drift-step9-2026-08-24"

REQUIRED_COLUMNS = [
    "subject",
    "aaSeqCDR3",
    "time",
    "observable",
    "x_latent",
    "rep1_x_latent_mean",
    "rep1_x_latent_median",
    "rep1_x_latent_sd",
    "rep2_x_latent_mean",
    "rep2_x_latent_median",
    "rep2_x_latent_sd",
]

OPTIONAL_COLUMNS = [
    "x_latent_sd",
    "log_freq_sd",
    "count_rep1",
    "count_rep2",
    "depth_rep1",
    "depth_rep2",
]

BASE_REPRESENTATIONS = ["naive_x0", "xstar", "cross_AB", "cross_BA"]
SENSITIVITY_REPRESENTATIONS = [
    "same_A", "same_B",
    "cross_median_AB", "cross_median_BA",
    "observed_cross_AB", "observed_cross_BA",
]


def eprint(*args: Any, **kwargs: Any) -> None:
    print(*args, file=sys.stderr, **kwargs)


def ensure_dir(path: Path) -> Path:
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def collect_streaming(lf: pl.LazyFrame) -> pl.DataFrame:
    try:
        return lf.collect(engine="streaming")
    except TypeError:
        return lf.collect(streaming=True)


def sink_parquet_streaming(
    lf: pl.LazyFrame,
    path: Path,
    compression: str,
    row_group_size: int,
) -> None:
    ensure_dir(path.parent)
    kwargs: Dict[str, Any] = {
        "compression": compression,
        "statistics": True,
        "maintain_order": True,
    }
    if int(row_group_size) > 0:
        kwargs["row_group_size"] = int(row_group_size)
    try:
        lf.sink_parquet(path, engine="streaming", mkdir=True, **kwargs)
    except TypeError:
        try:
            lf.sink_parquet(path, **kwargs)
        except TypeError:
            kwargs.pop("row_group_size", None)
            lf.sink_parquet(path, **kwargs)


def schema_names(path: Path) -> List[str]:
    return list(pl.scan_parquet(path).collect_schema().names())


def parse_bool_expr(column: str) -> pl.Expr:
    # The Step-4 trajectory constructor normally writes Boolean observable, but keep this tolerant.
    s = pl.col(column)
    return (
        pl.when(s.cast(pl.Boolean, strict=False).is_not_null())
        .then(s.cast(pl.Boolean, strict=False).fill_null(False))
        .otherwise(
            s.cast(pl.String, strict=False)
            .str.strip_chars()
            .str.to_lowercase()
            .is_in(["true", "t", "1", "yes", "y", "observable", "detected", "detectable"])
            .fill_null(False)
        )
    )


def discover_subject_times(path: Path) -> Dict[int, List[int]]:
    df = collect_streaming(
        pl.scan_parquet(path)
        .select(
            pl.col("subject").cast(pl.Int64, strict=False),
            pl.col("time").cast(pl.Int64, strict=False),
        )
        .drop_nulls()
        .unique()
        .sort(["subject", "time"])
    )
    out: Dict[int, List[int]] = {}
    for row in df.iter_rows(named=True):
        out.setdefault(int(row["subject"]), []).append(int(row["time"]))
    return out


def xobs_expr(count_col: str, depth_col: str, alias: str) -> pl.Expr:
    count = pl.col(count_col).cast(pl.Float64, strict=False)
    depth = pl.col(depth_col).cast(pl.Float64, strict=False)
    return (
        pl.when((count > 0) & (depth > 0))
        .then((count / depth).log())
        .otherwise(pl.lit(float("nan"), dtype=pl.Float64))
        .alias(alias)
    )


def load_subject(path: Path, subject: int, available: Sequence[str]) -> pl.DataFrame:
    cols = list(REQUIRED_COLUMNS)
    for c in OPTIONAL_COLUMNS:
        if c in available and c not in cols:
            cols.append(c)

    lf = (
        pl.scan_parquet(path)
        .filter(pl.col("subject").cast(pl.Int64, strict=False) == int(subject))
        .select([pl.col(c) for c in cols])
        .with_columns(
            [
                pl.col("subject").cast(pl.Int64, strict=False),
                pl.col("time").cast(pl.Int64, strict=False),
                pl.col("aaSeqCDR3").cast(pl.String, strict=False),
                parse_bool_expr("observable").alias("observable"),
            ]
        )
    )

    # Derive per-replicate observed log frequencies for optional sensitivity.
    if {"count_rep1", "count_rep2", "depth_rep1", "depth_rep2"}.issubset(set(cols)):
        lf = lf.with_columns(
            [
                xobs_expr("count_rep1", "depth_rep1", "rep1_x_obs"),
                xobs_expr("count_rep2", "depth_rep2", "rep2_x_obs"),
            ]
        )
    return collect_streaming(lf)


def endpoint_frame(subject_df: pl.DataFrame, time_value: int, suffix: str) -> pl.DataFrame:
    # TT-only first analysis: filter detectable/observable states before joining.
    endpoint = (
        subject_df
        .filter((pl.col("time") == int(time_value)) & pl.col("observable"))
        .drop(["subject", "time", "observable"])
    )
    rename_map = {
        c: "%s_%s" % (c, suffix)
        for c in endpoint.columns
        if c != "aaSeqCDR3"
    }
    return endpoint.rename(rename_map)


def build_pair(subject_df: pl.DataFrame, subject: int, t0: int, t1: int) -> pl.DataFrame:
    a = endpoint_frame(subject_df, t0, "t0")
    b = endpoint_frame(subject_df, t1, "t1")
    joined = a.join(b, on="aaSeqCDR3", how="inner")
    del a, b

    if joined.height == 0:
        return pl.DataFrame()

    x0 = pl.col("x_latent_t0").cast(pl.Float64, strict=False)
    x1 = pl.col("x_latent_t1").cast(pl.Float64, strict=False)
    dx = x1 - x0

    # The Step-4 trajectory table exposes x_latent_sd when available. Fall back to log_freq_sd.
    sd0_name = None
    sd1_name = None
    if {"x_latent_sd_t0", "x_latent_sd_t1"}.issubset(set(joined.columns)):
        sd0_name, sd1_name = "x_latent_sd_t0", "x_latent_sd_t1"
    elif {"log_freq_sd_t0", "log_freq_sd_t1"}.issubset(set(joined.columns)):
        sd0_name, sd1_name = "log_freq_sd_t0", "log_freq_sd_t1"

    midpoint = 0.5 * (x0 + x1)
    if sd0_name is not None and sd1_name is not None:
        sd0 = pl.col(sd0_name).cast(pl.Float64, strict=False)
        sd1 = pl.col(sd1_name).cast(pl.Float64, strict=False)
        valid = sd0.is_finite() & sd1.is_finite() & (sd0 > 0) & (sd1 > 0)
        w0 = 1.0 / (sd0.pow(2) + 1e-12)
        w1 = 1.0 / (sd1.pow(2) + 1e-12)
        xstar = pl.when(valid).then((w0 * x0 + w1 * x1) / (w0 + w1)).otherwise(midpoint)
        xstar_source = pl.when(valid).then(pl.lit("inverse_variance_weighted")).otherwise(pl.lit("midpoint_fallback"))
    else:
        xstar = midpoint
        xstar_source = pl.lit("midpoint_fallback")

    r1_mean0 = pl.col("rep1_x_latent_mean_t0").cast(pl.Float64, strict=False)
    r1_mean1 = pl.col("rep1_x_latent_mean_t1").cast(pl.Float64, strict=False)
    r2_mean0 = pl.col("rep2_x_latent_mean_t0").cast(pl.Float64, strict=False)
    r2_mean1 = pl.col("rep2_x_latent_mean_t1").cast(pl.Float64, strict=False)

    r1_med0 = pl.col("rep1_x_latent_median_t0").cast(pl.Float64, strict=False)
    r1_med1 = pl.col("rep1_x_latent_median_t1").cast(pl.Float64, strict=False)
    r2_med0 = pl.col("rep2_x_latent_median_t0").cast(pl.Float64, strict=False)
    r2_med1 = pl.col("rep2_x_latent_median_t1").cast(pl.Float64, strict=False)

    exprs: List[pl.Expr] = [
        pl.lit(int(subject), dtype=pl.Int64).alias("subject"),
        pl.col("aaSeqCDR3"),
        pl.lit(int(t0), dtype=pl.Int64).alias("t0"),
        pl.lit(int(t1), dtype=pl.Int64).alias("t1"),
        pl.lit(int(t1 - t0), dtype=pl.Int64).alias("dt"),
        x0.alias("x0_joint"),
        x1.alias("x1_joint"),
        dx.alias("dx_joint"),
        midpoint.alias("xmid_joint"),
        xstar.alias("xstar_joint"),
        xstar_source.alias("xstar_source"),
        # Primary replicate-decoupled cross-fit (median conditioning, mean displacement).
        r1_med0.alias("xcond_cross_AB"),
        (r2_mean1 - r2_mean0).alias("dx_cross_AB"),
        r2_med0.alias("xcond_cross_BA"),
        (r1_mean1 - r1_mean0).alias("dx_cross_BA"),

        # Matched same-replicate controls. Conditioning is IDENTICAL to its
        # paired cross-fit fold; only the outcome arm changes.
        r1_med0.alias("xcond_same_A"),
        (r1_mean1 - r1_mean0).alias("dx_same_A"),
        r2_med0.alias("xcond_same_B"),
        (r2_mean1 - r2_mean0).alias("dx_same_B"),

        # Median-to-median cross-fit sensitivity.
        r1_med0.alias("xcond_cross_median_AB"),
        (r2_med1 - r2_med0).alias("dx_cross_median_AB"),
        r2_med0.alias("xcond_cross_median_BA"),
        (r1_med1 - r1_med0).alias("dx_cross_median_BA"),
        r1_mean0.alias("rep1_x0_mean"),
        r1_mean1.alias("rep1_x1_mean"),
        r2_mean0.alias("rep2_x0_mean"),
        r2_mean1.alias("rep2_x1_mean"),
        r1_med0.alias("rep1_x0_median"),
        r1_med1.alias("rep1_x1_median"),
        r2_med0.alias("rep2_x0_median"),
        r2_med1.alias("rep2_x1_median"),
        (r1_med1 - r1_med0).alias("dx_rep1_median"),
        (r2_med1 - r2_med0).alias("dx_rep2_median"),
        pl.col("rep1_x_latent_sd_t0").cast(pl.Float64, strict=False).alias("rep1_x0_sd"),
        pl.col("rep1_x_latent_sd_t1").cast(pl.Float64, strict=False).alias("rep1_x1_sd"),
        pl.col("rep2_x_latent_sd_t0").cast(pl.Float64, strict=False).alias("rep2_x0_sd"),
        pl.col("rep2_x_latent_sd_t1").cast(pl.Float64, strict=False).alias("rep2_x1_sd"),
    ]

    if sd0_name is not None and sd1_name is not None:
        exprs.extend(
            [
                pl.col(sd0_name).cast(pl.Float64, strict=False).alias("x0_joint_sd"),
                pl.col(sd1_name).cast(pl.Float64, strict=False).alias("x1_joint_sd"),
            ]
        )

    # Optional count/depth fields and observed cross-fit sensitivity.
    for c in ["count_rep1", "count_rep2", "depth_rep1", "depth_rep2"]:
        c0 = "%s_t0" % c
        c1 = "%s_t1" % c
        if c0 in joined.columns:
            exprs.append(pl.col(c0).alias("%s_0" % c))
        if c1 in joined.columns:
            exprs.append(pl.col(c1).alias("%s_1" % c))

    if {"rep1_x_obs_t0", "rep1_x_obs_t1", "rep2_x_obs_t0", "rep2_x_obs_t1"}.issubset(set(joined.columns)):
        exprs.extend(
            [
                pl.col("rep1_x_obs_t0").alias("xcond_obs_AB"),
                (pl.col("rep2_x_obs_t1") - pl.col("rep2_x_obs_t0")).alias("dx_obs_cross_AB"),
                pl.col("rep2_x_obs_t0").alias("xcond_obs_BA"),
                (pl.col("rep1_x_obs_t1") - pl.col("rep1_x_obs_t0")).alias("dx_obs_cross_BA"),
            ]
        )

    out = joined.select(exprs)
    # Guard against malformed posterior summaries without altering valid tails.
    core = ["x0_joint", "x1_joint", "xcond_cross_AB", "dx_cross_AB", "xcond_cross_BA", "dx_cross_BA"]
    filt = pl.lit(True)
    for c in core:
        filt = filt & pl.col(c).is_not_null() & pl.col(c).is_finite()
    return out.filter(filt).sort("aaSeqCDR3")


def write_transition_parts(
    trajectories: Path,
    parts_dir: Path,
    dt: int,
    compression: str,
    row_group_size: int,
    restart: bool,
) -> Tuple[List[Path], Dict[str, Any]]:
    available = schema_names(trajectories)
    missing = [c for c in REQUIRED_COLUMNS if c not in available]
    if missing:
        raise ValueError(
            "Longitudinal trajectory table is missing required replicate-decoupling columns: %s" % missing
        )

    if restart and parts_dir.exists():
        shutil.rmtree(parts_dir)
    ensure_dir(parts_dir)

    subject_times = discover_subject_times(trajectories)
    all_parts: List[Path] = []
    report_rows: List[Dict[str, Any]] = []

    for subject in sorted(subject_times):
        times = sorted(subject_times[subject])
        valid_pairs = [(t, t + int(dt)) for t in times if (t + int(dt)) in set(times)]
        if not valid_pairs:
            eprint("[subject %s] no dt=%s pairs" % (subject, dt))
            continue

        eprint("[subject %s] loading trajectory states..." % subject)
        sdf = load_subject(trajectories, subject, available)
        eprint("[subject %s] states=%s pairs=%s" % (subject, sdf.height, len(valid_pairs)))

        for t0, t1 in valid_pairs:
            part = parts_dir / ("subject_%s_t%s_t%s.parquet" % (subject, t0, t1))
            if part.exists() and not restart:
                eprint("  [reuse] %s" % part.name)
                all_parts.append(part)
                continue

            pair = build_pair(sdf, subject, t0, t1)
            n = int(pair.height)
            eprint("  [pair %s->%s] TT transitions=%s" % (t0, t1, n))
            if n == 0:
                report_rows.append({"subject": subject, "t0": t0, "t1": t1, "n_tt": 0})
                continue
            pair.write_parquet(
                part,
                compression=compression,
                statistics=True,
                row_group_size=int(row_group_size) if int(row_group_size) > 0 else None,
            )
            all_parts.append(part)
            report_rows.append({"subject": subject, "t0": t0, "t1": t1, "n_tt": n})
            del pair
            gc.collect()

        del sdf
        gc.collect()

    report = {
        "dt": int(dt),
        "n_subjects_input": len(subject_times),
        "n_parts": len(all_parts),
        "pairs": report_rows,
    }
    return all_parts, report


def merge_parts(parts: Sequence[Path], out_path: Path, compression: str, row_group_size: int) -> None:
    if not parts:
        raise RuntimeError("No cross-fit transition parts were generated.")
    pattern = str(parts[0].parent / "*.parquet")
    # Do not globally sort here: transition parts are already ordered locally and
    # a global sort would defeat the memory-bounded design on large cohorts.
    lf = pl.scan_parquet(pattern)
    if out_path.exists():
        out_path.unlink()
    sink_parquet_streaming(lf, out_path, compression, row_group_size)


def read_edges_file(path: Path) -> np.ndarray:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        df = pl.read_csv(path)
    elif suffix in {".parquet", ".pq"}:
        df = pl.read_parquet(path)
    else:
        vals = []
        for line in path.read_text().splitlines():
            line = line.strip()
            if line:
                vals.append(float(line))
        arr = np.asarray(vals, dtype=float)
        if arr.size < 2:
            raise ValueError("Bin edge file must contain at least two numeric values.")
        return np.unique(arr)

    candidates = [c for c in ["edge", "bin_edge", "x_edge"] if c in df.columns]
    if candidates:
        arr = df[candidates[0]].to_numpy()
    elif {"x_left", "x_right"}.issubset(set(df.columns)):
        left = df["x_left"].to_numpy()
        right = df["x_right"].to_numpy()
        arr = np.concatenate([left[:1], right])
    else:
        raise ValueError("Could not infer bin edges from %s" % path)
    arr = np.asarray(arr, dtype=float)
    arr = arr[np.isfinite(arr)]
    arr = np.unique(arr)
    if arr.size < 2:
        raise ValueError("Bin edge file must contain at least two finite unique values.")
    return arr


def estimate_edges(
    transitions: Path,
    n_bins: int,
    mode: str,
    q_low: float,
    q_high: float,
) -> np.ndarray:
    x = (
        pl.scan_parquet(transitions)
        .select(pl.col("x0_joint").cast(pl.Float64, strict=False).alias("x"))
        .filter(pl.col("x").is_finite())
    )

    if mode == "quantile":
        probs = np.linspace(float(q_low), float(q_high), int(n_bins) + 1)
        exprs = [pl.col("x").quantile(float(q), interpolation="linear").alias("q_%04d" % i) for i, q in enumerate(probs)]
        row = collect_streaming(x.select(exprs)).row(0)
        edges = np.asarray(row, dtype=float)
    elif mode == "equal_width":
        qs = collect_streaming(
            x.select(
                [
                    pl.col("x").quantile(float(q_low), interpolation="linear").alias("lo"),
                    pl.col("x").quantile(float(q_high), interpolation="linear").alias("hi"),
                ]
            )
        )
        lo = float(qs["lo"][0])
        hi = float(qs["hi"][0])
        edges = np.linspace(lo, hi, int(n_bins) + 1)
    else:
        raise ValueError("Unknown binning mode: %s" % mode)

    edges = edges[np.isfinite(edges)]
    edges = np.unique(edges)
    if edges.size < 3:
        raise RuntimeError("Could not construct enough unique bin edges.")
    return edges


def save_edges(edges: np.ndarray, out_path: Path) -> None:
    rows = []
    for i in range(len(edges) - 1):
        rows.append(
            {
                "bin": i,
                "x_left": float(edges[i]),
                "x_right": float(edges[i + 1]),
                "x_center": float(0.5 * (edges[i] + edges[i + 1])),
            }
        )
    pl.DataFrame(rows).write_csv(out_path)


def bin_expr(x_col: str, edges: np.ndarray) -> pl.Expr:
    x = pl.col(x_col).cast(pl.Float64, strict=False)
    expr = pl.lit(None, dtype=pl.Int32)
    # Reverse nesting keeps the first bin conditions outermost after construction.
    for i in range(len(edges) - 2, -1, -1):
        lo = float(edges[i])
        hi = float(edges[i + 1])
        if i == len(edges) - 2:
            cond = (x >= lo) & (x <= hi)
        else:
            cond = (x >= lo) & (x < hi)
        expr = pl.when(cond).then(pl.lit(i, dtype=pl.Int32)).otherwise(expr)
    return expr.alias("bin")


def representation_columns(name: str) -> Tuple[str, str]:
    if name == "naive_x0":
        return "x0_joint", "dx_joint"
    if name == "xstar":
        return "xstar_joint", "dx_joint"
    if name == "cross_AB":
        return "xcond_cross_AB", "dx_cross_AB"
    if name == "cross_BA":
        return "xcond_cross_BA", "dx_cross_BA"
    if name == "same_A":
        return "xcond_same_A", "dx_same_A"
    if name == "same_B":
        return "xcond_same_B", "dx_same_B"
    if name == "cross_median_AB":
        return "xcond_cross_median_AB", "dx_cross_median_AB"
    if name == "cross_median_BA":
        return "xcond_cross_median_BA", "dx_cross_median_BA"
    if name == "observed_cross_AB":
        return "xcond_obs_AB", "dx_obs_cross_AB"
    if name == "observed_cross_BA":
        return "xcond_obs_BA", "dx_obs_cross_BA"
    raise ValueError(name)


def point_stats_one(transitions: Path, edges: np.ndarray, name: str) -> pl.DataFrame:
    x_col, dx_col = representation_columns(name)
    lf = (
        pl.scan_parquet(transitions)
        .select(
            [
                pl.col("subject"),
                pl.col(x_col).cast(pl.Float64, strict=False).alias("x"),
                pl.col(dx_col).cast(pl.Float64, strict=False).alias("dx"),
            ]
        )
        .filter(pl.col("x").is_finite() & pl.col("dx").is_finite())
        .with_columns(bin_expr("x", edges))
        .filter(pl.col("bin").is_not_null())
        .group_by("bin")
        .agg(
            [
                pl.len().alias("n"),
                pl.col("subject").n_unique().alias("n_subjects"),
                pl.col("x").mean().alias("x_mean"),
                pl.col("x").median().alias("x_median"),
                pl.col("dx").mean().alias("mean_dx"),
                pl.col("dx").median().alias("median_dx"),
                (pl.col("dx") > 0).mean().alias("p_dx_gt0"),
                pl.col("dx").std().alias("sd_dx"),
            ]
        )
        .sort("bin")
    )
    out = collect_streaming(lf).with_columns(pl.lit(name).alias("representation"))
    return out


def subject_sufficient_stats_one(transitions: Path, edges: np.ndarray, name: str) -> pl.DataFrame:
    x_col, dx_col = representation_columns(name)
    lf = (
        pl.scan_parquet(transitions)
        .select(
            [
                pl.col("subject").cast(pl.Int64, strict=False),
                pl.col(x_col).cast(pl.Float64, strict=False).alias("x"),
                pl.col(dx_col).cast(pl.Float64, strict=False).alias("dx"),
            ]
        )
        .filter(pl.col("x").is_finite() & pl.col("dx").is_finite())
        .with_columns(bin_expr("x", edges))
        .filter(pl.col("bin").is_not_null())
        .group_by(["subject", "bin"])
        .agg(
            [
                pl.len().alias("n"),
                pl.col("dx").sum().alias("sum_dx"),
                (pl.col("dx") > 0).sum().alias("n_pos"),
            ]
        )
        .sort(["subject", "bin"])
    )
    return collect_streaming(lf).with_columns(pl.lit(name).alias("representation"))


def combine_cross_point(ab: pl.DataFrame, ba: pl.DataFrame, edges: np.ndarray) -> pl.DataFrame:
    a = ab.select(
        [
            "bin",
            pl.col("n").alias("n_AB"),
            pl.col("n_subjects").alias("n_subjects_AB"),
            pl.col("x_mean").alias("x_mean_AB"),
            pl.col("mean_dx").alias("mean_dx_AB"),
            pl.col("median_dx").alias("median_dx_AB"),
            pl.col("p_dx_gt0").alias("p_dx_gt0_AB"),
        ]
    )
    b = ba.select(
        [
            "bin",
            pl.col("n").alias("n_BA"),
            pl.col("n_subjects").alias("n_subjects_BA"),
            pl.col("x_mean").alias("x_mean_BA"),
            pl.col("mean_dx").alias("mean_dx_BA"),
            pl.col("median_dx").alias("median_dx_BA"),
            pl.col("p_dx_gt0").alias("p_dx_gt0_BA"),
        ]
    )
    out = a.join(b, on="bin", how="full", coalesce=True).sort("bin")
    edge_df = pl.DataFrame(
        {
            "bin": np.arange(len(edges) - 1, dtype=np.int32),
            "x_left": edges[:-1],
            "x_right": edges[1:],
            "x_center": 0.5 * (edges[:-1] + edges[1:]),
        }
    )
    out = edge_df.join(out, on="bin", how="left")
    out = out.with_columns(
        [
            (0.5 * (pl.col("mean_dx_AB") + pl.col("mean_dx_BA"))).alias("mean_dx"),
            (0.5 * (pl.col("median_dx_AB") + pl.col("median_dx_BA"))).alias("median_dx"),
            (0.5 * (pl.col("p_dx_gt0_AB") + pl.col("p_dx_gt0_BA"))).alias("p_dx_gt0"),
            (0.5 * (pl.col("x_mean_AB") + pl.col("x_mean_BA"))).alias("x_mean"),
            pl.min_horizontal("n_subjects_AB", "n_subjects_BA").alias("n_subjects"),
            pl.lit("cross_combined").alias("representation"),
        ]
    )
    return out


def bootstrap_from_sufficient(
    suff_by_rep: Dict[str, pl.DataFrame],
    edges: np.ndarray,
    n_bootstrap: int,
    seed: int,
) -> pl.DataFrame:
    if n_bootstrap <= 0:
        return pl.DataFrame()

    all_subjects = sorted(
        {
            int(v)
            for df in suff_by_rep.values()
            for v in df["subject"].unique().to_list()
        }
    )
    if len(all_subjects) < 2:
        raise RuntimeError("Need at least two subjects for subject-cluster bootstrap.")

    n_bins = len(edges) - 1
    subj_to_i = {s: i for i, s in enumerate(all_subjects)}
    arrays: Dict[str, Tuple[np.ndarray, np.ndarray, np.ndarray]] = {}

    for name, df in suff_by_rep.items():
        n_arr = np.zeros((len(all_subjects), n_bins), dtype=np.float64)
        sum_arr = np.zeros_like(n_arr)
        pos_arr = np.zeros_like(n_arr)
        for row in df.iter_rows(named=True):
            i = subj_to_i[int(row["subject"])]
            b = int(row["bin"])
            n_arr[i, b] = float(row["n"])
            sum_arr[i, b] = float(row["sum_dx"])
            pos_arr[i, b] = float(row["n_pos"])
        arrays[name] = (n_arr, sum_arr, pos_arr)

    rng = np.random.default_rng(int(seed))
    records: List[Dict[str, Any]] = []
    for boot in range(int(n_bootstrap)):
        draw = rng.integers(0, len(all_subjects), size=len(all_subjects))
        multiplicity = np.bincount(draw, minlength=len(all_subjects)).astype(np.float64)[:, None]

        boot_vals: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}
        for name, (n_arr, sum_arr, pos_arr) in arrays.items():
            n = np.sum(multiplicity * n_arr, axis=0)
            s = np.sum(multiplicity * sum_arr, axis=0)
            p = np.sum(multiplicity * pos_arr, axis=0)
            mean_dx = np.divide(s, n, out=np.full(n_bins, np.nan), where=n > 0)
            p_pos = np.divide(p, n, out=np.full(n_bins, np.nan), where=n > 0)
            boot_vals[name] = (mean_dx, p_pos)

        # Every available representation is bootstrapped with the same subject draw.
        for name in sorted(boot_vals):
            mean_dx, p_pos = boot_vals[name]
            for b in range(n_bins):
                records.append(
                    {
                        "bootstrap": boot,
                        "representation": name,
                        "bin": b,
                        "mean_dx": float(mean_dx[b]),
                        "p_dx_gt0": float(p_pos[b]),
                    }
                )

        # Symmetric primary cross-fit: equal fold weight, not row concatenation.
        if "cross_AB" in boot_vals and "cross_BA" in boot_vals:
            ab_mean, ab_p = boot_vals["cross_AB"]
            ba_mean, ba_p = boot_vals["cross_BA"]
            cross_mean = 0.5 * (ab_mean + ba_mean)
            cross_p = 0.5 * (ab_p + ba_p)
            for b in range(n_bins):
                records.append(
                    {
                        "bootstrap": boot,
                        "representation": "cross_combined",
                        "bin": b,
                        "mean_dx": float(cross_mean[b]),
                        "p_dx_gt0": float(cross_p[b]),
                    }
                )

        # Symmetric median-to-median cross-fit sensitivity.
        if "cross_median_AB" in boot_vals and "cross_median_BA" in boot_vals:
            ab_mean, ab_p = boot_vals["cross_median_AB"]
            ba_mean, ba_p = boot_vals["cross_median_BA"]
            for b in range(n_bins):
                records.append({
                    "bootstrap": boot, "representation": "cross_median_combined", "bin": b,
                    "mean_dx": float(0.5 * (ab_mean[b] + ba_mean[b])),
                    "p_dx_gt0": float(0.5 * (ab_p[b] + ba_p[b])),
                })

    return pl.DataFrame(records)


def bootstrap_ci(boot: pl.DataFrame) -> pl.DataFrame:
    if boot.is_empty():
        return pl.DataFrame()
    return (
        boot.lazy()
        .filter(pl.col("mean_dx").is_finite())
        .group_by(["representation", "bin"])
        .agg(
            [
                pl.col("mean_dx").quantile(0.025, interpolation="linear").alias("mean_dx_ci025"),
                pl.col("mean_dx").quantile(0.975, interpolation="linear").alias("mean_dx_ci975"),
                pl.col("p_dx_gt0").quantile(0.025, interpolation="linear").alias("p_dx_gt0_ci025"),
                pl.col("p_dx_gt0").quantile(0.975, interpolation="linear").alias("p_dx_gt0_ci975"),
                pl.len().alias("n_bootstrap_valid"),
            ]
        )
        .sort(["representation", "bin"])
        .collect()
    )


def attach_edges(df: pl.DataFrame, edges: np.ndarray) -> pl.DataFrame:
    edge_df = pl.DataFrame(
        {
            "bin": np.arange(len(edges) - 1, dtype=np.int32),
            "x_left": edges[:-1],
            "x_right": edges[1:],
            "x_center": 0.5 * (edges[:-1] + edges[1:]),
        }
    )
    return edge_df.join(df, on="bin", how="left")


def build_summary(point_all: pl.DataFrame) -> pl.DataFrame:
    # Compact global descriptors of the binned directional signal.
    return (
        point_all.lazy()
        .filter(pl.col("mean_dx").is_finite())
        .group_by("representation")
        .agg(
            [
                pl.len().alias("n_bins_valid"),
                pl.col("mean_dx").abs().mean().alias("mean_abs_bin_mean_dx"),
                pl.col("mean_dx").abs().max().alias("max_abs_bin_mean_dx"),
                (pl.col("mean_dx").pow(2).mean().sqrt()).alias("rms_bin_mean_dx"),
                (pl.col("p_dx_gt0") - 0.5).abs().mean().alias("mean_abs_p_bias"),
            ]
        )
        .sort("representation")
        .collect()
    )


def available_representations(transitions: Path) -> List[str]:
    names = set(schema_names(transitions))
    out: List[str] = []
    for rep in BASE_REPRESENTATIONS + SENSITIVITY_REPRESENTATIONS:
        x_col, dx_col = representation_columns(rep)
        if x_col in names and dx_col in names:
            out.append(rep)
    return out


def matched_same_vs_cross(point: Dict[str, pl.DataFrame], boot: pl.DataFrame, edges: np.ndarray) -> pl.DataFrame:
    pairs = [("A", "same_A", "cross_AB"), ("B", "same_B", "cross_BA")]
    frames: List[pl.DataFrame] = []
    for fold, same_name, cross_name in pairs:
        if same_name not in point or cross_name not in point:
            continue
        same = point[same_name].select([
            "bin", pl.col("n").alias("n_same"), pl.col("n_subjects").alias("n_subjects_same"),
            pl.col("x_mean").alias("x_mean_same"), pl.col("mean_dx").alias("mean_dx_same"),
            pl.col("p_dx_gt0").alias("p_dx_gt0_same")])
        cross = point[cross_name].select([
            "bin", pl.col("n").alias("n_cross"), pl.col("n_subjects").alias("n_subjects_cross"),
            pl.col("x_mean").alias("x_mean_cross"), pl.col("mean_dx").alias("mean_dx_cross"),
            pl.col("p_dx_gt0").alias("p_dx_gt0_cross")])
        df = same.join(cross, on="bin", how="inner").with_columns([
            pl.lit(fold).alias("fold"),
            (pl.col("mean_dx_same") - pl.col("mean_dx_cross")).alias("delta_mean_same_minus_cross"),
            (pl.col("p_dx_gt0_same") - pl.col("p_dx_gt0_cross")).alias("delta_p_same_minus_cross"),
        ])
        if not boot.is_empty():
            bs = boot.filter(pl.col("representation") == same_name).select([
                "bootstrap", "bin", pl.col("mean_dx").alias("same_mean")])
            bc = boot.filter(pl.col("representation") == cross_name).select([
                "bootstrap", "bin", pl.col("mean_dx").alias("cross_mean")])
            bd = (bs.join(bc, on=["bootstrap", "bin"], how="inner")
                  .with_columns((pl.col("same_mean") - pl.col("cross_mean")).alias("delta"))
                  .group_by("bin").agg([
                      pl.col("delta").quantile(0.025, interpolation="linear").alias("delta_mean_ci025"),
                      pl.col("delta").quantile(0.975, interpolation="linear").alias("delta_mean_ci975")]))
            df = df.join(bd, on="bin", how="left")
        frames.append(attach_edges(df, edges))
    return pl.concat(frames, how="diagonal_relaxed").sort(["fold", "bin"]) if frames else pl.DataFrame()


def reliability_by_bin(transitions: Path, edges: np.ndarray) -> pl.DataFrame:
    names = set(schema_names(transitions))
    frames: List[pl.DataFrame] = []
    specs = [
        ("AB", "xcond_cross_AB", "rep1_x0_sd", "rep2_x0_sd", "rep2_x1_sd"),
        ("BA", "xcond_cross_BA", "rep2_x0_sd", "rep1_x0_sd", "rep1_x1_sd"),
    ]
    count_cols = ["count_rep1_0", "count_rep2_0", "count_rep1_1", "count_rep2_1"]
    has_counts = set(count_cols).issubset(names)
    for fold, xcol, cond_sd, out_sd0, out_sd1 in specs:
        if not {xcol, cond_sd, out_sd0, out_sd1}.issubset(names):
            continue
        exprs = [pl.col("subject"), pl.col(xcol).alias("x"), pl.col(cond_sd).alias("cond_sd"),
                 pl.col(out_sd0).alias("out_sd0"), pl.col(out_sd1).alias("out_sd1")]
        if has_counts:
            exprs += [pl.col(c).cast(pl.Float64, strict=False) for c in count_cols]
        lf = pl.scan_parquet(transitions).select(exprs).filter(pl.col("x").is_finite()).with_columns(bin_expr("x", edges)).filter(pl.col("bin").is_not_null())
        if has_counts:
            lf = lf.with_columns([
                pl.min_horizontal(*count_cols).alias("min_count_four"),
                pl.all_horizontal(*[(pl.col(c) > 0) for c in count_cols]).alias("four_positive"),
            ])
        aggs = [pl.len().alias("n"), pl.col("subject").n_unique().alias("n_subjects"),
                pl.col("cond_sd").median().alias("median_cond_sd"),
                pl.col("out_sd0").median().alias("median_outcome_sd_t0"),
                pl.col("out_sd1").median().alias("median_outcome_sd_t1")]
        if has_counts:
            aggs += [pl.col("four_positive").mean().alias("fraction_four_positive"),
                     pl.col("min_count_four").median().alias("median_min_count_four")]
        df = collect_streaming(lf.group_by("bin").agg(aggs).sort("bin")).with_columns(pl.lit(fold).alias("fold"))
        frames.append(attach_edges(df, edges))
    return pl.concat(frames, how="diagonal_relaxed").sort(["fold", "bin"]) if frames else pl.DataFrame()



def _sufficient_lookup(df: pl.DataFrame) -> Dict[Tuple[int, int], Tuple[float, float, float]]:
    """Map (subject, bin) -> (n, sum_dx, n_pos) for compact downstream diagnostics."""
    out: Dict[Tuple[int, int], Tuple[float, float, float]] = {}
    for row in df.iter_rows(named=True):
        out[(int(row["subject"]), int(row["bin"]))] = (
            float(row["n"]), float(row["sum_dx"]), float(row["n_pos"])
        )
    return out


def build_subject_cross_curves(
    suff_by_rep: Dict[str, pl.DataFrame],
    edges: np.ndarray,
) -> pl.DataFrame:
    """Subject-level primary cross_combined curves using equal AB/BA fold weight."""
    if "cross_AB" not in suff_by_rep or "cross_BA" not in suff_by_rep:
        return pl.DataFrame()
    ab = _sufficient_lookup(suff_by_rep["cross_AB"])
    ba = _sufficient_lookup(suff_by_rep["cross_BA"])
    subjects = sorted({s for s, _ in ab} | {s for s, _ in ba})
    rows: List[Dict[str, Any]] = []
    for subject in subjects:
        for b in range(len(edges) - 1):
            va = ab.get((subject, b))
            vb = ba.get((subject, b))
            if va is None or vb is None or va[0] <= 0 or vb[0] <= 0:
                continue
            mean_ab = va[1] / va[0]
            mean_ba = vb[1] / vb[0]
            p_ab = va[2] / va[0]
            p_ba = vb[2] / vb[0]
            rows.append({
                "subject": int(subject),
                "representation": "cross_combined",
                "bin": int(b),
                "x_left": float(edges[b]),
                "x_right": float(edges[b + 1]),
                "x_center": float(0.5 * (edges[b] + edges[b + 1])),
                "n_AB": int(va[0]),
                "n_BA": int(vb[0]),
                "mean_dx_AB": float(mean_ab),
                "mean_dx_BA": float(mean_ba),
                "mean_dx": float(0.5 * (mean_ab + mean_ba)),
                "p_dx_gt0_AB": float(p_ab),
                "p_dx_gt0_BA": float(p_ba),
                "p_dx_gt0": float(0.5 * (p_ab + p_ba)),
            })
    return pl.DataFrame(rows).sort(["subject", "bin"]) if rows else pl.DataFrame()


def build_loso_cross_curves(
    suff_by_rep: Dict[str, pl.DataFrame],
    edges: np.ndarray,
) -> pl.DataFrame:
    """Leave-one-subject-out primary curve; AB/BA remain equally weighted."""
    if "cross_AB" not in suff_by_rep or "cross_BA" not in suff_by_rep:
        return pl.DataFrame()
    ab = _sufficient_lookup(suff_by_rep["cross_AB"])
    ba = _sufficient_lookup(suff_by_rep["cross_BA"])
    subjects = sorted({s for s, _ in ab} | {s for s, _ in ba})
    if len(subjects) < 2:
        return pl.DataFrame()
    rows: List[Dict[str, Any]] = []
    for omitted in subjects:
        kept = [s for s in subjects if s != omitted]
        for b in range(len(edges) - 1):
            n_ab = sum(ab.get((s, b), (0.0, 0.0, 0.0))[0] for s in kept)
            sum_ab = sum(ab.get((s, b), (0.0, 0.0, 0.0))[1] for s in kept)
            pos_ab = sum(ab.get((s, b), (0.0, 0.0, 0.0))[2] for s in kept)
            n_ba = sum(ba.get((s, b), (0.0, 0.0, 0.0))[0] for s in kept)
            sum_ba = sum(ba.get((s, b), (0.0, 0.0, 0.0))[1] for s in kept)
            pos_ba = sum(ba.get((s, b), (0.0, 0.0, 0.0))[2] for s in kept)
            if n_ab <= 0 or n_ba <= 0:
                continue
            mean_ab = sum_ab / n_ab
            mean_ba = sum_ba / n_ba
            p_ab = pos_ab / n_ab
            p_ba = pos_ba / n_ba
            rows.append({
                "omitted_subject": int(omitted),
                "representation": "cross_combined",
                "bin": int(b),
                "x_left": float(edges[b]),
                "x_right": float(edges[b + 1]),
                "x_center": float(0.5 * (edges[b] + edges[b + 1])),
                "n_AB": int(n_ab),
                "n_BA": int(n_ba),
                "n_subjects_AB": int(sum(1 for s in kept if ab.get((s, b), (0.0, 0.0, 0.0))[0] > 0)),
                "n_subjects_BA": int(sum(1 for s in kept if ba.get((s, b), (0.0, 0.0, 0.0))[0] > 0)),
                "mean_dx_AB": float(mean_ab),
                "mean_dx_BA": float(mean_ba),
                "mean_dx": float(0.5 * (mean_ab + mean_ba)),
                "p_dx_gt0": float(0.5 * (p_ab + p_ba)),
            })
    return pl.DataFrame(rows).sort(["omitted_subject", "bin"]) if rows else pl.DataFrame()


def build_fold_concordance(point: Dict[str, pl.DataFrame]) -> pl.DataFrame:
    """Compact AB/BA agreement summary for the primary forward estimator."""
    if "cross_AB" not in point or "cross_BA" not in point:
        return pl.DataFrame()
    a = point["cross_AB"].select(["bin", pl.col("mean_dx").alias("AB")])
    b = point["cross_BA"].select(["bin", pl.col("mean_dx").alias("BA")])
    d = a.join(b, on="bin", how="inner").filter(pl.col("AB").is_finite() & pl.col("BA").is_finite())
    if d.height == 0:
        return pl.DataFrame()
    av = d["AB"].to_numpy().astype(float, copy=False)
    bv = d["BA"].to_numpy().astype(float, copy=False)
    diff = av - bv
    r = float(np.corrcoef(av, bv)[0, 1]) if av.size >= 2 and np.std(av) > 0 and np.std(bv) > 0 else float("nan")
    return pl.DataFrame([{
        "n_matched_bins": int(av.size),
        "pearson_r_AB_BA": r,
        "mean_abs_difference": float(np.mean(np.abs(diff))),
        "rms_difference": float(np.sqrt(np.mean(diff ** 2))),
        "max_abs_difference": float(np.max(np.abs(diff))),
    }])

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Step 9: replicate-decoupled forward drift for genuine longitudinal data from Step-4 latent trajectories."
    )
    p.add_argument("--trajectories", required=True, type=Path)
    p.add_argument("--dataset-label", default="healthy_longitudinal")
    p.add_argument("--outdir", required=True, type=Path)
    p.add_argument("--dt", type=int, default=1, help="Time lag. First analysis should use 1.")
    p.add_argument("--n-bins", type=int, default=20)
    p.add_argument("--binning", choices=["quantile", "equal_width"], default="quantile")
    p.add_argument("--q-low", type=float, default=0.005)
    p.add_argument("--q-high", type=float, default=0.995)
    p.add_argument("--bin-edges-file", type=Path, default=None,
                   help="Optional existing edges; use to enforce identical bins across datasets.")
    p.add_argument("--n-bootstrap", type=int, default=2000)
    p.add_argument("--bootstrap-seed", type=int, default=123)
    p.add_argument("--parquet-compression", default="zstd")
    p.add_argument("--parquet-row-group-size", type=int, default=100000)
    p.add_argument("--restart", action="store_true",
                   help="Delete resumable transition parts and rebuild them.")
    p.add_argument("--keep-bootstrap-draws", action="store_true",
                   help="Also save every bootstrap draw; default saves only CIs.")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    trajectories = args.trajectories.resolve()
    outdir = ensure_dir(args.outdir.resolve())
    parts_dir = outdir / (".forward_longitudinal_parts_dt%d" % int(args.dt))

    if not trajectories.exists():
        raise FileNotFoundError(trajectories)
    if int(args.dt) <= 0:
        raise ValueError("--dt must be positive")
    if int(args.n_bins) < 3:
        raise ValueError("--n-bins must be >= 3")
    if not (0.0 <= float(args.q_low) < float(args.q_high) <= 1.0):
        raise ValueError("Require 0 <= q-low < q-high <= 1")

    eprint("=== ClonoDynamics Step 9: replicate-decoupled forward drift ===")
    eprint("script version:", SCRIPT_VERSION)
    eprint("dataset:", args.dataset_label)
    eprint("trajectories:", trajectories)
    eprint("outdir:", outdir)
    eprint("dt:", args.dt)
    eprint("TT only: yes")

    parts, build_report = write_transition_parts(
        trajectories=trajectories,
        parts_dir=parts_dir,
        dt=int(args.dt),
        compression=str(args.parquet_compression),
        row_group_size=int(args.parquet_row_group_size),
        restart=bool(args.restart),
    )

    transitions_out = outdir / "forward_longitudinal_transitions_wide.parquet"
    eprint("Merging %s transition parts -> %s" % (len(parts), transitions_out.name))
    merge_parts(parts, transitions_out, str(args.parquet_compression), int(args.parquet_row_group_size))

    if args.bin_edges_file is not None:
        edges = read_edges_file(args.bin_edges_file)
        edge_source = str(args.bin_edges_file.resolve())
    else:
        edges = estimate_edges(
            transitions_out,
            n_bins=int(args.n_bins),
            mode=str(args.binning),
            q_low=float(args.q_low),
            q_high=float(args.q_high),
        )
        edge_source = "estimated_from_x0_joint"

    edges_out = outdir / "forward_drift_bin_edges.csv"
    save_edges(edges, edges_out)
    eprint("Bins:", len(edges) - 1, "source:", edge_source)

    reps = available_representations(transitions_out)
    required_new = {"same_A", "same_B", "cross_median_AB", "cross_median_BA"}
    missing_new = sorted(required_new.difference(reps))
    if missing_new:
        raise RuntimeError(
            "v3 transition table is missing required sensitivity representations %s. "
            "Old transition parts were probably reused; rerun with --restart." % missing_new
        )
    eprint("Sensitivity representations available:", ", ".join(reps))

    point: Dict[str, pl.DataFrame] = {}
    suff: Dict[str, pl.DataFrame] = {}
    for name in reps:
        eprint("Computing point statistics:", name)
        point[name] = point_stats_one(transitions_out, edges, name)
        suff[name] = subject_sufficient_stats_one(transitions_out, edges, name)

    point_frames: List[pl.DataFrame] = [attach_edges(point[name], edges) for name in reps]
    cross_combined = combine_cross_point(point["cross_AB"], point["cross_BA"], edges)
    point_frames.append(cross_combined)
    if "cross_median_AB" in point and "cross_median_BA" in point:
        cm = combine_cross_point(point["cross_median_AB"], point["cross_median_BA"], edges).with_columns(
            pl.lit("cross_median_combined").alias("representation")
        )
        point_frames.append(cm)
    point_all = pl.concat(point_frames, how="diagonal_relaxed").sort(["representation", "bin"])

    eprint("Subject-cluster bootstrap: n=%s" % int(args.n_bootstrap))
    boot = bootstrap_from_sufficient(suff, edges, int(args.n_bootstrap), int(args.bootstrap_seed))
    ci = bootstrap_ci(boot)
    if not ci.is_empty():
        point_all = point_all.join(ci, on=["representation", "bin"], how="left")

    point_out = outdir / "forward_drift_by_bin.csv"
    point_all.write_csv(point_out)

    fold_out = outdir / "forward_drift_by_fold.csv"
    fold_names = [n for n in ["cross_AB", "cross_BA", "same_A", "same_B", "cross_median_AB", "cross_median_BA", "observed_cross_AB", "observed_cross_BA"] if n in point]
    pl.concat([attach_edges(point[n], edges) for n in fold_names], how="diagonal_relaxed").sort(["representation", "bin"]).write_csv(fold_out)

    sensitivity_out = outdir / "forward_drift_sensitivity_by_fold.csv"
    pl.concat([attach_edges(point[n], edges) for n in fold_names if n not in ["cross_AB", "cross_BA"]], how="diagonal_relaxed").sort(["representation", "bin"]).write_csv(sensitivity_out)

    matched = matched_same_vs_cross(point, boot, edges)
    matched_out = outdir / "forward_drift_matched_same_vs_cross.csv"
    matched.write_csv(matched_out)

    reliability = reliability_by_bin(transitions_out, edges)
    reliability_out = outdir / "forward_drift_reliability_by_bin.csv"
    reliability.write_csv(reliability_out)

    summary = build_summary(point_all)
    summary_out = outdir / "forward_drift_global_summary.csv"
    summary.write_csv(summary_out)

    if bool(args.keep_bootstrap_draws) and not boot.is_empty():
        boot.write_parquet(
            outdir / "forward_drift_bootstrap_draws.parquet",
            compression=str(args.parquet_compression),
            statistics=True,
        )

    # Save subject/bin sufficient statistics: compact and audit-friendly.
    suff_out = pl.concat(list(suff.values()), how="diagonal_relaxed").sort(
        ["representation", "subject", "bin"]
    )
    suff_out.write_parquet(
        outdir / "forward_drift_subject_bin_sufficient.parquet",
        compression=str(args.parquet_compression),
        statistics=True,
    )

    # Manuscript-oriented subject robustness diagnostics for the primary estimator.
    subject_curves = build_subject_cross_curves(suff, edges)
    subject_curves_out = outdir / "forward_drift_subject_by_bin.csv"
    if not subject_curves.is_empty():
        subject_curves.write_csv(subject_curves_out)

    loso_curves = build_loso_cross_curves(suff, edges)
    loso_curves_out = outdir / "forward_drift_loso_by_bin.csv"
    if not loso_curves.is_empty():
        loso_curves.write_csv(loso_curves_out)

    fold_concordance = build_fold_concordance(point)
    fold_concordance_out = outdir / "forward_drift_fold_concordance.csv"
    if not fold_concordance.is_empty():
        fold_concordance.write_csv(fold_concordance_out)

    n_transitions = int(pl.scan_parquet(transitions_out).select(pl.len()).collect().item())
    subjects = collect_streaming(pl.scan_parquet(transitions_out).select("subject").unique()).height

    report = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "dataset_label": str(args.dataset_label),
        "primary_estimand": "replicate-decoupled E[delta x_latent | initial latent abundance x0]",
        "primary_representation": "cross_combined",
        "trajectories": str(trajectories),
        "dt": int(args.dt),
        "observability_filter": "TT (observable at both endpoints)",
        "n_unique_biological_transitions": n_transitions,
        "n_subjects": int(subjects),
        "replicate_decoupling": {
            "AB": "rep1 x0 posterior median -> rep2 posterior-mean longitudinal displacement",
            "BA": "rep2 x0 posterior median -> rep1 posterior-mean longitudinal displacement",
            "combined": "equal-weight average of AB and BA bin-wise estimates",
        },
        "comparators": {
            "naive_x0": "joint latent x0 -> joint latent dx",
            "xstar": "inverse-variance transition-centered joint latent coordinate -> joint latent dx",
        },
        "binning": {
            "source": edge_source,
            "n_bins": int(len(edges) - 1),
            "requested_mode": str(args.binning),
            "q_low": float(args.q_low),
            "q_high": float(args.q_high),
            "edges_file": str(edges_out),
        },
        "bootstrap": {
            "unit": "subject",
            "n_bootstrap": int(args.n_bootstrap),
            "seed": int(args.bootstrap_seed),
            "AB_BA_independence_assumed": False,
            "median_CI": "not estimated; median is point estimate only",
        },
        "build": build_report,
        "outputs": {
            "transitions": str(transitions_out),
            "bin_edges": str(edges_out),
            "by_bin": str(point_out),
            "by_fold": str(fold_out),
            "global_summary": str(summary_out),
            "matched_same_vs_cross": str(matched_out),
            "sensitivity_by_fold": str(sensitivity_out),
            "reliability_by_bin": str(reliability_out),
            "subject_by_bin": str(subject_curves_out) if not subject_curves.is_empty() else None,
            "loso_by_bin": str(loso_curves_out) if not loso_curves.is_empty() else None,
            "fold_concordance": str(fold_concordance_out) if not fold_concordance.is_empty() else None,
        },
    }
    run_config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "dataset_label": str(args.dataset_label),
        "trajectories": str(trajectories),
        "outdir": str(outdir),
        "dt": int(args.dt),
        "n_bins": int(args.n_bins),
        "binning": str(args.binning),
        "q_low": float(args.q_low),
        "q_high": float(args.q_high),
        "n_bootstrap": int(args.n_bootstrap),
        "bootstrap_seed": int(args.bootstrap_seed),
        "primary_representation": "cross_combined",
    }
    (outdir / "00_run_config.json").write_text(json.dumps(run_config, indent=2))
    (outdir / "forward_longitudinal_report.json").write_text(json.dumps(report, indent=2))

    print("\nCompleted replicate-decoupled longitudinal forward-drift analysis.")
    print("Unique TT transitions:", n_transitions)
    print("Subjects:", subjects)
    print("Outputs:")
    print(" -", transitions_out)
    print(" -", point_out)
    print(" -", fold_out)
    print(" -", summary_out)
    print(" -", matched_out)
    print(" -", sensitivity_out)
    print(" -", reliability_out)
    if not subject_curves.is_empty():
        print(" -", subject_curves_out)
    if not loso_curves.is_empty():
        print(" -", loso_curves_out)
    if not fold_concordance.is_empty():
        print(" -", fold_concordance_out)
    print(" -", edges_out)
    print(" -", outdir / "00_run_config.json")
    print(" -", outdir / "forward_longitudinal_report.json")


if __name__ == "__main__":
    main()
