#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
9-observed_replicate_decoupled_forward_drift.py
================================================

Canonical ClonoDynamics Step 9 under the final replicate-resolved framework.

PURPOSE
-------
Apply to the genuine longitudinal cohort the observed replicate-decoupled
forward estimator validated in the pseudo-longitudinal technical null
(Step 7).

The primary estimand is abundance-conditioned observed displacement at a fixed
longitudinal lag, using different technical replicates for conditioning and
outcome.

PRIMARY ESTIMANDS
-----------------
Let technical replicate 1 = A and replicate 2 = B.

AB:
    conditioning = x_observed_rep1_t0
    displacement = dx_observed_rep2
                 = x_observed_rep2_t1 - x_observed_rep2_t0
    support      = forward_ab_eligible

BA:
    conditioning = x_observed_rep2_t0
    displacement = dx_observed_rep1
                 = x_observed_rep1_t1 - x_observed_rep1_t0
    support      = forward_ba_eligible

The two folds are correlated reciprocal views of the same biological
transitions. They are estimated separately and are combined only AFTER
binning with equal fold weight:

    cross_combined_b
        = 0.5 * (cross_AB_b + cross_BA_b)

AB and BA are never concatenated and treated as independent biological
observations.

PRIMARY SUPPORT
---------------
Step 9 does NOT use TT/TF/FT/FF as a primary filter.

The primary supports are the Step-5 estimand-specific eligibility fields:

    forward_ab_eligible
    forward_ba_eligible

These are realized-positive observed-measurement support definitions, not
posterior-quality filters and not biological presence/absence states.

MATCHED SAME-VERSUS-CROSS CONTROL
---------------------------------
To quantify the technical amplification caused by reusing the same measurement
for conditioning and displacement, Step 9 also performs a matched comparison on
the stricter `common4` support:

    same_A:
        x_A(t0) -> Delta x_A

    cross_AB_matched:
        x_A(t0) -> Delta x_B

    same_B:
        x_B(t0) -> Delta x_B

    cross_BA_matched:
        x_B(t0) -> Delta x_A

Because all four observed endpoint measurements are positive on common4, these
comparisons use exactly the same biological transitions within each fold.

The matched comparison is a diagnostic/control. The primary longitudinal
forward estimator remains the broader AB/BA estimand-specific support.

INPUT
-----
The canonical input is the current generic Step-5 transition table:

    longitudinal_transitions.parquet

generated by:

    5-longitudinal_transition_assembly.py

Required columns:

    subject
    aaSeqCDR3
    t0
    t1
    dt

    x_observed_rep1_t0
    x_observed_rep2_t0

    dx_observed_rep1
    dx_observed_rep2

    forward_ab_eligible
    forward_ba_eligible
    common4

The script no longer reads the old latent trajectory table and no longer
requires replicate-specific latent posterior means/medians.

PRIMARY LAG
-----------
The default primary analysis is:

    dt = 1 week

to quantify forward structure over adjacent longitudinal sampling times.

Other lags can be analyzed explicitly with `--dt`, but the main Step-9
longitudinal forward analysis is intended for dt=1.

BINNING
-------
A common fixed observed-abundance grid is used by every Step-9 representation.

Default:
    n_bins  = 20
    binning = quantile
    q_low   = 0.005
    q_high  = 0.995

The default bin geometry is derived from the two PRIMARY conditioning
distributions with EXACT equal fold mass:

    0.5 mass:
        x_observed_rep1_t0 on forward_ab_eligible

    0.5 mass:
        x_observed_rep2_t0 on forward_ba_eligible

Each AB observation therefore receives weight 0.5/n_AB and each BA observation
weight 0.5/n_BA during edge construction. The bin geometry is consequently
invariant to unequal AB/BA eligible row counts.

The same resulting edges are then used for AB, BA and the common4 matched
same/cross controls.

An external bin-edge file can be supplied with `--bin-edges-file`.

POINT ESTIMATES
---------------
For each representation x abundance bin:

    n
    n_subjects
    x_mean
    x_median
    mean_dx
    median_dx
    p_dx_gt0
    sd_dx

A bin is marked as valid when:

    n >= --min-n

The default is 50 rows/bin.

PRIMARY COHORT CURVE
--------------------
For every bin where AB and BA are both valid:

    mean_dx_cross
        = 0.5 * (mean_dx_AB + mean_dx_BA)

    median_dx_cross
        = 0.5 * (median_dx_AB + median_dx_BA)

    p_dx_gt0_cross
        = 0.5 * (p_AB + p_BA)

The x coordinate is the fixed bin center.

For combined curves, support is reported fold-by-fold. The script does not
report a generic summed row count because AB and BA can contain overlapping
biological transitions and are not independent samples.

SUBJECT-CLUSTER BOOTSTRAP
-------------------------
Biological uncertainty is quantified by resampling SUBJECTS with replacement.

Default:
    n_bootstrap   = 2000
    bootstrap_seed = 123

The SAME subject draw is used for AB and BA and for all matched same/cross
controls.

Within each bootstrap draw:
    1. each fold is reconstructed separately from subject x bin sufficient
       statistics;
    2. AB and BA are combined with equal fold weight;
    3. same_A/same_B and matched cross folds are combined analogously.

The 2.5th–97.5th bootstrap percentiles are biological subject-cluster
confidence intervals.

LINEAR DESCRIPTORS
------------------
For each valid binned representation the script reports an unweighted linear
descriptor across valid bin centers:

    mean_dx = intercept + slope * x

and, when finite:

    x_zero = -intercept / slope

The line is a compact descriptor of the abundance-dependent curve; it is not
assumed to be the generative dynamical law.

Bootstrap distributions of slope, intercept and x_zero are reported for:
    cross_combined
    same_combined
    cross_combined_matched

Bootstrap linear descriptors are evaluated on the SAME fixed valid-bin set as
the corresponding point estimate. Bootstrap resampling therefore changes the
subject composition, not the definition of the abundance domain used by the
descriptor.

AB/BA CONCORDANCE
-----------------
Primary AB and BA mean-displacement curves are compared across matched valid
bins using:
    Pearson r
    mean absolute difference
    RMS difference
    maximum absolute difference

SUBJECT AND LOSO ROBUSTNESS
---------------------------
The primary cross_combined curve is reconstructed:
    - separately for each biological subject;
    - after leaving each subject out in turn.

These are descriptive robustness diagnostics.

OUTPUT
------
<outdir>/
    00_run_config.json
    00_pipeline_manifest.csv
    README_outputs.md

    01_forward_bin_edges.csv
    02_primary_forward_by_bin.csv
    03_matched_same_vs_cross_by_bin.csv
    04_forward_global_summary.csv
    05_subject_forward_by_bin.csv
    06_loso_forward_by_bin.csv
    07_AB_BA_concordance.csv
    08_subject_interval_support.csv
    09_bootstrap_linear_descriptors.csv

Optional:
    10_bootstrap_draws.parquet
        only with --keep-bootstrap-draws

PRIMARY RUN
-----------
python3 9-observed_replicate_decoupled_forward_drift.py \
    --transitions \
    ./results_4/5-longitudinal_transition_assembly/longitudinal_transitions.parquet \
    --outdir \
    ./results_4/9-observed_replicate_decoupled_forward_drift \
    --dataset-label healthy_longitudinal \
    --dt 1 \
    --n-bins 20 \
    --binning quantile \
    --q-low 0.005 \
    --q-high 0.995 \
    --min-n 50 \
    --n-bootstrap 2000 \
    --bootstrap-seed 123

INTERPRETATION
--------------
Step 9 asks whether a systematic abundance-dependent forward profile remains in
the genuine longitudinal cohort after direct same-replicate
conditioning/displacement coupling has been removed.

It does not compare the real curve to the pseudo ensemble. That empirical
real-versus-pseudo comparison belongs to Step 10.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np

try:
    import polars as pl
except Exception as exc:
    raise SystemExit(
        "ERROR: polars is required. Activate the ClonoDynamics environment."
    ) from exc


SCRIPT_VERSION = "v3-exact-equal-weight-ABBA-2026-09-17"

REQUIRED_COLUMNS = [
    "subject",
    "aaSeqCDR3",
    "t0",
    "t1",
    "dt",
    "x_observed_rep1_t0",
    "x_observed_rep2_t0",
    "dx_observed_rep1",
    "dx_observed_rep2",
    "forward_ab_eligible",
    "forward_ba_eligible",
    "common4",
]

PRIMARY_FOLDS = {
    "cross_AB": {
        "x": "x_observed_rep1_t0",
        "dx": "dx_observed_rep2",
        "support": "forward_ab_eligible",
    },
    "cross_BA": {
        "x": "x_observed_rep2_t0",
        "dx": "dx_observed_rep1",
        "support": "forward_ba_eligible",
    },
}

MATCHED_FOLDS = {
    "same_A": {
        "x": "x_observed_rep1_t0",
        "dx": "dx_observed_rep1",
        "support": "common4",
    },
    "cross_AB_matched": {
        "x": "x_observed_rep1_t0",
        "dx": "dx_observed_rep2",
        "support": "common4",
    },
    "same_B": {
        "x": "x_observed_rep2_t0",
        "dx": "dx_observed_rep2",
        "support": "common4",
    },
    "cross_BA_matched": {
        "x": "x_observed_rep2_t0",
        "dx": "dx_observed_rep1",
        "support": "common4",
    },
}

ALL_FOLDS = {**PRIMARY_FOLDS, **MATCHED_FOLDS}


# =============================================================================
# Generic helpers
# =============================================================================

def eprint(*args: Any, **kwargs: Any) -> None:
    import sys
    print(*args, file=sys.stderr, **kwargs)


def ensure_dir(path: Path) -> Path:
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def collect_streaming(lf: pl.LazyFrame) -> pl.DataFrame:
    try:
        return lf.collect(engine="streaming")
    except TypeError:
        return lf.collect(streaming=True)


def schema_names(path: Path) -> List[str]:
    return list(pl.scan_parquet(path).collect_schema().names())


def parse_bool_expr(column: str) -> pl.Expr:
    s = pl.col(column)
    return (
        pl.when(s.cast(pl.Boolean, strict=False).is_not_null())
        .then(s.cast(pl.Boolean, strict=False).fill_null(False))
        .otherwise(
            s.cast(pl.String, strict=False)
            .str.strip_chars()
            .str.to_lowercase()
            .is_in(["true", "t", "1", "yes", "y"])
            .fill_null(False)
        )
    )


def json_safe(x):
    if isinstance(x, Path):
        return str(x)
    if isinstance(x, np.integer):
        return int(x)
    if isinstance(x, np.floating):
        return None if np.isnan(x) else float(x)
    if isinstance(x, np.bool_):
        return bool(x)
    if isinstance(x, dict):
        return {str(k): json_safe(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [json_safe(v) for v in x]
    return x


def stable_json_sha256(payload: Mapping[str, object]) -> str:
    import hashlib
    raw = json.dumps(
        json_safe(dict(payload)),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def path_identity(path: Path) -> Dict[str, object]:
    p = path.expanduser().resolve(strict=True)
    stat = p.stat()
    return {
        "path": str(p),
        "size_bytes": int(stat.st_size),
        "mtime_ns": int(stat.st_mtime_ns),
    }


def finite_array(values) -> np.ndarray:
    x = np.asarray(values, dtype=float)
    return x[np.isfinite(x)]


def safe_slope_intercept(
    x: np.ndarray,
    y: np.ndarray,
) -> Tuple[float, float, float]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    if int(ok.sum()) < 2:
        return np.nan, np.nan, np.nan

    xv = x[ok]
    yv = y[ok]
    if np.ptp(xv) <= 0:
        return np.nan, np.nan, np.nan

    slope, intercept = np.polyfit(xv, yv, 1)
    slope = float(slope)
    intercept = float(intercept)

    if np.isfinite(slope) and abs(slope) > 1e-12:
        x_zero = float(-intercept / slope)
    else:
        x_zero = np.nan

    return slope, intercept, x_zero


def safe_pearson(
    x: np.ndarray,
    y: np.ndarray,
) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    if int(ok.sum()) < 2:
        return np.nan

    xv = x[ok]
    yv = y[ok]
    if np.std(xv) <= 0 or np.std(yv) <= 0:
        return np.nan
    return float(np.corrcoef(xv, yv)[0, 1])


# =============================================================================
# Bin geometry
# =============================================================================

def read_edges_file(path: Path) -> np.ndarray:
    path = Path(path)

    if path.suffix.lower() == ".csv":
        d = pl.read_csv(path)
    elif path.suffix.lower() in {".parquet", ".pq"}:
        d = pl.read_parquet(path)
    else:
        values = [
            float(line.strip())
            for line in path.read_text().splitlines()
            if line.strip()
        ]
        edges = np.unique(np.asarray(values, dtype=float))
        if edges.size < 3:
            raise ValueError("External bin-edge file contains too few edges.")
        return edges

    if "edge" in d.columns:
        edges = np.asarray(d["edge"].to_numpy(), dtype=float)
    elif {"x_left", "x_right"}.issubset(set(d.columns)):
        left = np.asarray(d["x_left"].to_numpy(), dtype=float)
        right = np.asarray(d["x_right"].to_numpy(), dtype=float)
        edges = np.r_[left[:1], right]
    elif {"x_lo", "x_hi"}.issubset(set(d.columns)):
        left = np.asarray(d["x_lo"].to_numpy(), dtype=float)
        right = np.asarray(d["x_hi"].to_numpy(), dtype=float)
        edges = np.r_[left[:1], right]
    else:
        raise ValueError(
            f"{path}: could not infer bin edges. Expected edge or x_left/x_right."
        )

    edges = np.unique(edges[np.isfinite(edges)])
    edges.sort()
    if edges.size < 3:
        raise ValueError("External bin-edge file contains too few finite edges.")
    return edges


def equal_fold_weighted_quantiles(
    x_ab: np.ndarray,
    x_ba: np.ndarray,
    probs: np.ndarray,
) -> np.ndarray:
    """Deterministic empirical quantiles with exact 0.5/0.5 fold mass."""
    a = np.asarray(x_ab, dtype=float)
    b = np.asarray(x_ba, dtype=float)
    a = a[np.isfinite(a)]
    b = b[np.isfinite(b)]

    if a.size == 0 or b.size == 0:
        raise ValueError(
            "Both AB and BA conditioning distributions must contain finite values."
        )

    values = np.concatenate([a, b])
    weights = np.concatenate([
        np.full(a.size, 0.5 / float(a.size), dtype=float),
        np.full(b.size, 0.5 / float(b.size), dtype=float),
    ])

    order = np.argsort(values, kind="mergesort")
    values = values[order]
    weights = weights[order]

    # Mid-weight CDF positions give deterministic linear interpolation while
    # preserving exact fold mass.
    cdf_mid = np.cumsum(weights) - 0.5 * weights
    xp = np.concatenate([[0.0], cdf_mid, [1.0]])
    fp = np.concatenate([[values[0]], values, [values[-1]]])

    q = np.asarray(probs, dtype=float)
    if np.any(~np.isfinite(q)) or np.any((q < 0) | (q > 1)):
        raise ValueError("Weighted quantile probabilities must lie in [0,1].")

    return np.interp(q, xp, fp)


def estimate_primary_edges(
    transitions: Path,
    dt: int,
    n_bins: int,
    mode: str,
    q_low: float,
    q_high: float,
) -> Tuple[np.ndarray, Dict[str, object]]:
    """Derive one common observed-abundance grid with exact AB/BA fold mass."""
    base = (
        pl.scan_parquet(transitions)
        .filter(pl.col("dt").cast(pl.Int64, strict=False) == int(dt))
        .select([
            pl.col("x_observed_rep1_t0").cast(pl.Float64, strict=False).alias("xA0"),
            pl.col("x_observed_rep2_t0").cast(pl.Float64, strict=False).alias("xB0"),
            parse_bool_expr("forward_ab_eligible").alias("ab"),
            parse_bool_expr("forward_ba_eligible").alias("ba"),
        ])
    )

    ab = collect_streaming(
        base.filter(pl.col("ab") & pl.col("xA0").is_finite())
        .select(pl.col("xA0").alias("x"))
    )
    ba = collect_streaming(
        base.filter(pl.col("ba") & pl.col("xB0").is_finite())
        .select(pl.col("xB0").alias("x"))
    )

    x_ab = np.asarray(ab["x"].to_numpy(), dtype=float)
    x_ba = np.asarray(ba["x"].to_numpy(), dtype=float)

    if x_ab.size == 0 or x_ba.size == 0:
        raise RuntimeError(
            "Could not derive observed forward bin edges: one primary fold has "
            "no finite eligible conditioning values."
        )

    if mode == "quantile":
        probs = np.linspace(float(q_low), float(q_high), int(n_bins) + 1)
        edges = equal_fold_weighted_quantiles(x_ab, x_ba, probs)
    elif mode == "equal_width":
        lo, hi = equal_fold_weighted_quantiles(
            x_ab, x_ba, np.asarray([float(q_low), float(q_high)])
        )
        edges = np.linspace(float(lo), float(hi), int(n_bins) + 1)
    else:
        raise ValueError(f"Unknown binning mode: {mode}")

    edges = np.unique(edges[np.isfinite(edges)])
    edges.sort()
    if edges.size < 3:
        raise RuntimeError("Could not derive at least two abundance bins.")

    info = {
        "policy": "exact_equal_fold_mass",
        "AB_mass": 0.5,
        "BA_mass": 0.5,
        "AB_row_count_weighting": False,
        "n_AB_conditioning_values": int(x_ab.size),
        "n_BA_conditioning_values": int(x_ba.size),
        "weighted_quantile_interpolation": "weighted_CDF_midpoint_linear",
        "requested_mode": str(mode),
        "q_low": float(q_low),
        "q_high": float(q_high),
        "n_bins": int(len(edges) - 1),
        "x_min": float(edges[0]),
        "x_max": float(edges[-1]),
    }
    return edges, info


def save_edges(
    edges: np.ndarray,
    path: Path,
) -> None:
    pl.DataFrame(
        {
            "bin": np.arange(len(edges) - 1, dtype=np.int32),
            "x_left": edges[:-1],
            "x_right": edges[1:],
            "x_center": 0.5 * (edges[:-1] + edges[1:]),
        }
    ).write_csv(path)


def bin_expr(
    x_col: str,
    edges: np.ndarray,
) -> pl.Expr:
    x = pl.col(x_col).cast(pl.Float64, strict=False)
    expr = pl.lit(None, dtype=pl.Int32)

    for i in range(len(edges) - 2, -1, -1):
        lo = float(edges[i])
        hi = float(edges[i + 1])
        if i == len(edges) - 2:
            cond = (x >= lo) & (x <= hi)
        else:
            cond = (x >= lo) & (x < hi)
        expr = (
            pl.when(cond)
            .then(pl.lit(i, dtype=pl.Int32))
            .otherwise(expr)
        )

    return expr.alias("bin")


# =============================================================================
# Point / sufficient statistics
# =============================================================================

def fold_point_stats(
    transitions: Path,
    edges: np.ndarray,
    dt: int,
    representation: str,
    min_n: int,
) -> pl.DataFrame:
    spec = ALL_FOLDS[representation]
    x_col = str(spec["x"])
    dx_col = str(spec["dx"])
    support_col = str(spec["support"])

    lf = (
        pl.scan_parquet(transitions)
        .filter(
            pl.col("dt").cast(pl.Int64, strict=False) == int(dt)
        )
        .select(
            [
                pl.col("subject").cast(pl.Int64, strict=False),
                pl.col(x_col).cast(pl.Float64, strict=False).alias("x"),
                pl.col(dx_col).cast(pl.Float64, strict=False).alias("dx"),
                parse_bool_expr(support_col).alias("eligible"),
            ]
        )
        .filter(
            pl.col("eligible")
            & pl.col("x").is_finite()
            & pl.col("dx").is_finite()
        )
        .with_columns(bin_expr("x", edges))
        .filter(pl.col("bin").is_not_null())
        .group_by("bin")
        .agg(
            [
                pl.len().alias("n"),
                pl.col("subject").n_unique().alias("n_subjects"),
                pl.col("x").mean().alias("x_mean"),
                pl.col("x").median().alias("x_median"),
                pl.col("dx").mean().alias("mean_dx"),
                pl.col("dx").median().alias("median_dx"),
                (pl.col("dx") > 0).mean().alias("p_dx_gt0"),
                pl.col("dx").std().alias("sd_dx"),
            ]
        )
        .sort("bin")
    )

    out = collect_streaming(lf).with_columns(
        [
            pl.lit(representation).alias("representation"),
            (pl.col("n") >= int(min_n)).alias("meets_min_n"),
        ]
    )
    return out


def fold_subject_sufficient(
    transitions: Path,
    edges: np.ndarray,
    dt: int,
    representation: str,
) -> pl.DataFrame:
    spec = ALL_FOLDS[representation]
    x_col = str(spec["x"])
    dx_col = str(spec["dx"])
    support_col = str(spec["support"])

    lf = (
        pl.scan_parquet(transitions)
        .filter(
            pl.col("dt").cast(pl.Int64, strict=False) == int(dt)
        )
        .select(
            [
                pl.col("subject").cast(pl.Int64, strict=False),
                pl.col(x_col).cast(pl.Float64, strict=False).alias("x"),
                pl.col(dx_col).cast(pl.Float64, strict=False).alias("dx"),
                parse_bool_expr(support_col).alias("eligible"),
            ]
        )
        .filter(
            pl.col("eligible")
            & pl.col("x").is_finite()
            & pl.col("dx").is_finite()
        )
        .with_columns(bin_expr("x", edges))
        .filter(pl.col("bin").is_not_null())
        .group_by(["subject", "bin"])
        .agg(
            [
                pl.len().alias("n"),
                pl.col("dx").sum().alias("sum_dx"),
                (pl.col("dx") > 0).sum().alias("n_pos"),
            ]
        )
        .sort(["subject", "bin"])
    )

    return collect_streaming(lf).with_columns(
        pl.lit(representation).alias("representation")
    )


def attach_edges(
    frame: pl.DataFrame,
    edges: np.ndarray,
) -> pl.DataFrame:
    edge_df = pl.DataFrame(
        {
            "bin": np.arange(len(edges) - 1, dtype=np.int32),
            "x_left": edges[:-1],
            "x_right": edges[1:],
            "x_center": 0.5 * (edges[:-1] + edges[1:]),
        }
    )
    return edge_df.join(frame, on="bin", how="left")


def combine_two_folds(
    left: pl.DataFrame,
    right: pl.DataFrame,
    edges: np.ndarray,
    representation: str,
    left_label: str,
    right_label: str,
) -> pl.DataFrame:
    a = left.select(
        [
            "bin",
            pl.col("n").alias(f"n_{left_label}"),
            pl.col("n_subjects").alias(f"n_subjects_{left_label}"),
            pl.col("x_mean").alias(f"x_mean_{left_label}"),
            pl.col("x_median").alias(f"x_median_{left_label}"),
            pl.col("mean_dx").alias(f"mean_dx_{left_label}"),
            pl.col("median_dx").alias(f"median_dx_{left_label}"),
            pl.col("p_dx_gt0").alias(f"p_dx_gt0_{left_label}"),
            pl.col("meets_min_n").alias(f"valid_{left_label}"),
        ]
    )
    b = right.select(
        [
            "bin",
            pl.col("n").alias(f"n_{right_label}"),
            pl.col("n_subjects").alias(f"n_subjects_{right_label}"),
            pl.col("x_mean").alias(f"x_mean_{right_label}"),
            pl.col("x_median").alias(f"x_median_{right_label}"),
            pl.col("mean_dx").alias(f"mean_dx_{right_label}"),
            pl.col("median_dx").alias(f"median_dx_{right_label}"),
            pl.col("p_dx_gt0").alias(f"p_dx_gt0_{right_label}"),
            pl.col("meets_min_n").alias(f"valid_{right_label}"),
        ]
    )

    m = a.join(b, on="bin", how="inner")

    m = m.with_columns(
        [
            (
                0.5
                * (
                    pl.col(f"mean_dx_{left_label}")
                    + pl.col(f"mean_dx_{right_label}")
                )
            ).alias("mean_dx"),
            (
                0.5
                * (
                    pl.col(f"median_dx_{left_label}")
                    + pl.col(f"median_dx_{right_label}")
                )
            ).alias("median_dx"),
            (
                0.5
                * (
                    pl.col(f"p_dx_gt0_{left_label}")
                    + pl.col(f"p_dx_gt0_{right_label}")
                )
            ).alias("p_dx_gt0"),
            (
                0.5
                * (
                    pl.col(f"x_mean_{left_label}")
                    + pl.col(f"x_mean_{right_label}")
                )
            ).alias("x_mean"),
            (
                0.5
                * (
                    pl.col(f"x_median_{left_label}")
                    + pl.col(f"x_median_{right_label}")
                )
            ).alias("x_median"),
            pl.min_horizontal(
                f"n_subjects_{left_label}",
                f"n_subjects_{right_label}",
            ).alias("n_subjects_min_fold"),
            pl.min_horizontal(
                f"n_{left_label}",
                f"n_{right_label}",
            ).alias("n_min_fold"),
            (
                pl.col(f"valid_{left_label}")
                & pl.col(f"valid_{right_label}")
            ).alias("meets_min_n"),
            pl.lit(representation).alias("representation"),
        ]
    )

    return attach_edges(m, edges)


def valid_bins(frame: pl.DataFrame) -> List[int]:
    if frame.is_empty():
        return []
    return [
        int(x)
        for x in (
            frame
            .filter(
                pl.col("meets_min_n").fill_null(False)
                & pl.col("mean_dx").is_finite()
            )["bin"]
            .drop_nulls()
            .unique()
            .sort()
            .to_list()
        )
    ]


# =============================================================================
# Bootstrap
# =============================================================================

def sufficient_to_arrays(
    suff: pl.DataFrame,
    subjects: Sequence[int],
    n_bins: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    si = {int(subject): i for i, subject in enumerate(subjects)}

    n = np.zeros((len(subjects), n_bins), dtype=float)
    sums = np.zeros_like(n)
    pos = np.zeros_like(n)

    for row in suff.iter_rows(named=True):
        subject = int(row["subject"])
        if subject not in si:
            continue
        i = si[subject]
        b = int(row["bin"])
        n[i, b] = float(row["n"])
        sums[i, b] = float(row["sum_dx"])
        pos[i, b] = float(row["n_pos"])

    return n, sums, pos


def all_subjects_from_sufficient(
    suff_by_rep: Mapping[str, pl.DataFrame],
) -> List[int]:
    subjects = set()
    for frame in suff_by_rep.values():
        if "subject" in frame.columns:
            subjects.update(
                int(x)
                for x in frame["subject"].drop_nulls().unique().to_list()
            )
    return sorted(subjects)


def bootstrap_curves(
    suff_by_rep: Mapping[str, pl.DataFrame],
    edges: np.ndarray,
    n_bootstrap: int,
    seed: int,
) -> pl.DataFrame:
    if int(n_bootstrap) <= 0:
        return pl.DataFrame()

    subjects = all_subjects_from_sufficient(suff_by_rep)
    if len(subjects) < 2:
        raise RuntimeError(
            "Need at least two biological subjects for subject-cluster bootstrap."
        )

    n_bins = len(edges) - 1
    arrays = {
        rep: sufficient_to_arrays(frame, subjects, n_bins)
        for rep, frame in suff_by_rep.items()
    }

    rng = np.random.default_rng(int(seed))
    rows: List[Dict[str, object]] = []

    for boot in range(int(n_bootstrap)):
        draw = rng.integers(
            0,
            len(subjects),
            size=len(subjects),
        )
        mult = np.bincount(
            draw,
            minlength=len(subjects),
        ).astype(float)[:, None]

        fold_values: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}

        for rep, (n_arr, sum_arr, pos_arr) in arrays.items():
            n = np.sum(mult * n_arr, axis=0)
            s = np.sum(mult * sum_arr, axis=0)
            p = np.sum(mult * pos_arr, axis=0)

            mean_dx = np.divide(
                s,
                n,
                out=np.full(n_bins, np.nan),
                where=n > 0,
            )
            p_pos = np.divide(
                p,
                n,
                out=np.full(n_bins, np.nan),
                where=n > 0,
            )
            fold_values[rep] = (mean_dx, p_pos)

        combined_specs = {
            "cross_combined": ("cross_AB", "cross_BA"),
            "same_combined": ("same_A", "same_B"),
            "cross_combined_matched": (
                "cross_AB_matched",
                "cross_BA_matched",
            ),
        }

        # Store primary fold curves and combined controls.
        for rep in ["cross_AB", "cross_BA"]:
            if rep not in fold_values:
                continue
            mean_dx, p_pos = fold_values[rep]
            for b in range(n_bins):
                rows.append(
                    {
                        "bootstrap": int(boot),
                        "representation": rep,
                        "bin": int(b),
                        "mean_dx": float(mean_dx[b]),
                        "p_dx_gt0": float(p_pos[b]),
                    }
                )

        for combined, (left, right) in combined_specs.items():
            if left not in fold_values or right not in fold_values:
                continue
            l_mean, l_p = fold_values[left]
            r_mean, r_p = fold_values[right]

            mean_dx = 0.5 * (l_mean + r_mean)
            p_pos = 0.5 * (l_p + r_p)

            for b in range(n_bins):
                rows.append(
                    {
                        "bootstrap": int(boot),
                        "representation": combined,
                        "bin": int(b),
                        "mean_dx": float(mean_dx[b]),
                        "p_dx_gt0": float(p_pos[b]),
                    }
                )

    return pl.DataFrame(rows)


def bootstrap_ci(
    boot: pl.DataFrame,
    valid_bins_by_rep: Mapping[str, Sequence[int]],
) -> pl.DataFrame:
    """Bootstrap intervals on the fixed point-estimate valid-bin domain."""
    if boot.is_empty():
        return pl.DataFrame()

    allowed_rows = []
    for rep, bins in valid_bins_by_rep.items():
        for b in sorted(set(int(x) for x in bins)):
            allowed_rows.append({"representation": str(rep), "bin": int(b)})

    if not allowed_rows:
        return pl.DataFrame()

    allowed = pl.DataFrame(allowed_rows)
    return (
        boot.lazy()
        .join(allowed.lazy(), on=["representation", "bin"], how="inner")
        .filter(pl.col("mean_dx").is_finite())
        .group_by(["representation", "bin"])
        .agg([
            pl.col("mean_dx").quantile(0.025, interpolation="linear").alias("mean_dx_ci025"),
            pl.col("mean_dx").quantile(0.975, interpolation="linear").alias("mean_dx_ci975"),
            pl.col("p_dx_gt0").quantile(0.025, interpolation="linear").alias("p_dx_gt0_ci025"),
            pl.col("p_dx_gt0").quantile(0.975, interpolation="linear").alias("p_dx_gt0_ci975"),
            pl.len().alias("n_bootstrap_valid"),
        ])
        .sort(["representation", "bin"])
        .collect()
    )


def bootstrap_linear_descriptors(
    boot: pl.DataFrame,
    edges: np.ndarray,
    min_bins: int,
    valid_bins_by_rep: Mapping[str, Sequence[int]],
) -> pl.DataFrame:
    """Bootstrap linear descriptors on each point estimator's fixed valid bins."""
    if boot.is_empty():
        return pl.DataFrame()

    centers = 0.5 * (edges[:-1] + edges[1:])
    target_reps = {
        "cross_combined",
        "same_combined",
        "cross_combined_matched",
    }

    rows: List[Dict[str, object]] = []

    for rep in sorted(target_reps):
        allowed = sorted(set(int(x) for x in valid_bins_by_rep.get(rep, [])))
        if len(allowed) < int(min_bins):
            continue

        d = boot.filter(
            (pl.col("representation") == rep)
            & pl.col("bin").is_in(allowed)
        )
        if d.is_empty():
            continue

        for boot_id, g in d.group_by("bootstrap", maintain_order=True):
            if isinstance(boot_id, tuple):
                boot_id = boot_id[0]

            by_bin = {
                int(row["bin"]): row["mean_dx"]
                for row in g.iter_rows(named=True)
            }
            x_values = []
            y_values = []
            for b in allowed:
                value = by_bin.get(b)
                if value is None or not np.isfinite(float(value)):
                    continue
                x_values.append(float(centers[b]))
                y_values.append(float(value))

            if len(x_values) < int(min_bins):
                continue

            slope, intercept, x_zero = safe_slope_intercept(
                np.asarray(x_values, dtype=float),
                np.asarray(y_values, dtype=float),
            )
            rows.append({
                "bootstrap": int(boot_id),
                "representation": rep,
                "n_bins": int(len(x_values)),
                "slope": slope,
                "intercept": intercept,
                "x_zero": x_zero,
            })

    return pl.DataFrame(rows)


# =============================================================================
# Global summaries
# =============================================================================

def curve_descriptors(
    frame: pl.DataFrame,
    min_bins: int,
) -> Dict[str, object]:
    if frame.is_empty():
        return {
            "n_bins_valid": 0,
            "mean_abs_bin_mean_dx": np.nan,
            "rms_bin_mean_dx": np.nan,
            "max_abs_bin_mean_dx": np.nan,
            "mean_abs_probability_bias": np.nan,
            "slope_mean_dx_vs_x": np.nan,
            "intercept_mean_dx_vs_x": np.nan,
            "x_zero": np.nan,
        }

    d = frame.filter(
        pl.col("meets_min_n").fill_null(False)
        & pl.col("mean_dx").is_finite()
        & pl.col("x_center").is_finite()
    )

    if d.height < int(min_bins):
        return {
            "n_bins_valid": int(d.height),
            "mean_abs_bin_mean_dx": np.nan,
            "rms_bin_mean_dx": np.nan,
            "max_abs_bin_mean_dx": np.nan,
            "mean_abs_probability_bias": np.nan,
            "slope_mean_dx_vs_x": np.nan,
            "intercept_mean_dx_vs_x": np.nan,
            "x_zero": np.nan,
        }

    x = d["x_center"].to_numpy().astype(float)
    y = d["mean_dx"].to_numpy().astype(float)
    p = d["p_dx_gt0"].to_numpy().astype(float)

    slope, intercept, x_zero = safe_slope_intercept(x, y)

    return {
        "n_bins_valid": int(d.height),
        "mean_abs_bin_mean_dx": float(np.mean(np.abs(y))),
        "rms_bin_mean_dx": float(np.sqrt(np.mean(y * y))),
        "max_abs_bin_mean_dx": float(np.max(np.abs(y))),
        "mean_abs_probability_bias": float(np.mean(np.abs(p - 0.5))),
        "slope_mean_dx_vs_x": slope,
        "intercept_mean_dx_vs_x": intercept,
        "x_zero": x_zero,
    }


def summarize_bootstrap_linear(
    linear_boot: pl.DataFrame,
) -> pl.DataFrame:
    if linear_boot.is_empty():
        return pl.DataFrame()

    rows = []
    for rep in sorted(
        linear_boot["representation"].drop_nulls().unique().to_list()
    ):
        d = linear_boot.filter(pl.col("representation") == rep)

        for metric in ["slope", "intercept", "x_zero"]:
            values = finite_array(
                d[metric].to_numpy().astype(float)
            )
            if values.size == 0:
                continue

            rows.append(
                {
                    "representation": rep,
                    "metric": metric,
                    "n_bootstrap_valid": int(values.size),
                    "median": float(np.median(values)),
                    "bootstrap_q025": float(
                        np.quantile(values, 0.025)
                    ),
                    "bootstrap_q975": float(
                        np.quantile(values, 0.975)
                    ),
                    "mean": float(np.mean(values)),
                }
            )

    return pl.DataFrame(rows)


# =============================================================================
# Subject / LOSO
# =============================================================================

def sufficient_lookup(
    frame: pl.DataFrame,
) -> Dict[Tuple[int, int], Tuple[float, float, float]]:
    out = {}
    for row in frame.iter_rows(named=True):
        out[(int(row["subject"]), int(row["bin"]))] = (
            float(row["n"]),
            float(row["sum_dx"]),
            float(row["n_pos"]),
        )
    return out


def build_subject_primary_curves(
    suff_ab: pl.DataFrame,
    suff_ba: pl.DataFrame,
    edges: np.ndarray,
) -> pl.DataFrame:
    ab = sufficient_lookup(suff_ab)
    ba = sufficient_lookup(suff_ba)

    subjects = sorted(
        {s for s, _ in ab}
        | {s for s, _ in ba}
    )

    rows = []
    for subject in subjects:
        for b in range(len(edges) - 1):
            a = ab.get((subject, b))
            z = ba.get((subject, b))
            if a is None or z is None:
                continue
            if a[0] <= 0 or z[0] <= 0:
                continue

            mean_ab = a[1] / a[0]
            mean_ba = z[1] / z[0]
            p_ab = a[2] / a[0]
            p_ba = z[2] / z[0]

            rows.append(
                {
                    "subject": int(subject),
                    "representation": "cross_combined",
                    "bin": int(b),
                    "x_left": float(edges[b]),
                    "x_right": float(edges[b + 1]),
                    "x_center": float(
                        0.5 * (edges[b] + edges[b + 1])
                    ),
                    "n_AB": int(a[0]),
                    "n_BA": int(z[0]),
                    "mean_dx_AB": float(mean_ab),
                    "mean_dx_BA": float(mean_ba),
                    "mean_dx": float(
                        0.5 * (mean_ab + mean_ba)
                    ),
                    "p_dx_gt0": float(
                        0.5 * (p_ab + p_ba)
                    ),
                }
            )

    return (
        pl.DataFrame(rows).sort(["subject", "bin"])
        if rows else pl.DataFrame()
    )


def build_loso_primary_curves(
    suff_ab: pl.DataFrame,
    suff_ba: pl.DataFrame,
    edges: np.ndarray,
) -> pl.DataFrame:
    ab = sufficient_lookup(suff_ab)
    ba = sufficient_lookup(suff_ba)

    subjects = sorted(
        {s for s, _ in ab}
        | {s for s, _ in ba}
    )
    if len(subjects) < 2:
        return pl.DataFrame()

    rows = []

    for omitted in subjects:
        kept = [s for s in subjects if s != omitted]

        for b in range(len(edges) - 1):
            n_ab = sum(
                ab.get((s, b), (0.0, 0.0, 0.0))[0]
                for s in kept
            )
            sum_ab = sum(
                ab.get((s, b), (0.0, 0.0, 0.0))[1]
                for s in kept
            )
            pos_ab = sum(
                ab.get((s, b), (0.0, 0.0, 0.0))[2]
                for s in kept
            )

            n_ba = sum(
                ba.get((s, b), (0.0, 0.0, 0.0))[0]
                for s in kept
            )
            sum_ba = sum(
                ba.get((s, b), (0.0, 0.0, 0.0))[1]
                for s in kept
            )
            pos_ba = sum(
                ba.get((s, b), (0.0, 0.0, 0.0))[2]
                for s in kept
            )

            if n_ab <= 0 or n_ba <= 0:
                continue

            mean_ab = sum_ab / n_ab
            mean_ba = sum_ba / n_ba
            p_ab = pos_ab / n_ab
            p_ba = pos_ba / n_ba

            rows.append(
                {
                    "omitted_subject": int(omitted),
                    "representation": "cross_combined",
                    "bin": int(b),
                    "x_left": float(edges[b]),
                    "x_right": float(edges[b + 1]),
                    "x_center": float(
                        0.5 * (edges[b] + edges[b + 1])
                    ),
                    "n_AB": int(n_ab),
                    "n_BA": int(n_ba),
                    "mean_dx_AB": float(mean_ab),
                    "mean_dx_BA": float(mean_ba),
                    "mean_dx": float(
                        0.5 * (mean_ab + mean_ba)
                    ),
                    "p_dx_gt0": float(
                        0.5 * (p_ab + p_ba)
                    ),
                }
            )

    return (
        pl.DataFrame(rows).sort(["omitted_subject", "bin"])
        if rows else pl.DataFrame()
    )


# =============================================================================
# Concordance / support
# =============================================================================

def fold_concordance(
    ab: pl.DataFrame,
    ba: pl.DataFrame,
) -> pl.DataFrame:
    a = (
        ab.filter(pl.col("meets_min_n"))
        .select(
            [
                "bin",
                pl.col("mean_dx").alias("AB"),
            ]
        )
    )
    b = (
        ba.filter(pl.col("meets_min_n"))
        .select(
            [
                "bin",
                pl.col("mean_dx").alias("BA"),
            ]
        )
    )

    d = (
        a.join(b, on="bin", how="inner")
        .filter(
            pl.col("AB").is_finite()
            & pl.col("BA").is_finite()
        )
    )

    if d.is_empty():
        return pl.DataFrame()

    x = d["AB"].to_numpy().astype(float)
    y = d["BA"].to_numpy().astype(float)
    delta = x - y

    return pl.DataFrame(
        [
            {
                "n_matched_bins": int(len(x)),
                "pearson_r_AB_BA": safe_pearson(x, y),
                "mean_abs_difference": float(
                    np.mean(np.abs(delta))
                ),
                "rms_difference": float(
                    np.sqrt(np.mean(delta * delta))
                ),
                "max_abs_difference": float(
                    np.max(np.abs(delta))
                ),
            }
        ]
    )


def subject_interval_support(
    transitions: Path,
    dt: int,
) -> pl.DataFrame:
    lf = (
        pl.scan_parquet(transitions)
        .filter(
            pl.col("dt").cast(pl.Int64, strict=False) == int(dt)
        )
        .select(
            [
                pl.col("subject").cast(pl.Int64, strict=False),
                pl.col("t0").cast(pl.Int64, strict=False),
                pl.col("t1").cast(pl.Int64, strict=False),
                parse_bool_expr("forward_ab_eligible").alias("ab"),
                parse_bool_expr("forward_ba_eligible").alias("ba"),
                parse_bool_expr("common4").alias("common4"),
            ]
        )
        .group_by(["subject", "t0", "t1"])
        .agg(
            [
                pl.len().alias("n_transitions"),
                pl.col("ab").sum().alias("n_forward_ab_eligible"),
                pl.col("ba").sum().alias("n_forward_ba_eligible"),
                pl.col("common4").sum().alias("n_common4"),
                pl.col("ab").mean().alias(
                    "fraction_forward_ab_eligible"
                ),
                pl.col("ba").mean().alias(
                    "fraction_forward_ba_eligible"
                ),
                pl.col("common4").mean().alias(
                    "fraction_common4"
                ),
            ]
        )
        .sort(["subject", "t0", "t1"])
    )
    return collect_streaming(lf)


# =============================================================================
# Matched same-vs-cross table
# =============================================================================

def build_matched_table(
    point: Mapping[str, pl.DataFrame],
    edges: np.ndarray,
    ci: pl.DataFrame,
) -> pl.DataFrame:
    same_combined = combine_two_folds(
        point["same_A"],
        point["same_B"],
        edges,
        representation="same_combined",
        left_label="A",
        right_label="B",
    )
    cross_combined = combine_two_folds(
        point["cross_AB_matched"],
        point["cross_BA_matched"],
        edges,
        representation="cross_combined_matched",
        left_label="AB",
        right_label="BA",
    )

    same = same_combined.select(
        [
            "bin",
            "x_left",
            "x_right",
            "x_center",
            pl.col("n_A").alias("n_fold_A"),
            pl.col("n_B").alias("n_fold_B"),
            pl.col("n_subjects_A").alias("n_subjects_fold_A"),
            pl.col("n_subjects_B").alias("n_subjects_fold_B"),
            pl.col("n_min_fold").alias("n_min_fold"),
            pl.col("n_subjects_min_fold").alias("n_subjects_min_fold"),
            pl.col("mean_dx").alias("mean_dx_same"),
            pl.col("median_dx").alias("median_dx_same"),
            pl.col("p_dx_gt0").alias("p_dx_gt0_same"),
            pl.col("meets_min_n").alias("valid_same"),
        ]
    )

    cross = cross_combined.select(
        [
            "bin",
            pl.col("n_AB").alias("n_cross_fold_AB"),
            pl.col("n_BA").alias("n_cross_fold_BA"),
            pl.col("n_subjects_AB").alias("n_subjects_cross_fold_AB"),
            pl.col("n_subjects_BA").alias("n_subjects_cross_fold_BA"),
            pl.col("n_min_fold").alias("n_cross_min_fold"),
            pl.col("n_subjects_min_fold").alias("n_subjects_cross_min_fold"),
            pl.col("mean_dx").alias("mean_dx_cross"),
            pl.col("median_dx").alias("median_dx_cross"),
            pl.col("p_dx_gt0").alias("p_dx_gt0_cross"),
            pl.col("meets_min_n").alias("valid_cross"),
        ]
    )

    out = same.join(cross, on="bin", how="inner").with_columns(
        [
            (
                pl.col("mean_dx_same")
                - pl.col("mean_dx_cross")
            ).alias("delta_mean_same_minus_cross"),
            (
                pl.col("p_dx_gt0_same")
                - pl.col("p_dx_gt0_cross")
            ).alias("delta_p_same_minus_cross"),
        ]
    )

    if not ci.is_empty():
        same_ci = (
            ci.filter(
                pl.col("representation") == "same_combined"
            )
            .select(
                [
                    "bin",
                    pl.col("mean_dx_ci025").alias(
                        "same_mean_dx_ci025"
                    ),
                    pl.col("mean_dx_ci975").alias(
                        "same_mean_dx_ci975"
                    ),
                ]
            )
        )
        cross_ci = (
            ci.filter(
                pl.col("representation")
                == "cross_combined_matched"
            )
            .select(
                [
                    "bin",
                    pl.col("mean_dx_ci025").alias(
                        "cross_mean_dx_ci025"
                    ),
                    pl.col("mean_dx_ci975").alias(
                        "cross_mean_dx_ci975"
                    ),
                ]
            )
        )
        out = (
            out.join(same_ci, on="bin", how="left")
            .join(cross_ci, on="bin", how="left")
        )

    return out.sort("bin")


# =============================================================================
# Pipeline manifest / README
# =============================================================================

def write_manifest(
    outdir: Path,
) -> None:
    rows = []
    for path in sorted(Path(outdir).rglob("*")):
        if path.is_file():
            rows.append(
                {
                    "relative_path": str(
                        path.relative_to(outdir)
                    ),
                    "suffix": path.suffix.lower(),
                    "size_bytes": int(path.stat().st_size),
                }
            )
    pl.DataFrame(rows).write_csv(
        outdir / "00_pipeline_manifest.csv"
    )


def write_readme(
    outdir: Path,
) -> None:
    text = """# Step 9 — observed replicate-decoupled longitudinal forward drift

Primary forward estimator:
- AB: x_observed_rep1_t0 -> dx_observed_rep2 on forward_ab_eligible
- BA: x_observed_rep2_t0 -> dx_observed_rep1 on forward_ba_eligible
- cross_combined: exact 0.5 AB + 0.5 BA fold weight after binning

Primary support is estimand-specific realized-positive support. No TT/TF/FT/FF
restriction is applied to the primary analysis.

Bin geometry:
- default bin edges use an exact equal-mass AB/BA empirical mixture;
- AB and BA row counts never determine their relative contribution to binning;
- the same fixed edges are used by primary and matched controls.

Matched technical-coupling control:
- support: common4
- same_A: xA0 -> dxA
- cross_AB_matched: xA0 -> dxB
- same_B: xB0 -> dxB
- cross_BA_matched: xB0 -> dxA

Uncertainty:
- biological subject-cluster bootstrap
- the same subject draw is used for all folds and controls
- AB and BA are never treated as independent subjects

Support reporting for combined curves:
- fold-specific counts are retained separately;
- n_min_fold / n_subjects_min_fold are support descriptors only;
- no summed generic n is reported for AB/BA-combined curves, because reciprocal
  folds can contain overlapping biological transitions and are not independent.

The binned linear slope and zero-crossing are compact descriptors of the
nonparametric curve, not a predefined generative drift law. Bootstrap linear
descriptors use the same fixed valid-bin domain as their point estimator.

Step 9 characterizes genuine longitudinal forward structure only. Comparison
against the 1x12 pseudo technical-null ensemble is performed in Step 10.
"""
    (outdir / "README_outputs.md").write_text(
        text,
        encoding="utf-8",
    )


# =============================================================================
# CLI
# =============================================================================

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Step 9: observed replicate-decoupled forward drift in the genuine "
            "longitudinal cohort."
        ),
    )

    p.add_argument(
        "--transitions",
        required=True,
        type=Path,
        help="Current Step-5 longitudinal_transitions.parquet.",
    )
    p.add_argument(
        "--outdir",
        required=True,
        type=Path,
    )
    p.add_argument(
        "--dataset-label",
        default="healthy_longitudinal",
    )
    p.add_argument(
        "--dt",
        type=int,
        default=1,
    )

    p.add_argument(
        "--n-bins",
        type=int,
        default=20,
    )
    p.add_argument(
        "--binning",
        choices=["quantile", "equal_width"],
        default="quantile",
    )
    p.add_argument(
        "--q-low",
        type=float,
        default=0.005,
    )
    p.add_argument(
        "--q-high",
        type=float,
        default=0.995,
    )
    p.add_argument(
        "--bin-edges-file",
        type=Path,
        default=None,
    )

    p.add_argument(
        "--min-n",
        type=int,
        default=50,
        help="Minimum rows per fold x abundance bin.",
    )
    p.add_argument(
        "--min-valid-bins",
        type=int,
        default=6,
        help="Minimum valid bins for global curve descriptors.",
    )

    p.add_argument(
        "--n-bootstrap",
        type=int,
        default=2000,
    )
    p.add_argument(
        "--bootstrap-seed",
        type=int,
        default=123,
    )
    p.add_argument(
        "--keep-bootstrap-draws",
        action="store_true",
    )
    return p


def validate_args(
    args: argparse.Namespace,
) -> None:
    if int(args.dt) < 1:
        raise ValueError("--dt must be >=1")
    if int(args.n_bins) < 3:
        raise ValueError("--n-bins must be >=3")
    if not (
        0.0 <= float(args.q_low)
        < float(args.q_high)
        <= 1.0
    ):
        raise ValueError("Require 0 <= q-low < q-high <= 1")
    if int(args.min_n) < 1:
        raise ValueError("--min-n must be >=1")
    if int(args.min_valid_bins) < 2:
        raise ValueError("--min-valid-bins must be >=2")
    if int(args.n_bootstrap) < 0:
        raise ValueError("--n-bootstrap must be >=0")


# =============================================================================
# Main
# =============================================================================

def main(
    argv: Optional[Sequence[str]] = None,
) -> int:
    args = build_parser().parse_args(argv)
    validate_args(args)

    transitions = args.transitions.expanduser().resolve(strict=True)
    outdir = ensure_dir(args.outdir.expanduser().resolve())

    available = set(schema_names(transitions))
    missing = [c for c in REQUIRED_COLUMNS if c not in available]
    if missing:
        raise ValueError(
            "Current Step-5 transition table is missing required Step-9 "
            f"columns: {missing}"
        )

    eprint("=== ClonoDynamics Step 9 ===")
    eprint("script version:", SCRIPT_VERSION)
    eprint("dataset:", args.dataset_label)
    eprint("transitions:", transitions)
    eprint("outdir:", outdir)
    eprint("dt:", int(args.dt))
    eprint("primary support: forward_ab_eligible / forward_ba_eligible")
    eprint("TT restriction: NO")
    eprint("primary estimator: observed replicate-decoupled AB/BA")
    eprint("AB/BA combined weighting: exact 0.5 / 0.5 after binning")
    eprint("AB/BA row-count weighting: NO")

    if args.bin_edges_file is not None:
        edges = read_edges_file(
            args.bin_edges_file.expanduser().resolve(strict=True)
        )
        edge_source = str(
            args.bin_edges_file.expanduser().resolve(strict=True)
        )
        edge_info = {
            "policy": "external_bin_edges_file",
            "path": edge_source,
            "AB_mass": None,
            "BA_mass": None,
            "AB_row_count_weighting": None,
            "n_bins": int(len(edges) - 1),
            "x_min": float(edges[0]),
            "x_max": float(edges[-1]),
        }
    else:
        edges, edge_info = estimate_primary_edges(
            transitions,
            dt=int(args.dt),
            n_bins=int(args.n_bins),
            mode=str(args.binning),
            q_low=float(args.q_low),
            q_high=float(args.q_high),
        )
        edge_source = (
            "exact 0.5/0.5 weighted empirical mixture of primary "
            "AB and BA observed conditioning distributions"
        )

    edges_path = outdir / "01_forward_bin_edges.csv"
    save_edges(edges, edges_path)

    eprint("abundance bins:", len(edges) - 1)
    eprint("edge source:", edge_source)

    # ---------------------------------------------------------------
    # Fold point estimates and compact subject sufficient statistics.
    # ---------------------------------------------------------------
    point: Dict[str, pl.DataFrame] = {}
    sufficient: Dict[str, pl.DataFrame] = {}

    for representation in ALL_FOLDS:
        eprint("point statistics:", representation)
        point[representation] = fold_point_stats(
            transitions,
            edges,
            dt=int(args.dt),
            representation=representation,
            min_n=int(args.min_n),
        )
        sufficient[representation] = fold_subject_sufficient(
            transitions,
            edges,
            dt=int(args.dt),
            representation=representation,
        )

    primary_combined = combine_two_folds(
        point["cross_AB"],
        point["cross_BA"],
        edges,
        representation="cross_combined",
        left_label="AB",
        right_label="BA",
    )

    same_combined = combine_two_folds(
        point["same_A"],
        point["same_B"],
        edges,
        representation="same_combined",
        left_label="A",
        right_label="B",
    )

    matched_cross_combined = combine_two_folds(
        point["cross_AB_matched"],
        point["cross_BA_matched"],
        edges,
        representation="cross_combined_matched",
        left_label="AB",
        right_label="BA",
    )

    valid_bins_by_rep = {
        "cross_AB": valid_bins(attach_edges(point["cross_AB"], edges)),
        "cross_BA": valid_bins(attach_edges(point["cross_BA"], edges)),
        "cross_combined": valid_bins(primary_combined),
        "same_combined": valid_bins(same_combined),
        "cross_combined_matched": valid_bins(matched_cross_combined),
    }

    # ---------------------------------------------------------------
    # Subject-cluster bootstrap.
    # ---------------------------------------------------------------
    eprint(
        "subject-cluster bootstrap:",
        int(args.n_bootstrap),
        "seed=",
        int(args.bootstrap_seed),
    )

    boot = bootstrap_curves(
        sufficient,
        edges,
        n_bootstrap=int(args.n_bootstrap),
        seed=int(args.bootstrap_seed),
    )
    ci = bootstrap_ci(boot, valid_bins_by_rep)

    if not ci.is_empty():
        primary_combined = primary_combined.join(
            ci.filter(
                pl.col("representation") == "cross_combined"
            ).drop("representation"),
            on="bin",
            how="left",
        )

        for rep in ["cross_AB", "cross_BA"]:
            point[rep] = point[rep].join(
                ci.filter(
                    pl.col("representation") == rep
                ).drop("representation"),
                on="bin",
                how="left",
            )

    # ---------------------------------------------------------------
    # Primary by-bin output.
    # ---------------------------------------------------------------
    primary_frames = [
        attach_edges(point["cross_AB"], edges),
        attach_edges(point["cross_BA"], edges),
        primary_combined,
    ]
    primary_by_bin = pl.concat(
        primary_frames,
        how="diagonal_relaxed",
    ).sort(["representation", "bin"])

    primary_path = outdir / "02_primary_forward_by_bin.csv"
    primary_by_bin.write_csv(primary_path)

    # ---------------------------------------------------------------
    # Matched same-versus-cross output.
    # ---------------------------------------------------------------
    matched_table = build_matched_table(
        point,
        edges,
        ci,
    )
    matched_path = outdir / "03_matched_same_vs_cross_by_bin.csv"
    matched_table.write_csv(matched_path)

    # ---------------------------------------------------------------
    # Global descriptors.
    # ---------------------------------------------------------------
    descriptors = []

    descriptor_frames = {
        "cross_AB": attach_edges(point["cross_AB"], edges),
        "cross_BA": attach_edges(point["cross_BA"], edges),
        "cross_combined": primary_combined,
        "same_combined": same_combined,
        "cross_combined_matched": matched_cross_combined,
    }

    for representation, frame in descriptor_frames.items():
        metrics = curve_descriptors(
            frame,
            min_bins=int(args.min_valid_bins),
        )
        descriptors.append(
            {
                "representation": representation,
                **metrics,
            }
        )

    global_summary = pl.DataFrame(descriptors)

    linear_boot = bootstrap_linear_descriptors(
        boot,
        edges,
        min_bins=int(args.min_valid_bins),
        valid_bins_by_rep=valid_bins_by_rep,
    )
    linear_summary = summarize_bootstrap_linear(linear_boot)

    if not linear_summary.is_empty():
        wide = (
            linear_summary
            .select(
                [
                    "representation",
                    "metric",
                    "n_bootstrap_valid",
                    "median",
                    "bootstrap_q025",
                    "bootstrap_q975",
                ]
            )
        )
        # Keep long-form bootstrap descriptor summary separately and preserve
        # compact point-estimate global table.
        wide.write_csv(
            outdir / "09_bootstrap_linear_descriptors.csv"
        )

    global_path = outdir / "04_forward_global_summary.csv"
    global_summary.write_csv(global_path)

    # ---------------------------------------------------------------
    # Subject / LOSO robustness.
    # ---------------------------------------------------------------
    subject_curves = build_subject_primary_curves(
        sufficient["cross_AB"],
        sufficient["cross_BA"],
        edges,
    )
    subject_path = outdir / "05_subject_forward_by_bin.csv"
    subject_curves.write_csv(subject_path)

    loso_curves = build_loso_primary_curves(
        sufficient["cross_AB"],
        sufficient["cross_BA"],
        edges,
    )
    loso_path = outdir / "06_loso_forward_by_bin.csv"
    loso_curves.write_csv(loso_path)

    concordance = fold_concordance(
        point["cross_AB"],
        point["cross_BA"],
    )
    concordance_path = outdir / "07_AB_BA_concordance.csv"
    concordance.write_csv(concordance_path)

    support = subject_interval_support(
        transitions,
        dt=int(args.dt),
    )
    support_path = outdir / "08_subject_interval_support.csv"
    support.write_csv(support_path)

    if (
        bool(args.keep_bootstrap_draws)
        and not boot.is_empty()
    ):
        boot.write_parquet(
            outdir / "10_bootstrap_draws.parquet",
            compression="zstd",
            statistics=True,
        )

    # ---------------------------------------------------------------
    # Run config.
    # ---------------------------------------------------------------
    subjects = (
        collect_streaming(
            pl.scan_parquet(transitions)
            .filter(
                pl.col("dt").cast(pl.Int64, strict=False)
                == int(args.dt)
            )
            .select(
                pl.col("subject")
                .cast(pl.Int64, strict=False)
            )
            .unique()
        )
        .height
    )

    signature_payload = {
        "script_version": SCRIPT_VERSION,
        "input": path_identity(transitions),
        "dataset_label": str(args.dataset_label),
        "dt": int(args.dt),
        "binning": {
            "edge_source": edge_source,
            "edge_info": edge_info,
            "edges": [float(x) for x in edges],
        },
        "min_n": int(args.min_n),
        "min_valid_bins": int(args.min_valid_bins),
        "n_bootstrap": int(args.n_bootstrap),
        "bootstrap_seed": int(args.bootstrap_seed),
        "AB_BA_combination_policy": "exact_equal_fold_weight_after_binning",
        "AB_BA_row_count_weighting": False,
    }
    analysis_signature = stable_json_sha256(signature_payload)

    (outdir / "00_run_signature.json").write_text(
        json.dumps(
            {
                "analysis_signature": analysis_signature,
                "signature_payload": signature_payload,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    run_config = {
        "script": Path(__file__).name,
        "script_version": SCRIPT_VERSION,
        "dataset_label": str(args.dataset_label),
        "transitions": str(transitions),
        "outdir": str(outdir),
        "analysis_signature": analysis_signature,
        "dt": int(args.dt),
        "n_subjects": int(subjects),
        "primary_support": {
            "AB": "forward_ab_eligible",
            "BA": "forward_ba_eligible",
            "operational_TT_filter": False,
        },
        "primary_estimand": {
            "AB": (
                "x_observed_rep1_t0 -> dx_observed_rep2"
            ),
            "BA": (
                "x_observed_rep2_t0 -> dx_observed_rep1"
            ),
            "combined": (
                "exact 0.5*AB + 0.5*BA after binning"
            ),
            "AB_BA_combination_policy": (
                "exact_equal_fold_weight_after_binning"
            ),
            "AB_BA_row_count_weighting": False,
        },
        "matched_same_vs_cross": {
            "support": "common4",
            "same_A": "xA0 -> dxA",
            "cross_AB_matched": "xA0 -> dxB",
            "same_B": "xB0 -> dxB",
            "cross_BA_matched": "xB0 -> dxA",
        },
        "binning": {
            "source": edge_source,
            "edge_info": edge_info,
            "n_bins": int(len(edges) - 1),
            "requested_mode": str(args.binning),
            "q_low": float(args.q_low),
            "q_high": float(args.q_high),
            "min_n": int(args.min_n),
            "min_valid_bins": int(args.min_valid_bins),
            "edges_file": str(edges_path),
            "fold_weighting": (
                "exact 0.5 AB / 0.5 BA"
                if args.bin_edges_file is None
                else "defined by external edge file"
            ),
        },
        "bootstrap": {
            "unit": "biological subject",
            "n_bootstrap": int(args.n_bootstrap),
            "seed": int(args.bootstrap_seed),
            "same_subject_draw_for_all_folds": True,
            "AB_BA_independence_assumed": False,
        },
        "linear_descriptor": {
            "model": "mean_dx = intercept + slope*x_center",
            "role": "compact curve descriptor, not generative law",
            "x_zero": "-intercept/slope when finite",
            "bootstrap_bin_domain": (
                "fixed to point-estimate valid bins for each representation"
            ),
        },
    }

    (outdir / "00_run_config.json").write_text(
        json.dumps(
            json_safe(run_config),
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    write_readme(outdir)
    write_manifest(outdir)

    print("\n[DONE] Step 9 observed replicate-decoupled forward drift")
    print("Biological subjects             :", subjects)
    print("Primary TT restriction          : NO")
    print("Primary estimator               : observed AB/BA")
    print("AB/BA combined weighting        : exact 0.5 / 0.5")
    print("AB/BA row-count weighting       : NO")
    print("Primary support                 : AB/BA estimand-specific")
    print("Matched control support         : common4")
    print("Outputs:")
    for path in [
        edges_path,
        primary_path,
        matched_path,
        global_path,
        subject_path,
        loso_path,
        concordance_path,
        support_path,
        outdir / "09_bootstrap_linear_descriptors.csv",
    ]:
        if path.exists():
            print(" -", path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
